[package]
name = "wild-guardians-africa"
version = "0.1.0"
description = "Wild Guardians Africa"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }

[profile.release]
strip = true
lto = true
codegen-units = 1
