// Stable IDs shared by save validation, profile memory and presentation.
export const BASIC_STEPS=['intro','center','plant','hire','observe','harvest','done'];
export const BASIC_MESSAGES={intro:'basic.introduction',center:'basic.center',plant:'basic.plant',hire:'basic.hiring',observe:'basic.work',harvest:'basic.harvest',done:'basic.complete'};
export const TUTORIAL_MESSAGES={
  'basic.introduction':{gesture:'greeting',text:'Estas tierras me conocen. Soy el Espíritu que las guarda. Al anochecer, una maldición agita a los animales. Echa raíces junto al poblado: levanta un centro, siembra; tu comunidad cuidará los cultivos.'},
  'basic.center':{gesture:'speak',text:'Toda cosecha necesita un hogar. Elige Centro de trabajo en Construir: 800 monedas para alzarlo en suelo libre junto al poblado, donde señala mi mano. Desde allí se ordenarán las tareas; allí volverán las cajas de cosecha.'},
  'basic.plant':{gesture:'curious',text:'Abre Cultivar: cada semilla es una promesa. Elige una y toca suelo libre junto al centro, donde señala mi mano. Al plantar pagas y nace el brote; crecerá tras la siembra y el primer riego del trabajador. No prometas más de lo que puedas cuidar; reserva monedas para contratar.'},
  'basic.hiring':{gesture:'acknowledge',text:'Sembrar es prometer; cuidar es cumplir. Tras plantar se abrirá sola la ventana para contratar. Ajusta los cuatro perfiles a tus monedas; pagarás una vez al confirmar. Los trabajadores se repartirán entre centros y atenderán cada tarea por turno.'},
  'basic.work':{gesture:'idle',text:'Confía en esas manos. Siembran y riegan solas; cada cultivo tiene su ritmo y su paciencia ante la sed. Agotada esa paciencia, el crecimiento espera al riego. Maduro, ya no necesita agua.'},
  'basic.harvest':{gesture:'reveal',text:'La tierra cumple su promesa. El equipo recoge por sí solo cada cultivo maduro y lleva su caja al centro; sólo al entregarla nacen las monedas.'},
  'basic.complete':{gesture:'farewell',text:'¿Ves? Ya conoces el lenguaje de la tierra. Tu primera caja está en el centro. Guarda monedas para mañana y escucha las nuevas enseñanzas del poblado.'},
  'mechanic.defenses':{gesture:'warning',text:'Levanta un refugio, no una prisión. Esta noche llegará la primera incursión: en Construir, combina módulos y puertas dejando caminos libres. Los animales dañan cultivos y estructuras; pagarás las reparaciones cuando el trabajador llegue.'},
  'mechanic.first-raid':{gesture:'warning',text:'Primero, las vidas; después, la cosecha. Los animales han entrado: el equipo deja sus tareas y huye al poblado. La incursión terminará cuando salga el último; se reorganizarán los cuidados de los cultivos supervivientes. Las reparaciones manuales interrumpidas deberán solicitarse de nuevo.'},
  'magic.shield':{gesture:'reveal',text:'Te presto mi Escudo. En Magias, invócalo donde no haya animales: 20 segundos de amparo. Podrás volver a llamarlo 90 segundos después de lanzarlo. No empuja animales ni repara edificios; las zonas mágicas no pueden solaparse.'},
  'magic.growth':{gesture:'reveal',text:'El agua ya ha despertado tus brotes. Toca uno con Crecimiento y préstale mi fuerza. Puedes volver a ayudar, pero la potencia del día se reparte entre tus cultivos.'},
  'magic.multiply':{gesture:'reveal',text:'Prueba Multiplicar en otro cultivo: su próxima cosecha valdrá más. La fuerza espiritual del día se reparte; ningún fruto puede valer más del doble. Su caja traerá el beneficio al poblado.'},
  'reminder.shield':{gesture:'warning',text:'Las bestias pisan tus campos. Mi Escudo está listo: abre Magias y resguarda tus cultivos donde no haya animales.'},
  'reminder.growth':{gesture:'reveal',text:'Tus brotes aún tienen camino. Crecimiento está listo: préstales mi fuerza y acerca la cosecha. El riego seguirá en manos del equipo.'},
  'reminder.multiply':{gesture:'reveal',text:'Quedan frutos sin bendecir. Multiplicar puede aumentar su próxima cosecha; la potencia que queda hoy se reparte entre tus cultivos.'},
  'worker.recovery':{gesture:'warning',text:'No le pidas prisa a una herida. Dos golpes en esta incursión han incapacitado a un trabajador: hoy no volverá. Si lo contratas mañana, seguirá sanando y no correrá al trabajar; pasado mañana recuperará su movilidad habitual. La herida sigue a la persona, no al perfil.'},
  'campaign.liberation':{gesture:'reveal',text:'Escucha. Tras cien noches, el silencio ya es paz: la maldición se ha roto. Puedes cerrar esta historia… o seguir cultivando sin ataques y fundar nuevos poblados, conservando tu finca y cuanto has levantado.'},
  'world.expansion':{gesture:'curious',text:'Nuevas raíces, la misma finca. Puedes fundar otro poblado en paz: elige cultura y revisa toda la ubicación antes de confirmar. Conservas monedas, construcciones y cultivos; el nuevo poblado se sumará al reparto de trabajadores al próximo amanecer.'}
};
export const TUTORIAL_IDS=Object.keys(TUTORIAL_MESSAGES);
export const DEFENSES_FOLLOWUP={gesture:'warning',text:'No confundas silencio con paz. Prepara la finca para otras incursiones: en Construir, une módulos y puertas sin cerrar caminos. Los animales dañan cultivos y estructuras; pagarás las reparaciones cuando llegue el trabajador.'};
