// Stable IDs shared by save validation, profile memory and presentation.
export const BASIC_STEPS=['intro','center','plant','hire','observe','harvest','done'];
export const BASIC_MESSAGES={intro:'basic.introduction',center:'basic.center',plant:'basic.plant',hire:'basic.hiring',observe:'basic.work',harvest:'basic.harvest',done:'basic.complete'};
export const TUTORIAL_MESSAGES={
  'basic.introduction':{gesture:'greeting',text:'Soy el Espíritu que cuida estas tierras. Una maldición inquieta a los animales al caer el sol. Junto al poblado levantarás una finca: construiremos un centro, sembrarás y tu comunidad cuidará los cultivos.'},
  'basic.center':{gesture:'speak',text:'Pulsa Construir y elige Centro de trabajo. Después coloca tu primer centro por 800 monedas donde señala la mano. Busca suelo libre junto al poblado. El centro organizará las tareas y recibirá las cajas de cosecha.'},
  'basic.plant':{gesture:'curious',text:'Pulsa Cultivar y elige una semilla. Después toca el suelo libre que señala la mano cerca del centro. Pagas la semilla al plantar y aparece el brote. Su crecimiento empieza cuando un trabajador completa la siembra y el primer riego. Planta lo que puedas cuidar; reserva monedas para contratar.'},
  'basic.hiring':{gesture:'acknowledge',text:'La contratación se abre automáticamente cuando termines de plantar. Puedes ajustar los cuatro perfiles al saldo disponible. El salario se cobra una sola vez al confirmar. Los trabajadores se reparten entre los centros y siguen las tareas por orden.'},
  'basic.work':{gesture:'idle',text:'Deja trabajar al equipo. Siembran y riegan automáticamente; cada cultivo tiene sus tiempos y tolerancia al agua. Cuando esa tolerancia se agota, el crecimiento espera al riego. Una planta madura ya no necesita agua.'},
  'basic.harvest':{gesture:'reveal',text:'Los trabajadores recogen automáticamente los cultivos maduros. Cada cosecha se convierte en una caja que llevan al centro. Las monedas llegan al entregar la caja.'},
  'basic.complete':{gesture:'farewell',text:'Tu primera caja ha llegado al centro. Ya conoces el trabajo de la finca. Conserva monedas para la próxima jornada y escucha al poblado cuando aparezca algo nuevo.'},
  'mechanic.defenses':{gesture:'warning',text:'La primera incursión llegará esta noche. Prepara las defensas desde Construir: combina módulos y puertas para proteger la finca y dejar pasos transitables. Los animales dañan cultivos y estructuras; las reparaciones se cobran cuando llega el trabajador.'},
  'mechanic.first-raid':{gesture:'warning',text:'Los animales han entrado en la finca. El equipo abandona sus tareas y huye hacia el poblado. La incursión termina cuando sale el último animal; después se reconstruyen las tareas de los cultivos que siguen vivos. Las reparaciones manuales interrumpidas deben pedirse de nuevo.'},
  'magic.shield':{gesture:'reveal',text:'Ya puedes usar Escudo desde Magias. Colócalo en una zona libre de animales: protege durante 20 segundos y se recarga en 90 segundos desde el lanzamiento. No empuja animales ni cura edificios. Las zonas mágicas no pueden solaparse.'},
  'magic.growth':{gesture:'reveal',text:'Crecimiento acelera las plantas de su zona durante 30 segundos. No sustituye los riegos obligatorios ni permite madurar con agua pendiente. Se recarga en 90 segundos desde el lanzamiento; las pausas del juego congelan duración y recarga.'},
  'magic.multiply':{gesture:'reveal',text:'Multiplicar marca durante 15 segundos los cultivos de su zona para duplicar su próxima cosecha, aunque se recoja después. La recarga empieza al lanzarlo y dura 120 segundos; no concede monedas antes de entregar las cajas.'},
  'worker.recovery':{gesture:'warning',text:'Un segundo golpe en la misma incursión ha incapacitado a un trabajador. No volverá al trabajo hoy. Si lo contratas mañana, estará recuperándose y no tendrá carrera laboral; en la jornada posterior recuperará su movilidad habitual. La lesión pertenece a esa persona, no a todo su perfil.'},
  'campaign.liberation':{gesture:'reveal',text:'Has sobrevivido a cien noches y la maldición ha terminado. Esta misma finca queda en paz. Puedes cerrar la historia o seguir cultivando, sin ataques, y fundar nuevos poblados con tu explotación actual.'},
  'world.expansion':{gesture:'curious',text:'La tierra liberada permite fundar otros poblados. Elige una cultura y revisa la ubicación completa antes de confirmar. Conservas saldo, construcciones y cultivos; el nuevo poblado participa en la distribución de trabajadores a partir del siguiente amanecer.'}
};
export const TUTORIAL_IDS=Object.keys(TUTORIAL_MESSAGES);
export const DEFENSES_FOLLOWUP={gesture:'warning',text:'Prepara las defensas para las próximas incursiones desde Construir: combina módulos y puertas para proteger la finca y dejar pasos transitables. Los animales dañan cultivos y estructuras; las reparaciones se cobran cuando llega el trabajador.'};
