// Generated by tools/generate_balance.py. Edit canonical JSON and player revisions, then regenerate.
export const BALANCE = {
  "schema": "wg-master-plan-balance-2.0",
  "date": "2026-10-01",
  "status": "valores de diseño aprobados; integración todavía no ejecutada",
  "clock": {
    "cycle_seconds_at_1x": 600,
    "day_seconds": 300,
    "night_seconds": 300,
    "dawn": "07:05",
    "night_start": "19:05",
    "calm_night_speed": 5,
    "pause_on_hidden": true
  },
  "initial_money": 1500,
  "work_center": {
    "cost": 800,
    "max_hp": 600,
    "collapse_damage_fraction": 0.79,
    "collapse_seconds": 3.2,
    "max_workers": null
  },
  "crops": [
    {
      "id": "mijo",
      "name": "Mijo",
      "plant_cost": 5,
      "base_harvest_value": 9,
      "growth_seconds": 140,
      "total_waters": 2,
      "water_tolerance_fraction": 1,
      "nominal_water_interval_seconds": 70.0,
      "derived_tolerance_seconds": 70.0
    },
    {
      "id": "girasol",
      "name": "Girasol",
      "plant_cost": 18,
      "base_harvest_value": 32,
      "growth_seconds": 180,
      "total_waters": 3,
      "water_tolerance_fraction": 0.6,
      "nominal_water_interval_seconds": 60.0,
      "derived_tolerance_seconds": 36.0
    },
    {
      "id": "sorgo",
      "name": "Sorgo",
      "plant_cost": 6,
      "base_harvest_value": 11,
      "growth_seconds": 220,
      "total_waters": 2,
      "water_tolerance_fraction": 1,
      "nominal_water_interval_seconds": 110.0,
      "derived_tolerance_seconds": 110.0
    },
    {
      "id": "maiz",
      "name": "Maíz",
      "plant_cost": 8,
      "base_harvest_value": 15,
      "growth_seconds": 270,
      "total_waters": 3,
      "water_tolerance_fraction": 0.4,
      "nominal_water_interval_seconds": 90.0,
      "derived_tolerance_seconds": 36.0
    },
    {
      "id": "batata",
      "name": "Batata",
      "plant_cost": 10,
      "base_harvest_value": 20,
      "growth_seconds": 330,
      "total_waters": 2,
      "water_tolerance_fraction": 0.8,
      "nominal_water_interval_seconds": 165.0,
      "derived_tolerance_seconds": 132.0
    },
    {
      "id": "algodon",
      "name": "Algodón",
      "plant_cost": 100,
      "base_harvest_value": 160,
      "growth_seconds": 405,
      "total_waters": 4,
      "water_tolerance_fraction": 0.75,
      "nominal_water_interval_seconds": 101.25,
      "derived_tolerance_seconds": 75.9375
    },
    {
      "id": "yuca",
      "name": "Yuca",
      "plant_cost": 12,
      "base_harvest_value": 28,
      "growth_seconds": 480,
      "total_waters": 2,
      "water_tolerance_fraction": 1.2,
      "nominal_water_interval_seconds": 240.0,
      "derived_tolerance_seconds": 288.0
    },
    {
      "id": "platano",
      "name": "Plátano",
      "plant_cost": 150,
      "base_harvest_value": 240,
      "growth_seconds": 570,
      "total_waters": 6,
      "water_tolerance_fraction": 0.25,
      "nominal_water_interval_seconds": 95.0,
      "derived_tolerance_seconds": 23.75
    }
  ],
  "workers": {
    "older_wage": 30,
    "young_wage": 40,
    "young_work_speed": 1.5,
    "male_harvest_multiplier": 1.2,
    "male_shift_end": "17:05",
    "female_shift_end": "19:05",
    "idle_radius_max_m": 8,
    "run_start_pending_tasks_per_worker_over": 2,
    "daily_run_distance_long_trips": 3,
    "long_trip_distance_m": null
  },
  "walls": [
    {
      "id": "zarzas",
      "name": "Zarzas",
      "cost": 10,
      "hp": 100,
      "gate_hp": 60
    },
    {
      "id": "empalizada",
      "name": "Madera",
      "cost": 20,
      "hp": 200,
      "gate_hp": 120
    },
    {
      "id": "adobe",
      "name": "Adobe",
      "cost": 35,
      "hp": 300,
      "gate_hp": 180
    },
    {
      "id": "reforzado",
      "name": "Adobe reforzado",
      "cost": 55,
      "hp": 400,
      "gate_hp": 240
    },
    {
      "id": "piedra",
      "name": "Piedra",
      "cost": 80,
      "hp": 500,
      "gate_hp": 300
    }
  ],
  "wall_collapse": {
    "remaining_hp_fraction": 0.2,
    "seconds": 1.4
  },
  "animals": [
    {
      "id": "warthog",
      "name": "Facóquero",
      "threat_cost": 1,
      "structure_hit_damage": 20,
      "hit_budget_min": 2,
      "hit_budget_max": 4,
      "max_per_raid": 3
    },
    {
      "id": "hyena",
      "name": "Hiena",
      "threat_cost": 3,
      "structure_hit_damage": 25,
      "hit_budget_min": 3,
      "hit_budget_max": 5,
      "max_per_raid": 2
    },
    {
      "id": "buffalo",
      "name": "Búfalo",
      "threat_cost": 5,
      "structure_hit_damage": 35,
      "hit_budget_min": 4,
      "hit_budget_max": 6,
      "max_per_raid": 2
    },
    {
      "id": "lion",
      "name": "León",
      "threat_cost": 7,
      "structure_hit_damage": 40,
      "hit_budget_min": 4,
      "hit_budget_max": 7,
      "max_per_raid": 2
    },
    {
      "id": "rhino",
      "name": "Rinoceronte",
      "threat_cost": 10,
      "structure_hit_damage": 60,
      "hit_budget_min": 5,
      "hit_budget_max": 8,
      "max_per_raid": 1
    }
  ],
  "threat_tiers": [
    {
      "attraction_min": 0,
      "attraction_max_exclusive": 100,
      "night_attack_probability": 1,
      "threat_min": 1,
      "threat_max": 2,
      "unlocked_species": [
        "warthog"
      ]
    },
    {
      "attraction_min": 100,
      "attraction_max_exclusive": 300,
      "night_attack_probability": 1,
      "threat_min": 3,
      "threat_max": 4,
      "unlocked_species": [
        "warthog",
        "hyena"
      ]
    },
    {
      "attraction_min": 300,
      "attraction_max_exclusive": 800,
      "night_attack_probability": 1,
      "threat_min": 5,
      "threat_max": 7,
      "unlocked_species": [
        "warthog",
        "hyena",
        "buffalo"
      ]
    },
    {
      "attraction_min": 800,
      "attraction_max_exclusive": 2000,
      "night_attack_probability": 1,
      "threat_min": 7,
      "threat_max": 10,
      "unlocked_species": [
        "warthog",
        "hyena",
        "buffalo",
        "lion"
      ]
    },
    {
      "attraction_min": 2000,
      "attraction_max_exclusive": null,
      "night_attack_probability": 1,
      "threat_min": 10,
      "threat_max": 14,
      "unlocked_species": [
        "warthog",
        "hyena",
        "buffalo",
        "lion",
        "rhino"
      ]
    }
  ],
  "raids": {
    "night_window": [
      "20:00",
      "05:00"
    ],
    "day_window": [
      "09:00",
      "16:00"
    ],
    "day_probability": 0.1,
    "day_attraction_min": 10000,
    "day_threat": [
      7,
      10
    ],
    "max_animals": 5,
    "min_budget_spend_fraction": 0.75,
    "max_budget_spend_fraction": 1,
    "independent_rolls": true,
    "tutorial_night": 2,
    "tutorial_species": "warthog",
    "tutorial_count": 1,
    "attack_animation_weights": {
      "right_slash": 0.45,
      "charged_slash": 0.3,
      "combo_1": 0.15,
      "combo_2": 0.1
    },
    "logical_hits_per_attack_animation": 1,
    "worker_pass_front_attack_probability": 0.6,
    "worker_collision_knockback_m": [
      1.5,
      2
    ]
  },
  "spells": [
    {
      "id": "shield",
      "name": "Escudo",
      "duration_seconds": 20,
      "cooldown_seconds": 90,
      "unlock": "night_1",
      "coverage_reference_plants": [
        5,
        6
      ],
      "radius_m": null
    },
    {
      "id": "growth",
      "name": "Crecimiento",
      "duration_seconds": 30,
      "cooldown_seconds": 90,
      "unlock": "day_3",
      "coverage_reference_plants": [
        9,
        10
      ],
      "growth_multiplier": 1.5,
      "radius_m": null
    },
    {
      "id": "multiply",
      "name": "Multiplicar",
      "duration_seconds": 15,
      "cooldown_seconds": 120,
      "unlock": "day_5",
      "coverage_reference_plants": [
        6,
        8
      ],
      "harvest_multiplier": 2,
      "radius_m": null
    }
  ],
  "no_overlap_between_spell_areas": true,
  "events": {
    "max_per_night": 1,
    "probability": 0.2,
    "negative_probability": 0.6,
    "positive_probability": 0.4,
    "negative_magnitude_max": 0.3,
    "positive_magnitudes": [
      0.1,
      0.2,
      0.3
    ],
    "species_specific_probability": 0.6,
    "general_probability": 0.4,
    "min_plants_for_species_event": 5,
    "effect_target": null
  },
  "postgame": {
    "after_completed_nights": 100,
    "attacks": false,
    "max_villages": null,
    "additional_village_cost": {
      "formula": "50000 + 25000 * (n - 2)",
      "min_n": 2,
      "initial_village_ordinal": 1
    },
    "culture_stats_differ": false
  },
  "game_over": {
    "after_raid_no_center_min_money": 800,
    "dawn": {
      "center_and_resources": 100,
      "center_without_resources": 105,
      "no_center_with_resources": 900,
      "no_center_without_resources": 905
    }
  },
  "unresolved_contracts": {
    "currency_rounding": null,
    "spell_cooldown_starts_at": null,
    "harvest_order_persists_across_queue_rebuild": null,
    "first_water_growth_gate_details": null
  },
  "null_semantics": "null en capacidades significa sin límite artificial; null en parámetros/importaciones significa dato no verificado, no valor cero."
};
