import test from 'node:test';import assert from 'node:assert/strict';
import {Navigation} from '../src/world/navigation.js';import {animalSegmentClearance} from '../src/world/animal-segment-clearance.js';
function world(slope){const n=new Navigation(712,'sabana',{});n.field={slope,fluidInside:()=>false};n.propsAt=()=>[];n.version=1;return n;}
const start={x:0,z:0},end={x:1,z:0};
test('animal quarter-metre proof rejects a narrow forbidden band before landing',()=>{const n=world(x=>Math.abs(x-.15)<.02?.52:.49);assert.equal(n.coarseSegmentClear(start,end,0,null,false),true);assert.equal(n.segmentClear(start,end,0,null,false),false);assert.equal(n.terrainValid(.15,0,0,false),false);});
test('near-limit proof checks the full footprint rather than only its center',()=>{const n=world((x,z)=>Math.abs(x-.15)<.02&&Math.abs(z-.85)<.01?.52:.49);assert.equal(n.segmentClear(start,end,.85,null,false),false);});
test('ordinary flat edges stay coarse and exact repeated proof is reused until epoch changes',()=>{let samples=0;const n=world(()=>{samples++;return .2;});assert.equal(n.coarseSegmentClear(start,end,0,null,false),true);const coarse=samples;samples=0;assert.equal(n.segmentClear(start,end,0,null,false),true);const first=samples;assert.equal(first,coarse,'Flat proof must not add fine terrain samples');assert.equal(animalSegmentClearance(n,start,end,0,null),true);assert.equal(samples,first);n.version++;assert.equal(animalSegmentClearance(n,start,end,0,null),true);assert(samples>first);});
test('near-limit cache invalidates when the geometry epoch changes',()=>{let blocked=false;const n=world(x=>blocked&&Math.abs(x-.15)<.02?.52:.49);assert(n.segmentClear(start,end,0,null,false));blocked=true;n.version++;n.segmentCache.clear();assert.equal(n.segmentClear(start,end,0,null,false),false);});
test('water, lava and newly introduced solids remain forbidden',()=>{for(const kind of ['water','lava','solid']){const n=world(()=>.49);if(kind==='solid')n.obstacles=[{id:'wall',kind:'house',x:.5,z:0,radius:.1}];else n.field.fluidInside=x=>x>.4&&x<.6;assert.equal(n.segmentClear(start,end,0,null,false),false);}});
