import test from 'node:test';
import assert from 'node:assert/strict';
import * as Game from '../src/simulation/game.js';
import {createPlant} from '../src/simulation/crops.js';
import {cropSpec} from '../src/simulation/rules.js';
import {numberOf} from '../src/simulation/money.js';
import {serialize,deserialize} from '../src/persistence/snapshots.js';
const nav={placement:()=>({valid:true,suppress:[]}),setState:()=>{},terrainValid:()=>true,walkable:()=>true,path:(a,b)=>[{x:b.x,z:b.z}]};
function setup(){const s=Game.newGame({seed:712,slotId:'automatic'});Game.placeStructure(s,'center',{x:4,z:0},nav);const p=createPlant('ripe','mijo',8,0,s.structures[0].id);p.water.forEach(w=>w.status='manual');p.growth=cropSpec('mijo').growth_seconds-.05;s.plants.push(p);return {s,p};}
test('maturity schedules harvest without a player command or immediate income',()=>{const {s,p}=setup(),balance=numberOf(s.ledger.balance);Game.tick(s,.1,nav);assert.equal(p.harvestRequested,true);assert.equal(s.tasks.filter(t=>t.kind==='harvest'&&t.targetId===p.id).length,1);assert.equal(numberOf(s.ledger.balance),balance);assert.deepEqual(s.commandIds,['center']);assert.equal(s.events.filter(e=>e.type==='HarvestRequested'&&e.automatic).length,1);Game.tick(s,1,nav);assert.equal(s.tasks.filter(t=>t.kind==='harvest').length,1);assert.equal(s.events.filter(e=>e.type==='HarvestRequested').length,1);});
test('an already ripe saved plant schedules itself after load and queue reconstruction',()=>{const {s,p}=setup();p.growth=cropSpec('mijo').growth_seconds;const loaded=deserialize(serialize(s));Game.rebuildTasks(loaded);assert.equal(loaded.plants[0].harvestRequested,true);assert.equal(loaded.tasks.filter(t=>t.kind==='harvest').length,1);Game.rebuildTasks(loaded);assert.equal(loaded.tasks.filter(t=>t.kind==='harvest').length,1);});
test('automatic orders survive attack cancellation and regenerate only for living ripe plants',()=>{const {s,p}=setup();Game.tick(s,.1,nav);s.tasks=[];s.raid={animals:[]};Game.rebuildTasks(s);assert.equal(p.harvestRequested,true);assert.equal(s.tasks.filter(t=>t.kind==='harvest').length,0);s.raid=null;Game.rebuildTasks(s);assert.equal(s.tasks.filter(t=>t.kind==='harvest').length,1);p.alive=false;Game.rebuildTasks(s);assert.equal(s.tasks.filter(t=>t.kind==='harvest').length,0);});
test('a paid worker collects and delivers automatically, settling income once',()=>{const {s,p}=setup();Game.openInitialHiring(s);Game.hire(s,'hire',{olderMale:1});const w=s.workers[0];w.status='idle';w.x=7.4;w.z=0;const before=numberOf(s.ledger.balance);for(let i=0;i<400&&!s.crates.some(c=>c.delivered);i++)Game.tick(s,.1,nav);assert.equal(p.alive,false);assert.equal(p.harvestRequested,false);assert.equal(s.crates.length,1);assert.equal(s.crates[0].delivered,true);assert.ok(numberOf(s.ledger.balance)>before);const after=numberOf(s.ledger.balance);Game.tick(s,1,nav);assert.equal(numberOf(s.ledger.balance),after);assert.ok(!s.commandIds.some(id=>id.includes('harvest')));});
