import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {spawnSync} from 'node:child_process';import * as THREE from 'three';
import {Assets} from '../src/rendering/assets.js';import {loadCropBridges} from '../src/rendering/crop-library.js';import {createCropBatch} from '../src/rendering/crop-batch.js';import {cropSpec} from '../src/simulation/rules.js';import {assetUrl,assetExpectedBytes} from '../src/rendering/asset-url.js';import {cropRuntimeDescriptor as descriptor,runtimeGeometryManifest} from '../src/rendering/crop-runtime.js';
import {WorldScene} from '../src/rendering/scene.js';import {LoadingDiorama} from '../src/rendering/loading-diorama.js';
const meta=JSON.parse(fs.readFileSync('public/content/crop-bridges.json')),catalog=JSON.parse(fs.readFileSync('public/content/models.json')).find(m=>m.source.includes('Cultivos')),deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
function fixture(t,{image}={}){const assets=new Assets(),requests=[],textures=[],self=globalThis.self,progress=globalThis.ProgressEvent;globalThis.self=globalThis;globalThis.ProgressEvent??=class {constructor(type,fields){Object.assign(this,{type},fields);}};
 t.mock.method(globalThis,'fetch',async request=>{const url=typeof request==='string'?request:request.url,file=new URL(url,'http://localhost/').pathname;if(file.startsWith('/content/'))return new Response(fs.readFileSync('public'+file));requests.push(url);assert.ok(file.startsWith('/assets/crop-partition-v1-'),'no full-library fetch: '+file);const data=fs.readFileSync('public'+file);assert.equal(assetExpectedBytes(url),data.length);return new Response(data,{headers:{'Content-Length':String(data.length)}});});
 assets.textures.loadAsync=async url=>{textures.push(url);return image?await image(url):new THREE.Texture();};t.after(()=>{assets.disposeModels();globalThis.self=self;globalThis.ProgressEvent=progress;});return {assets,requests,textures};}
const meshCount=g=>{let n=0;g.scene.traverse(o=>{if(o.isMesh)n++;});return n;};
test('generic catalog/loadCropBridges path shares one owner, all4 real GLBs and all species morphs',async t=>{const f=fixture(t),partition=await f.assets.getCropPartition();await partition.models('maize');await partition.bridges(meta,'maize');
 const [states,same]=await Promise.all([f.assets.model(catalog.url),f.assets.model(catalog.url)]),bridges=await loadCropBridges(meta,url=>f.assets.model(url));assert.strictEqual(states,same);assert.strictEqual(f.assets.cropPartition,partition);assert.equal(meshCount(states),40);assert.equal(bridges.bakedTemplates.size,32);assert.equal(f.requests.length,5);assert.equal(new Set(f.requests).size,5);assert.equal(f.textures.length,4);assert.equal(new Set(f.textures).size,4);
 const scene=new THREE.Scene(),batch=createCropBatch(scene,{capabilities:{getMaxAnisotropy:()=>1}},states,bridges,16);for(const species of ['maiz','algodon','girasol','platano','sorgo','mijo','yuca','batata'])for(const normalized of [0,.15,.3,.5,.75,.95,1]){batch.update([{id:species,species,growth:normalized*cropSpec(species).growth_seconds,x:1,z:2,rotation:0}],0,()=>0);assert.equal(scene.children.reduce((n,m)=>n+m.count,0),1);}batch.dispose();assert.equal(partition.closed,false);
 const sources=[];states.scene.traverse(o=>{if(o.isMesh)sources.push(o);});assert.ok(sources.filter(o=>o.material.map===sources[0].material.map).length>5);assert.equal(sources[0].material.map.colorSpace,THREE.SRGBColorSpace);assert.equal(sources[0].material.normalMap.colorSpace,THREE.NoColorSpace);const counts=new Map();for(const resource of f.assets.ownedResources)resource.addEventListener('dispose',()=>counts.set(resource,(counts.get(resource)??0)+1));f.assets.disposeModels();f.assets.disposeModels();assert.equal(partition.closed,true);assert.ok([...counts.values()].every(n=>n===1));});
test('historical authored/compressed aliases use same collection without old payload requests',async t=>{const f=fixture(t);for(const row of descriptor.replaced)for(const url of ['/'+row.source,'/'+row.runtime,assetUrl('/'+row.source)])assert.equal(meshCount(await f.assets.model(url)),row.kind==='steady'?40:32);assert.equal(f.requests.length,5);});
test('cancel at native image await closes singleton and releases late resources once',async t=>{const started=deferred(),late=deferred(),f=fixture(t,{image:()=>{started.resolve();return late.promise;}}),pending=f.assets.model(catalog.url),rejected=assert.rejects(pending,/disposed|cancelled/i);await started.promise;f.assets.disposeModels();let disposed=0;const texture=new THREE.Texture();texture.addEventListener('dispose',()=>disposed++);late.resolve(texture);await rejected;assert.equal(disposed,1);assert.equal(f.assets.modelSources.size,0);await assert.rejects(f.assets.getCropPartition(),/disposed/);});
test('failed canonical image retries same partition files, not full libraries',async t=>{let fail=true;const f=fixture(t,{image:async()=>{if(fail)throw Error('decode failure');return new THREE.Texture();}});await assert.rejects(f.assets.model(catalog.url),/decode failure/);fail=false;assert.equal(meshCount(await f.assets.model(catalog.url)),40);assert.equal(f.requests.filter(url=>url.endsWith('partition-manifest.json')).length,1);assert.ok(f.requests.every(url=>url.includes('/crop-partition-v1-')));});
test('runtime manifest replaces two full GLBs with4 partitions, preserving historical verification',()=>{const original=JSON.parse(fs.readFileSync('content/manifests/web-assets.json')),runtime=runtimeGeometryManifest(original);assert.equal(original.records.length,22);assert.equal(runtime.records.length,24);assert.equal(runtime.records.filter(row=>row.partition).length,4);for(const row of descriptor.replaced){assert.ok(original.records.some(x=>x.source===row.source));assert.ok(!runtime.records.some(x=>x.source===row.source));assert.ok(fs.existsSync('public/'+row.source)&&fs.existsSync('public/'+row.runtime));}assert.match(catalog.url,/partition-manifest.json#steady$/);assert.match(meta.bakedAsset,/partition-manifest.json#bridges$/);assert.equal(catalog.collection,'crop-partition-v1-steady');assert.equal(meta.bakedCollection,'crop-partition-v1-bridges');});
test('default collection uses actual asset-url under nested itch/CDN and Tauri roots',()=>{for(const moduleUrl of ['https://cdn.itch.zone/html/9876/game/assets/index.js','https://tauri.localhost/assets/index.js']){const p=spawnSync(process.execPath,['--experimental-loader','./tests/fixtures/crop-partition-hosting-loader.mjs','./tests/fixtures/crop-runtime-hosting.mjs'],{encoding:'utf8',env:{...process.env,CROP_HOST_MODULE:moduleUrl}});assert.equal(p.status,0,p.stdout+'\n'+p.stderr);assert.match(p.stdout,/default collection hosting PASS/);}});
test('standalone real diorama prepare reads virtual catalogue and adopts only maize before World completes',async t=>{const f=fixture(t),stop=Error('soil adoption boundary'),world=Object.assign(Object.create(WorldScene.prototype),{loading:new AbortController(),assets:f.assets,sky:{load:async()=>{}}}),owner=Object.assign(Object.create(LoadingDiorama.prototype),{world,abort:new AbortController(),resourceOverlap:false,serialImageChain:false,ground:{material:{}},textureOwner:{borrow:()=>{throw stop;}}});await assert.rejects(owner.prepare(),error=>error===stop);assert.equal(f.requests.length,3);assert.ok(f.requests.slice(1).every(url=>url.includes('/maize-')));assert.equal(world.cropPartition,undefined);await f.assets.model(catalog.url);await loadCropBridges(meta,url=>f.assets.model(url));assert.equal(f.requests.length,5);});
test('actual World.load generic Assets path completes new/save40/32 without App installation or full payloads',()=>{const p=spawnSync(process.execPath,['--experimental-loader','./tests/fixtures/world-load-crop-default-loader.mjs','./tests/fixtures/world-load-crop-default.mjs'],{encoding:'utf8'});assert.equal(p.status,0,p.stdout+'\n'+p.stderr);assert.match(p.stdout,/generic default Assets callpath: New \+ saved Continue PASS/);});
