import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {runInNewContext} from 'node:vm';
const source=readFileSync(new URL('../src-tauri/smoke.js',import.meta.url),'utf8');
const observe=runInNewContext(source.slice(0,source.indexOf('// Runs only'))+';observeDesktopWorldLoading');
function fixture(){let clock=0,hidden=false,busy='true',phase='Preparing rendering resources',failure=null;const pending=new Map();let id=0;const native=function(callback){pending.set(++id,callback);return id;};const win={requestAnimationFrame:native},doc={get visibilityState(){return hidden?'hidden':'visible';},get hidden(){return hidden;},hasFocus:()=>!hidden,querySelector(selector){if(selector==='#stage')return {getAttribute:()=>busy};if(selector==='#world-loading')return busy==='true'?{}:null;if(selector==='[role="progressbar"]')return {getAttribute:()=> '73'};if(selector==='.interactive-loading-title')return {textContent:phase};if(selector==='.loading-failure')return failure?{textContent:failure}:null;if(selector==='#world')return {width:1280,height:720};return null;}};return {win,doc,native,pending,now:()=>clock,set(values){clock=values.clock??clock;hidden=values.hidden??hidden;busy=values.busy??busy;failure=values.failure??failure;phase=values.phase??phase;}};}
test('desktop loading diagnostics preserve native RAF handles and observe delivered app frames without scheduling extra work',()=>{const f=fixture(),observer=observe(f.win,f.doc,f.now);assert.equal(f.pending.size,0);let calls=0;function frame(){calls++;}const handle=f.win.requestAnimationFrame(frame);assert.equal(handle,1);f.pending.get(handle)(1000);f.win.requestAnimationFrame(frame);f.pending.get(2)(2000);const report=observer.sample();assert.equal(calls,2);assert.equal(report.rafDelivery.callbacks,2);assert.equal(report.rafDelivery.maxIntervalMs,1000);assert.equal(f.pending.size,2);observer.stop();assert.equal(f.win.requestAnimationFrame,f.native);});
test('desktop loading reports distinguish hidden pending GPU presentation, returned menu failure, and actual stage readiness',()=>{const f=fixture(),observer=observe(f.win,f.doc,f.now);f.set({clock:90000,hidden:true});const blocked=observer.sample();assert.equal(blocked.current.stageBusy,'true');assert.equal(blocked.current.hidden,true);assert.equal(blocked.current.phase,'Preparing rendering resources');f.set({clock:90001,failure:'Graphics context lost during loading.'});assert.match(observer.sample().current.failure,/context lost/);f.set({clock:90002,hidden:false,busy:'false'});const ready=observer.sample();assert.equal(ready.current.stageBusy,'false');assert.equal(ready.current.overlay,false);assert.equal(ready.transitions.length,3);observer.stop();});
test('observer cleanup does not replace a newer RAF owner and stops counting late delivered callbacks',()=>{const f=fixture(),observer=observe(f.win,f.doc,f.now);function frame(){}f.win.requestAnimationFrame(frame);const replacement=()=>7;f.win.requestAnimationFrame=replacement;observer.stop();f.pending.get(1)(1000);assert.equal(observer.sample().rafDelivery.callbacks,0);assert.equal(f.win.requestAnimationFrame,replacement);});
test('production smoke retains original 90-second deadline and exact stage readiness gate',()=>{assert.match(source,/worldEnd = performance.now\(\) \+ 90000/);assert.match(source,/Production world did not finish loading/);assert.match(source,/getAttribute\('aria-busy'\) !== 'false'/);assert.doesNotMatch(source,/document.hidden\s*=/);});

test('diagnostics count minified and anonymous production callbacks without calling them app frames',()=>{const f=fixture(),observer=observe(f.win,f.doc,f.now);function a(){}f.win.requestAnimationFrame(a);f.win.requestAnimationFrame(()=>{});f.pending.get(1)(1000);f.pending.get(2)(1000);const delivery=observer.sample().rafDelivery;assert.equal(delivery.callbacks,2);assert.equal(delivery.distinctTimestamps,1);assert.equal(delivery.callbackNames.a,1);assert.equal(delivery.callbackNames['(anonymous)'],1);observer.stop();});

test('smoke phase diagnostics retain unresolved phases, completed waits and ownership cleanup',()=>{const f=fixture(),previous=()=>{};f.win.__desktopSmokeLoadingSpan=previous;const observer=observe(f.win,f.doc,f.now),hook=f.win.__desktopSmokeLoadingSpan;hook.onBegin({label:'warm-compile-world',start:0});f.set({clock:30000});assert.equal(observer.sample().spans.active[0].elapsedMs,30000);hook({label:'loading-compile-readiness-wait',start:1,end:30001,duration:30000,scope:'Awaited readiness; not CPU/GPU'});assert.equal(observer.sample().spans.totals['loading-compile-readiness-wait'].totalMs,30000);hook({label:'warm-compile-world',start:0,end:30002,duration:30002});assert.equal(observer.sample().spans.active.length,0);observer.stop();assert.equal(f.win.__desktopSmokeLoadingSpan,previous);});

const modelLoad=runInNewContext(source.slice(0,source.indexOf('// Runs only'))+';observeDesktopModelLoad');
test('native preflight attribution uses one fetch, one original body read and one decode',async()=>{
 let clock=0,fetches=0,bodies=0,decodes=0;const input=new ArrayBuffer(12),output=new ArrayBuffer(24);
 const result=await modelLoad('model.glb',async path=>{assert.equal(path,'model.glb');fetches++;clock=10;return {arrayBuffer:async()=>{bodies++;clock=30;return input;}};},async buffer=>{decodes++;assert.equal(buffer,input);clock=40;return output;},()=>clock);
 assert.equal(result.decoded,output);assert.deepEqual([fetches,bodies,decodes],[1,1,1]);assert.equal(result.stages.fetchToHeadersMs,10);assert.equal(result.stages.bodyCollectionMs,20);assert.equal(result.stages.decodeMs,10);assert.equal(result.stages.bytes,12);assert.match(result.stages.scope,/dispatcher/);
});
test('native preflight preserves the exact original decode rejection without another request',async()=>{
 const original=Error('decoder');let calls=0;await assert.rejects(modelLoad('model.glb',async()=>{calls++;return {arrayBuffer:async()=>new ArrayBuffer(1)};},()=>{throw original;},()=>0),error=>error===original);assert.equal(calls,1);
});
