import test from 'node:test';
import assert from 'node:assert/strict';
import {setFarComponentIsolation} from './browser/far-component-isolation.js';
function fixture(){const root={visible:true},material={visible:true},shared={visible:true},ground={visible:true,userData:{farGround:true}},draw={mesh:{parent:root,material:shared}},adapter={layer:{current:{prototype:{impostors:{material,children:[ground]}}}},standbyDraws:()=>[draw]};return {root,material,shared,ground,adapter,backdrop:{visible:true}};}
test('component isolation changes only its category and restores prior QA masks',()=>{const f=fixture();setFarComponentIsolation([f.adapter],f.backdrop,'no-sprites');assert.equal(f.material.visible,false);assert.equal(f.ground.visible,true);assert.equal(f.root.visible,true);assert.equal(f.shared.visible,true);setFarComponentIsolation([f.adapter],f.backdrop,'no-standby');assert.equal(f.material.visible,true);assert.equal(f.root.visible,false);assert.equal(f.shared.visible,true);setFarComponentIsolation([f.adapter],f.backdrop,'no-backdrop');assert.equal(f.root.visible,true);assert.equal(f.backdrop.visible,false);setFarComponentIsolation([f.adapter],f.backdrop);assert.equal(f.backdrop.visible,true);});
test('freshly adopted bank roots receive the mask without editing matrices or shared materials',()=>{const f=fixture(),matrix=[1,2,3],newRoot={visible:true};f.adapter.standbyDraws=()=>[{mesh:{parent:newRoot,material:f.shared,instanceMatrix:{array:matrix}}}];setFarComponentIsolation([f.adapter],null,'no-standby');assert.equal(newRoot.visible,false);assert.deepEqual(matrix,[1,2,3]);assert.equal(f.shared.visible,true);assert.equal(f.root.visible,true);assert.throws(()=>setFarComponentIsolation([f.adapter],null,'unknown'),/Invalid/);});

test('QA masks never resurrect disabled owner banks or backdrop during native baseline',()=>{const f=fixture();f.adapter.enabled=false;for(const mode of ['all','no-sprites','no-standby','no-backdrop']){setFarComponentIsolation([f.adapter],f.backdrop,mode,false);assert.equal(f.root.visible,false);assert.equal(f.backdrop.visible,false);}f.adapter.enabled=true;setFarComponentIsolation([f.adapter],f.backdrop,'all',true);assert.equal(f.root.visible,true);assert.equal(f.backdrop.visible,true);});


test('ground isolation includes new regional proxies and respects independent user hiding',()=>{const f=fixture(),other={visible:true,userData:{}};f.adapter.layer.current.prototype.impostors.children.push(other);setFarComponentIsolation([f.adapter],f.backdrop,'no-ground');assert.equal(f.ground.visible,false);assert.equal(f.material.visible,true);assert.equal(f.root.visible,true);assert.equal(other.visible,true);setFarComponentIsolation([f.adapter],f.backdrop,'all',true,false);assert.equal(f.ground.visible,false);setFarComponentIsolation([f.adapter],f.backdrop);assert.equal(f.ground.visible,true);});
