import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {createStandbyMaterialProbe} from './browser/far-standby-material.js';
function fixture(){const source=new THREE.MeshStandardMaterial({map:new THREE.Texture(),alphaTest:.35,side:THREE.DoubleSide,color:0xabc123});source.userData.nativeSurface={params:[.87,0,1,0]};const mesh={material:source},adapter={standbyDraws:()=>[{mesh}]};return {source,mesh,adapter};}
test('diagnostic bridge preserves alpha sampling and dither without changing native sources',()=>{const f=fixture(),originalCompile=f.source.onBeforeCompile,probe=createStandbyMaterialProbe();probe.update([f.adapter],'basic');const material=f.mesh.material;assert.equal(material.isMeshBasicMaterial,true);assert.equal(material.map,f.source.map);assert.equal(material.alphaTest,.35);assert.equal(material.side,f.source.side);assert.deepEqual(material.color,f.source.color);const shader={vertexShader:'#include <begin_vertex>',fragmentShader:'#include <map_fragment>\n#include <clipping_planes_fragment>',uniforms:{}};material.onBeforeCompile(shader,{});assert.match(shader.fragmentShader,/texture2D\( map, vMapUv, \.65 \)/);assert.match(shader.fragmentShader,/vNativeVisibility/);assert.equal(f.source.onBeforeCompile,originalCompile);probe.update([f.adapter],'basic');assert.equal(f.mesh.material,material);assert.equal(probe.size,1);probe.update([f.adapter],'native');assert.equal(f.mesh.material,f.source);assert.equal(probe.size,0);});
test('replaced banks and owner disposal release private probes exactly once and preserve shared maps',()=>{const f=fixture(),probe=createStandbyMaterialProbe();let mapDisposals=0;f.source.map.addEventListener('dispose',()=>mapDisposals++);probe.update([f.adapter],'basic');let privateDisposals=0;f.mesh.material.addEventListener('dispose',()=>privateDisposals++);probe.update([],'basic');assert.equal(privateDisposals,1);assert.equal(f.mesh.material,f.source);probe.update([f.adapter],'basic');f.mesh.material.addEventListener('dispose',()=>privateDisposals++);probe.dispose();probe.dispose();assert.equal(privateDisposals,2);assert.equal(mapDisposals,0);assert.equal(f.mesh.material,f.source);assert.throws(()=>probe.update([]),/Disposed/);});

test('native noise diagnostic changes only its private noise uniform and key, keeps shared clocks/textures',()=>{const f=fixture(),noise={value:1},night={value:.5};f.source.onBeforeCompile=shader=>{shader.uniforms={uFineNoise:noise,uNight:night};shader.fragmentShader='native-recipe';};f.source.customProgramCacheKey=()=> 'native-key';const controller=createStandbyMaterialProbe();controller.update([f.adapter],'no-noise');const material=f.mesh.material,shader={uniforms:{}};material.onBeforeCompile(shader,{});assert.equal(material.isMeshStandardMaterial,true);assert.equal(material.map,f.source.map);assert.equal(material.normalMap,f.source.normalMap);assert.equal(shader.fragmentShader,'native-recipe');assert.deepEqual(shader.uniforms.uFineNoise,{value:0});assert.equal(noise.value,1);assert.equal(shader.uniforms.uNight,night);assert.match(material.customProgramCacheKey(),/native-key\|QA-standby-fine-noise-0/);controller.update([f.adapter],'basic');assert.equal(f.mesh.material.isMeshBasicMaterial,true);controller.dispose();assert.equal(f.mesh.material,f.source);});
