import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {WorldScene} from '../src/rendering/scene.js';import {activeChunkRegion} from '../src/world/active-region.js';
for(const quality of ['muy_baja','baja','media','alta'])test(quality+': a compact visual world retains the normal raid border and logical prop state',()=>{for(const range of [null,1,2,3]){const eye=new THREE.Vector3(149,20,-30),suppressed=new Set(['tree-preserved']),routes=new Map([['logical-path',[1,2,3]]]),world=Object.create(WorldScene.prototype);let jobs;Object.assign(world,{camera:{position:eye},quality,farResidentRange:range,nav:{config:{layers:[]},suppressed,routes,setActiveBounds(bounds){this.activeBounds=[...bounds];},setRaidView(){}},prototypes:[],pack:{profile:{}},horizon:{update:()=>null},chunks:new Map(),terrainMeshes:[],controls:{target:new THREE.Vector3()},chunkStream:{plan(next){jobs=next;},dispatch(){}},contacts:{update(){}},syncResidentProps(){}});world.syncChunks();assert.deepEqual(world.nav.activeBounds,activeChunkRegion(eye,quality).bounds);assert.equal(jobs.size,Math.pow(2*(range??(quality==='alta'?3:2))+1,2));assert.deepEqual(world.nearBounds,activeChunkRegion(eye,quality,range).bounds);assert.equal(world.nav.suppressed,suppressed);assert.equal(world.nav.routes,routes);assert.deepEqual(routes.get('logical-path'),[1,2,3]);}});
test('visual-only compaction preserves exact terrain picking, CPU residency, raid bounds, and restores visibility',()=>{
 const world=Object.create(WorldScene.prototype),eye=new THREE.Vector3(0,10,0);let requested,invalidation=0;Object.assign(world,{camera:{position:eye},quality:'media',farVisualRange:1,nav:{config:{layers:[]},setActiveBounds(bounds){this.activeBounds=[...bounds];},setRaidView(){}},prototypes:[],pack:{profile:{}},horizon:{update(c,p,r){requested=r;return r;}},chunks:new Map(),terrainMeshes:[],controls:{target:new THREE.Vector3()},chunkStream:{plan(){},dispatch(){}},contacts:{update(){}},syncResidentProps(){},releaseNativeShadow:{cache:{invalidate(){invalidation++;}}}});const scene=new THREE.Scene();
 for(let z=-2;z<=2;z++)for(let x=-2;x<=2;x++){const group=new THREE.Group();group.position.set(x*48,0,z*48);group.userData.nativeChunkOrigin=[x*48,z*48];const mesh=new THREE.Mesh(new THREE.PlaneGeometry(48,48).rotateX(-Math.PI/2),new THREE.MeshBasicMaterial());group.add(mesh);scene.add(group);world.chunks.set(x+','+z,group);world.terrainMeshes.push(mesh);}
 world.syncChunks();assert.equal(requested.range,1);assert.equal(world.chunks.size,25);assert.equal(world.terrainMeshes.length,25);assert.equal([...world.chunks.values()].filter(g=>g.visible).length,9);assert.deepEqual(world.nearBounds,[-72,-72,72,72]);assert.deepEqual(world.nav.activeBounds,[-120,-120,120,120]);assert.equal(invalidation,1);scene.updateMatrixWorld(true);
 for(const group of world.chunks.values()){const ray=new THREE.Raycaster(group.position.clone().add(new THREE.Vector3(0,10,0)),new THREE.Vector3(0,-1,0));const hits=ray.intersectObjects(world.terrainMeshes,false);assert.ok(hits.length);assert.equal(hits[0].point.y,0);assert.equal(hits[0].point.x,group.position.x);assert.equal(hits[0].point.z,group.position.z);}
 world.farVisualRange=null;world.syncChunks();assert.equal(world.chunks.size,25);assert.equal([...world.chunks.values()].filter(g=>g.visible).length,25);assert.deepEqual(world.nearBounds,world.nav.activeBounds);assert.equal(invalidation,2);for(const mesh of world.terrainMeshes){mesh.geometry.dispose();mesh.material.dispose();}
});

test('tree-only compaction keeps exact ground and native horizon extents while shortening prop color residency',()=>{
 const world=Object.create(WorldScene.prototype);let horizonRequest;Object.assign(world,{camera:{position:new THREE.Vector3(0,10,0)},quality:'media',farVisualRange:1,farPreserveTerrain:true,nav:{config:{layers:[]},setActiveBounds(bounds){this.activeBounds=bounds;},setRaidView(){}},prototypes:[],pack:{profile:{}},horizon:{update(c,p,r){horizonRequest=r;return r;}},chunks:new Map(),terrainMeshes:[],controls:{target:new THREE.Vector3()},chunkStream:{plan(){},dispatch(){}},contacts:{update(){}},syncResidentProps(){}});
 for(let z=-2;z<=2;z++)for(let x=-2;x<=2;x++){const g=new THREE.Group();g.userData.nativeChunkOrigin=[x*48,z*48];world.chunks.set(x+','+z,g);}
 world.syncChunks();assert.equal(horizonRequest.range,2);assert.equal([...world.chunks.values()].filter(g=>g.visible).length,25);assert.equal([...world.chunks.values()].filter(g=>g.userData.farPropsVisible).length,9);assert.deepEqual(world.nearBounds,[-120,-120,120,120]);assert.deepEqual(world.nav.activeBounds,world.nearBounds);
 world.farVisualRange=null;world.syncChunks();assert.ok([...world.chunks.values()].every(g=>g.visible&&g.userData.farPropsVisible));
});
