import test from 'node:test';import assert from 'node:assert/strict';import {FirstCropTrace} from './browser/first-crop-trace.js';
test('forwards native calls once with receiver/return, records only threshold calls and adds no queries',()=>{let calls=0,clock=0;const gl={getProgramInfoLog(program){assert.equal(this,gl);assert.equal(program,7);calls++;clock+=10;return 'native';}};const renderer={getContext:()=>gl};const original=gl.getProgramInfoLog,trace=new FirstCropTrace(renderer,{now:()=>clock});assert.equal(gl.getProgramInfoLog(7),'native');assert.equal(calls,1);assert.equal(trace.report.calls[0].cpuMs,10);assert.equal(trace.report.calls[0].method,'getProgramInfoLog');trace.dispose();trace.dispose();assert.equal(gl.getProgramInfoLog,original);});
test('bounds records and preserves native exceptions',()=>{let clock=0;const gl={linkProgram(){clock+=9;throw Error('native-failure');}};const trace=new FirstCropTrace({getContext:()=>gl},{now:()=>clock,limit:1});assert.throws(()=>gl.linkProgram(),/native-failure/);assert.throws(()=>gl.linkProgram(),/native-failure/);assert.equal(trace.report.calls.length,1);trace.dispose();});
test('does not overwrite a later wrapper owner during cleanup',()=>{const gl={getProgramInfoLog(){}};const trace=new FirstCropTrace({getContext:()=>gl});const later=()=>{};gl.getProgramInfoLog=later;trace.dispose();assert.equal(gl.getProgramInfoLog,later);});

test('records pinned Three r180 renderBufferDirect material/object positions',()=>{let clock=0;const renderer={getContext:()=>({}),renderBufferDirect(){clock+=8;}};const trace=new FirstCropTrace(renderer,{now:()=>clock});renderer.renderBufferDirect({}, {}, {}, {name:'crop-depth',type:'MeshDepthMaterial',customProgramCacheKey:()=> 'growth-depth'}, {name:'maize-stage-0',type:'InstancedMesh'}, {});assert.equal(trace.report.calls[0].object,'maize-stage-0');assert.equal(trace.report.calls[0].material,'crop-depth');assert.equal(trace.report.calls[0].recipe,'growth-depth');trace.dispose();});

test('upload attribution reads source dimensions without GL queries',()=>{let clock=0,calls=0;class FakeBitmap{constructor(){this.width=2048;this.height=1024;}}const image=new FakeBitmap(),gl={texSubImage2D(...args){calls++;clock+=8;},texImage2D(...args){calls++;clock+=8;},getParameter(){assert.fail('must not query');}};const trace=new FirstCropTrace({getContext:()=>gl},{now:()=>clock});gl.texSubImage2D(3553,0,0,0,6408,5121,image);gl.texSubImage2D(3553,1,0,0,128,64,6408,5121,new Uint8Array(128*64*4));gl.texImage2D(3553,0,6408,6408,5121,image);assert.equal(calls,3);assert.deepEqual(trace.report.calls.map(c=>[c.width,c.height,c.imageType]),[[2048,1024,'FakeBitmap'],[128,64,'Uint8Array'],[2048,1024,'FakeBitmap']]);trace.dispose();});
test('shadow attribution retains actual selected program and assigned map source metadata',()=>{let clock=0;const map={uuid:'atlas-original',source:{id:42},image:{width:2048,height:2048}},renderer={getContext:()=>({}),properties:{get:()=>({currentProgram:{cacheKey:'actual-linear-shadow-no-fog'}})},renderBufferDirect(){clock+=8;}};const trace=new FirstCropTrace(renderer,{now:()=>clock});renderer.renderBufferDirect({},null,{}, {type:'MeshDepthMaterial',map}, {name:'maize',type:'Mesh'},null);assert.equal(trace.report.calls[0].programCacheKey,'actual-linear-shadow-no-fog');assert.deepEqual(trace.report.calls[0].map,{uuid:'atlas-original',sourceId:42,width:2048,height:2048,imageType:'Object'});trace.dispose();});
