import test from 'node:test';import assert from 'node:assert/strict';
import {installGlResourceEpoch,createRendererWithGlEpoch} from '../src/rendering/gl-resource-epoch.js';
const pairs=[['createBuffer','deleteBuffer'],['createVertexArray','deleteVertexArray'],['createTexture','deleteTexture'],['createProgram','deleteProgram'],['createShader','deleteShader'],['fenceSync','deleteSync'],['createFramebuffer','deleteFramebuffer'],['createRenderbuffer','deleteRenderbuffer']];
function fixture(){const deleted=[],canvas=new EventTarget(),gl={canvas,getError(){throw new Error('No GL queries permitted');}};for(const [create,remove]of pairs){gl[create]=function(...args){assert.equal(this,gl);return {create,args};};gl[remove]=function(...args){assert.equal(this,gl);deleted.push({remove,args});return 'native';};}return {gl,canvas,deleted};}
for(const [create,remove]of pairs)test(create+' keeps current/unknown/type-mismatched deletes and rejects only known old epoch',()=>{const f=fixture(),guard=installGlResourceEpoch(f.gl),old=f.gl[create]('arg');assert.equal(f.gl[remove](old),'native');f.canvas.dispatchEvent(new Event('webglcontextlost'));f.canvas.dispatchEvent(new Event('webglcontextrestored'));assert.equal(f.gl[remove](old),undefined);const current=f.gl[create]('new');assert.equal(f.gl[remove](current),'native');assert.equal(f.gl[remove]({}),'native');assert.equal(f.gl[remove](null),'native');const other=f.gl[create==='createBuffer'?'createTexture':'createBuffer']();assert.equal(f.gl[remove](other),'native');assert.equal(f.deleted.length,5);assert.equal(guard.stats.staleDeletes,1);guard.dispose();});
test('multiple loss/restore cycles track resources created by the first restoration listener',()=>{const f=fixture();let restored;f.canvas.addEventListener('webglcontextrestored',()=>{restored=f.gl.createBuffer();});const guard=installGlResourceEpoch(f.gl),first=f.gl.createBuffer();for(let i=1;i<=3;i++){const previous=restored??first;f.canvas.dispatchEvent(new Event('webglcontextlost'));f.canvas.dispatchEvent(new Event('webglcontextrestored'));f.gl.deleteBuffer(previous);f.gl.deleteBuffer(restored);assert.equal(guard.stats.epoch,i);}assert.equal(guard.stats.staleDeletes,3);assert.equal(f.deleted.length,3);guard.dispose();});
test('dispose restores own and inherited descriptors, listeners, and is idempotent',()=>{const f=fixture(),original=f.gl.createBuffer,remove=f.gl.deleteBuffer;const inherited=Object.create(f.gl);inherited.canvas=f.canvas;const guard=installGlResourceEpoch(inherited);assert.equal(Object.hasOwn(inherited,'createBuffer'),true);guard.dispose();guard.dispose();assert.equal(Object.hasOwn(inherited,'createBuffer'),false);assert.equal(inherited.createBuffer,original);assert.equal(inherited.deleteBuffer,remove);f.canvas.dispatchEvent(new Event('webglcontextlost'));assert.equal(guard.stats.epoch,0);});
test('unknown and current handles preserve native errors without consuming getError',()=>{const f=fixture();f.gl.deleteBuffer=()=>{throw new Error('native invalid handle');};const guard=installGlResourceEpoch(f.gl),old=f.gl.createBuffer();assert.throws(()=>f.gl.deleteBuffer(old),/native invalid handle/);assert.throws(()=>f.gl.deleteBuffer({}),/native invalid handle/);f.canvas.dispatchEvent(new Event('webglcontextlost'));assert.doesNotThrow(()=>f.gl.deleteBuffer(old));guard.dispose();});
test('constructor intercept preserves native context args and installs before allocation',()=>{const f=fixture(),calls=[];const original=function(...args){assert.equal(this,f.canvas);calls.push(args);return f.gl;};f.canvas.getContext=original;const attributes={alpha:true,antialias:true};let created;const {renderer,guard}=createRendererWithGlEpoch(f.canvas,()=>{const gl=f.canvas.getContext('webgl2',attributes);created=gl.createBuffer();return {gl};});assert.equal(renderer.gl,f.gl);assert.deepEqual(calls,[['webgl2',attributes]]);assert.equal(f.canvas.getContext,original);assert.equal(guard.stats.created,1);f.canvas.dispatchEvent(new Event('webglcontextlost'));f.gl.deleteBuffer(created);assert.equal(f.deleted.length,0);guard.dispose();});
test('failed constructor releases context hooks and original methods, preserving its error',()=>{const f=fixture(),original=f.gl.createBuffer;f.canvas.getContext=()=>f.gl;const get=f.canvas.getContext;assert.throws(()=>createRendererWithGlEpoch(f.canvas,()=>{f.canvas.getContext('webgl2');throw new Error('constructor failure');}),/constructor failure/);assert.equal(f.gl.createBuffer,original);assert.equal(f.canvas.getContext,get);});
test('null context and unsupported methods retain constructor behavior',()=>{const canvas={getContext:()=>null},original=canvas.getContext;const result=createRendererWithGlEpoch(canvas,()=>{assert.equal(canvas.getContext('webgl2'),null);return 7;});assert.equal(result.renderer,7);assert.equal(result.guard,null);assert.equal(canvas.getContext,original);});
