import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {convexHull,impostorHullShape} from '../tools/experiments/impostor-hull.js';import {createFarImpostorPrototype} from '../tools/experiments/far-impostor-prototype.js';
const hull=convexHull([[.3,0],[.7,0],[1,.6],[1,1],[0,1],[0,.6]]);
test('convex hull discards interior points but strictly preserves all boundary supports',()=>{const result=convexHull([...hull,[.5,.5],[.3,0]]);assert.deepEqual(result,hull);for(const p of [[.5,.5],...hull])for(let i=0;i<hull.length;i++){const a=hull[i],b=hull[(i+1)%hull.length];assert.ok((b[0]-a[0])*(p[1]-a[1])-(b[1]-a[1])*(p[0]-a[0])>=-1e-12);}});
test('hull and rectangle share buffers, UV/base coordinates and explicit draw count without new allocations on toggle',()=>{const h=impostorHullShape(hull),attrs={...h.shape.attributes},index=h.shape.index;assert.equal(h.shape.drawRange.count,12);assert.equal(h.set(false),true);assert.equal(h.shape.drawRange.count,6);assert.deepEqual([...h.shape.attributes.uv.array].slice(0,8),[0,0,1,0,1,1,0,1]);assert.equal(h.set(false),false);h.set(true);for(const [key,value]of Object.entries(attrs))assert.equal(h.shape.attributes[key],value);assert.equal(h.shape.index,index);h.shape.dispose();for(const bad of [[],[[0,0],[1,0],[0,1],[.5,.5]],[[0,0],[2,0],[0,1]],[[0,0],[0,1],[1,0]]])assert.throws(()=>impostorHullShape(bad),/hull/);});
test('geometry switch retains instance IDs/transforms, atlas/shader and readiness without source resource ownership',()=>{const source={geometry:new THREE.BoxGeometry(),material:new THREE.MeshBasicMaterial()},tex=new THREE.Texture(),metadata={impostorHull:hull,impostorWidth:2,impostorHeight:3,localBase:[0,0,0]},trees=[{id:'tree',x:4,y:2,z:6,yaw:.3,scale:1.2}],p=createFarImpostorPrototype(source,tex,metadata,trees,{nativeModels:false}),g=p.impostors.geometry,instance=g.attributes.aTreeBase,shader=p.impostors.material.fragmentShader;p.setTreeReadiness('tree',.7);const ready=g.attributes.aTreeReady;p.setHullEnabled(false);assert.equal(g.drawRange.count,6);p.setHullEnabled(true);assert.equal(g.drawRange.count,12);assert.equal(g.attributes.aTreeBase,instance);assert.deepEqual([...instance.array],[4,2,6]);assert.equal(g.attributes.aTreeReady,ready);assert.ok(Math.abs(p.treeState('tree').ready-.7)<1e-6);assert.equal(p.impostors.material.fragmentShader,shader);assert.equal(p.uniforms.uAtlas.value,tex);p.dispose({disposeTexture:false});source.geometry.dispose();source.material.dispose();tex.dispose();});

test('offline conservative hulls cover alpha in every source cell of both phases and preserve atlas hashes',async()=>{
 const fs=await import('node:fs/promises'),sharp=(await import('sharp')).default,{createHash}=await import('node:crypto'),data=JSON.parse(await fs.readFile('docs/qa/far-hulls-current-public/hulls.json','utf8')),manifest=JSON.parse(await fs.readFile('public/content/far-vegetation.json','utf8'));const historical=JSON.parse(await fs.readFile('docs/qa/far-hull-cost-review/hulls.json','utf8'));assert.deepEqual(data.biomes,historical.biomes,'reviewed current alpha recipe must preserve historical conservative hulls');assert.equal(data.marginPixels,16);let species=0,phases=0;for(const [biome,trees]of Object.entries(manifest.biomes))for(const tree of trees){species++;const shape=data.biomes[biome].find(h=>h.slot===tree.slot);assert.ok(shape.area>0&&shape.area<=1);const geometry=impostorHullShape(shape.hull);geometry.shape.dispose();for(const phase of ['day','night']){phases++;const path='public/'+tree[phase].slice(2),bytes=await fs.readFile(path),raw=await sharp(bytes).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(createHash('sha256').update(bytes).digest('hex'),data.sources.find(s=>s.path===path).sha256);const points=new Set();for(let y=0;y<raw.info.height;y++)for(let x=0;x<raw.info.width;x++)if(raw.data[(y*raw.info.width+x)*4+3])points.add((y%128)*128+x%128);for(const encoded of points){const x=(encoded%128+.5)/128,y=1-(Math.floor(encoded/128)+.5)/128;for(let i=0;i<shape.hull.length;i++){const a=shape.hull[i],b=shape.hull[(i+1)%shape.hull.length];assert.ok((b[0]-a[0])*(y-a[1])-(b[1]-a[1])*(x-a[0])>=-1e-12,biome+'/'+tree.slot+'/'+phase);}}}}assert.equal(species,22);assert.equal(phases,44);
});
