import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {prepareBiomeTangents} from '../src/rendering/biome-tangents.js';
import {prepareBiomeTangentsAsync} from '../src/rendering/prepare-biome-tangents.js';
import {computeTangents} from '../src/rendering/surface-source.js';
test('packed tangent preparation preserves the native typed views and byte-identical results across six biomes',()=>{const types={'<f4':Float32Array,'<u2':Uint16Array,'<u4':Uint32Array};for(const biome of ['savanna','grand_river','mangrove','volcanoes','canyons','desert']){const pack=JSON.parse(readFileSync(new URL('../public/content/biome-'+biome+'.json',import.meta.url))),bytes=readFileSync(new URL('../public'+pack.binary.url,import.meta.url)),buffer=bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength),assets=[pack.assets[0],pack.assets.at(-1)],prepared=prepareBiomeTangents(buffer,assets),view=desc=>new types[desc.type](buffer,desc.offset,desc.count);for(const [a,asset] of assets.entries())for(const [l,lod] of asset.lods.entries())assert.deepEqual(prepared[a][l],computeTangents(view(lod.position),view(lod.normal),view(lod.uv),view(lod.index)),biome+':'+a+':'+l);assert.equal(buffer.byteLength,bytes.byteLength);}});
test('tangent worker transfers a disposable copy and closes on cancellation without touching packed geometry',async()=>{let worker,posted,terminated=0;const buffer=new Uint8Array([1,2,3,4]).buffer,controller=new AbortController(),promise=prepareBiomeTangentsAsync(buffer,[],{signal:controller.signal,workerAvailable:true,createWorker:()=>worker={postMessage(message,transfers){posted={message,transfers};},terminate(){terminated++;}}});assert.notEqual(posted.message.buffer,buffer);assert.deepEqual(new Uint8Array(posted.message.buffer),new Uint8Array(buffer));assert.equal(posted.transfers[0],posted.message.buffer);controller.abort();await assert.rejects(promise,/cancelled/);assert.equal(terminated,1);worker.onmessage({data:{tangents:[]}});assert.equal(terminated,1);assert.equal(buffer.byteLength,4);});
test('tangent worker completion and error settle once and terminate ownership',async()=>{let worker,terminated=0;const createWorker=()=>worker={postMessage(){},terminate(){terminated++;}},buffer=new ArrayBuffer(0);const success=prepareBiomeTangentsAsync(buffer,[],{workerAvailable:true,createWorker});worker.onmessage({data:{tangents:[]}});assert.deepEqual(await success,[]);const failure=prepareBiomeTangentsAsync(buffer,[],{workerAvailable:true,createWorker});worker.onerror({message:'bad packing'});await assert.rejects(failure,/bad packing/);assert.equal(terminated,2);assert.deepEqual(await prepareBiomeTangentsAsync(buffer,[],{workerAvailable:false}),[]);});
