import test from 'node:test';
import assert from 'node:assert/strict';
import {LoadingGpuQa} from '../src/app/loading-gpu-qa.js';
import {installLoadingProgressQa} from '../src/app/loading-progress-qa.js';
function fixture(){const events=[],timer={begin:frame=>{events.push(['begin',frame]);return true;},end:()=>events.push(['end']),poll:()=>events.push(['poll']),report:()=>({pending:2,samples:[{frame:0,ms:5}],disjointEvents:0}),dispose:()=>events.push(['dispose'])};return {events,timer,qa:new LoadingGpuQa({getContext:()=>({})},{timerFactory:()=>timer,now:()=>100})};}
test('single active GPU envelope includes nested synchronous draws and preserves result/failure',()=>{const f=fixture(),result={};assert.equal(f.qa.measure('outer',()=>f.qa.measure('nested',()=>result)),result);assert.deepEqual(f.events,[['begin',0],['end']]);assert.equal(f.qa.labels.length,1);const error=Error('render');assert.throws(()=>f.qa.measure('failed',()=>{throw error;}),e=>e===error);assert.deepEqual(f.events.slice(-2),[['begin',1],['end']]);});
test('close polls/disposes queries once, retains unresolved scope and cannot start late work',()=>{const f=fixture();f.qa.measure('world',()=>{});const a=f.qa.close();assert.equal(a.pendingBeforeDispose,2);assert.match(a.scope,/excludes async/);assert.equal(f.qa.close(),a);assert.equal(f.qa.measure('late',()=>42),42);assert.deepEqual(f.events,[['begin',0],['end'],['poll'],['dispose']]);});
test('explicit disabled application QA never creates GPU timer or touches renderer',()=>{let el;const qa=installLoadingProgressQa({createElement:()=>({textContent:''}),head:{append:e=>el=e}},{gpuFactory:()=>assert.fail('GPU touched')});qa.begin(100,{getContext:()=>assert.fail('GL touched')});qa.invocation('presentation-diorama-render',()=>{});qa.close({snapshot:()=>({ready:false})},null,{cancelled:true});assert.equal(JSON.parse(el.textContent).gpu,undefined);});
test('enabled application QA measures only presentation calls and closes on cancellation/repeat',()=>{let el,closes=0,measures=[];const qa=installLoadingProgressQa({createElement:()=>({textContent:''}),head:{append:e=>el=e}},{gpu:true,gpuFactory:()=>({measure:(label,run)=>{measures.push(label);return run();},close:()=>{closes++;return {pendingBeforeDispose:1};}})});qa.begin(100,{});qa.invocation('presentation-overlay-refresh',()=>{});qa.invocation('presentation-diorama-render',()=>{});qa.invocation('presentation-cinematic-step',()=>{});qa.close({snapshot:()=>({ready:false})},null,{cancelled:true});assert.deepEqual(measures,['presentation-diorama-render','presentation-cinematic-step']);assert.equal(closes,1);assert.equal(JSON.parse(el.textContent).gpu.pendingBeforeDispose,1);qa.close(null,null);assert.equal(closes,1);qa.begin(200,{});qa.close({snapshot:()=>({ready:false})},null);assert.equal(closes,2);});
