import test from 'node:test';
import assert from 'node:assert/strict';
import {loadingProgramIdentityWitness} from '../src/rendering/loading-program-identity.js';

test('identity witness is off without smoke gate and reads no metadata or clock',()=>{
 const old=globalThis.__desktopSmokeLoadingPollWitness;try{delete globalThis.__desktopSmokeLoadingPollWitness;assert.equal(loadingProgramIdentityWitness({properties:{get(){throw Error('unexpected properties');}}},()=>{throw Error('unexpected observer');},()=>{throw Error('unexpected clock');}),null);}finally{globalThis.__desktopSmokeLoadingPollWitness=old;}
});
test('identity copies all existing material variants without compile/readiness/cache callbacks',()=>{
 const old=globalThis.__desktopSmokeLoadingPollWitness;try{globalThis.__desktopSmokeLoadingPollWitness=true;let clock=0,reads=0;const rows=[],program={id:20,name:'TerrainNative',type:'MeshStandardMaterial',cacheKey:'standard,FOG,INSTANCING',isReady(){throw Error('extra query');}},second={...program,id:23,cacheKey:'standard,SHADOW'},material={uuid:'m1',name:'ground',type:'MeshStandardMaterial',defines:{FOG:true,MODE:2},customProgramCacheKey(){throw Error('extra callback');}},variants=new Map([['day',program],['shadow',second]]),renderer={properties:{get(){reads++;return {programs:variants,currentProgram:second};}},compile(){throw Error('extra compile');}};const observe=loadingProgramIdentityWitness(renderer,row=>rows.push(row),()=>clock++);observe(new Set([material]),[{name:'World terrain',type:'Mesh',material,geometry:{type:'BufferGeometry',attributes:{position:{}}},castShadow:true}]);observe(new Set([material]));assert.equal(reads,2);assert.deepEqual(rows[0].identities.map(x=>x.programId),[20,23]);assert.equal(rows[1].identities.length,0);material.defines.MODE=99;variants.clear();assert.equal(rows[0].identities[0].defines.MODE,2);assert.equal(rows[0].identities[0].cacheKey,'standard,FOG,INSTANCING');assert.equal(rows[0].duration,1);assert.equal(rows[0].identities[0].currentProgram,false);assert.equal(rows[0].identities[1].currentProgram,true);assert.equal(rows[0].identities[0].objects[0].name,'World terrain');assert.deepEqual(rows[0].identities[0].objects[0].attributes,['position']);}finally{globalThis.__desktopSmokeLoadingPollWitness=old;}
});
test('identity observer failures cannot alter the original readiness recipe',()=>{
 const old=globalThis.__desktopSmokeLoadingPollWitness;try{globalThis.__desktopSmokeLoadingPollWitness=true;const program={id:1,cacheKey:'x'.repeat(65537)},material={uuid:'m'};let row;const observe=loadingProgramIdentityWitness({properties:{get:()=>({currentProgram:program})}},value=>{row=value;throw Error('observer');});assert.doesNotThrow(()=>observe([material]));assert.equal(row.identities[0].cacheKey.length,65536);assert.equal(row.identities[0].cacheKeyLength,65537);assert.equal(row.identities[0].cacheKeyTruncated,true);}finally{globalThis.__desktopSmokeLoadingPollWitness=old;}
});
