import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {readFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {LoadingDiorama} from '../src/rendering/loading-diorama.js';
import {Assets} from '../src/rendering/assets.js';
import {WorldScene} from '../src/rendering/scene.js';
import {loadingSerialImageChainEnabled} from '../src/rendering/loading-serial-images.js';
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
const flush=async()=>{for(let i=0;i<4;i++)await new Promise(r=>setImmediate(r));};
function fixture(t,{enabled=true}={}){
 const sky=deferred(),model=deferred(),bridge=deferred(),soil=deferred(),atlas=deferred(),calls=[],assets=new Assets(),release=()=>{},stop=Error('adoption boundary');let adoptions=0;
 t.mock.method(globalThis,'fetch',async url=>{calls.push(String(url));return new Response(JSON.stringify(String(url).includes('models.json')?[{source:'Cultivos',url:'/steady.glb'}]:String(url).includes('crop-bridges.json')?{recipeVersion:4,bakedAsset:'/bridges.glb'}:{canyons:{base:'/soil.webp'}}));});
 assets.loader.loadAsync=url=>{calls.push(url);return url==='/steady.glb'?model.promise:bridge.promise;};
 assets.textures.loadAsync=url=>{calls.push(url==='/soil.webp'?'soil':'atlas');return url==='/soil.webp'?soil.promise:atlas.promise;};
 const world=Object.assign(Object.create(WorldScene.prototype),{loading:new AbortController(),assets,sky:{load:()=>{calls.push('sky');return sky.promise;}}});
 const owner=Object.assign(Object.create(LoadingDiorama.prototype),{world,serialImageChain:enabled,resourceOverlap:false,abort:new AbortController(),mist:{dispose:release},ground:{geometry:{dispose:release},material:{dispose:release,color:{set:release}}},textureOwner:{borrow:()=>{adoptions++;throw stop;},dispose:release},toon:{shadowUniforms:{uNativeShadowFiltered:{value:null},fallback:{dispose:release}}},scene:{clear:release}});
 const steady={scene:new THREE.Scene()},bridges={scene:new THREE.Scene()};for(let i=0;i<32;i++){const mesh=new THREE.Mesh();mesh.userData.bridgeIndex=i;bridges.scene.add(mesh);}
 const close=()=>{owner.dispose();world.disposed=true;world.loading.abort();assets.disposeModels();};
 return {sky,model,bridge,soil,atlas,calls,assets,world,owner,steady,bridges,stop,close,get adoptions(){return adoptions;}};
}
test('real prepare preserves sky/catalogues, overlaps GLB pair with soil then atlas, joins before scene/GPU adoption',async t=>{
 const f=fixture(t),pending=f.owner.prepare(),rejected=assert.rejects(pending,e=>e===f.stop);await flush();assert.deepEqual(f.calls,['sky']);f.sky.resolve();await flush();assert.ok(f.calls.includes('/steady.glb'));assert.ok(f.calls.includes('/bridges.glb'));assert.ok(f.calls.includes('soil'));assert.ok(!f.calls.includes('atlas'));assert.equal(f.adoptions,0);
 f.soil.resolve(new THREE.Texture());await flush();assert.ok(f.calls.includes('atlas'));f.atlas.resolve(new THREE.Texture());await flush();assert.equal(f.adoptions,0);f.model.resolve(f.steady);await flush();assert.equal(f.adoptions,0);f.bridge.resolve(f.bridges);await rejected;assert.equal(f.adoptions,1);
 assert.strictEqual(await f.assets.model('/steady.glb'),f.steady);assert.strictEqual(await f.assets.model('/bridges.glb'),f.bridges);assert.equal(f.calls.filter(x=>x==='/steady.glb').length,1);assert.equal(f.calls.filter(x=>x==='/bridges.glb').length,1);f.close();
});
test('default OFF real prepare preserves GLB join before soil, then atlas',async t=>{const f=fixture(t,{enabled:false}),pending=f.owner.prepare(),rejected=assert.rejects(pending,e=>e===f.stop);f.sky.resolve();await flush();assert.ok(!f.calls.includes('soil'));f.model.resolve(f.steady);f.bridge.resolve(f.bridges);await flush();assert.ok(f.calls.includes('soil'));assert.ok(!f.calls.includes('atlas'));f.soil.resolve(new THREE.Texture());await rejected;assert.ok(!f.calls.includes('atlas'));f.close();});
test('failed GLB sibling prevents atlas after late soil and observes late bridge rejection',async t=>{const f=fixture(t),errors=[],hook=e=>errors.push(e);process.on('unhandledRejection',hook);try{const error=Error('model failure'),pending=f.owner.prepare().catch(e=>{f.close();throw e;}),rejected=assert.rejects(pending,e=>e===error);f.sky.resolve();await flush();f.model.reject(error);await rejected;const texture=new THREE.Texture();let count=0;texture.addEventListener('dispose',()=>count++);f.soil.resolve(texture);f.bridge.reject(Error('late bridge'));await flush();assert.equal(count,1);assert.ok(!f.calls.includes('atlas'));assert.equal(f.adoptions,0);assert.deepEqual(errors,[]);}finally{process.off('unhandledRejection',hook);}});
test('soil failure never starts atlas; all pending GLB rejections observed',async t=>{const f=fixture(t),errors=[],hook=e=>errors.push(e);process.on('unhandledRejection',hook);try{const error=Error('soil failure'),pending=f.owner.prepare().catch(e=>{f.close();throw e;}),rejected=assert.rejects(pending,e=>e===error);f.sky.resolve();await flush();f.soil.reject(error);await rejected;f.model.reject(Error('late model'));f.bridge.reject(Error('late bridge'));await flush();assert.ok(!f.calls.includes('atlas'));assert.deepEqual(errors,[]);}finally{process.off('unhandledRejection',hook);}});
test('real TextureLoader fallback atlas arrival after failed sibling is disposed exactly once',async t=>{const f=fixture(t),pending=f.owner.prepare().catch(e=>{f.close();throw e;}),error=Error('bridge failure'),rejected=assert.rejects(pending,e=>e===error);f.sky.resolve();await flush();f.soil.resolve(new THREE.Texture());await flush();assert.ok(f.calls.includes('atlas'));f.bridge.reject(error);await rejected;let disposed=0;const texture=new THREE.Texture();texture.addEventListener('dispose',()=>disposed++);f.atlas.resolve(texture);f.model.resolve(f.steady);await flush();assert.equal(disposed,1);assert.equal(f.owner.backdropTexture,undefined);f.close();assert.equal(disposed,1);});
test('abort during pending soil prevents atlas and late shared resources dispose once',async t=>{const f=fixture(t),pending=f.owner.prepare(),rejected=assert.rejects(pending);f.sky.resolve();await flush();f.close();await rejected;let count=0;const texture=new THREE.Texture();texture.addEventListener('dispose',()=>count++);f.soil.resolve(texture);f.model.resolve(f.steady);f.bridge.resolve(f.bridges);await flush();assert.ok(!f.calls.includes('atlas'));assert.equal(count,1);assert.equal(f.adoptions,0);});
test('sky failure prevents every catalogue/resource start; mutually exclusive recipes fail before loading',async t=>{const f=fixture(t),error=Error('sky'),pending=f.owner.prepare(),rejected=assert.rejects(pending,e=>e===error);f.sky.reject(error);await rejected;assert.deepEqual(f.calls,['sky']);f.owner.resourceOverlap=true;await assert.rejects(f.owner.prepare(),/isolated/);assert.deepEqual(f.calls,['sky']);f.close();});
test('GPU warm tail and default OFF loader branch remain byte-identical',()=>{const source=readFileSync(new URL('../src/rendering/loading-diorama.js',import.meta.url),'utf8'),original=execFileSync('git',['show','37427276:src/rendering/loading-diorama.js'],{encoding:'utf8'});const normal=source.replace("    if(world.cropPartition&&(this.resourceOverlap||this.serialImageChain))throw Error('Crop partition must remain isolated');\n",'').replace("world.cropPartition?world.cropPartition.models('maize'):world.assets.model(descriptor.url)",'world.assets.model(descriptor.url)').replace("world.cropPartition?world.cropPartition.bridges(bridges,'maize'):loadCropBridges(bridges,url=>world.assets.model(url))",'loadCropBridges(bridges,url=>world.assets.model(url))');assert.equal(normal.replaceAll('\r\n','\n'),original.replaceAll('\r\n','\n'));assert.match(source,/serialImageChain=false/);});
test('serial image selection requires explicit smoke ownership and boolean opt-in',()=>{
 for(const value of [undefined,null,false,0,1,'true',{}])assert.equal(loadingSerialImageChainEnabled({__desktopSmokeStarted:true,__desktopSmokeSerialImageChain:value}),false);
 assert.equal(loadingSerialImageChainEnabled({__desktopSmokeStarted:true,__desktopSmokeSerialImageChain:true}),true);
 let reads=0;assert.equal(loadingSerialImageChainEnabled({get __desktopSmokeSerialImageChain(){reads++;throw Error('ordinary path must not read flag');}}),false);assert.equal(reads,0);
 assert.equal(loadingSerialImageChainEnabled({__desktopSmokeStarted:false,__desktopSmokeSerialImageChain:true}),false);
});
test('App, guarded CLI, explicit recipe and both original workflow gates wire smoke-only selection',()=>{
 const read=p=>readFileSync(new URL('../'+p,import.meta.url),'utf8'),app=read('src/app/main.js'),rust=read('src-tauri/src/main.rs'),smoke=read('src-tauri/smoke.js'),workflow=read('.github/workflows/windows.yml');
 assert.match(app,/serialImageChain:loadingSerialImageChainEnabled\(\)/);
 assert.ok(rust.indexOf('arg == "--smoke-report"')<rust.indexOf('let serial_image_chain'));
 assert.match(rust,/let serial_image_chain = std::env::args\(\).any\(\|arg\| arg == "--smoke-serial-image-chain"\)/);
 assert.match(smoke,/serialImageChain:window.__desktopSmokeSerialImageChain===true/);
 assert.match(workflow,/serial_image_chain:[\s\S]*?type: boolean\s+default: false/);
 assert.equal(workflow.match(/\$smokeArgs \+= '--smoke-serial-image-chain'/g).length,2);
 assert.match(smoke,/worldEnd = worldStartedAt \+ 90000/);assert.match(smoke,/await wait\(300000\)/);assert.match(workflow,/WaitForExit\(900000\)/);
 for(const flag of ['wall_buffer_package','compile_window','resource_overlap'])assert.match(workflow,new RegExp(flag+':[\\s\\S]*?type: boolean\\s+default: false'));
});
test('existing bitmap atlas path retains flipY/owner disposer after abort',async t=>{const f=fixture(t),previousWorker=globalThis.Worker,previousBitmap=globalThis.createImageBitmap;try{globalThis.Worker=function(){};globalThis.createImageBitmap=()=>{};let options;f.assets.loadingTexture=(url,value)=>{f.calls.push('bitmap atlas');options=value;return f.atlas.promise;};const pending=f.owner.prepare(),rejected=assert.rejects(pending);f.sky.resolve();await flush();f.soil.resolve(new THREE.Texture());await flush();assert.deepEqual(options,{flipY:true,premultiplyAlpha:false});assert.ok(f.calls.includes('bitmap atlas'));f.close();await rejected;const texture=new THREE.Texture();let count=0;texture.addEventListener('dispose',()=>count++);f.atlas.resolve(texture);f.model.resolve(f.steady);f.bridge.resolve(f.bridges);await flush();assert.equal(count,1);assert.equal(f.adoptions,0);}finally{globalThis.Worker=previousWorker;globalThis.createImageBitmap=previousBitmap;}});
