import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {pauseLoadingMenu} from '../src/app/loading-menu-pause.js';
function fixture(){const calls=[],frame={isConnected:true,contentWindow:{WildGuardiansMenu:{setRenderPaused(value){calls.push(value);}}}};let current=frame;return {calls,frame,get:()=>current,replace(value){current=value;}};}
test('default path never reads or changes menu',()=>{pauseLoadingMenu(()=>{throw Error('unexpected read');})()});
test('definitive pause restores same connected owner once on completion/error/cancel',()=>{for(const reason of ['ready','error','cancel']){const f=fixture(),restore=pauseLoadingMenu(f.get,{enabled:true});try{assert.deepEqual(f.calls,[true]);if(reason!=='ready')throw Error(reason);}catch{}finally{restore();restore();}assert.deepEqual(f.calls,[true,false]);}});
test('removed/replaced menu is not retained or resumed through stale API',()=>{const f=fixture(),restore=pauseLoadingMenu(f.get,{enabled:true});f.frame.isConnected=false;const replacement=fixture();f.replace(replacement.frame);restore();assert.deepEqual(f.calls,[true]);assert.deepEqual(replacement.calls,[]);});
test('missing/cross-origin API is safe and pause failure attempts rollback',()=>{pauseLoadingMenu(()=>null,{enabled:true})();pauseLoadingMenu(()=>{throw Error('frame access');},{enabled:true})();const f=fixture();f.frame.contentWindow.WildGuardiansMenu.setRenderPaused=value=>{f.calls.push(value);if(value)throw Error('after mutation');};pauseLoadingMenu(f.get,{enabled:true})();assert.deepEqual(f.calls,[true,false]);});
test('restore failure does not replace a game cancellation/error',()=>{const f=fixture(),error=Error('game');const restore=pauseLoadingMenu(f.get,{enabled:true});f.frame.contentWindow.WildGuardiansMenu.setRenderPaused=()=>{throw Error('restore');};assert.throws(()=>{try{throw error;}finally{restore();}},e=>e===error);});
test('start path owns restore in finally and preparation does not pause menu',()=>{const source=readFileSync(new URL('../src/app/main.js',import.meta.url),'utf8'),start=source.slice(source.indexOf('async function startGame('),source.indexOf('function guidedHudAction(')),prepare=source.slice(source.indexOf('function prepareLoadingScene('),source.indexOf('function releasePreparedLoading('));assert.match(start,/if\(starting\)return/);assert.match(start,/pauseLoadingMenu/);assert.match(start,/finally\{restoreLoadingMenu\(\)/);assert.doesNotMatch(prepare,/pauseLoadingMenu/);});

test('missing/failing WeakRef leaves menu untouched without strong fallback ownership',()=>{const original=globalThis.WeakRef;try{for(const constructor of [undefined,class{constructor(){throw Error('weak ownership');}}]){globalThis.WeakRef=constructor;const f=fixture();pauseLoadingMenu(f.get,{enabled:true})();assert.deepEqual(f.calls,[]);}}finally{globalThis.WeakRef=original;}});
