import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import * as THREE from 'three';
import {TerrainField} from '../src/world/terrain.js';
import {buildFarSceneData,farSceneTransferables} from '../tools/experiments/far-scene-data.js';
import {attachNativeFarGround} from '../tools/experiments/native-far-ground.js';
test('loading worker water samples match float-rounded native ground vertices in all biomes without changing geometry',()=>{for(const biome of ['savanna','grand_river','mangrove','volcanoes','canyons','desert']){const profile=JSON.parse(readFileSync(new URL('../public/content/biome-'+biome+'.json',import.meta.url))).profile,config={seed:'712',biome,relief:1,river:true,density:1,n:1,cx:0,cz:0,layers:Array(6).fill(true)},request={config,profile,slots:[0],treeBounds:{minX:-32,maxX:32,minZ:-32,maxZ:32},groundBounds:{minX:-32,maxX:32,minZ:-32,maxZ:32},step:16},original=buildFarSceneData(request),prepared=buildFarSceneData({...request,nativeWaterSamples:true}),field=new TerrainField(config);for(const key of ['positions','colors','indices'])assert.deepEqual(prepared.ground[key],original.ground[key]);for(let i=0;i<prepared.ground.water.length;i++)assert.equal(prepared.ground.water[i],field.waterInfo(prepared.ground.positions[i*3],prepared.ground.positions[i*3+2]).inside?1:0);assert.ok(farSceneTransferables(prepared).includes(prepared.ground.water.buffer));}});
test('loading attachment consumes transferred native water flags without reevaluating terrain',()=>{const candidate={impostors:new THREE.Mesh(),dispose(){}},water=new Float32Array([0,1,0]),world={nearBounds:[-24,-24,24,24],nav:{field:{waterInfo(){throw Error('Must use transferred samples');}}},toon:{uniforms:{uWorldOrigin:{value:new THREE.Vector2()},uNight:{value:0},uFineNoise:{value:1}},environmentUniforms:{}},biomeGround:{attach(material){material.userData.biomeGround={uGroundMapped:{value:1},uGroundMicro:{value:1},uGroundRelief:{value:1}};}}};attachNativeFarGround(candidate,{positions:new Float32Array([0,0,0,1,0,0,0,0,1]),colors:new Float32Array(9).fill(.5),indices:new Uint32Array([0,2,1]),water},world);assert.equal(candidate.impostors.children[0].geometry.attributes.aFarWater.array,water);candidate.dispose();});
