import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {WorldScene} from '../src/rendering/scene.js';
import {LoadingSyncQueue} from '../src/rendering/loading-sync-queue.js';
import {releaseActorRig} from '../src/rendering/animal-preload.js';
function fixture(queued){
 const geometry=new THREE.BoxGeometry(1,2,1),material=new THREE.MeshStandardMaterial();const vertices=geometry.attributes.position.count;
 geometry.setAttribute('skinIndex',new THREE.Uint16BufferAttribute(new Uint16Array(vertices*4),4));const weights=new Float32Array(vertices*4);for(let i=0;i<vertices;i++)weights[i*4]=1;geometry.setAttribute('skinWeight',new THREE.Float32BufferAttribute(weights,4));
 const mesh=new THREE.SkinnedMesh(geometry,material),bone=new THREE.Bone();bone.name='rootBone';mesh.add(bone);mesh.bind(new THREE.Skeleton([bone]));const source=new THREE.Group();source.add(mesh);
 const clip=new THREE.AnimationClip('idle',1,[new THREE.NumberKeyframeTrack('rootBone.rotation[z]',[0,1],[0,.2])]);let clock=0,frames=0;
 const queue=new LoadingSyncQueue({now:()=>clock,nextFrame:()=>{frames++;return Promise.resolve();}});const state={workers:Array.from({length:36},(_,i)=>({id:'w'+i,profile:'olderFemale'}))};
 const world={state,objects:new Map(state.workers.map(w=>[w.id,new THREE.Group()])),mixers:new Map(),workerLibraries:{olderFemale:{url:'borrowed.glb'}},assets:{model:async()=>({scene:source,animations:[clip]})},loadingProgress:queued?{ready:false}:null,loadingActorPreparation:()=>queue,loadReady:p=>Promise.resolve(p),updateActor(entity){const rig=this.mixers.get(entity.id);rig.mixer.clipAction(rig.clips[0]).play();rig.mixer.setTime(.4);clock+=7;}};
 return {world,queue,source,geometry,material,getFrames:()=>frames};
}
test('36 queued native SkeletonUtils clones preserve rig, borrowed material/UV and posed bounds against direct path',async()=>{
 const direct=fixture(false),queued=fixture(true);for(const f of [direct,queued])await Promise.all(f.world.state.workers.map(w=>WorldScene.prototype.actor.call(f.world,w,'worker')));
 assert.equal(queued.getFrames(),35);assert.equal(queued.world.mixers.size,36);const skeletons=new Set();
 for(const worker of queued.world.state.workers){const a=direct.world.mixers.get(worker.id),b=queued.world.mixers.get(worker.id);let ma,mb;a.model.traverse(m=>{if(m.isSkinnedMesh)ma=m;});b.model.traverse(m=>{if(m.isSkinnedMesh)mb=m;});assert.equal(mb.geometry,queued.geometry);assert.equal(mb.material,queued.material);assert.equal(mb.geometry.attributes.uv,queued.geometry.attributes.uv);assert.deepEqual(mb.skeleton.bones[0].matrixWorld.toArray(),ma.skeleton.bones[0].matrixWorld.toArray());assert.deepEqual(mb.boundingSphere.center.toArray(),ma.boundingSphere.center.toArray());assert.equal(mb.boundingSphere.radius,ma.boundingSphere.radius);assert.equal(b.clips[0].name,a.clips[0].name);assert.equal(b.mixer.time,a.mixer.time);skeletons.add(mb.skeleton);assert.notEqual(mb.skeleton,queued.source.children[0].skeleton);}
 assert.equal(skeletons.size,36);for(const f of [direct,queued]){for(const rig of f.world.mixers.values())releaseActorRig(rig);f.queue.dispose();}
});
test('requestActor deduplicates repeated requests and readiness waits every restored rig',async()=>{const f=fixture(true);for(const worker of f.world.state.workers){const root=f.world.objects.get(worker.id);f.world.actor=(e,t)=>WorldScene.prototype.actor.call(f.world,e,t);WorldScene.prototype.requestActor.call(f.world,worker,'worker',root);WorldScene.prototype.requestActor.call(f.world,worker,'worker',root);}await WorldScene.prototype.loadedWorkerActors.call(f.world);assert.equal(f.queue.stats.submitted,36);assert.equal(f.world.mixers.size,36);for(const rig of f.world.mixers.values())releaseActorRig(rig);f.queue.dispose();});
test('late replacement rejects adoption before clone; failing pose releases only owned skeleton/mixer',async()=>{
 const f=fixture(true),worker=f.world.state.workers[0];let resolve;f.world.assets.model=()=>new Promise(r=>resolve=r);const pending=WorldScene.prototype.actor.call(f.world,worker,'worker');f.world.objects.set(worker.id,new THREE.Group());resolve({scene:f.source,animations:[]});await pending;assert.equal(f.world.mixers.size,0);assert.equal(f.queue.stats.submitted,0);f.queue.dispose();
 const fail=fixture(true),error=Error('pose');let releases=0;fail.world.updateActor=()=>{const rig=fail.world.mixers.get('w0');rig.model.traverse(m=>{if(m.isSkinnedMesh)m.skeleton.dispose=()=>releases++;});throw error;};fail.geometry.dispose=()=>assert.fail('borrowed geometry disposed');fail.material.dispose=()=>assert.fail('borrowed material disposed');await assert.rejects(WorldScene.prototype.actor.call(fail.world,fail.world.state.workers[0],'worker'),e=>e===error);assert.equal(releases,1);assert.equal(fail.world.mixers.size,0);assert.equal(fail.world.objects.get('w0').children.length,0);fail.queue.dispose();
});

test('repeated queued actor cancellation never adopts later roots or disposes shared assets',async()=>{for(let run=0;run<3;run++){const f=fixture(true);f.queue.nextFrame=()=>new Promise(()=>{});const work=f.world.state.workers.map(w=>WorldScene.prototype.actor.call(f.world,w,'worker'));const settled=Promise.allSettled(work);for(let i=0;i<12;i++)await Promise.resolve();assert.equal(f.queue.stats.completed,1);assert.equal(f.queue.stats.yields,1);f.queue.dispose();const results=await settled;assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.ok(results.filter(r=>r.status==='rejected').every(r=>r.reason.name==='AbortError'));assert.equal(f.world.mixers.size,1);assert.equal([...f.world.objects.values()].filter(root=>root.children.length).length,1);for(const rig of f.world.mixers.values())releaseActorRig(rig);assert.equal(f.source.children[0].geometry,f.geometry);assert.equal(f.source.children[0].material,f.material);assert.equal(f.queue.jobs.length,0);}});
