import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {LoadingImageDecoder} from '../src/rendering/loading-image-decoder.js';
import {ownLoadingBitmap} from '../src/rendering/loading-image.js';
function fixture(signal){let closed=0;const messages=[],worker={postMessage(message,transfers){messages.push(message);structuredClone(message,{transfer:transfers});},terminate(){closed++;}};return {worker,messages,decoder:new LoadingImageDecoder({signal,createWorker:()=>worker}),closed:()=>closed};}
test('compressed source remains intact and returned bitmap has a single Texture owner',async()=>{const f=fixture(),source=new Uint8Array([4,8,16,32]).buffer,pending=f.decoder.decode(source);assert.equal(source.byteLength,4);assert.equal(f.messages[0].buffer.byteLength,0);let closes=0;const bitmap={width:64,height:64,close(){closes++;}};f.worker.onmessage({data:{id:1,bitmap}});assert.equal(await pending,bitmap);const texture=ownLoadingBitmap(new THREE.Texture(),bitmap),borrowed=texture.clone();borrowed.dispose();assert.equal(closes,0);texture.dispose();assert.equal(closes,1);f.decoder.dispose();f.decoder.dispose();assert.equal(f.closed(),1);});
test('abort terminates once, rejects pending requests and closes late bitmaps',async()=>{const controller=new AbortController(),f=fixture(controller.signal),one=f.decoder.decode(new ArrayBuffer(2)),two=f.decoder.decode(new ArrayBuffer(3));controller.abort();await assert.rejects(one,/cancelled/);await assert.rejects(two,/cancelled/);let closes=0;f.worker.onmessage({data:{id:1,bitmap:{close(){closes++;}}}});assert.equal(closes,1);assert.equal(f.closed(),1);await assert.rejects(f.decoder.decode(new ArrayBuffer(0)),/cancelled/);});
test('single decode errors preserve other requests; unsupported is explicit and fatal Worker errors close ownership',async()=>{const f=fixture(),one=f.decoder.decode(new ArrayBuffer(2)),two=f.decoder.decode(new ArrayBuffer(3));f.worker.onmessage({data:{id:1,error:'Unsupported bitmap',unsupported:true}});await assert.rejects(one,e=>e.unsupported===true);f.worker.onerror({message:'Worker failed'});await assert.rejects(two,/Worker failed/);assert.equal(f.closed(),1);});

test('native image orientation is transmitted without changing the cached compressed source',async()=>{const f=fixture(),source=new Uint8Array([9,7]).buffer,p=f.decoder.decode(source,'image/webp',{flipY:true});assert.equal(f.messages[0].flipY,true);assert.equal(source.byteLength,2);f.worker.onmessage({data:{id:1,bitmap:{}}});await p;f.decoder.dispose();});

test('decoder bounds compressed copies and rejects queued work without dispatch on cancellation',async()=>{const f=fixture(),promises=[2,3,5,7].map(n=>f.decoder.decode(new ArrayBuffer(n)));assert.equal(f.messages.length,2);assert.equal(f.decoder.active,2);assert.equal(f.decoder.transferBytes,5);f.worker.onmessage({data:{id:1,bitmap:{}}});await promises[0];assert.equal(f.messages.length,3);assert.equal(f.decoder.active,2);assert.equal(f.decoder.transferBytes,8);assert.equal(f.decoder.stats.peakActive,2);f.decoder.dispose();await Promise.all(promises.slice(1).map(p=>assert.rejects(p,/cancelled/)));assert.equal(f.messages.length,3);assert.equal(f.decoder.pending.size,0);assert.equal(f.decoder.active,0);assert.equal(f.decoder.transferBytes,0);});
