import test from 'node:test';import assert from 'node:assert/strict';
import {LoadingFrameSlack} from '../src/rendering/loading-frame-slack.js';
import {loadingYieldBudget} from '../src/rendering/loading-yield-budget.js';
function prepared(){const frame=new LoadingFrameSlack({targetMs:16});for(const timestamp of [0,16,32,48])frame.observeFrame({timestamp,start:timestamp+.2,end:timestamp+1.2});const lane=frame.createLane();lane.recordWork(2);return {frame,lane};}
test('no observed RAF and uncertain step costs preserve the existing fallback budget',()=>{const frame=new LoadingFrameSlack(),lane=frame.createLane();assert.equal(lane.shouldYield(3,0,4),false);assert.equal(lane.shouldYield(4,0,4),true);for(const timestamp of [0,16,32,48])frame.observeFrame({timestamp,start:timestamp,end:timestamp+1});assert.equal(lane.shouldYield(50,44,6),true);assert.equal(frame.stats.adaptiveDecisions,0);});
test('a genuinely delivered RAF replaces an old awaited wall budget without adding a redundant frame',()=>{const {frame,lane}=prepared();assert.equal(lane.shouldYield(50,0,4),false);assert.equal(lane.shouldYield(62,0,4),true);assert.equal(frame.stats.adaptiveDecisions,2);assert.equal(frame.stats.lastTargetMs,16);assert.ok(frame.stats.lastReserveMs>=1);});
test('delayed presentation callbacks, stalled intervals and stale timestamps never manufacture slack',()=>{const {frame,lane}=prepared();assert.equal(lane.shouldYield(70,68,4),false);assert.equal(lane.shouldYield(70,66,4),true);frame.observeFrame({timestamp:64,start:81,end:82});assert.equal(lane.shouldYield(83,79,4),true);assert.equal(frame.stats.adaptiveDecisions,0);const stall=prepared();stall.frame.observeFrame({timestamp:81,start:81,end:82});assert.equal(stall.lane.shouldYield(85,81,4),true);assert.equal(stall.frame.stats.adaptiveDecisions,0);});
test('the next step estimate retains recent expensive work and zero budgets remain unconditional',()=>{const {frame,lane}=prepared();lane.recordWork(20);lane.recordWork(.1);assert.equal(lane.shouldYield(50,46,4),true);assert.equal(frame.stats.adaptiveDecisions,0);const other=prepared();assert.equal(other.lane.shouldYield(50,50,0),true);});
test('invalid and disposed frame owners reject observations and fall back safely',()=>{const {frame,lane}=prepared();frame.observeFrame({timestamp:NaN,start:1,end:2});assert.equal(lane.shouldYield(54,50,4),true);assert.equal(frame.stats.invalidFrames,1);frame.dispose();const before=frame.stats.frames;frame.observeFrame({timestamp:64,start:64,end:65});assert.equal(frame.stats.frames,before);assert.equal(lane.shouldYield(60,54,6),true);assert.throws(()=>new LoadingFrameSlack({history:2}),/Invalid/);});
test('adaptive yielding still observes owner cancellation and waits only through the existing frame helper',async()=>{const {frame}=prepared();let clock=50,frames=0;const owner=new AbortController();const yieldWork=loadingYieldBudget({frameBudget:4,frameSlack:frame,now:()=>clock,signal:owner.signal,nextFrame:async()=>{frames++;frame.observeFrame({timestamp:64,start:64.2,end:65.2});clock=66;}});yieldWork.recordWork(2);await yieldWork();assert.equal(frames,0);clock=62;await yieldWork();assert.equal(frames,1);await yieldWork();assert.equal(frames,1);owner.abort();await assert.rejects(yieldWork(),/cancelled/);assert.equal(frames,1);});

test('adaptive frame waits remain abortable when the existing RAF stops and consume no late frame',async()=>{const {frame}=prepared(),owner=new AbortController();let clock=62,lateReject;const yieldWork=loadingYieldBudget({frameBudget:4,frameSlack:frame,now:()=>clock,signal:owner.signal,nextFrame:()=>new Promise((resolve,reject)=>{lateReject=reject;})});yieldWork.recordWork(2);const pending=yieldWork();owner.abort();await assert.rejects(pending,/cancelled/);lateReject(Error('late frame'));await new Promise(resolve=>setImmediate(resolve));});

test('mandatory fallback keeps depth barriers without trustworthy presentation observations',()=>{const frame=new LoadingFrameSlack(),lane=frame.createLane();lane.recordWork(1);assert.equal(lane.shouldYield(1,0,6,true),true);const good=prepared();assert.equal(good.lane.shouldYield(50,0,6,true),false);assert.equal(good.lane.shouldYield(62,0,6,true),true);assert.equal(good.lane.shouldYield(70,69,6,true),true);good.lane.recordWork(20);assert.equal(good.lane.shouldYield(50,49,6,true),true);});
