import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';import {readFileSync} from 'node:fs';import {frozenSource} from './frozen-loading-source.js';import {normalizePairWiring} from './world-crop-pair-wiring-normalize.js';
import {LoadingPlants} from '../src/rendering/loading-plants.js';import {LoadingDiorama} from '../src/rendering/loading-diorama.js';import {LoadingVisualQa} from '../src/app/loading-visual-qa.js';import {installLoadingVisualQa} from '../src/app/loading-visual-bridge.js';
function setup({progress65=true,aspect=16/9,angle=0}={}){const state={plants:[{id:'paid-yuca',species:'yuca',growth:90}],time:302},before=JSON.stringify(state),ground=new THREE.Mesh(new THREE.PlaneGeometry(15,15),new THREE.MeshBasicMaterial());ground.rotation.x=-Math.PI/2;ground.position.y=.09;ground.updateMatrixWorld();const camera=new THREE.PerspectiveCamera(40,aspect,.1,80);const distance=aspect<.8?1.65:1;camera.position.set((4.8*Math.cos(angle)+6.4*Math.sin(angle))*distance,3.1*(aspect<.8?1.45:1),(6.4*Math.cos(angle)-4.8*Math.sin(angle))*distance);camera.lookAt(0,1.15,0);camera.updateMatrixWorld();
 const world={state,loading:new AbortController(),canvas:{width:1024,height:576,getBoundingClientRect:()=>({left:0,top:0,width:aspect*720,height:720})}},diorama={world,state,ground,camera,ray:new THREE.Raycaster(),cursor:new THREE.Vector2(),plants:new LoadingPlants(),prepared:true,interactive:true,night:1,plantAt:LoadingDiorama.prototype.plantAt};let calls=0;const real=diorama.plantAt;diorama.plantAt=function(...args){calls++;return real.apply(this,args);};const scope={__desktopSmokeVisualCapture:true,__desktopSmokeVisualPlant:true,...(progress65?{__desktopSmokeVisualPlantProgress65:true}:{})};const owner=installLoadingVisualQa(world,diorama,{scope,create:options=>new LoadingVisualQa({...options,capture:()=> 'data:image/png;base64,AA==',now:()=>0})});
 const draw=(dt,p,ready=false)=>{diorama.plants.update(dt,p,{ready});diorama.onAfterDraw?.(diorama,p);};return {state,before,diorama,world,scope,owner,draw,calls:()=>calls,dispose(){owner.close();ground.geometry.dispose();ground.material.dispose();}};
}
test('natural threshold captures four then actual raycast fifth, intermediate deficit and mature equality without state mutation',()=>{
 const f=setup();f.draw(.35,.2);f.draw(.35,.64);assert.equal(f.calls(),0);f.draw(.35,.65);assert.equal(f.calls(),1);assert.equal(f.diorama.plants.plants.length,5);f.draw(.1,.66);f.draw(.2,.67);f.draw(.8,1,true);f.draw(.1,1,true);const report=f.scope.__wildGuardiansLoadingVisualQa.report;assert.deepEqual(report.frames.map(v=>v.label),['initial','preplant','additional-plant','catchup-mid','mature']);assert.equal(report.plantAction.progress,.65);assert.equal(report.frames[1].plants.length,4);const mid=report.frames[3];assert.ok(mid.plants[4].growth>0&&mid.plants[4].growth<mid.plants[0].growth);assert.ok(report.frames[4].plants.every(p=>p.growth===report.frames[4].plants[0].growth));assert.equal(JSON.stringify(f.state),f.before);assert.equal(f.calls(),1);f.dispose();
});
test('skipped threshold/cancel/cinematic/replaced owner never backfills or retries',()=>{
 for(const mode of ['skipped','cancel','cinematic','replacement']){const f=setup();f.draw(.35,.3);if(mode==='cancel')f.world.loading.abort();if(mode==='cinematic')f.world.cinematic={};if(mode==='replacement')f.diorama.onAfterDraw=()=>{};f.draw(.35,mode==='skipped'?1:.7,true);f.owner.close({cancelled:mode==='cancel'});assert.equal(f.calls(),0);assert.ok(f.scope.__wildGuardiansLoadingVisualQa.report.plantAction.skipped);f.dispose();}
});
test('old default still plants after first draw, while selection stays under visual and plant guards',()=>{
 const f=setup({progress65:false});f.draw(.35,.2);assert.equal(f.calls(),1);assert.equal(f.scope.__wildGuardiansLoadingVisualQa.report.plantAction.startProgress,0);f.dispose();const rust=readFileSync('src-tauri/src/main.rs','utf8');assert.match(rust,/--smoke-report[\s\S]*--smoke-visual"[\s\S]*--smoke-visual-plant"[\s\S]*--smoke-visual-plant-progress65/);
 for(const file of ['src-tauri/src/main.rs','src-tauri/smoke.js'])assert.equal(normalizePairWiring(file,readFileSync(file,'utf8')),frozenSource('71d4db4e',file));
});

test('threshold uses actual raycast under orbit and portrait CPU aspects, never logical save planting',()=>{
 for(const aspect of [16/9,420/900])for(const angle of [0,1.1,3.8]){const f=setup({aspect,angle});f.draw(.35,.3);f.draw(.35,.65);assert.equal(f.calls(),1);assert.equal(f.diorama.plants.plants.length,5);assert.equal(JSON.stringify(f.state),f.before);assert.ok(f.scope.__wildGuardiansLoadingVisualQa.report.plantAction.candidates<=12);f.dispose();}
});
