import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {prepareCropShadowPrograms} from '../tools/experiments/prepare-crop-shadow-programs.js';
function fixture(){
 const scene=new THREE.Scene(),geometry=new THREE.BoxGeometry(),material=new THREE.MeshStandardMaterial({map:new THREE.Texture(),side:THREE.DoubleSide}),depth=new THREE.MeshDepthMaterial({depthPacking:THREE.RGBADepthPacking});depth.customProgramCacheKey=()=> 'bioma-growth-depth-v3-opaque';
 const mesh=new THREE.InstancedMesh(geometry,material,4);mesh.name='maiz_01_brote';mesh.customDepthMaterial=depth;mesh.count=0;mesh.visible=false;scene.add(mesh);const light=new THREE.DirectionalLight();light.castShadow=true;scene.add(light);
 const prior={name:'prior'},shadow={name:'shadow'},canvas=new EventTarget(),gl={canvas,isContextLost:()=>false},viewport=new THREE.Vector4(1,2,3,4),scissor=new THREE.Vector4(4,3,2,1);let target=prior,test=true;
 const properties=new Map(),calls=[];const renderer={shadowMap:{enabled:true,type:THREE.PCFSoftShadowMap},getContext:()=>gl,properties:{get:material=>properties.get(material)??{}},getRenderTarget:()=>target,getActiveCubeFace:()=>2,getActiveMipmapLevel:()=>1,getViewport:v=>v.copy(viewport),getScissor:v=>v.copy(scissor),getScissorTest:()=>test,setViewport:v=>viewport.copy(v),setScissor:v=>scissor.copy(v),setScissorTest:v=>{test=v;},setRenderTarget:v=>{target=v;viewport.set(0,0,10,10);},render:()=>assert.fail('no draw'),initTexture:()=>assert.fail('no texture upload'),compile(root,camera,view){assert.equal(target,shadow);assert.equal(view.fog,null);assert.equal(view.children.filter(o=>o.isLight).length,1);assert.notEqual(view.children[0],light);const materials=new Set();root.traverse(object=>{assert.equal(object,mesh);assert.equal(object.geometry,geometry);assert.equal(object.count,0);assert.equal(object.visible,false);assert.equal(object.material,depth);assert.equal(depth.map,material.map);assert.equal(depth.side,THREE.DoubleSide);materials.add(depth);});calls.push('compile');properties.set(depth,{currentProgram:{cacheKey:'exact-depth-shadow',isReady:()=>true}});return materials;}};
 const world={scene,renderer,disposed:false,loading:new AbortController(),glResourceEpoch:{stats:{epoch:0}},sun:{shadow:{map:shadow,camera:new THREE.PerspectiveCamera()}}};
 const restored=()=>{assert.equal(mesh.material,material);assert.equal(depth.map,null);assert.equal(depth.side,THREE.FrontSide);assert.equal(target,prior);assert.deepEqual(viewport.toArray(),[1,2,3,4]);assert.deepEqual(scissor.toArray(),[4,3,2,1]);assert.equal(test,true);assert.equal(mesh.parent,scene);assert.equal(mesh.count,0);assert.equal(mesh.visible,false);};
 return {world,mesh,material,depth,renderer,calls,restored,cleanup:()=>{geometry.dispose();material.map.dispose();material.dispose();depth.dispose();},options:{bindings:()=>{restored();calls.push('bindings');return {initialized:1};},fence:async()=>{restored();calls.push('fence');}}};
}
test('prepares original invisible crop shadow programs without a draw, count change or geometry upload',async()=>{const f=fixture();try{const result=await prepareCropShadowPrograms(f.world,f.options);f.restored();assert.deepEqual(f.calls,['compile','bindings','fence']);assert.equal(result.sources,1);assert.equal(result.programs[0].key,'exact-depth-shadow');}finally{f.cleanup();}});
test('borrowed material and renderer target are restored before compilation readiness waits',async()=>{const f=fixture();let release;try{const pending=prepareCropShadowPrograms(f.world,{...f.options,compile:async(renderer,root,camera,scene,{check})=>{renderer.compile(root,camera,scene);f.restored();await new Promise(resolve=>{release=resolve;});check();}});f.restored();release();await pending;f.restored();}finally{f.cleanup();}});
test('submission failure preserves original materials/target and never proceeds to bindings',async()=>{const f=fixture();f.renderer.compile=()=>{throw Error('native compile fault');};try{await assert.rejects(prepareCropShadowPrograms(f.world,f.options),/native compile fault/);f.restored();assert.deepEqual(f.calls,[]);}finally{f.cleanup();}});
test('owner abort releases compiler wait without readiness adoption or late program queries',async()=>{const f=fixture();const original=f.renderer.compile;let queries=0;f.renderer.compile=(...args)=>{const materials=original(...args);f.renderer.properties.get(f.depth).currentProgram.isReady=()=>{queries++;return false;};return materials;};try{const pending=prepareCropShadowPrograms(f.world,f.options);await Promise.resolve();f.world.loading.abort();await assert.rejects(pending,/cancelled/);const ended=queries;await new Promise(resolve=>setTimeout(resolve,20));assert.equal(queries,ended);f.restored();assert.deepEqual(f.calls,['compile']);}finally{f.cleanup();}});
test('early context loss/restoration aborts pending compilation before touching stale programs',async()=>{const f=fixture();const original=f.renderer.compile;let queries=0;f.renderer.compile=(...args)=>{const materials=original(...args);f.renderer.properties.get(f.depth).currentProgram.isReady=()=>{assert.equal(f.world.glResourceEpoch.stats.epoch,0);queries++;return false;};return materials;};try{const pending=prepareCropShadowPrograms(f.world,f.options);await Promise.resolve();f.world.glResourceEpoch.stats.epoch++;f.renderer.getContext().canvas.dispatchEvent(new Event('webglcontextlost'));await assert.rejects(pending,/cancelled|context lost/);const ended=queries;await new Promise(resolve=>setTimeout(resolve,20));assert.equal(queries,ended);f.restored();assert.deepEqual(f.calls,['compile']);}finally{f.cleanup();}});

test('never-ready crop programs time out without remaining readiness queries',async()=>{const f=fixture();const original=f.renderer.compile;let queries=0,clock=0;f.renderer.compile=(...args)=>{const materials=original(...args);f.renderer.properties.get(f.depth).currentProgram.isReady=()=>{queries++;return false;};return materials;};try{const pending=prepareCropShadowPrograms(f.world,{...f.options,timeout:1,now:()=>clock});clock=2;await assert.rejects(pending,/timed out/);const ended=queries;await new Promise(resolve=>setTimeout(resolve,20));assert.equal(queries,ended);f.restored();assert.deepEqual(f.calls,['compile']);}finally{f.cleanup();}});
