import test from 'node:test';import assert from 'node:assert/strict';import {Vector4} from 'three';
import {renderScreenPreload,waitForGpuPreload} from '../src/rendering/screen-preload.js';
test('screen preload submits on the backbuffer and restores target, viewport, scissor and clearing after a draw error',()=>{
 const viewport=new Vector4(1,2,300,200),scissor=new Vector4(3,4,100,80),original={};let target=original;const renderer={autoClear:true,test:false,getViewport:v=>v.copy(viewport),getScissor:v=>v.copy(scissor),getScissorTest(){return this.test;},setViewport(...args){viewport.copy(args[0]?.isVector4?args[0]:new Vector4(...args));},setScissor(...args){scissor.copy(args[0]?.isVector4?args[0]:new Vector4(...args));},setScissorTest(value){this.test=value;},getRenderTarget:()=>target,setRenderTarget:value=>{target=value;viewport.set(0,0,900,600);},render(){assert.deepEqual(viewport.toArray(),[0,0,0,0]);assert.deepEqual(scissor.toArray(),[0,0,0,0]);assert.equal(this.autoClear,false);assert.equal(this.test,true);assert.equal(this.getRenderTarget(),null);throw Error('draw failed');}};
 assert.throws(()=>renderScreenPreload(renderer,{},{}),/draw failed/);assert.equal(target,original);assert.deepEqual(viewport.toArray(),[1,2,300,200]);assert.deepEqual(scissor.toArray(),[3,4,100,80]);assert.equal(renderer.autoClear,true);assert.equal(renderer.test,false);
});
function setup(statuses){const sync={},calls=[];const gl={SYNC_GPU_COMMANDS_COMPLETE:1,ALREADY_SIGNALED:2,CONDITION_SATISFIED:3,WAIT_FAILED:4,TIMEOUT_EXPIRED:5,isContextLost:()=>false,fenceSync:(...args)=>{calls.push(['fence',...args]);return sync;},flush:()=>calls.push(['flush']),clientWaitSync:(...args)=>{calls.push(['wait',...args]);return statuses.shift()??3;},deleteSync:value=>calls.push(['delete',value])};return {gl,calls,sync,renderer:{getContext:()=>gl}};}
test('GPU readiness waits across frames without a blocking wait and deletes the fence',async()=>{
 const {renderer,calls,sync}=setup([5,5,3]);let frames=0;await waitForGpuPreload(renderer,{nextFrame:async()=>{frames++;}});assert.equal(frames,2);assert.deepEqual(calls.filter(c=>c[0]==='wait'),[['wait',sync,0,0],['wait',sync,0,0],['wait',sync,0,0]]);assert.deepEqual(calls.at(-1),['delete',sync]);
});
test('cancellation while waiting rejects readiness and releases its fence',async()=>{
 const {renderer,calls,sync}=setup([5]);let cancelled=false;await assert.rejects(waitForGpuPreload(renderer,{cancelled:()=>cancelled,nextFrame:async()=>{cancelled=true;}}),/cancelled/);assert.deepEqual(calls.at(-1),['delete',sync]);
});
test('failed and expired waits release their fences',async()=>{
 const failed=setup([4]);await assert.rejects(waitForGpuPreload(failed.renderer),/fence failed/);assert.equal(failed.calls.at(-1)[0],'delete');
 const expired=setup([5]);let time=0;await assert.rejects(waitForGpuPreload(expired.renderer,{timeout:10,now:()=>time,nextFrame:async()=>{time=11;}}),/timed out/);assert.equal(expired.calls.at(-1)[0],'delete');
});
import {Scene,Mesh,BoxGeometry,MeshBasicMaterial,DirectionalLight} from 'three';
import {renderScreenPreloadBatched} from '../src/rendering/screen-preload.js';
function batchFixture(){const scene=new Scene(),meshes=Array.from({length:5},()=>new Mesh(new BoxGeometry(),new MeshBasicMaterial())),hidden=new Mesh(new BoxGeometry(),new MeshBasicMaterial()),light=new DirectionalLight();hidden.visible=false;scene.add(...meshes,hidden,light);let viewport=new Vector4(1,2,3,4),scissor=new Vector4(4,3,2,1),test=false;const calls=[];const renderer={target:null,getRenderTarget(){return this.target;},setRenderTarget(value){this.target=value;},shadowMap:{needsUpdate:false},autoClear:true,getContext:()=>({isContextLost:()=>false}),getViewport:v=>v.copy(viewport),getScissor:v=>v.copy(scissor),getScissorTest:()=>test,setViewport(...v){viewport=v[0]?.isVector4?v[0].clone():new Vector4(...v);},setScissor(...v){scissor=v[0]?.isVector4?v[0].clone():new Vector4(...v);},setScissorTest:v=>{test=v;},render(s){const visible=[];s.traverseVisible(o=>{if(o.isMesh)visible.push(o);});calls.push(visible);}};return {scene,meshes,hidden,light,renderer,calls};}
test('native preload batches actual meshes, restores visibility before every yield and draws full final shadows',async()=>{const f=batchFixture();let yields=0;await renderScreenPreloadBatched(f.renderer,f.scene,{}, {batchSize:2,nextFrame:async()=>{yields++;assert.ok(f.meshes.every(m=>m.visible));assert.equal(f.hidden.visible,false);}});assert.deepEqual(f.calls.map(c=>c.length),[2,2,1,5]);assert.equal(yields,3);assert.ok(f.meshes.every(m=>m.visible));assert.equal(f.renderer.shadowMap.needsUpdate,false);assert.equal(f.light.shadow.needsUpdate,false);});
test('cancelled uploads restore all borrowed visibility and shadow update flags',async()=>{const f=batchFixture();let stop=false;await assert.rejects(renderScreenPreloadBatched(f.renderer,f.scene,{}, {cancelled:()=>stop,nextFrame:async()=>{stop=true;}}),/cancelled/);assert.equal(f.calls.length,1);assert.ok(f.meshes.every(m=>m.visible));assert.equal(f.hidden.visible,false);assert.equal(f.renderer.shadowMap.needsUpdate,false);});

test('partial color uploads retain shadow-enabled shader variants but reuse maps until the complete final shadow draw',async()=>{const f=batchFixture(),states=[];f.renderer.shadowMap.enabled=true;f.renderer.shadowMap.autoUpdate=true;f.light.shadow.autoUpdate=true;const original=f.renderer.render;f.renderer.render=s=>{states.push([f.renderer.shadowMap.enabled,f.renderer.shadowMap.autoUpdate,f.renderer.shadowMap.needsUpdate,f.light.shadow.autoUpdate,f.light.shadow.needsUpdate]);original(s);};await renderScreenPreloadBatched(f.renderer,f.scene,{}, {batchSize:2,nextFrame:async()=>{assert.equal(f.renderer.shadowMap.autoUpdate,true);assert.equal(f.light.shadow.autoUpdate,true);}});assert.deepEqual(states,[[true,false,false,false,false],[true,false,false,false,false],[true,false,false,false,false],[true,true,true,true,true]]);assert.equal(f.renderer.shadowMap.autoUpdate,true);assert.equal(f.light.shadow.autoUpdate,true);});

test('loading shadow priming submits bounded native casters then restores a complete shadow map',async()=>{const f=batchFixture(),states=[];f.renderer.shadowMap.autoUpdate=true;f.light.shadow.autoUpdate=true;const original=f.renderer.render;f.renderer.render=s=>{states.push([f.renderer.shadowMap.needsUpdate,f.light.shadow.needsUpdate]);original(s);};await renderScreenPreloadBatched(f.renderer,f.scene,{}, {batchSize:2,warmShadows:true,nextFrame:async()=>{assert.ok(f.meshes.every(m=>m.visible));assert.equal(f.renderer.shadowMap.needsUpdate,false);assert.equal(f.light.shadow.needsUpdate,false);}});assert.deepEqual(f.calls.map(c=>c.length),[2,2,1,5]);assert.ok(states.every(s=>s.every(Boolean)));assert.equal(f.renderer.shadowMap.needsUpdate,false);assert.equal(f.light.shadow.needsUpdate,false);});
