import test from 'node:test';import assert from 'node:assert/strict';import {GameScreenWakeLock} from '../src/ui/screen-wake-lock.js';
const flush=()=>new Promise(done=>setImmediate(done));
function fixture(){const document=new EventTarget();document.hidden=false;const requests=[],sentinels=[];const wakeLock={request(type){requests.push(type);const sentinel=new EventTarget();sentinel.released=false;sentinel.release=async()=>{sentinel.released=true;sentinel.dispatchEvent(new Event('release'));};sentinels.push(sentinel);return Promise.resolve(sentinel);}};return {document,requests,sentinels,wakeLock,controller:new GameScreenWakeLock({document,wakeLock})};}
test('one screen lock survives gameplay pauses and repeated input, and releases on scene exit',async()=>{const f=fixture();f.controller.setActive(true);for(let i=0;i<30;i++)f.document.dispatchEvent(new Event('pointerdown'));await flush();assert.deepEqual(f.requests,['screen']);f.controller.setActive(true);assert.equal(f.requests.length,1);f.controller.setActive(false);await flush();assert.equal(f.sentinels[0].released,true);f.document.dispatchEvent(new Event('pointerdown'));assert.equal(f.requests.length,1);f.controller.dispose();});
test('hidden documents release; returning while playing reacquires a fresh sentinel',async()=>{const f=fixture();f.controller.setActive(true);await flush();f.document.hidden=true;f.document.dispatchEvent(new Event('visibilitychange'));await flush();assert.equal(f.sentinels[0].released,true);f.document.hidden=false;f.document.dispatchEvent(new Event('visibilitychange'));await flush();assert.equal(f.requests.length,2);assert.equal(f.controller.sentinel,f.sentinels[1]);f.controller.dispose();});
test('late platform grant after leaving the game is immediately released',async()=>{const f=fixture();let resolve;f.controller.api={request:()=>new Promise(done=>resolve=done)};f.controller.setActive(true);f.controller.setActive(false);const s=new EventTarget();s.release=async()=>s.released=true;resolve(s);await flush();assert.equal(s.released,true);assert.equal(f.controller.sentinel,null);f.controller.dispose();});
test('denial, unsupported platforms and system release do not form per-frame retry loops',async()=>{const f=fixture();f.controller.api={request:()=>{f.requests.push('denied');return Promise.reject(Error('Policy'));}};f.controller.setActive(true);await flush();assert.equal(f.controller.pending,null);assert.equal(f.requests.length,1);f.controller.dispose();const no=new GameScreenWakeLock({document:f.document,wakeLock:null});assert.doesNotThrow(()=>no.setActive(true));no.dispose();const g=fixture();g.controller.setActive(true);await flush();await g.sentinels[0].release();await flush();assert.equal(g.requests.length,1);g.document.dispatchEvent(new Event('pointerdown'));await flush();assert.equal(g.requests.length,2);g.controller.dispose();});
test('dispose removes lifecycle listeners and cancels pending grants',async()=>{const f=fixture();f.controller.setActive(true);await flush();f.controller.dispose();f.document.dispatchEvent(new Event('pointerdown'));f.document.dispatchEvent(new Event('visibilitychange'));assert.equal(f.requests.length,1);assert.equal(f.controller.active,false);assert.equal(f.sentinels[0].released,true);});

test('a hidden-to-visible transition cannot let an old pending grant replace the new lock',async()=>{const f=fixture(),grants=[];f.controller.api={request:()=>new Promise(resolve=>grants.push(resolve))};f.controller.setActive(true);f.document.hidden=true;f.document.dispatchEvent(new Event('visibilitychange'));f.document.hidden=false;f.document.dispatchEvent(new Event('visibilitychange'));assert.equal(grants.length,2);const old=new EventTarget(),fresh=new EventTarget();old.release=async()=>old.released=true;fresh.release=async()=>fresh.released=true;grants[1](fresh);await flush();grants[0](old);await flush();assert.equal(old.released,true);assert.equal(f.controller.sentinel,fresh);assert.equal(fresh.released,undefined);f.controller.dispose();assert.equal(fresh.released,true);});
