import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {probeSharedGroundClip} from '../src/rendering/shared-ground-clip-probe.js';
function fixture(mode){
 const resident=new THREE.MeshBasicMaterial(),horizon=new THREE.MeshBasicMaterial(),bounds=new THREE.Vector4(-48,-48,48,48);resident.userData.biomeGround={};horizon.userData.horizonBounds=bounds;let borrowedDisposals=0,geometryDisposals=0,targetDisposals=0;for(const m of [resident,horizon])m.addEventListener('dispose',()=>borrowedDisposals++);
 const viewport=new THREE.Vector4(10,20,30,40),scissor=new THREE.Vector4(40,30,20,10),previous={},color=new THREE.Color(0x123456),original=color.clone();let target=previous,scissorTest=true,alpha=.6,read=0,watched=false,lost=false;const world={terrainMeshes:[{material:resident}],horizon:{group:{children:[{material:horizon}]}},scene:{fog:null},toon:{sharedGroundClip:true},loading:new AbortController(),disposed:false};
 const renderer=world.renderer={autoClear:true,properties:{get:()=>({currentProgram:{id:10,cacheKey:'offscreen-test'}})},getContext:()=>({isContextLost:()=>lost}),getRenderTarget:()=>target,getActiveCubeFace:()=>3,getActiveMipmapLevel:()=>1,getViewport:v=>v.copy(viewport),getScissor:v=>v.copy(scissor),getScissorTest:()=>scissorTest,getClearColor:c=>{if(mode==='state')throw Error('state snapshot');return c.copy(color);},getClearAlpha:()=>alpha,setRenderTarget:(value,face,level)=>{if(value===previous&&mode==='restore')throw Error('restore target');target=value;viewport.set(0,0,1,1);if(value===previous){assert.equal(face,3);assert.equal(level,1);}else if(value&&!watched){value.addEventListener('dispose',()=>targetDisposals++);watched=true;}},setViewport:(v,...rest)=>typeof v==='number'?viewport.set(v,...rest):viewport.copy(v),setScissor:v=>scissor.copy(v),setScissorTest:value=>{scissorTest=value;},setClearColor:(value,a)=>{color.set(value);alpha=a;},clear:()=>{},render:scene=>{const geometry=scene.children[0].geometry;if(!geometry.userData.testWatched){geometry.userData.testWatched=true;geometry.addEventListener('dispose',()=>geometryDisposals++);}if(mode==='render')throw Error('render failure');},readRenderTargetPixels:(rt,x,y,w,h,pixel)=>{read++;if(mode==='error'&&read===4)throw Error('readback failure');pixel[3]=[255,0,255,255][read-1];if(mode==='cancel'&&read===4)world.loading.abort();if(mode==='loss'&&read===4)lost=true;}};
 return {world,verify:(allocations=1)=>{if(mode!=='restore')assert.equal(target,previous);assert.deepEqual(viewport.toArray(),[10,20,30,40]);assert.deepEqual(scissor.toArray(),[40,30,20,10]);assert.equal(scissorTest,true);assert.equal(alpha,.6);assert.ok(color.equals(original));assert.equal(renderer.autoClear,true);assert.deepEqual(bounds.toArray(),[-48,-48,48,48]);assert.equal(borrowedDisposals,0);assert.equal(geometryDisposals,allocations);assert.equal(targetDisposals,allocations);resident.dispose();horizon.dispose();}};
}
test('probe restores renderer/bounds and disposes only private allocations on success',()=>{const f=fixture();const report=probeSharedGroundClip(f.world);assert.equal(report.passed,true);assert.deepEqual(report.steps.map(x=>x.alpha),[255,0,255,255]);assert.ok(report.scope.includes('offscreen'));f.verify();});
for(const mode of ['error','cancel','loss'])test('probe restores mutated bounds and renderer on '+mode,()=>{const f=fixture(mode);assert.throws(()=>probeSharedGroundClip(f.world),mode==='error'?/readback failure/:/cancelled/);f.verify();});

test('state snapshot failure occurs before private resource allocation',()=>{const f=fixture('state');assert.throws(()=>probeSharedGroundClip(f.world),/state snapshot/);f.verify(0);});
for(const mode of ['render','restore'])test('probe releases private allocations and attempts remaining state restores after '+mode+' failure',()=>{const f=fixture(mode);assert.throws(()=>probeSharedGroundClip(f.world),mode==='render'?/render failure/:/restore target/);f.verify();});
