import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {wallBufferReader,wallBufferPackageEnabled} from '../src/rendering/wall-buffer-package.js';
import {wallBufferReferences,prepareWallBufferPackage} from '../tools/prepare_wall_buffer_package.mjs';
import {Assets} from '../src/rendering/assets.js';
import * as THREE from 'three';
const root=new URL('../',import.meta.url),read=path=>readFileSync(new URL(path,root)),pack=JSON.parse(read('public/content/walls.json')),manifest=JSON.parse(read('content/manifests/wall-buffer-package.json'));
const payload=read('public'+manifest.url),ab=data=>data.buffer.slice(data.byteOffset,data.byteOffset+data.byteLength),hash=data=>createHash('sha256').update(data).digest('hex');
test('all160 unique payloads, aligned lanes and original descriptor bytes are exact',async()=>{
 assert.equal(wallBufferReferences(pack).length,160);assert.equal(manifest.entries.length,160);assert.equal(new Set(manifest.entries.map(e=>e.url)).size,160);assert.equal(hash(payload),manifest.sha256);
 let calls=0;const reader=await wallBufferReader(pack,{load:async url=>{calls++;assert.equal(url,manifest.url);return ab(payload);}});
 for(const entry of manifest.entries){assert.equal(entry.offset%4,0);const original=read('public'+entry.url),result=Buffer.from(await reader(entry.url));assert.deepEqual(result,original);assert.equal(hash(result),entry.sha256);assert.equal(result.byteLength%(entry.type==='f32'?4:2),0);}
 assert.equal(calls,1);assert.equal(manifest.entries.reduce((n,e)=>n+e.length,0),5135408);assert.equal(payload.length,5135464);
});
test('generator deterministic and originals untouched',async()=>{const before=manifest.entries.map(e=>hash(read('public'+e.url)));const generated=await prepareWallBufferPackage();assert.deepEqual(generated,manifest);assert.deepEqual(manifest.entries.map(e=>hash(read('public'+e.url))),before);});
test('resolved descriptor URLs and subset descriptor remain compatible',async()=>{const subset={pieces:{x:Object.values(pack.pieces)[0]}};const clone=structuredClone(subset);for(const row of wallBufferReferences(clone))row.descriptor.url='http://tauri.localhost'+row.descriptor.url;const reader=await wallBufferReader(clone,{load:async()=>ab(payload)});assert.deepEqual(Buffer.from(await reader(Object.values(clone.pieces)[0].p.url)),read('public'+Object.values(subset.pieces)[0].p.url));});
test('unknown descriptor rejected before any request; truncated payload rejected',async()=>{let calls=0;const bad=structuredClone(pack);Object.values(bad.pieces)[0].p.url='/assets/unknown.bin';await assert.rejects(wallBufferReader(bad,{load:async()=>{calls++;return ab(payload);}}),/Unknown/);assert.equal(calls,0);await assert.rejects(wallBufferReader(pack,{load:async()=>new ArrayBuffer(8)}),/length/);});
test('abort before fetch and late body delivery do not adopt any lane',async()=>{const first=new AbortController();first.abort();let calls=0;await assert.rejects(wallBufferReader(pack,{signal:first.signal,load:()=>{calls++;}}),/cancelled/);assert.equal(calls,0);const owner=new AbortController();let resolve;const pending=wallBufferReader(pack,{signal:owner.signal,load:(_,options)=>{assert.equal(options.signal,owner.signal);return new Promise(r=>resolve=r);}});owner.abort();resolve(ab(payload));await assert.rejects(pending,/cancelled/);});
test('reader checks owner after decode and each later lane read; request rejection propagated',async()=>{let closed=false;const reader=await wallBufferReader(pack,{assertOpen:()=>{if(closed)throw Error('closed');},load:async()=>ab(payload)});closed=true;await assert.rejects(reader(manifest.entries[0].url),/closed/);const fault=Error('body failed');await assert.rejects(wallBufferReader(pack,{load:async()=>{throw fault;}}),e=>e===fault);});
async function build(t,packed){const assets=new Assets();assets.texture=async()=>assets.own(new THREE.Texture());let requests=[];t.mock.method(globalThis,'fetch',async url=>{requests.push(url);const path=new URL(url,'http://localhost').pathname;return new Response(read('public'+path));});const walls=await assets.walls(pack,{bufferPackage:packed});return {assets,walls,requests};}
const lanes=mesh=>[...Object.values(mesh.geometry.attributes).map(a=>a.array),mesh.geometry.index.array,mesh.userData.nativePiece.faceRegions,...Object.values(mesh.userData.nativePiece.morph).flatMap(x=>[x.p,x.n])];
test('real Assets.walls identical geometries/morph peers/bounds/material recipes,160→1requests',async t=>{const a=await build(t,false);t.mock.restoreAll();const b=await build(t,true);assert.equal(a.requests.length,160);assert.equal(b.requests.length,1);assert.deepEqual(Object.keys(a.walls).sort(),Object.keys(b.walls).sort());for(const name of Object.keys(a.walls)){const x=a.walls[name],y=b.walls[name];for(const [i,v] of lanes(x).entries())assert.deepEqual(v,lanes(y)[i]);assert.deepEqual(x.geometry.boundingBox,y.geometry.boundingBox);assert.deepEqual(x.geometry.boundingSphere,y.geometry.boundingSphere);assert.deepEqual(Object.fromEntries(Object.entries(x.userData.nativePiece.morph).map(([k,v])=>[k,v.peers])),Object.fromEntries(Object.entries(y.userData.nativePiece.morph).map(([k,v])=>[k,v.peers])));assert.equal(y.material.side,x.material.side);assert.equal(y.castShadow,x.castShadow);assert.equal(y.receiveShadow,x.receiveShadow);for(const bridge of Object.values(y.userData.nativePiece.morph)){assert.equal(bridge.p.length,y.geometry.attributes.position.array.length);assert.equal(bridge.n.length,y.geometry.attributes.normal.array.length);}}a.assets.disposeModels();b.assets.disposeModels();});
test('real Assets owner disposed during pending package releases material exactlyonce and no late geometry',async t=>{const assets=new Assets(),texture=assets.own(new THREE.Texture());assets.texture=async()=>texture;let finish; t.mock.method(globalThis,'fetch',()=>new Promise(r=>finish=r));const pending=assets.walls(pack,{bufferPackage:true});await new Promise(r=>setImmediate(r));const material=[...assets.ownedResources].find(x=>x.isMaterial);let count=0;material.addEventListener('dispose',()=>count++);assets.disposeModels();finish(new Response(payload));await assert.rejects(pending);assert.equal(count,1);assert.equal(assets.ownedResources.size,0);assets.disposeModels();assert.equal(count,1);});
test('flag requires both smoke booleans; normal path defaultsOFF',()=>{for(const scope of [{},{__desktopSmokeStarted:true},{__desktopSmokeWallBufferPackage:true},{__desktopSmokeStarted:true,__desktopSmokeWallBufferPackage:'true'}])assert.equal(wallBufferPackageEnabled(scope),false);assert.equal(wallBufferPackageEnabled({__desktopSmokeStarted:true,__desktopSmokeWallBufferPackage:true}),true);});
test('packed geometry and morph lanes share one buffer, not160 full copies',async t=>{const built=await build(t,true);const buffers=new Set();for(const mesh of Object.values(built.walls))for(const lane of lanes(mesh))buffers.add(lane.buffer);assert.equal(buffers.size,1);assert.equal([...buffers][0].byteLength,manifest.byteLength);built.assets.disposeModels();});
test('descriptor field type mismatch fails before fetch',async()=>{const bad=structuredClone(pack),piece=Object.values(bad.pieces)[0];piece.p=piece.i;let requests=0;await assert.rejects(wallBufferReader(bad,{load:()=>requests++}),/lane type/);assert.equal(requests,0);});
test('real late texture after cancellation disposed once; package not requested',async t=>{const assets=new Assets();let resolve;assets.textures={loadAsync:()=>new Promise(r=>resolve=r)};let calls=0;t.mock.method(globalThis,'fetch',()=>{calls++;throw Error('unexpected');});const pending=assets.walls(pack,{bufferPackage:true});assets.disposeModels();const texture=new THREE.Texture();let disposed=0;texture.addEventListener('dispose',()=>disposed++);resolve(texture);await assert.rejects(pending,/disposed/);assert.equal(disposed,1);assert.equal(calls,0);});
test('CLI and both native smoke invocations record explicit OFF default flag without gate changes',()=>{
 const rust=read('src-tauri/src/main.rs').toString(),workflow=read('.github/workflows/windows.yml').toString(),smoke=read('src-tauri/smoke.js').toString();
 assert.ok(rust.indexOf('--smoke-report')<rust.indexOf('--smoke-wall-buffer-package'));assert.match(rust,/let wall_buffer_package = std::env::args\(\).any\(\|arg\| arg == "--smoke-wall-buffer-package"\)/);assert.match(rust,/window\.__desktopSmokeWallBufferPackage=\{wall_buffer_package\}/);
 assert.match(workflow,/wall_buffer_package:[\s\S]*?type: boolean[\s\S]*?default: false/);assert.equal(workflow.split("$smokeArgs += '--smoke-wall-buffer-package'").length-1,2);
 assert.match(smoke,/wallBufferPackage:window\.__desktopSmokeWallBufferPackage===true/);assert.match(smoke,/90000/);assert.match(smoke,/await wait\(300000\)/);assert.match(workflow,/WaitForExit\(900000\)/);
 const scene=read('src/rendering/scene.js').toString();assert.match(scene,/bufferPackage:wallBufferPackageEnabled\(\)/);assert.ok(scene.indexOf("milestone('walls')")<scene.indexOf("phase('load-warm-gpu'"));
});
