import test from 'node:test';import assert from 'node:assert/strict';
import {Navigation} from '../src/world/navigation.js';import {workerReturnRoute} from '../src/simulation/worker-return-route.js';
const actor=(id='worker')=>({id,status:'fleeing',x:0,z:0,radius:.28}),end={id:'home',x:3,z:0};
function stub(){let slices=0;return {version:1,*findPathSteps(){for(let i=0;i<4;i++){slices++;yield null;}return [end];},get slices(){return slices;}};}
test('return search resumes bounded native slices rather than draining synchronously',()=>{const nav=stub(),a=actor();for(let i=0;i<4;i++){assert.equal(workerReturnRoute(nav,a,end),null);assert.equal(nav.slices,i+1);}assert.deepEqual(workerReturnRoute(nav,a,end),[end]);});
test('ordinary worker tasks never start a return search',()=>{for(const status of ['idle','acting','carrying','arriving']){const n=stub();assert.equal(workerReturnRoute(n,{...actor(),status},end),null);assert.equal(n.slices,0);}});
test('failed search memo follows exact origin, destination and navigation epoch',()=>{let calls=0;const n={version:1,*findPathSteps(){calls++;return null;}},a=actor();for(let i=0;i<20;i++)workerReturnRoute(n,a,end);assert.equal(calls,1);workerReturnRoute(n,a,{...end,x:4});assert.equal(calls,2);a.x=.1;workerReturnRoute(n,a,end);assert.equal(calls,3);n.version++;workerReturnRoute(n,a,end);assert.equal(calls,4);});
test('only eight pending searches retain native frontier memory per navigation',()=>{let starts=0;const n={version:1,*findPathSteps(){starts++;while(true)yield null;}},workers=Array.from({length:20},(_,i)=>actor(String(i)));for(const w of workers)workerReturnRoute(n,w,end);assert.equal(starts,8);workers[0].x=1;workerReturnRoute(n,workers[8],end);assert.equal(starts,9);});
test('a never-ending iterator is abandoned and memoized at its explicit total bound',()=>{let calls=0;const n={version:1,*findPathSteps(){while(true){calls++;yield null;}}},a=actor();for(let i=0;i<4200;i++)workerReturnRoute(n,a,end);assert.equal(calls,4096);});
test('native worker avoidance view is used for the wider search',()=>{const n=stub(),view=stub();n.workerNavigationView=()=>view;const a=actor();for(let i=0;i<5;i++)workerReturnRoute(n,a,end);assert.equal(n.slices,0);assert.equal(view.slices,4);});
function world(){const n=new Navigation(712,'sabana',{});n.field={slope:()=>0,fluidInside:()=>false};n.propsAt=()=>[];n.version=1;return n;}
for(const obstruction of ['water','lava','solid','steep'])test(`wider native return does not cross ${obstruction}`,()=>{const n=world(),a=actor();if(obstruction==='solid')n.obstacles=[{id:'closed-house',x:0,z:0,radius:2,kind:'house'}];else if(obstruction==='steep')n.field.slope=()=>.7;else n.field.fluidInside=()=>true;for(let i=0;i<10;i++)assert.equal(workerReturnRoute(n,a,end),null);assert.equal(a.x,0);assert.equal(a.z,0);});

test('a real closed wall ring cannot be escaped by enlarging the search corridor',()=>{const n=world(),a=actor();n.obstacles=[{id:'north',kind:'wall',x:0,z:2,yaw:0,baseScaleX:3},{id:'south',kind:'wall',x:0,z:-2,yaw:0,baseScaleX:3},{id:'west',kind:'wall',x:-2,z:0,yaw:Math.PI/2,baseScaleX:3},{id:'east',kind:'wall',x:2,z:0,yaw:Math.PI/2,baseScaleX:3}];let path=null;for(let i=0;i<50;i++)path=workerReturnRoute(n,a,{id:'home',x:6,z:0});assert.equal(path,null);assert.equal(a.x,0);});
test('a new navigation epoch abandons the pending return proof',()=>{const n=stub(),a=actor();workerReturnRoute(n,a,end);n.version++;assert.equal(workerReturnRoute(n,a,end),null);assert.equal(n.slices,2);for(let i=0;i<3;i++)assert.equal(workerReturnRoute(n,a,end),null);assert.deepEqual(workerReturnRoute(n,a,end),[end]);});

test('dry canyon cliffs retain their worker-surface slope restriction',()=>{const n=world(),a=actor();n.field={canyon:true,riverLevel:-10,surface:x=>2*x,waterInfo:()=>({inside:false})};for(let i=0;i<10;i++)assert.equal(workerReturnRoute(n,a,end),null);assert.equal(n.terrainValid(0,0,.28,true),false);assert.equal(a.x,0);});
