import test from 'node:test';
import assert from 'node:assert/strict';
import * as THREE from 'three';
import {SceneMaterialRegistry} from '../src/rendering/material-registry.js';
import {workerFrontsideNames} from '../tools/lib/worker-frontside-pilot.mjs';
import {WorkerDesktopQa,prepareWorkerQaMaterials,workerQaEnabled,workerQaCases,selectWorkerQaCases,snapshotWorkerQaMixer,restoreWorkerQaMixer,observeSelectedDraws,WORKER_QA_SOURCE} from '../src/rendering/worker-desktop-qa.js';

function fixture(){
 const geometry=new THREE.BoxGeometry(),body=new THREE.Mesh(geometry,new THREE.MeshStandardMaterial({side:THREE.FrontSide})),model=new THREE.Group(),parent=new THREE.Group(),associations=new Map();body.name='Mesh0';model.add(body);parent.add(model);
 const sources=workerFrontsideNames.map((name,i)=>{const material=new THREE.MeshStandardMaterial({side:THREE.DoubleSide}),mesh=new THREE.Mesh(geometry,material);mesh.name=name;model.add(mesh);associations.set(material,{materials:[5,6,7,2,3][i]});return material;});
 let geometryDisposed=0;sources.forEach(m=>m.addEventListener('dispose',()=>assert.fail('Source material disposed')));geometry.addEventListener('dispose',()=>geometryDisposed++);
 const toon={materials:new WeakSet(),calls:new Map(),material(m){if(this.materials.has(m))return;this.materials.add(m);this.calls.set(m,(this.calls.get(m)??0)+1);const original=m.onBeforeCompile;m.onBeforeCompile=function(...args){original.apply(this,args);};}};
 const state={time:150,elapsed:10,day:1,workers:[]},renderer={autoClear:true,shadowMap:{enabled:true},getContext(){return {isContextLost:()=>false,getContextAttributes:()=>({antialias:true})};},getRenderTarget:()=>null,getActiveCubeFace:()=>0,getActiveMipmapLevel:()=>0,getViewport:v=>v.set(0,0,1366,768),getScissor:v=>v.set(0,0,1366,768),getScissorTest:()=>false,getClearColor:c=>c.set('#123456'),getClearAlpha:()=>1,getPixelRatio:()=>1,setRenderTarget(){},setViewport(){},setScissor(){},setScissorTest(){},setClearColor(){}};
 const world={toon,state,renderer,nav:{field:{surface:()=>0}},canvas:{width:1366,height:768},camera:new THREE.PerspectiveCamera(),controls:{target:new THREE.Vector3(),enabled:true},loading:{signal:{aborted:false}},actorsReady:()=>true,sync(){},releaseNativeShadow:{cache:{invalidate(){}}}};
 world.materialRegistry=new SceneMaterialRegistry(new THREE.Scene(),toon);
 const rig={profile:'youngMale',model,mixer:new THREE.AnimationMixer(model),action:null,name:'Idle',clips:[]};return {world,rig,gltf:{parser:{associations}},descriptor:{sha256:WORKER_QA_SOURCE},sources,body,geometry,get geometryDisposed(){return geometryDisposed;}};
}
test('native QA is OFF unless all explicit existing-tester gates match',()=>{assert.equal(workerQaEnabled({}),false);assert.equal(workerQaEnabled({__desktopSmokeStarted:true,__desktopSmokeWorkerQa:true}),false);assert.equal(workerQaEnabled({__desktopSmokeStarted:true,__desktopSmokeWorkerQa:true,__TAURI_INTERNALS__:{invoke(){}}}),true);assert.equal(workerQaCases().length,48);assert.equal(new Set(workerQaCases().map(p=>p.clip)).size,12);});
test('preadoption aliases receive exactly one registry decoration, originals and shared nonselected material stay unchanged',()=>{
 const f=fixture(),nonselected=new THREE.Mesh(f.geometry,f.sources[0]);f.rig.model.add(nonselected);const originalBody=f.body.material,p=prepareWorkerQaMaterials(f.world,f.rig,f.gltf,f.descriptor);
 f.world.materialRegistry.root.add(f.rig.model);assert.equal(f.world.toon.calls.get(f.sources[0]),1);p.setEnabled(true);for(const e of p.entries)f.world.materialRegistry.refresh(e.mesh);
 for(const e of p.entries){assert.equal(f.world.toon.calls.get(e.candidate),1);assert.equal(e.mesh.geometry,f.geometry);assert.equal(e.source.side,2);assert.equal(e.candidate.side,0);assert.ok(Object.hasOwn(e.candidate.defines,'DOUBLE_SIDED'));}
 p.setEnabled(false);for(const e of p.entries)f.world.materialRegistry.refresh(e.mesh);p.setEnabled(true);for(const e of p.entries)f.world.materialRegistry.refresh(e.mesh);assert.ok(p.entries.every(e=>f.world.toon.calls.get(e.candidate)===1));assert.equal(nonselected.material,f.sources[0]);assert.equal(nonselected.material.side,2);assert.equal(f.body.material,originalBody);assert.equal(f.body.material.side,0);
 p.setEnabled(false);for(const e of p.entries)f.world.materialRegistry.refresh(e.mesh);p.release();assert.equal(f.geometryDisposed,0);f.world.materialRegistry.dispose();
});
test('decorated source or association mismatch fails before aliases exist',()=>{const f=fixture();f.world.toon.material(f.sources[0]);assert.throws(()=>prepareWorkerQaMaterials(f.world,f.rig,f.gltf,f.descriptor),/precede/);assert.ok(f.sources.every(m=>m.side===2));const g=fixture();g.gltf.parser.associations.set(g.sources[0],{materials:99});assert.throws(()=>prepareWorkerQaMaterials(g.world,g.rig,g.gltf,g.descriptor),/association/);assert.ok(g.sources.every(m=>m.side===2));});
test('native-hide cancellation restores world/camera/borrowed identities, releases owned aliases, keeps renderer',async()=>{
 const f=fixture(),owner=new WorkerDesktopQa(f.world);owner.adopt(f.rig,f.gltf,f.descriptor);const before=JSON.stringify(f.world.state),camera=f.world.camera.position.clone(),pending=owner.start({limit:1});f.world.state.time=450;f.world.controls.enabled=false;f.world.camera.position.set(10,20,30);const previous=globalThis.document;globalThis.document={hidden:true};try{assert.equal(owner.frame(),true);}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous;}
 const report=await pending;assert.match(report.errors[0],/cancelled/);assert.equal(JSON.stringify(f.world.state),before);assert.ok(f.world.camera.position.equals(camera));assert.equal(report.cleanup.stateExact,true);assert.equal(report.cleanup.borrowedGeometryAttributesExact,true);assert.equal(report.cleanup.borrowedDisposeEvents,0);assert.equal(report.cleanup.ownedMaterialsRemaining,0);assert.equal(report.cleanup.rendererRetained,true);assert.equal(f.geometryDisposed,0);assert.ok(owner.pilot.entries.every(e=>e.mesh.material===e.source));owner.dispose();assert.equal(globalThis.__desktopSmokeWorkerProbe,undefined);
});

test('bounded explicit selection defaults to naturally active crate and hoe clips without removing the 48 cases',()=>{
 assert.deepEqual(selectWorkerQaCases().map(p=>[p.caseIndex,p.clip,p.fraction,p.night]),[[34,'Carry_Crate',.625,false],[18,'Dig',.625,false]]);
 assert.equal(selectWorkerQaCases({limit:1})[0].clip,'Carry_Crate');assert.equal(selectWorkerQaCases({caseIndices:Array.from({length:48},(_,i)=>i)}).length,48);
 for(const caseIndices of [[48],[-1],[1,1],[],[1.5]])assert.throws(()=>selectWorkerQaCases({caseIndices}),/indices/);
 assert.throws(()=>selectWorkerQaCases({caseIndices:[18],limit:2}),/limit/);
});
test('mixer snapshot rejects concurrent/faded activity before mutation and restores only owned touched actions',()=>{
 const root=new THREE.Object3D(),mixer=new THREE.AnimationMixer(root),clips=['Idle','Dig','Carry_Crate'].map(name=>new THREE.AnimationClip(name,2,[new THREE.NumberKeyframeTrack('.position[x]',[0,2],[0,2])])),actions=clips.map(c=>mixer.clipAction(c));
 const rig={model:root,mixer,action:actions[0],name:'Idle'};actions[0].play();actions[0].paused=true;actions[0].time=.3;mixer.update(0);mixer.time=7;mixer.timeScale=.5;
 actions[1].play();assert.throws(()=>snapshotWorkerQaMixer(rig),/concurrent/);assert.equal(actions[1].isScheduled(),true);actions[1].stop();
 actions[0].fadeOut(1);assert.throws(()=>snapshotWorkerQaMixer(rig),/fade/);actions[0].stopFading();const snapshot=snapshotWorkerQaMixer(rig);
 const before=snapshot.actions.map(r=>({...r.values}));actions[0].stop();rig.action=actions[2].reset().play();rig.name='Carry_Crate';rig.action.time=1.25;rig.action.paused=true;mixer.update(0);
 mixer.stopAllAction=()=>assert.fail('Global mixer cancellation forbidden');assert.equal(restoreWorkerQaMixer(rig,snapshot,new Set([actions[2]])),true);
 assert.equal(rig.action,actions[0]);assert.equal(rig.name,'Idle');assert.equal(mixer.time,7);assert.equal(mixer.timeScale,.5);assert.deepEqual(snapshot.actions.map(r=>Object.fromEntries(Object.keys(r.values).map(k=>[k,r.action[k]]))),before);
 assert.equal(actions[0].isScheduled(),true);assert.equal(actions[1].isScheduled(),false);assert.equal(actions[2].isScheduled(),false);
});
test('selected draw witnesses preserve native callbacks on success and cancellation, without drawing hidden tools',()=>{
 const f=fixture(),mesh=f.rig.model.children[1],entry={mesh,geometry:f.geometry};let colorCalls=0,shadowCalls=0;const color=()=>colorCalls++,shadow=()=>shadowCalls++;mesh.onAfterRender=color;mesh.onAfterShadow=shadow;
 const renderer={getRenderTarget:()=>null,getContext:()=>({CULL_FACE:1,CULL_FACE_MODE:2,FRONT_FACE:3,isEnabled:()=>true,getParameter:p=>p===2?1029:2305})},camera=f.world.camera,depth=new THREE.MeshDepthMaterial({side:THREE.DoubleSide});
 const draws=observeSelectedDraws([entry],()=>{mesh.onAfterRender(renderer,null,camera,f.geometry,mesh.material,null);mesh.onAfterShadow(renderer,mesh,camera,camera,f.geometry,depth,null);});
 assert.equal(colorCalls,1);assert.equal(shadowCalls,1);assert.deepEqual(draws.map(d=>d.role),['screen','shadow']);assert.equal(draws[0].cullMode,1029);assert.equal(draws[1].depthSide,2);assert.equal(mesh.onAfterRender,color);assert.equal(mesh.onAfterShadow,shadow);
 mesh.visible=false;assert.deepEqual(observeSelectedDraws([entry],()=>{}),[]);assert.equal(mesh.visible,false);
 assert.throws(()=>observeSelectedDraws([entry],()=>{throw Error('cancel');}),/cancel/);assert.equal(mesh.onAfterRender,color);assert.equal(mesh.onAfterShadow,shadow);
});

test('timing owns one original RAF draw per step, exact protocol, no visual witnesses/readbacks inside queries and full cleanup',async()=>{
 const f=fixture(),owner=new WorkerDesktopQa(f.world);owner.adopt(f.rig,f.gltf,f.descriptor);f.world.scene=f.world.materialRegistry.root;f.world.scene.add(f.rig.model.parent);f.rig.clips=['Carry_Crate','Dig'].map(name=>new THREE.AnimationClip(name,2,[new THREE.NumberKeyframeTrack('.position[x]',[0,2],[0,2])]));
 const ext={TIME_ELAPSED_EXT:1,QUERY_COUNTER_BITS_EXT:2,GPU_DISJOINT_EXT:3};let active=null,queries=0,deleted=0,draws=0,readbacks=0,invalidations=0;
 const gl={CULL_FACE:10,CULL_FACE_MODE:11,FRONT_FACE:12,CURRENT_QUERY:13,QUERY_RESULT_AVAILABLE:14,QUERY_RESULT:15,RGBA:16,UNSIGNED_BYTE:17,getExtension:()=>ext,getQuery:(t,p)=>p===ext.QUERY_COUNTER_BITS_EXT?64:active,isContextLost:()=>false,getContextAttributes:()=>({antialias:true}),getParameter:p=>p===ext.GPU_DISJOINT_EXT?false:p===11?1029:2305,isEnabled:()=>true,createQuery:()=>({id:++queries}),beginQuery:(t,q)=>{assert.equal(active,null);active=q;},endQuery:()=>{assert.ok(active);active.ns=owner.pilot.entries[0].mesh.material.side===0?9500000:10000000;active=null;},getQueryParameter:(q,p)=>p===14?true:q.ns,deleteQuery:()=>deleted++,readPixels(){assert.equal(active,null);readbacks++;}};
 f.world.renderer.getContext=()=>gl;f.world.renderer.info={render:{calls:6,triangles:72}};f.world.canvas={width:4,height:4,toDataURL(){assert.equal(active,null);return 'data:image/png;base64,CPU_STUB';}};f.world.releaseNativeShadow.cache={stats:{hits:0,misses:0},invalidate(){invalidations++;}};
 f.world.renderFrameUpdates=function*(){assert.equal(active,null);};f.world.drawRenderFrame=()=>{draws++;for(const entry of owner.pilot.entries){if(active)assert.equal(entry.mesh.onAfterShadow,THREE.Object3D.prototype.onAfterShadow);entry.mesh.onAfterRender(f.world.renderer,null,f.world.camera,entry.geometry,entry.mesh.material,null);entry.mesh.onAfterShadow(f.world.renderer,entry.mesh,f.world.camera,f.world.camera,entry.geometry,new THREE.MeshDepthMaterial(),null);}};
 const before=JSON.stringify(f.world.state),previous=globalThis.document;globalThis.document={hidden:false};let report;
 try{const pending=owner.start({mode:'timing'});for(let frames=0;owner.active&&frames<4100;frames++)owner.frame();assert.equal(owner.active,false);report=await pending;}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous;owner.dispose();}
 assert.deepEqual(report.errors,[]);assert.equal(report.coverage.complete,true);assert.equal(queries,2880);assert.equal(deleted,2880);assert.equal(draws,3966);assert.equal(readbacks,6);assert.equal(invalidations,7);assert.equal(report.timing.raw.length,2880);assert.equal(report.timing.blocks.length,24);assert.equal(report.timing.status,'useful-fixed-pose-pilot');assert.equal(report.cleanup.ownedQueriesRemaining,0);assert.equal(report.cleanup.mixerActivityRestored,true);assert.equal(report.cleanup.stateExact,true);assert.equal(JSON.stringify(f.world.state),before);assert.equal(report.cleanup.borrowedDisposeEvents,0);
});

test('native camera protection that prevents full framing cancels owner before draw/query/readback and restores borrowed state',async()=>{
 const f=fixture(),owner=new WorkerDesktopQa(f.world);owner.adopt(f.rig,f.gltf,f.descriptor);f.rig.clips=['Carry_Crate','Dig'].map(name=>new THREE.AnimationClip(name,2,[new THREE.NumberKeyframeTrack('.position[x]',[0,2],[0,2])]));
 const before=JSON.stringify(f.world.state);f.world.camera.position.set(1,2,3);const camera=f.world.camera.clone(),target=f.world.controls.target.clone();let queries=0,reads=0,draws=0,protections=0;
 const originalGl=f.world.renderer.getContext();f.world.renderer.getContext=()=>({...originalGl,getExtension:()=>({TIME_ELAPSED_EXT:1,QUERY_COUNTER_BITS_EXT:2}),getQuery:()=>64,createQuery:()=>{queries++;assert.fail('Query must not begin after protected-camera failure');},readPixels:()=>{reads++;assert.fail('Readback must not occur after framing failure');}});
 f.world.renderFrameUpdates=function*(){protections++;f.world.camera.position.copy(f.world.controls.target).add(new THREE.Vector3(0,.5,.1));f.world.camera.lookAt(f.world.controls.target);f.world.camera.updateMatrixWorld();};f.world.drawRenderFrame=()=>{draws++;assert.fail('Cannot draw rejected framing');};
 const previous=globalThis.document;globalThis.document={hidden:false};let report;
 try{const pending=owner.start({mode:'timing'});owner.frame();report=await pending;}finally{if(previous===undefined)delete globalThis.document;else globalThis.document=previous;owner.dispose();}
 assert.equal(report.lastFraming.fits,false);assert.ok(report.lastFraming.intended.eye);assert.ok(report.lastFraming.actual.eye);assert.ok(report.lastFraming.bounds);assert.equal(protections,1);assert.equal(queries,0);assert.equal(reads,0);assert.equal(draws,0);assert.match(report.errors[0],/Native camera cannot retain/);assert.equal(report.timing.status,'inconclusive');assert.equal(report.cleanup.ownedQueriesRemaining,0);assert.equal(report.cleanup.stateExact,true);assert.equal(report.cleanup.mixerActivityRestored,true);assert.equal(report.cleanup.borrowedGeometryAttributesExact,true);assert.equal(report.cleanup.borrowedDisposeEvents,0);assert.equal(report.cleanup.ownedMaterialsRemaining,0);assert.equal(report.cleanup.closed,true);assert.equal(JSON.stringify(f.world.state),before);assert.ok(f.world.camera.position.equals(camera.position));assert.ok(f.world.camera.quaternion.equals(camera.quaternion));assert.ok(f.world.controls.target.equals(target));assert.equal(f.world.controls.enabled,true);assert.equal(f.geometryDisposed,0);assert.ok(owner.pilot.entries.every(e=>e.mesh.material===e.source));
});
