// Generated by tools/prepare_guardian.py from the original Guardian V8 lab.
const clamp = (x,a,b) => Math.max(a,Math.min(b,x));
const smoothstep = (a,b,x) => {const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t);};

export const GUARDIAN_SPRITE='/assets/5170de5cc32e7da971a861db79d090b4bdc2c6cece5b22e4b1c06fe3de59e464.webp';
export const GESTURE_MIN_SECONDS={greeting:5.8,speak:5.8,acknowledge:6.8,curious:6.8,warning:6.2,reveal:7.8,idle:7,farewell:6.8};
class SpriteMesh {
 constructor(canvas,image){
  this.canvas=canvas;this.image=image;this.renderImage=image;this.gl=null;this.ctx=null;this.debug=false;this.lost=false;this.dirty=true;this.lastPose=[Infinity,Infinity,Infinity];
  this.pad=.06;this.scale=.88;this.overscan=.22;this.viewportSpan=1+2*this.overscan;this.pivotX=.567;this.pivotY=.624;
  try{this.gl=canvas.getContext('webgl',{alpha:true,antialias:true,premultipliedAlpha:true,preserveDrawingBuffer:false,powerPreference:'low-power'});}catch(e){console.warn('WebGL no disponible; se usa Canvas 2D.',e);}
  this.nx=this.gl?64:24;this.ny=this.gl?76:28;
  const count=(this.nx+1)*(this.ny+1);this.base=new Float32Array(count*2);this.positions=new Float32Array(count*2);this.weights=new Float32Array(count);this.depths=new Float32Array(count);this.uvs=new Float32Array(count*2);
  for(let y=0;y<=this.ny;y++)for(let x=0;x<=this.nx;x++){
   const i=y*(this.nx+1)+x,u=x/this.nx,v=y/this.ny;
   this.base[i*2]=u;this.base[i*2+1]=v;this.uvs[i*2]=u;this.uvs[i*2+1]=v;
   // V4.1: la mandíbula completa pertenece a la cabeza. La punta del mentón
   // acaba en v≈0.600; una fila de seguridad impide que la interpolación de
   // triángulos arrastre ese borde al empezar la articulación del cuello.
   const neckT=clamp((v-.608)/(.652-.608),0,1);
   // Casi lineal: a diferencia de un smoothstep puro, no concentra toda la
   // compresión en el centro del cuello ni lo pliega en los gestos amplios.
   const neckBlend=neckT+.18*(neckT*neckT*(3-2*neckT)-neckT);
   this.weights[i]=1-neckBlend;
   // Plano facial coherente. Antes el relieve se extinguía entre boca y
   // barbilla: al asentir, cada fila viajaba una distancia distinta y el
   // mentón se aplastaba. Ahora toda la cara inferior comparte profundidad;
   // solo la frente y la nariz conservan un relieve pequeño, sin tocar labios.
   const dx=(u-.54)/.325,dy=(v-.365)/.335;
   const dome=Math.sqrt(Math.max(0,1-dx*dx-dy*dy));
   const nose=Math.exp(-((u-.565)**2/.0036+(v-.446)**2/.008));
   const upperRelief=1-smoothstep(.425,.480,v);
   this.depths[i]=.090+(.020*dome+.010*nose)*upperRelief;
  }
  const tris=[],lines=[];
  for(let y=0;y<this.ny;y++)for(let x=0;x<this.nx;x++){const a=y*(this.nx+1)+x,b=a+1,c=a+this.nx+1,d=c+1;tris.push(a,c,b,b,c,d);}
  const skip=this.gl?3:2;
  for(let y=0;y<=this.ny;y+=skip)for(let x=0;x<this.nx;x++){const a=y*(this.nx+1)+x;lines.push(a,a+1);}
  for(let x=0;x<=this.nx;x+=skip)for(let y=0;y<this.ny;y++){const a=y*(this.nx+1)+x;lines.push(a,a+this.nx+1);}
  this.indices=new Uint16Array(tris);this.lines=new Uint16Array(lines);
  if(this.gl){
   this.initGL();
   canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();this.lost=true;this.canvas.dataset.engine='WebGL suspendido · esperando recuperación';});
   canvas.addEventListener('webglcontextrestored',()=>{this.lost=false;this.initGL();this.resize();this.canvas.dataset.engine=this.description();});
  }else{this.ctx=canvas.getContext('2d',{alpha:true});if(!this.ctx)throw new Error('El navegador no ofrece Canvas 2D ni WebGL.');const small=document.createElement('canvas');small.width=Math.min(640,image.width);small.height=Math.round(small.width*image.height/image.width);small.getContext('2d').drawImage(image,0,0,small.width,small.height);this.renderImage=small;}
  this.resize();this.update(0,0,0);this.draw();
 }
 description(){return this.gl?`WebGL · ${this.nx} × ${this.ny} · ${this.weights.length.toLocaleString('es-ES')} vértices`:`Canvas 2D · malla de respaldo ${this.nx} × ${this.ny}`;}
 initGL(){
  const gl=this.gl;
  const vertex=`attribute vec2 aPosition;attribute vec2 aUV;attribute float aWeight;varying vec2 vUV;varying float vWeight;void main(){vUV=aUV;vWeight=aWeight;gl_Position=vec4(aPosition,0.0,1.0);}`;
  const fragment=`precision mediump float;uniform sampler2D uTexture;uniform float uDebug;varying vec2 vUV;varying float vWeight;void main(){vec4 c=texture2D(uTexture,vUV);if(uDebug>.5){if(c.a<.16)discard;vec3 col=mix(vec3(1.,.64,.20),vec3(.31,1.,.83),vWeight);gl_FragColor=vec4(col*.77,.77);}else{gl_FragColor=c;}}`;
  const shader=(type,source)=>{const s=gl.createShader(type);gl.shaderSource(s,source);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS)){const log=gl.getShaderInfoLog(s);gl.deleteShader(s);throw new Error('No se ha podido compilar el shader: '+log);}return s;};
  const vs=shader(gl.VERTEX_SHADER,vertex),fs=shader(gl.FRAGMENT_SHADER,fragment);this.program=gl.createProgram();gl.attachShader(this.program,vs);gl.attachShader(this.program,fs);gl.linkProgram(this.program);gl.deleteShader(vs);gl.deleteShader(fs);if(!gl.getProgramParameter(this.program,gl.LINK_STATUS))throw new Error('No se ha podido enlazar el shader.');gl.useProgram(this.program);
  const attr=(name,data,size,dynamic=false)=>{const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,data,dynamic?gl.DYNAMIC_DRAW:gl.STATIC_DRAW);const loc=gl.getAttribLocation(this.program,name);gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,size,gl.FLOAT,false,0,0);return b;};
  this.positionBuffer=attr('aPosition',this.positions,2,true);this.uvBuffer=attr('aUV',this.uvs,2);this.weightBuffer=attr('aWeight',this.weights,1);
  this.indexBuffer=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,this.indices,gl.STATIC_DRAW);this.lineBuffer=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.lineBuffer);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,this.lines,gl.STATIC_DRAW);
  this.texture=gl.createTexture();gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,this.texture);gl.pixelStorei(gl.UNPACK_PREMULTIPLY_ALPHA_WEBGL,true);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,gl.RGBA,gl.UNSIGNED_BYTE,this.image);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.CLAMP_TO_EDGE);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.uniform1i(gl.getUniformLocation(this.program,'uTexture'),0);this.uDebug=gl.getUniformLocation(this.program,'uDebug');gl.disable(gl.DEPTH_TEST);gl.disable(gl.CULL_FACE);gl.enable(gl.BLEND);gl.blendFunc(gl.ONE,gl.ONE_MINUS_SRC_ALPHA);gl.clearColor(0,0,0,0);
 }
 resize(){this.dirty=true;const dpr=Math.min(devicePixelRatio||1,this.gl?2:1.25);this.canvas.width=Math.max(2,Math.round(this.canvas.clientWidth*dpr));this.canvas.height=Math.max(2,Math.round(this.canvas.clientHeight*dpr));if(this.gl&&!this.lost)this.gl.viewport(0,0,this.canvas.width,this.canvas.height);}

 // La cabeza puede tapar casi todo el cuello, pero la malla no debe invertirse.
 // Se reserva un pequeño tramo cervical; el límite desplaza la cabeza como
 // bloque rígido y NO cambia su forma ni las curvas de los ocho gestos.
 cervicalOffset(cr,sr,cy,sy,cp,sp,headY=0){
  const top=.608,depth=.090,dy=top-this.pivotY;
  let maximumDrop=-Infinity;
  for(const u of [.465,.598]){
   const dx=u-this.pivotX,x=dx*cy+depth*sy,y=dy*cp-depth*sp;
   maximumDrop=Math.max(maximumDrop,x*sr+y*cr-dy+headY);
  }
  return headY-Math.max(0,maximumDrop-.033);
 }
 update(roll,yaw,pitch){
  const cr=Math.cos(roll),sr=Math.sin(roll),cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch),px=this.pivotX,py=this.pivotY;
  const headOffsetY=this.cervicalOffset(cr,sr,cy,sy,cp,sp);
  for(let i=0;i<this.weights.length;i++){
   const u=this.base[i*2],v=this.base[i*2+1],weight=this.weights[i],dx=u-px,dy=v-py,depth=this.depths[i];
   const x=dx*cy+depth*sy,y=dy*cp-depth*sp;
   const rx=x*cr-y*sr,ry=x*sr+y*cr;
   const fx=u+(rx-dx)*weight,fy=v+(ry-dy+headOffsetY)*weight;
   this.positions[i*2]=(this.overscan+this.pad+fx*this.scale)/this.viewportSpan*2-1;this.positions[i*2+1]=1-(this.overscan+this.pad+fy*this.scale)/this.viewportSpan*2;
  }
 }
 draw(){
  this.dirty=false;
  if(this.gl){if(this.lost)return;const gl=this.gl;gl.useProgram(this.program);gl.bindBuffer(gl.ARRAY_BUFFER,this.positionBuffer);gl.bufferSubData(gl.ARRAY_BUFFER,0,this.positions);gl.clear(gl.COLOR_BUFFER_BIT);gl.uniform1f(this.uDebug,0);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.indexBuffer);gl.drawElements(gl.TRIANGLES,this.indices.length,gl.UNSIGNED_SHORT,0);if(this.debug){gl.uniform1f(this.uDebug,1);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,this.lineBuffer);gl.drawElements(gl.LINES,this.lines.length,gl.UNSIGNED_SHORT,0);}return;}
  // Respaldo sin WebGL: las mismas deformaciones con triángulos afines Canvas 2D.
  const ctx=this.ctx,w=this.canvas.width,h=this.canvas.height,iw=this.renderImage.width,ih=this.renderImage.height;ctx.clearRect(0,0,w,h);ctx.imageSmoothingEnabled=true;
  const vertex=i=>[(this.positions[i*2]+1)*.5*w,(1-this.positions[i*2+1])*.5*h];
  for(let k=0;k<this.indices.length;k+=3){
   const i0=this.indices[k],i1=this.indices[k+1],i2=this.indices[k+2],p0=vertex(i0),p1=vertex(i1),p2=vertex(i2);
   const u0=this.uvs[i0*2]*iw,v0=this.uvs[i0*2+1]*ih,u1=this.uvs[i1*2]*iw,v1=this.uvs[i1*2+1]*ih,u2=this.uvs[i2*2]*iw,v2=this.uvs[i2*2+1]*ih;
   const du1=u1-u0,dv1=v1-v0,du2=u2-u0,dv2=v2-v0,det=du1*dv2-du2*dv1;if(Math.abs(det)<1e-6)continue;
   const a=((p1[0]-p0[0])*dv2-(p2[0]-p0[0])*dv1)/det,b=((p1[1]-p0[1])*dv2-(p2[1]-p0[1])*dv1)/det,c=((p2[0]-p0[0])*du1-(p1[0]-p0[0])*du2)/det,d=((p2[1]-p0[1])*du1-(p1[1]-p0[1])*du2)/det;
   const mx=(p0[0]+p1[0]+p2[0])/3,my=(p0[1]+p1[1]+p2[1])/3;
   ctx.save();ctx.beginPath();for(let j=0;j<3;j++){const p=[p0,p1,p2][j],len=Math.hypot(p[0]-mx,p[1]-my)||1,xx=p[0]+(p[0]-mx)*.38/len,yy=p[1]+(p[1]-my)*.38/len;j?ctx.lineTo(xx,yy):ctx.moveTo(xx,yy);}ctx.closePath();ctx.clip();ctx.transform(a,b,c,d,p0[0]-a*u0-c*v0,p0[1]-b*u0-d*v0);const su=Math.max(0,Math.min(u0,u1,u2)-1),sv=Math.max(0,Math.min(v0,v1,v2)-1),sw=Math.min(iw,Math.max(u0,u1,u2)+1)-su,sh=Math.min(ih,Math.max(v0,v1,v2)+1)-sv;ctx.drawImage(this.renderImage,su,sv,sw,sh,su,sv,sw,sh);ctx.restore();
  }
  if(this.debug){ctx.lineWidth=.75;for(let k=0;k<this.lines.length;k+=2){const i=this.lines[k],j=this.lines[k+1],a=vertex(i),b=vertex(j);ctx.strokeStyle=this.weights[i]>.5?'#65ffd7bb':'#ffb248aa';ctx.beginPath();ctx.moveTo(...a);ctx.lineTo(...b);ctx.stroke();}}
 }
}

// --------------------------------------------------------------------------
// Cuatro huesos virtuales locales, sobre LA MISMA textura. No se cortan capas:
// las máscaras solo cambian pesos de vértices en los adornos y su contorno.
// Los polígonos están expresados en UV de la imagen original, no de la ventana.
// --------------------------------------------------------------------------
const ORNAMENTS = [
 {name:'Pluma flotante izquierda',anchor:[.164,.343],floating:true,phase:.3,delay:.10,
  polygon:[[.145,.309],[.184,.323],[.184,.385],[.169,.423],[.175,.479],[.152,.532],[.119,.545],[.087,.507],[.099,.437],[.127,.384]]},
 {name:'Colgante izquierdo',anchor:[.294,.535],floating:false,phase:1.7,delay:.13,
  polygon:[[.252,.540],[.288,.526],[.326,.546],[.332,.618],[.308,.654],[.301,.734],[.231,.778],[.192,.721],[.207,.636],[.245,.582]]},
 {name:'Pluma flotante derecha',anchor:[.722,.215],floating:true,phase:3.4,delay:.115,
  polygon:[[.700,.183],[.739,.184],[.755,.245],[.800,.271],[.848,.318],[.862,.386],[.815,.391],[.757,.345],[.720,.291],[.700,.252]]},
 {name:'Colgante derecho',anchor:[.720,.472],floating:false,phase:4.5,delay:.15,
  polygon:[[.704,.449],[.747,.455],[.753,.486],[.801,.498],[.850,.559],[.868,.616],[.813,.640],[.750,.603],[.719,.650],[.670,.644],[.666,.574],[.684,.522]]}
];
function polygonWeight(x,y,points){
 let inside=false,nearest=Infinity;
 for(let i=0,j=points.length-1;i<points.length;j=i++){
  const a=points[j],b=points[i];
  if(((a[1]>y)!==(b[1]>y))&&(x<(b[0]-a[0])*(y-a[1])/(b[1]-a[1])+a[0]))inside=!inside;
  const dx=b[0]-a[0],dy=b[1]-a[1],t=clamp(((x-a[0])*dx+(y-a[1])*dy)/(dx*dx+dy*dy||1),0,1);
  nearest=Math.min(nearest,Math.hypot(x-a[0]-dx*t,y-a[1]-dy*t));
 }
 // El fundido de borde ocupa sobre todo píxeles transparentes, no el rostro.
 return inside?1:1-smoothstep(0,.018,nearest);
}
export class GuardianMesh extends SpriteMesh {
 constructor(canvas,image){
  super(canvas,image);
  this.regions=new Array(this.weights.length);this.accessoryWeight=new Float32Array(this.weights.length);
  for(let i=0;i<this.weights.length;i++){
   const u=this.base[i*2],v=this.base[i*2+1],list=[];let sum=0;
   ORNAMENTS.forEach((o,k)=>{
    let m=polygonWeight(u,v,o.polygon);
    // Evitar que el contorno difuso de los pendientes arrastre el hombro.
    if(k===1)m*=1-smoothstep(.265,.31,u)*smoothstep(.65,.735,v);
    if(k===3)m*=1-(1-smoothstep(.705,.755,u))*smoothstep(.615,.665,v);
    if(m>.001){list.push([k,m]);sum+=m;}
   });
   this.regions[i]=list;this.accessoryWeight[i]=Math.min(1,sum);
  }
  this.rigReady=true;
 }
 update(roll,yaw,pitch,extra=null){
  if(!this.rigReady||!extra){super.update(roll,yaw,pitch);return;}
  const cr=Math.cos(roll),sr=Math.sin(roll),cy=Math.cos(yaw),sy=Math.sin(yaw),cp=Math.cos(pitch),sp=Math.sin(pitch);
  const px=this.pivotX,py=this.pivotY,blend=extra.blend;
  const headOffsetY=this.cervicalOffset(cr,sr,cy,sy,cp,sp,extra.headY||0);
  const cs=extra.angles.map(Math.cos),ss=extra.angles.map(Math.sin);
  const bc=Math.cos(extra.bodyRoll||0),bs=Math.sin(extra.bodyRoll||0);
  for(let i=0;i<this.weights.length;i++){
   const u=this.base[i*2],v=this.base[i*2+1];let du=0,dv=0;
   for(const [k,m] of this.regions[i]){
    const o=ORNAMENTS[k],x=u-o.anchor[0],y=v-o.anchor[1],gain=m*blend;
    du+=(x*cs[k]-y*ss[k]-x)*gain;
    dv+=(x*ss[k]+y*cs[k]-y+extra.offsets[k])*gain;
   }
   // Los colgantes heredan la cabeza, aunque caigan por debajo del cuello.
   // El pecho sigue siendo rígido; la levitación traslada el busto entero.
   const weight=this.weights[i]+(1-this.weights[i])*this.accessoryWeight[i]*blend;
   const dx=u+du-px,dy=v+dv-py,depth=this.depths[i];
   const x=dx*cy+depth*sy,y=dy*cp-depth*sp;
   let fx=u+du+(x*cr-y*sr-dx+(extra.headX||0))*weight,fy=v+dv+(x*sr+y*cr-dy+headOffsetY)*weight;
   const bx=fx-px,by=fy-.84;
   fx=px+(bx*bc-by*bs)*(1+extra.zoom)+(extra.bodyX||0);fy=.84+(bx*bs+by*bc)*(1+extra.zoom)+extra.lift;
   this.positions[i*2]=(this.overscan+this.pad+fx*this.scale)/this.viewportSpan*2-1;this.positions[i*2+1]=1-(this.overscan+this.pad+fy*this.scale)/this.viewportSpan*2;
  }
 }
 // Interpolación sobre la malla deformada: los brillos y pivotes siguen la
 // imagen incluso con los cambios de perspectiva o la física secundaria.
 project(u,v){
  const xx=clamp(u,0,.999999)*this.nx,yy=clamp(v,0,.999999)*this.ny,x=Math.floor(xx),y=Math.floor(yy),tx=xx-x,ty=yy-y;
  const a=y*(this.nx+1)+x,b=a+1,c=a+this.nx+1,d=c+1;
  const interp=k=>(this.positions[a*2+k]*(1-tx)+this.positions[b*2+k]*tx)*(1-ty)+(this.positions[c*2+k]*(1-tx)+this.positions[d*2+k]*tx)*ty;
  return [(interp(0)+1)*.5,(1-interp(1))*.5];
 }
}
class DampedSpring {
 constructor(frequency,damping){this.omega=frequency;this.damping=damping;this.x=0;this.v=0;}
 reset(){this.x=0;this.v=0;}
 step(target,dt){
  // Integración con subpasos: no explota con una pausa o con pocos FPS.
  const n=Math.max(1,Math.ceil(dt*120)),h=dt/n,w=this.omega;
  for(let i=0;i<n;i++){this.v+=(w*w*(target-this.x)-2*this.damping*w*this.v)*h;this.x+=this.v*h;}
  return this.x;
 }
}
export class OrnamentPhysics {
 constructor(){this.bones=ORNAMENTS.map((o,i)=>({angle:new DampedSpring(5.8+i*.28,.58),height:new DampedSpring(4.6+i*.19,.65)}));this.history=[];this.angles=[0,0,0,0];this.offsets=[0,0,0,0];}
 reset(){this.history.length=0;this.bones.forEach(b=>{b.angle.reset();b.height.reset();});this.angles.fill(0);this.offsets.fill(0);}
 step(t,dt,roll,yaw,reveal,amplitude,strength){
  this.history.push({t,roll,yaw});while(this.history.length>2&&this.history[1].t<t-.30)this.history.shift();
  ORNAMENTS.forEach((o,k)=>{
   const at=t-o.delay;let a=this.history[0],b=a;
   for(let i=1;i<this.history.length;i++){b=this.history[i];if(b.t>=at)break;a=b;}
   const f=clamp((at-a.t)/(b.t-a.t||1),0,1),r=a.roll+(b.roll-a.roll)*f,y=a.yaw+(b.yaw-a.yaw)*f;
   const float=o.floating,wind=(float?.034:.016)*Math.sin(t*(float?.62:.51)+o.phase)*amplitude;
   const target=r*(float?.8:.35)+y*(float?.28:.14)+wind+reveal*.047*Math.sin(o.phase);
   const rotation=this.bones[k].angle.step(target,dt);
   const rise=float?(-.0058*Math.sin(t*.69+o.phase)*amplitude-reveal*.009):0;
   this.angles[k]=clamp(rotation-roll,-.155,.155)*strength;
   this.offsets[k]=this.bones[k].height.step(rise,dt)*strength;
  });
 }
}
export class GuardianMagic {
 constructor(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d',{alpha:true});this.resize();}
 resize(){const size=this.canvas.clientWidth||300,dpr=Math.min(devicePixelRatio||1,2);this.canvas.width=Math.round(size*dpr);this.canvas.height=Math.round(size*dpr);}
 draw(mesh,t,light,debug){
  const g=this.ctx;if(!g)return;const w=this.canvas.width,h=this.canvas.height;g.clearRect(0,0,w,h);
  const at=(u,v)=>{const p=mesh.project(u,v);return [p[0]*w,p[1]*h];};
  const glow=(u,v,rx,ry,power)=>{
   if(power<.001)return;power=clamp(power,0,.94);const [x,y]=at(u,v);g.save();g.translate(x,y);g.scale(rx*w/mesh.viewportSpan,ry*h/mesh.viewportSpan);
   const gradient=g.createRadialGradient(0,0,0,0,0,1);gradient.addColorStop(0,`rgba(255,233,165,${power})`);gradient.addColorStop(.32,`rgba(255,209,101,${power*.60})`);gradient.addColorStop(1,'rgba(255,185,58,0)');g.fillStyle=gradient;g.fillRect(-1,-1,2,2);g.restore();
  };
  // Sin parpadeos ni boca animada: luz cálida y lenta, localizada en ojos y sol.
  glow(.414,.431,.059,.044,light.eyes);glow(.627,.375,.045,.052,light.eyes*.9);
  glow(.625,.795,.111,.105,light.medallion);glow(.625,.795,.047,.045,light.medallion*.40);
  if(light.reveal>.001){
   glow(.57,.48,.33,.39,light.reveal*.085);
   for(let k=0;k<9;k++){
    const a=k*2.399+t*.23,side=k%2===0?-1:1;
    const u=.55+side*(.28+.025*Math.sin(a)),v=.60-.27*(.5+.5*Math.sin(a*.65+k));
    const p=at(clamp(u,.05,.93),v),r=(1.45+.4*Math.sin(a*1.2))*w/(440*mesh.viewportSpan);
    const gradient=g.createRadialGradient(p[0],p[1],0,p[0],p[1],r*4);
    gradient.addColorStop(0,`rgba(255,241,172,${clamp(light.reveal*.62,0,.95)})`);gradient.addColorStop(.28,`rgba(255,220,123,${clamp(light.reveal*.40,0,.85)})`);gradient.addColorStop(1,'rgba(255,200,74,0)');g.fillStyle=gradient;g.fillRect(p[0]-r*4,p[1]-r*4,r*8,r*8);
   }
  }
  if(debug){
   g.lineWidth=Math.max(1,w/440);g.strokeStyle='#dbb9ffb0';
   ORNAMENTS.forEach(o=>{g.beginPath();o.polygon.forEach((p,i)=>{const q=at(...p);i?g.lineTo(...q):g.moveTo(...q);});g.closePath();g.stroke();const p=at(...o.anchor);g.fillStyle='#e8baff';g.beginPath();g.arc(...p,2.7*w/440,0,Math.PI*2);g.fill();});
  }
 }
}


export function guardianPose(state,age,duration,logicalTime=age,restIntensity=1){
const hump=(t,start,end)=>{const p=clamp((t-start)/(end-start),0,1);return Math.sin(Math.PI*p)**2;};
const hold=(t,a,b,c,d)=>smoothstep(a,b,t)*(1-smoothstep(c,d,t));
function livingRest(time){
 // Mismas amplitudes que el habla V3, pero continuas y sin reiniciar su fase.
 const k=restIntensity;
 return {
  roll:k*(.0035*Math.sin(time*.43)+.0018*Math.sin(time*.73)+.022*Math.sin(time*1.18+.3)+.006*Math.sin(time*2.05+.183)),
  yaw:k*(.008*Math.sin(time*.34+.8)+.043*Math.sin(time*.81+.24)+.012*Math.sin(time*1.69+.8)),
  pitch:k*(.0035*Math.sin(time*.52)+.026*Math.sin(time*1.36+.3)+.009*Math.sin(time*2.36+.3)),
  lift:k*.0015*Math.sin(time*.78),zoom:0,headX:0,headY:0,bodyX:0,bodyRoll:0,
  eyes:.031+.009*Math.sin(time*.56),medallion:.018+.006*Math.sin(time*.48+.8),reveal:0
 };
}
function enhancedPose(state,age,duration){
 const q=livingRest(logicalTime);q.state=state;
 if(state==='idle')return q;
 if(state==='enter'||state==='exit'){
  for(const key of ['roll','yaw','pitch','lift','zoom','headX','headY','bodyX','bodyRoll'])q[key]=0;
  return q;
 }
 const d=Math.max(duration,1),p=clamp(age/d,0,1);
 // El final se mezcla con el reposo antes de agotar la lectura: no hay salto.
 const envelope=smoothstep(0,.55,age)*(1-smoothstep(Math.max(.65,d-1.05),d,age));
 const pose={roll:0,yaw:0,pitch:0,lift:0,zoom:0,headX:0,headY:0,bodyX:0,bodyRoll:0};
 let eyes=0,medallion=0,reveal=0;
 if(state==='speak'){
  // Habla: alternancia rítmica ancha, no una inclinación sostenida.
  pose.roll=.145*Math.sin(age*1.43+.15)+.028*Math.sin(age*2.23+.6);
  pose.yaw=.185*Math.sin(age*.94+.55)+.032*Math.sin(age*1.57);
  pose.pitch=.102*Math.sin(age*1.68-.4);
  pose.headY=.008*Math.sin(age*1.68-.4);
  pose.lift=.004*Math.sin(age*1.10);eyes=.018;
 }else if(state==='greeting'){
  // Bienvenida: se abre en diagonal, mira al jugador y regresa al centro.
  const welcome=hump(p,0,.82),answer=hump(p,.63,.96);
  pose.roll=-.245*welcome+.085*answer;
  pose.yaw=.17*welcome-.075*answer;
  pose.pitch=-.10*hump(p,.06,.56);
  pose.headX=-.015*welcome;pose.headY=.012*welcome;
  pose.zoom=.025*welcome;medallion=.18*welcome;eyes=.05*welcome;
 }else if(state==='acknowledge'){
  // Aprobación: evita el cabeceo frontal. En su lugar hace una doble
  // inclinación corta hacia un lado, con un leve acercamiento cálido.
  const first=hold(p,0,.12,.36,1),second=hold(p,.42,.56,.80,1);
  const settle=hump(p,.74,.98);
  pose.roll=.165*first-.115*second+.04*settle;
  pose.yaw=-.09*first+.065*second-.02*settle;
  pose.pitch=.028*first+.018*second;
  pose.headX=.010*first-.008*second;
  pose.headY=-.004*(first+second);
  pose.zoom=.035*first+.026*second;
  pose.lift=-.008*first-.006*second;
  pose.bodyRoll=.028*first-.020*second;
  medallion=.42*(first+.85*second);eyes=.07*(first+.8*second);
 }else if(state==='curious'){
  // Curiosidad: inclinación muy clara (unos 18 grados), mirada sostenida.
  const lean=hold(p,0,.19,.79,1);
  pose.roll=.32*lean+.012*Math.sin(age*1.05)*lean;
  pose.yaw=-.16*lean+.026*Math.sin(age*.80)*lean;
  pose.pitch=.048*lean;pose.headX=.014*lean;
  pose.zoom=.018*lean;eyes=.045*lean;
 }else if(state==='warning'){
  // Alerta: un 15 % más cerca, cabeza erguida y quietud; nada de balanceo.
  const approach=hold(p,0,.12,.87,1);
  pose.zoom=.15*approach;pose.pitch=.10*approach;
  pose.headY=-.014*approach;pose.lift=.005*approach;
  pose.roll=-.030*hump(p,0,.27);
  eyes=.43*approach;medallion=.04*approach;
 }else if(state==='reveal'){
  // Revelación: asciende todo el busto; las otras animaciones no lo hacen.
  const rise=hold(p,0,.22,.76,1);
  pose.lift=-.112*rise;pose.zoom=.045*rise;
  pose.roll=(-.105+.030*Math.sin(age*.72))*rise;
  pose.yaw=.095*Math.sin(age*.60+.3)*rise;
  pose.pitch=.12*rise;pose.headY=-.008*rise;
  pose.bodyX=.012*Math.sin(age*.72)*rise;
  eyes=.29*rise;medallion=.48*rise;reveal=1.05*rise;
 }else if(state==='farewell'){
  // Despedida: inclinación lenta hacia un lado y retirada suave. Se evita la
  // reverencia frontal porque aplastaba la cabeza al no existir volumen 3D.
  const lean=hold(p,0,.16,.70,1),returnLook=hump(p,.70,1);
  pose.roll=-.19*lean+.060*returnLook;
  pose.yaw=-.12*lean+.055*returnLook;
  pose.pitch=.020*lean;
  pose.headX=-.010*lean+.004*returnLook;
  pose.headY=-.004*lean;
  pose.bodyRoll=-.052*lean;
  pose.zoom=-.072*lean+.010*returnLook;
  pose.lift=.030*lean;
  medallion=.16*lean;eyes=.032*lean;
 }
 // Solo se mezcla con el reposo al entrar y salir de la curva. Durante el gesto
 // se conservan sus rasgos propios, sin contaminarlo con el vaivén de habla.
 for(const key of ['roll','yaw','pitch','lift','zoom','headX','headY','bodyX','bodyRoll'])q[key]+=(pose[key]-q[key])*envelope;
 q.eyes+=eyes*envelope;q.medallion+=medallion*envelope;q.reveal=reveal*envelope;
 return q;
}


return enhancedPose(state,age,duration);
}
