(()=>{'use strict';
const $=id=>document.getElementById(id),stage=$('stage'),canvas=$('world'),host=$('modalHost');
const A={};const E=[
 ['Cosecha lista','La cosecha está preparada.','info'],['Dinero ganado','La granja sigue creciendo.','info'],['Ataque de animales','Una bestia se acerca.','urgent'],['Edificio bajo ataque','Acude a protegerlo.','urgent'],['Muralla bajo ataque','La defensa está sufriendo daños.','urgent'],['Edificio destruido','Repara para recuperarlo.','urgent'],['Muralla destruida','Hay una brecha en la defensa.','urgent'],['Construcción terminada','Lista para usar.','info'],['Reparación terminada','De nuevo en buen estado.','info'],['Nuevo día','Otro amanecer en la sabana.','info'],['Centro urbano creado','Nuevo destino disponible en Volver.','info'],['Aviso de la granja','Hay un lugar que revisar.','info']
];
const SPELLS=[{name:'Escudo',detail:'Protege una zona durante 12 s.',cooldown:26,color:'blue'},{name:'Crecimiento rápido',detail:'Madura los cultivos cercanos.',cooldown:22,color:'green'},{name:'Multiplicación',detail:'La próxima cosecha vale el doble.',cooldown:32,color:'purple'}];
let gfx,world,ready=false,last=0,uiClock=0,uiTick=0,tutorialUntil=0,fly=null,focusReturn=null,audioContext=null,eventId=0;
let dims={w:1,h:1,portrait:false,short:false,reserve:100,header:100,aw:180},selection=null,placement=null;
const state={money:1240,day:17,minute:HIRING_RULES.dawnMinute,autoEvents:true,eventInterval:11,eventCountdown:7,audio:true,reduced:window.matchMedia('(prefers-reduced-motion: reduce)').matches,guide:false,preview:'real',modal:null,systemPaused:false,cooldowns:[0,0,0],events:[],floats:[],tasks:[],speed:1,minutesPerSecond:3,night:0};
// Daily recruitment: draft -> validated payment -> replacement of today's crew.
// Storage is optional: Android content:// may disallow it; in-memory recall works regardless.
const CREW_STORAGE_KEY='wild-guardians-hud-lab-crew-v2';
function sanitizeCrew(values){return NPC_TYPES.map((_,i)=>{const n=Number(values?.[i]);return Number.isFinite(n)?clamp(Math.floor(n),0,HIRING_RULES.maxPerType):0})}
function readCrewPreference(){try{const saved=JSON.parse(localStorage.getItem(CREW_STORAGE_KEY)||'null');if(Array.isArray(saved)&&saved.length===4)return sanitizeCrew(saved)}catch(_){}return null}
const rememberedCrew=readCrewPreference();
state.hiring={pending:false,draft:[1,1,1,1],lastSelection:rememberedCrew||[1,1,1,1],hasPrevious:!!rememberedCrew,lastOfferedDay:null,confirmedDay:null,paidToday:0,ledger:[]};
const hhmm=n=>`${String(Math.floor(n/60)%24).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
function crewCost(counts){return counts.reduce((total,n,i)=>total+n*NPC_TYPES[i].wage,0)}
function crewSummary(){const counts=sanitizeCrew(state.hiring.draft),cost=crewCost(counts);return {counts,count:counts.reduce((a,b)=>a+b,0),cost,available:state.money,balance:state.money-cost,affordable:cost<=state.money}}
function hiringMarkup(){
 const previous=state.hiring.hasPrevious?'Hemos recuperado tu última selección. Puedes ajustarla antes de pagar.':'Elige cuántas personas trabajarán hoy. Empiezas con una de cada perfil.';
 return `<section class="panel hiring-panel" role="dialog" aria-modal="true" aria-labelledby="hiringTitle" aria-describedby="hiringIntro">
 <canvas class="frame-canvas" aria-hidden="true"></canvas>
 <header class="panel-head"><div><h2 class="panel-title" id="hiringTitle" tabindex="-1">Contrata tu equipo</h2><p class="panel-subtitle">Día ${state.day} · ${hhmm(HIRING_RULES.dawnMinute)} · nuevo amanecer</p></div><span class="hiring-pause"><i aria-hidden="true">Ⅱ</i><span>Tiempo en pausa</span></span></header>
 <div class="panel-body hiring-body"><p id="hiringIntro" class="hiring-intro">${previous}</p>
 <div class="hiring-grid">${NPC_TYPES.map((p,i)=>`<article class="hire-card" data-crew-card="${i}">
 <img class="hire-portrait" src="${ASSETS['npc_'+p.key].src}" alt="${p.name}">
 <h3>${p.name}</h3><div class="hire-wage">${image('coin')}<strong>${fmt(p.wage)}</strong><small>/ día</small></div>
 <div class="hire-stats"><span>Ritmo <b>×${p.speed.toFixed(2).replace('.',',')}</b></span><span>Cosecha <b>${p.male?'+20 %':'base'}</b></span></div>
 <div class="hire-shift"><b>${p.shiftMinutes/60} h${p.male?'':' · +20 %'}</b><span>${hhmm(p.start)}–${hhmm(p.end)}</span></div>
 <div class="hire-stepper"><button type="button" data-crew-step="${i}" data-delta="-1" aria-label="Contratar un ${p.name.toLowerCase()} menos">−</button><input type="number" id="crewCount${i}" data-crew-count="${i}" min="0" max="${HIRING_RULES.maxPerType}" step="1" inputmode="numeric" aria-label="Cantidad: ${p.name}" value="${state.hiring.draft[i]}"><button type="button" data-crew-step="${i}" data-delta="1" aria-label="Contratar un ${p.name.toLowerCase()} más">+</button></div>
 </article>`).join('')}</div>
 <details class="hiring-rules"><summary>Cómo trabajan y qué se paga</summary><p>Contratas para una sola jornada y pagas al confirmar. Mañana se recuerda esta combinación, pero no se vuelve a cobrar sin tu confirmación.</p><p>Los jóvenes cuestan un 20 % más y trabajan a ×1,50 de velocidad. Los hombres generan un 20 % más de cosecha por ciclo. Las mujeres trabajan 12 horas frente a las 10 de los hombres: un 20 % más. Ambos sexos cobran lo mismo dentro de cada edad.</p><p>En esta simulación cada persona atiende una parcela y luego pasa a otra. Si varias comparten un ciclo, el extra de cosecha se pondera por el trabajo de los hombres, con un máximo del 20 %; no se acumula por cada hombre. Se combina con la multiplicación mágica de la cosecha. Al terminar su jornada, vuelven a casa. Sin personal, los cultivos esperan; puedes seguir recolectando lo que ya esté listo y usar magia.</p><p>Valores de prueba configurables: sueldo base ${HIRING_RULES.baseWage}, inicio ${hhmm(HIRING_RULES.dawnMinute)}, jornada base de ${HIRING_RULES.maleShiftMinutes/60} h. Máximo de ${HIRING_RULES.maxPerType} por perfil en este lab. Los figurantes 3D son provisionales; los retratos son tus cuatro NPCs.</p></details>
 </div>
 <footer class="hiring-footer"><div class="hiring-budget"><div><span>Disponible</span><strong id="hireAvailable"></strong></div><div><span>Coste de hoy</span><strong id="hireCost"></strong></div><div><span>Saldo restante</span><strong id="hireBalance"></strong></div></div><p id="hireBudgetMessage" role="status" aria-live="polite"></p><div class="hire-confirm-row"><button type="button" class="hire-clear" data-hire="clear">Poner a cero</button><button type="button" class="wood-button hire-confirm" data-hire="confirm" id="hireConfirm">Contratar y empezar</button></div></footer>
 </section>`;
}
function updateHiringTotals(){
 if(!state.hiring.pending||state.modal!=='hire'||!$('hireConfirm'))return;
 const s=crewSummary();
 $('hireAvailable').textContent=fmt(s.available);$('hireCost').textContent=fmt(s.cost);
 $('hireBalance').textContent=(s.balance<0?'−':'')+fmt(Math.abs(s.balance));
 $('hireBalance').classList.toggle('over-budget',!s.affordable);
 $('hireBudgetMessage').classList.toggle('over-budget',!s.affordable);
 const msg=!s.affordable?`Faltan ${fmt(-s.balance)} monedas. Reduce la selección para continuar.`:s.count===0?'Sin contratar: no se cobra nada. Las parcelas esperarán personal.':`${s.count} ${s.count===1?'persona seleccionada':'personas seleccionadas'} · pago único para esta jornada.`;
 if($('hireBudgetMessage').textContent!==msg)$('hireBudgetMessage').textContent=msg;
 $('hireConfirm').disabled=!s.affordable;
 $('hireConfirm').textContent=s.count?'Contratar y empezar':'Empezar sin contratar';
 NPC_TYPES.forEach((p,i)=>{host.querySelector(`[data-crew-card="${i}"]`)?.classList.toggle('has-crew',s.counts[i]>0);host.querySelector(`[data-crew-step="${i}"][data-delta="-1"]`).disabled=s.counts[i]===0;host.querySelector(`[data-crew-step="${i}"][data-delta="1"]`).disabled=s.counts[i]>=HIRING_RULES.maxPerType});
 requestAnimationFrame(()=>{if(state.modal==='hire')placeModal()});
}
function editCrew(index,value,fromInput=false){
 if(!state.hiring.pending||!NPC_TYPES[index])return;
 const n=Number(value);state.hiring.draft[index]=Number.isFinite(n)?clamp(Math.floor(n),0,HIRING_RULES.maxPerType):0;
 const input=$('crewCount'+index);if(input&&(!fromInput||input.value!==''))input.value=state.hiring.draft[index];
 updateHiringTotals();
}
function setHiringInert(active){for(const id of ['hud','events','contextPanel','placementBanner','tutorial','world'])$(id).inert=active}
function trapHiringFocus(e){
 const list=[...host.querySelectorAll('button:not(:disabled),input:not(:disabled),summary')].filter(el=>el.offsetParent!==null),first=list[0],lastEl=list[list.length-1];
 if(!first){e.preventDefault();return}
 if(e.shiftKey&&(document.activeElement===first||!list.includes(document.activeElement))){e.preventDefault();lastEl.focus()}
 else if(!e.shiftKey&&(document.activeElement===lastEl||!list.includes(document.activeElement))){e.preventDefault();first.focus()}
}
function openHiringDay(){
 const h=state.hiring;if(!ready||h.pending||h.lastOfferedDay===state.day)return false;
 h.pending=true;h.lastOfferedDay=state.day;h.draft=[...h.lastSelection];h.paidToday=0;
 state.modal='hire';state.systemPaused=true;state.renderDirty=true;fly=null;keys.clear();
 for(const id of pointers.keys())try{if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id)}catch(_){}
 pointers.clear();gesture=null;lastPinch=null;selection=null;placement=null;focusReturn=$('menuButton');
 $('contextPanel').style.display='none';$('placementBanner').style.display='none';
 stage.classList.add('system-open','hiring-open');$('tutorial').style.visibility='hidden';
 document.querySelectorAll('[data-menu]').forEach(b=>b.classList.remove('active'));
 host.innerHTML=hiringMarkup();host.style.display='block';setHiringInert(true);
 updateStats();updateHiringTotals();placeModal();$('hiringTitle')?.focus({preventScroll:true});
 return true;
}
function confirmHiring(){
 const h=state.hiring;if(!h.pending||state.modal!=='hire'||h.confirmedDay===state.day)return false;
 const s=crewSummary();if(!s.affordable){updateHiringTotals();sound('warn');return false}
 // Recheck and debit the complete total once; no deductions happen during editing.
 h.confirmedDay=state.day;h.pending=false;h.lastSelection=[...s.counts];h.draft=[...s.counts];h.hasPrevious=true;h.paidToday=s.cost;
 h.ledger.push({day:state.day,counts:[...s.counts],cost:s.cost});if(h.ledger.length>60)h.ledger.shift();
 if(s.cost)changeMoney(-s.cost);
 try{localStorage.setItem(CREW_STORAGE_KEY,JSON.stringify(h.lastSelection))}catch(_){}
 world.workMinute=state.minute;world.setCrew(s.counts);world.update(0);
 setHiringInert(false);stage.classList.remove('hiring-open');closeMenu();
 state.renderDirty=true;last=performance.now();sound(s.cost?'coin':'click');
 const home=world.towns.find(t=>!t.destroyed)||world.towns[0];if(s.count)world.mark(home.x,home.z,'#e5df96',3,2);
 return true;
}
function startNextDay(){
 if(!ready||state.hiring.pending)return false;
 state.day++;state.minute=HIRING_RULES.dawnMinute;world.workMinute=state.minute;
 updateStats();const notice=addNotice(9,null,`Día ${state.day} · empieza una nueva jornada`);openHiringDay();return notice;
}
// Return the exact simulation step up to the next dawn. Long/accelerated steps
// never skip a daily dialog and never silently charge several days at once.
function dailyClockStep(dt){
 const from=state.minute,dawn=HIRING_RULES.dawnMinute,nextDawn=from<dawn-1e-7?dawn:dawn+1440;
 const rate=state.minutesPerSecond;
 if(rate<=0)return {dt,dawn:false};
 const limit=(nextDawn-from)/rate,hit=dt>=limit;
 const used=hit?limit:dt;state.minute=hit?dawn:(from+used*rate)%1440;
 return {dt:used,dawn:hit};
}

const fmt=n=>String(Math.round(n)).replace(/\B(?=(\d{3})+(?!\d))/g,'.');
const image=(key,cl='')=>`<img class="${cl}" src="${ASSETS[key].src}" alt="" draggable="false">`;
const price=n=>`<span class="price">${image('coin')}${fmt(n)}</span>`;
function svgWrap(body){return `<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="leaf" x2=".7" y2="1"><stop stop-color="#bada62"/><stop offset="1" stop-color="#508944"/></linearGradient><linearGradient id="gold" x2=".6" y2="1"><stop stop-color="#ffe891"/><stop offset="1" stop-color="#dc9538"/></linearGradient><linearGradient id="purple" x2=".5" y2="1"><stop stop-color="#e7bcee"/><stop offset="1" stop-color="#9955ad"/></linearGradient></defs>${body}</svg>`}
function cropSVG(i){let s='';if(i<4){s+='<path d="M49 91Q50 64 53 21" fill="none" stroke="#58894a" stroke-width="5" stroke-linecap="round"/><path d="M49 79Q14 76 13 48Q42 45 49 79M50 64Q83 60 87 37Q62 37 50 64" fill="url(#leaf)" stroke="#4f7638" stroke-width="2"/>';const col=i===1?'#bd7a4f':i===3?'#c7d876':'url(#gold)';if(i===0){s+='<ellipse cx="53" cy="40" rx="17" ry="31" fill="url(#gold)" stroke="#b77931" stroke-width="2"/>';for(let y=20;y<66;y+=9)for(let x=43;x<=63;x+=10)s+=`<path d="M${x} ${y}v5" stroke="#fff0ae" stroke-width="3" stroke-linecap="round"/>`}else{for(let j=0;j<5;j++){let yy=17+j*10;s+=`<ellipse cx="${j%2?59:45}" cy="${yy}" rx="7" ry="11" transform="rotate(${j%2?28:-28} ${j%2?59:45} ${yy})" fill="${col}" stroke="#a0843e" stroke-width="1.5"/>`}}}else if(i===6){s='<path d="M53 22Q50 7 64 10" fill="none" stroke="#507647" stroke-width="7" stroke-linecap="round"/><ellipse cx="51" cy="59" rx="36" ry="31" fill="#d97829" stroke="#945127" stroke-width="3"/><ellipse cx="39" cy="58" rx="16" ry="30" fill="#f49a39"/><ellipse cx="62" cy="58" rx="17" ry="30" fill="#ef9632"/><ellipse cx="51" cy="59" rx="12" ry="31" fill="#ffc363"/><path d="M54 25Q28 27 21 11Q46 8 54 25" fill="url(#leaf)" stroke="#507647" stroke-width="2"/>'}else if(i===7){s='<path d="M22 80Q71 75 77 14Q34 33 22 80Z" fill="url(#leaf)" stroke="#4d813d" stroke-width="3"/>';for(let j=0;j<4;j++)s+=`<ellipse cx="${34+j*10}" cy="${65-j*12}" rx="9" ry="10" transform="rotate(35 ${34+j*10} ${65-j*12})" fill="#b5d96c" stroke="#6b9c4b" stroke-width="2"/>`}else{const c=i===4?'#bd8b59':'#c67c63';s=`<path d="M32 31Q44 22 67 35Q89 51 76 77Q67 94 42 79Q17 61 23 42Z" fill="${c}" stroke="#855235" stroke-width="3"/><path d="M39 31Q34 9 59 12Q77 17 54 30" fill="url(#leaf)" stroke="#4d813d" stroke-width="2"/><path d="M41 43l-5 7m18 7-5 7m17 4-4 6" stroke="#f2c28c" stroke-width="3" stroke-linecap="round"/>`}
 return svgWrap(s)}
function spellSVG(i){return svgWrap(i===0?'<path d="M50 10L82 23V48Q82 74 50 91Q18 74 18 48V23Z" fill="#bceff3" stroke="#fff5d8" stroke-width="4"/><path d="M50 21L72 30V49Q72 66 50 79Z" fill="#7acdd7"/><path d="M36 47l10 11 20-25" fill="none" stroke="#fff9db" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"/>':i===1?'<path d="M51 88V47" fill="none" stroke="#effbc8" stroke-width="7" stroke-linecap="round"/><path d="M51 64Q11 60 15 26Q47 25 51 64Z" fill="#d9f3a7" stroke="#fff8cd" stroke-width="3"/><path d="M51 49Q83 49 87 13Q57 17 51 49Z" fill="#a6dc8a" stroke="#fff8cd" stroke-width="3"/><path d="M76 61v-8m-4 4h8" stroke="#fff4a3" stroke-width="4" stroke-linecap="round"/>':'<path d="M32 87V52m39 35V52" stroke="#fbf0ff" stroke-width="6" stroke-linecap="round"/><path d="M32 57Q9 52 9 29Q36 29 32 57M32 50Q30 22 49 18Q60 38 32 50M71 57Q51 51 54 29Q77 30 71 57M72 49Q71 20 93 19Q95 41 72 49" fill="#e4c3ef" stroke="#fff4d9" stroke-width="2.5"/><path d="M52 62l4 9 10 2-8 6 1 10-8-5-8 5 1-10-7-6 10-2Z" fill="#ffe8ac"/>')}
function sound(kind='click'){if(!state.audio||kind==='silent')return;try{if(!audioContext)audioContext=new(window.AudioContext||window.webkitAudioContext)();if(audioContext.state==='suspended')audioContext.resume();const now=audioContext.currentTime,notes=kind==='coin'?[740,1046,1396]:kind==='magic'?[523,784,1046]:kind==='warn'?[155,120]:kind==='build'?[240,320]:[520];notes.forEach((freq,i)=>{let o=audioContext.createOscillator(),g=audioContext.createGain();o.type=kind==='warn'?'triangle':'sine';o.frequency.setValueAtTime(freq,now+i*.065);o.frequency.exponentialRampToValueAtTime(freq*.92,now+i*.065+.15);g.gain.setValueAtTime(0,now+i*.065);g.gain.linearRampToValueAtTime(kind==='warn'?.05:.035,now+i*.065+.007);g.gain.exponentialRampToValueAtTime(.001,now+i*.065+.18);o.connect(g).connect(audioContext.destination);o.start(now+i*.065);o.stop(now+i*.065+.22)})}catch(_){}}
function toast(text,seconds=3){/* Feedback is now handled by world/HUD state and icon notifications only. */}
function showTutorial(text,seconds=10){$('tutorialText').textContent=text||'Arrastra para explorar. Un dedo mueve la cámara; dos dedos permiten acercar y girar. Los avisos te llevan directamente al lugar del evento.';$('tutorial').classList.add('show');tutorialUntil=uiClock+seconds}
function hideTutorial(){$('tutorial').classList.remove('show');tutorialUntil=0}
function changeMoney(amount,origin=null){state.money=Math.max(0,state.money+amount);$('money').classList.remove('bump');void $('money').offsetWidth;$('money').classList.add('bump');if(origin)floating((amount>0?'+':'−')+fmt(Math.abs(amount)),origin.x,1.8,origin.z,amount>0?'#ffe582':'#f3c099');updateStats();if(state.hiring.pending)updateHiringTotals()}
function floating(text,x,y,z,color='#ffea8b'){const el=document.createElement('span');el.className='float-label';el.textContent=text;el.style.color=color;$('floatLayer').appendChild(el);state.floats.push({el,x,y,z,life:2,max:2})}
function updateStats(){let h=Math.floor(state.minute/60)%24,m=Math.floor(state.minute%60);$('clockValue').textContent=`${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}`;$('moneyValue').textContent=fmt(state.money);$('dayValue').textContent='Día '+state.day;$('clock').title=`${h}:${String(m).padStart(2,'0')} · ciclo de día y noche simulado`;$('money').title=`${fmt(state.money)} monedas`;$('days').title=`Día de supervivencia ${state.day}`;let hh=state.minute/60;state.night=hh>=7&&hh<17?0:hh>=17&&hh<20?(hh-17)/3:hh>=5&&hh<7?1-(hh-5)/2:1;stage.style.setProperty('--night',state.night.toFixed(3))}
function layout(){const w=stage.clientWidth,h=stage.clientHeight,p=h>w*1.08,short=h<500,reserve=p?Math.min(125,h*.16):short?62:Math.min(120,h*.17),header=p?112:short?71:103;dims={w,h,portrait:p,short,reserve,header,aw:180};stage.classList.toggle('portrait',p);stage.classList.toggle('short',short);stage.style.setProperty('--reserve',reserve+'px');stage.style.setProperty('--header',header+'px');
 let clockW,moneyW,moneyX,dayX,timeY=10,moneyY,dayY;
 if(p){clockW=clamp(w*.34,106,145);moneyW=clamp(w*.34,113,155);moneyX=clockW+17;dayX=moneyX;moneyY=8;dayY=57;$('menuButton').style.cssText=`right:9px;top:12px;width:${w<355?45:50}px;height:${w<355?45:50}px`}
 else{clockW=short?132:184;moneyW=short?128:173;moneyX=clockW+27;dayX=moneyX+moneyW+11;moneyY=short?13:23;dayY=moneyY;$('menuButton').style.cssText=`right:${short?10:17}px;top:12px;width:${short?49:66}px;height:${short?49:66}px`}
 function box(id,x,y,ww){let ar=ASSETS[id].h/ASSETS[id].w;$(id).style.left=x+'px';$(id).style.top=y+'px';$(id).style.width=ww+'px';$(id).style.height=ww*ar+'px'}box('clock',12,timeY,clockW);box('money',moneyX,moneyY,moneyW);box('days',dayX,dayY,moneyW);
 if(p){$('moneyValue').style.fontSize=(w<360?15:17)+'px';$('dayValue').style.fontSize=(w<360?14:16)+'px';$('clockValue').style.fontSize='18px'}else{$('moneyValue').style.fontSize='';$('dayValue').style.fontSize='';$('clockValue').style.fontSize=''}
 const gap=short?3:p?4:6,avail=h-header-reserve-10-3*gap;let aw=p?Math.min(clamp(w*.24,78,108),avail/4*.715):Math.min(clamp(w*.155,164,221),avail/4*2.17);aw=Math.max(58,aw);dims.aw=aw;let ah=p?aw/.715:aw/2.17,total=ah*4+3*gap,navY=header+Math.max(5,(h-reserve-header-total)/2);$('actions').style.top=navY+'px';$('actions').style.gap=gap+'px';stage.style.setProperty('--action-w',aw+'px');stage.style.setProperty('--action-font',(p?clamp(aw*.143,10,15):clamp(aw*.082,11,18))+'px');
 const ew=p?Math.min(240,w-aw-35):short?208:254;$('events').style.width=ew+'px';$('events').style.left=(short?12:17)+'px';$('events').style.top=(header+(p?10:9))+'px';$('placementBanner').style.top=(header+8)+'px';
 if(gfx){gfx.resize(w,h,devicePixelRatio);if(state.lastOrientation!==p){gfx.camera.distance=p?43:33;state.lastOrientation=p}gfx.updateCamera();state.renderDirty=true}placeModal();positionContext();}
function framePaint(){const c=host.querySelector('.frame-canvas');if(!c)return;const panel=c.parentElement,w=panel.clientWidth,h=panel.clientHeight,dpr=Math.min(devicePixelRatio||1,2);c.width=Math.ceil(w*dpr);c.height=Math.ceil(h*dpr);const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);const cw=dims.short?74:dims.portrait?81:98,ch=cw*330/400;
 ctx.drawImage(A.frame_center,cw*.32,cw*.33,w-cw*.64,h-cw*.66);
 const barX=cw*.966,barW=w-barX*2;
 ctx.drawImage(A.frame_top,barX,cw*.22,Math.max(1,barW),cw*.19);
 ctx.drawImage(A.frame_bottom,barX,h-cw*.45,Math.max(1,barW),cw*.1975);
 ctx.drawImage(A.frame_left,cw*.245,cw*.79,cw*.19,Math.max(1,h-cw*1.58));
 ctx.drawImage(A.frame_right,w-cw*.4325,cw*.79,cw*.19,Math.max(1,h-cw*1.58));
 ctx.drawImage(A.frame_tl,0,0,cw,ch);ctx.drawImage(A.frame_tr,w-cw,0,cw,ch);ctx.drawImage(A.frame_bl,0,h-ch,cw,ch);ctx.drawImage(A.frame_br,w-cw,h-ch,cw,ch);
}
function placeModal(){if(!state.modal)return;if(state.modal==='hire'){
 const width=Math.max(220,Math.min(dims.w-16,1060));const top=dims.short?4:dims.portrait?6:Math.min(42,dims.header);
 const maxH=Math.max(160,dims.h-dims.reserve-top-7);stage.style.setProperty('--panel-max',maxH+'px');
 host.style.width=width+'px';host.style.left=((dims.w-width)/2)+'px';
 const ph=host.firstElementChild?.offsetHeight||maxH;host.style.top=Math.max(top,Math.min(top+30,(dims.h-dims.reserve-ph)/2))+'px';framePaint();return}
const isSystem=['menu','options','lab','title'].includes(state.modal);let maxWidth=isSystem?Math.min(dims.w-20,state.modal==='lab'?655:460):Math.min(dims.w-dims.aw-36,state.modal==='grow'?603:state.modal==='magic'?532:490);if(dims.portrait&&!isSystem)maxWidth=Math.max(215,dims.w-dims.aw-31);let x=isSystem?(dims.w-maxWidth)/2:dims.w-dims.aw-23-maxWidth;host.style.width=maxWidth+'px';host.style.left=Math.max(6,x)+'px';const topLimit=isSystem?Math.min(dims.header,40):dims.header+7;const maxH=Math.max(145,dims.h-dims.reserve-topLimit-9);stage.style.setProperty('--panel-max',maxH+'px');const h=host.firstElementChild?.offsetHeight||maxH;host.style.top=clamp((dims.h-dims.reserve-h)/2+15,topLimit,dims.h-dims.reserve-h-5)+'px';framePaint()}
function headerTitle(type){return {home:['Volver a casa','Elige un centro urbano'],build:['Construir','Elige y coloca en el terreno'],grow:['Cultivar','8 cultivos de muestra'],magic:['Magia','Poderes del espíritu'],menu:['Pausa','Wild Guardians · HUD Lab'],options:['Opciones','Preferencias de la demostración'],lab:['Laboratorio','Prueba cada estado de la interfaz'],title:['Wild Guardians','Laboratorio de interfaz']}[type]}
function modalContent(type){if(type==='home')return `<div class="town-list">${world.towns.map(t=>`<button class="town-row ${t.destroyed?'ruined':''}" data-town="${t.id}">${image('home_icon')}<span><strong>${t.name}</strong><small>${t.destroyed?'Centro en ruinas · ':''}${Math.round(Math.hypot(t.x-gfx.camera.target[0],t.z-gfx.camera.target[2]))} m de la vista actual</small></span><span class="arrow">›</span></button>`).join('')}</div><p class="panel-note">Viaja hasta cualquier asentamiento sin perderte al explorar.</p>`;
 if(type==='build')return `<div class="card-grid two"><button class="choice-card" data-build="town" ${state.money<450?'disabled':''}>${image('home_icon','card-image')}<strong>Centro urbano</strong><span class="detail">Un nuevo hogar y destino.</span>${price(450)}</button><button class="choice-card" data-build="wall" ${state.money<45?'disabled':''}>${image('event8','card-image')}<strong>Muralla</strong><span class="detail">Protege tu asentamiento.</span>${price(45)}</button></div><p class="panel-note">Elige una opción y toca un espacio libre. Los costes son de prueba.</p>`;
 if(type==='grow')return `<div class="card-grid crop-grid">${CROP_TYPES.map((t,i)=>`<button class="choice-card" data-crop="${i}" ${state.money<t.cost?'disabled':''}><span class="card-image">${cropSVG(i)}</span><strong>${t.name}</strong>${price(t.cost)}</button>`).join('')}</div><p class="panel-note">Sembrar cuesta monedas. Recoge la cosecha directamente en el terreno.</p>`;
 if(type==='magic')return `<div class="card-grid three">${SPELLS.map((s,i)=>`<button class="choice-card spell-card" data-spell="${i}" ${state.cooldowns[i]>0?'disabled':''}><span class="spell-symbol ${s.color}">${spellSVG(i)}<span class="spell-cooldown" data-cd="${i}"></span><span class="cooldown-number" data-cdn="${i}"></span></span><strong>${s.name}</strong><span class="detail">${s.detail}</span><span class="price spell-status" data-cds="${i}">Disponible</span></button>`).join('')}</div><p class="panel-note">Selecciona un poder y toca la zona donde quieres aplicarlo. Se recarga con el tiempo.</p>`;
 if(type==='menu')return `<div class="menu-list"><button class="wood-button" data-do="resume">Continuar</button><button class="wood-button secondary" data-open="options">Opciones</button><button class="wood-button secondary" data-open="lab">Herramientas del laboratorio</button><button class="wood-button secondary" data-open="title">Menú principal de prueba</button></div><p class="menu-meta">La simulación está en pausa.<br>Personal de hoy: ${world.workers.length} · en jornada: ${world.workers.filter(w=>w.active).length}.<br>Escena y reglas de demostración; no es todavía el juego final.</p>`;
 if(type==='title')return `<div class="menu-list"><p class="panel-note" style="margin:1px 0 12px">Una pequeña sabana para probar tu interfaz, los menús y los acontecimientos.</p><button class="wood-button" data-do="resume">Entrar a la granja</button><button class="wood-button secondary" data-open="options">Opciones</button><button class="wood-button secondary" data-open="lab">Laboratorio del HUD</button></div><p class="menu-meta">Tus sprites, texto superpuesto y una escena WebGL de prueba.<br>Un único archivo · sin conexiones externas.</p>`;
 if(type==='options')return `${switchRow('audio','Sonidos de prueba','Clics, monedas y señales sintetizadas.')}${switchRow('autoEvents','Eventos automáticos','Activa los acontecimientos aleatorios.')}${switchRow('reduced','Movimiento reducido','Viajes de cámara más breves.')}${switchRow('guide','Mostrar zona del tutorial','Guía de espacio; no forma parte del HUD final.')}<div class="range-row"><label>Frecuencia de eventos <b id="intervalLabel">${state.eventInterval} s</b></label><input aria-label="Intervalo entre eventos" id="eventInterval" type="range" min="5" max="22" step="1" value="${state.eventInterval}"></div><button class="wood-button secondary" style="width:100%" data-open="menu">Volver al menú</button>`;
 return `<div class="lab-events">${E.map((e,i)=>`<button class="lab-event" data-test="${i}">${image('event'+i)}<span>${e[0]}</span></button>`).join('')}</div><p class="lab-note">Cada botón provoca el evento real de esta simulación y vuelve a la escena. El aviso permite localizarlo.</p><div class="lab-controls"><div class="small-buttons"><button class="wood-button secondary" data-do="day">Día</button><button class="wood-button secondary" data-do="night">Noche</button><button class="wood-button secondary" data-do="tutorial">Tutorial</button></div><p class="lab-note">Composición de pantalla</p><div class="small-buttons"><button class="wood-button secondary" data-preview="real">Ventana</button><button class="wood-button secondary" data-preview="landscape">Horizontal</button><button class="wood-button secondary" data-preview="portrait">Vertical</button></div><div class="small-buttons" style="margin-top:10px"><button class="wood-button secondary" data-do="money">+500 monedas</button><button class="wood-button secondary" data-do="reset">Reiniciar lab</button></div></div><p class="key-help">Arrastrar: mover · Botón derecho: girar · Rueda: zoom<br><kbd>1–4</kbd> menús · <kbd>H</kbd> casa · <kbd>E</kbd> evento · <kbd>T</kbd> tutorial · <kbd>Esc</kbd> cerrar<br>Dos dedos: acercar y girar.</p>`;
}
function switchRow(key,title,desc){return `<div class="option-row"><span>${title}<small>${desc}</small></span><button class="switch" role="switch" aria-label="${title}" aria-checked="${state[key]}" data-toggle="${key}"></button></div>`}
function openMenu(type){if(!ready||state.hiring.pending)return;if(state.modal===type){closeMenu();return}sound();focusReturn=document.activeElement;state.modal=type;state.systemPaused=['menu','options','lab','title'].includes(type);stage.classList.toggle('system-open',state.systemPaused);selection=null;placement=null;$('contextPanel').style.display='none';$('placementBanner').style.display='none';let [title,subtitle]=headerTitle(type);host.innerHTML=`<section class="panel" role="dialog" aria-label="${title}" aria-modal="${state.systemPaused}"><canvas class="frame-canvas" aria-hidden="true"></canvas><header class="panel-head"><div><h2 class="panel-title">${title}</h2><p class="panel-subtitle">${subtitle}</p></div><button class="close-panel" data-do="close" aria-label="Cerrar">×</button></header><div class="panel-body">${modalContent(type)}</div></section>`;host.style.display='block';document.querySelectorAll('[data-menu]').forEach(b=>b.classList.toggle('active',b.dataset.menu===type));$('tutorial').style.visibility=state.systemPaused?'hidden':'visible';placeModal();updateCooldowns();host.querySelector('.close-panel')?.focus({preventScroll:true})}
function closeMenu(){if(state.hiring.pending)return;state.modal=null;state.systemPaused=false;host.style.display='none';host.innerHTML='';stage.classList.remove('system-open');document.querySelectorAll('[data-menu]').forEach(b=>b.classList.remove('active'));$('tutorial').style.visibility='visible';if(focusReturn?.isConnected)focusReturn.focus({preventScroll:true})}
function updateCooldowns(){if(state.modal!=='magic')return;for(let i=0;i<3;i++){let n=state.cooldowns[i];host.querySelector(`[data-cd="${i}"]`).style.setProperty('--cd',(n/SPELLS[i].cooldown*100)+'%');host.querySelector(`[data-cdn="${i}"]`).textContent=n>0?Math.ceil(n):'';host.querySelector(`[data-cds="${i}"]`).textContent=n>0?'Recargando':'Disponible';host.querySelector(`[data-spell="${i}"]`).disabled=n>0}}
function setPreview(mode){state.preview=mode;const s=stage.style;if(mode==='real'){s.width='100%';s.height='100%';s.position='relative';s.left='';s.top='';s.transform='';s.boxShadow=''}else{const ratio=mode==='portrait'?390/844:16/9;let h=Math.min(innerHeight-20,(innerWidth-20)/ratio),w=h*ratio;s.width=Math.round(w)+'px';s.height=Math.round(h)+'px';s.position='absolute';s.left='50%';s.top='50%';s.transform='translate(-50%,-50%)';s.boxShadow='0 0 0 1px #87948644,0 15px 60px #0006'}layout()}
function beginPlacement(kind,type){if(state.hiring.pending)return;closeMenu();selection=null;placement={kind,type,point:[gfx.camera.target[0],0,gfx.camera.target[2]],valid:true};const name=kind==='town'?'Centro urbano':kind==='wall'?'Muralla':kind==='crop'?CROP_TYPES[type].name:SPELLS[type].name;$('placementBanner').querySelector('span').innerHTML=`<b>${name}</b>${kind==='spell'?'Toca la zona para usar el poder.':'Toca un espacio libre del terreno.'}`;$('placementBanner').style.display='flex';$('contextPanel').style.display='none';sound()}
function cancelPlacement(){placement=null;$('placementBanner').style.display='none'}
function validPoint(p,kind){return p&&Math.abs(p[0])<80&&Math.abs(p[2])<80&&(kind==='spell'||Math.abs(p[0]-riverX(p[2]))>5.4)}
function commitPlacement(point){if(state.hiring.pending||!placement||!point)return;const {kind,type}=placement;if(!validPoint(point,kind)){sound('warn');toast('Elige una zona de tierra firme.');return}let x=point[0],z=point[2];if(kind!=='spell'&&world.pick(x,z)){toast('Ese espacio está ocupado. Prueba un poco más lejos.');return}let cost=kind==='town'?450:kind==='wall'?45:kind==='crop'?CROP_TYPES[type].cost:0;if(cost>state.money){toast('No tienes monedas suficientes.');return}cancelPlacement();let obj;
 if(kind==='town'){if(world.towns.length>=10){toast('Esta prueba admite hasta 10 centros urbanos.');return}obj=world.addTown(x,z,'Refugio '+(world.towns.length+1));changeMoney(-cost,obj);obj.buildUntil=world.time+2;state.tasks.push({at:world.time+2,fn:()=>addNotice(10,obj)});toast('Construyendo un nuevo centro urbano…');sound('build')}
 else if(kind==='wall'){obj=world.addWall(x,z,Math.round(gfx.camera.yaw/(Math.PI/2))*Math.PI/2);changeMoney(-cost,obj);obj.buildUntil=world.time+2;state.tasks.push({at:world.time+2,fn:()=>addNotice(7,obj)});toast('Levantando la muralla…');sound('build')}
 else if(kind==='crop'){if(world.plots.length>=32){toast('Esta prueba admite hasta 32 parcelas.');return}obj=world.addCrop(x,z,type,0);changeMoney(-cost,obj);world.burst(x,.4,z,'#bed872',12);toast(CROP_TYPES[type].name+' sembrado.');sound('build')}
 else{if(state.cooldowns[type]>0){toast('Ese poder todavía se está recargando.');return}world.cast(type,x,z);state.cooldowns[type]=SPELLS[type].cooldown;toast(type===0?'Escudo activo: la zona está protegida.':type===1?'Los cultivos cercanos ya se pueden recoger.':'Multiplicación: la próxima cosecha vale el doble.');if(type===1){let p=world.nearestCrop(x,z);if(p)addNotice(0,p)}sound('magic')}
 if(obj){world.mark(x,z,'#e8d191',3,obj.radius);selection=obj;renderContext()}}
function flyTo(x,z,callback){cancelPlacement();const target=gfx.camera.target.slice();fly={from:target,to:[x,0,z],start:uiClock,duration:state.reduced?.15:1.1+Math.min(1,Math.hypot(x-target[0],z-target[2])/70),callback,distance:gfx.camera.distance};selection=null;$('contextPanel').style.display='none'}
function selectItem(obj){selection=obj;renderContext();if(obj)world.mark(obj.x,obj.z,'#e7dca3',1.5,obj.radius)}
function renderContext(){let p=$('contextPanel');if(!selection||placement||state.modal){p.style.display='none';return}let o=selection,action='',info='';if(o.kind==='crop'){info=o.ready?'Cosecha lista'+(o.multiplier===2?' · valor ×2':''):(world.recruitmentEnabled&&!o.working?'Esperando personal · ':'Creciendo · ')+Math.round(o.progress*100)+' %';if(o.ready)action=`<button class="context-action" data-context="harvest">Recolectar · +${fmt(world.harvestValue(o))}</button>`}
 else{info=o.destroyed?'Destruido':o.hp<1?'Estado · '+Math.round(o.hp*100)+' %':'En buen estado';if(o.hp<1){let cost=o.kind==='wall'?(o.destroyed?45:25):(o.destroyed?180:60);action=`<button class="context-action repair" data-context="repair" ${state.money<cost?'disabled':''}>Reparar · ${cost} monedas</button>`}}
 p.innerHTML=`<div class="context-title"><span>${o.name}</span><button aria-label="Deseleccionar" data-context="close">×</button></div><div class="context-info">${info}</div>${action}`;p.style.display='block';positionContext()}
function positionContext(){if(!gfx||!selection||placement||state.modal)return;const point=gfx.project([selection.x,selection.kind==='crop'?1.3:2.8,selection.z]),panel=$('contextPanel');if(!point||point.depth>100||point.x<-100||point.x>dims.w+100){panel.style.visibility='hidden';return}panel.style.visibility='visible';const width=panel.offsetWidth||160,height=panel.offsetHeight||75;panel.style.left=clamp(point.x,width/2+12,dims.w-width/2-12)+'px';panel.style.top=clamp(point.y-height-12,dims.header+3,dims.h-dims.reserve-height-8)+'px'}
function contextAction(action){if(state.hiring.pending)return;if(action==='close'){selection=null;$('contextPanel').style.display='none';return}let o=selection;if(!o)return;if(action==='harvest'){const amount=world.harvest(o);if(amount){changeMoney(amount,o);sound('coin');addNotice(1,o,`+${fmt(amount)} monedas`,{value:amount});removeTargetNotices(o,0);toast('Cosecha recogida.')}}else if(action==='repair'){let cost=o.kind==='wall'?(o.destroyed?45:25):(o.destroyed?180:60);if(state.money<cost)return;changeMoney(-cost,o);world.repair(o);sound('build');addNotice(8,o);toast('Reparación terminada.')}renderContext()}
function addNotice(type,target=null,detail=null,extra={}){if(type===0&&state.events.some(e=>e.type===0&&e.target===target))return;const spec=E[type],life=type===1?5:spec[2]==='urgent'?17:11;let n={id:++eventId,type,target,life,max:life,...extra};const el=document.createElement('div');n.el=el;el.className='notice '+(spec[2]==='urgent'?'urgent':'');el.dataset.notice=n.id;el.tabIndex=0;el.setAttribute('role','button');el.setAttribute('aria-label',spec[0]+(target?', ir a '+target.name:''));const info=detail||(type===0?target?.name+' · toca para localizar':type===9?'Día '+state.day+' · seguimos adelante':spec[1]);el.innerHTML=`${image('event'+type)}<span><strong>${spec[0]}</strong><small>${info}</small></span><button class="dismiss" data-dismiss="${n.id}" aria-label="Descartar aviso">×</button><i class="life"></i>`;el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();visitNotice(n.id)}});state.events.push(n);$('events').appendChild(el);while(state.events.length>(dims.short?2:3)){let old=state.events.find(e=>E[e.type][2]!=='urgent'&&e!==n)||state.events[0];removeNotice(old.id)}if(spec[2]==='urgent')sound('warn');return n}
function removeNotice(id){let i=state.events.findIndex(e=>e.id===id);if(i<0)return;state.events[i].el.remove();state.events.splice(i,1)}
function removeTargetNotices(target,type){for(let e of [...state.events])if(e.target===target&&e.type===type)removeNotice(e.id)}
function visitNotice(id){if(state.hiring.pending)return;let n=state.events.find(e=>e.id===id);if(!n)return;removeNotice(id);closeMenu();sound();if(n.type===1){toast((n.value?'+'+fmt(n.value)+' monedas. ':'')+'Dinero añadido al contador.');if(n.target)world.mark(n.target.x,n.target.z,'#ffdd75',2);return}if(n.type===9){toast('Día '+state.day+': un nuevo amanecer.');return}if(n.target){let o=n.target;flyTo(o.x,o.z,()=>{world.mark(o.x,o.z,E[n.type][2]==='urgent'?'#ffac70':'#fce398',4,o.radius*1.2);selectItem(o);if(n.type===0)toast('Toca Recolectar para recoger la cosecha.');else if(n.type===5||n.type===6)toast('El elemento está destruido. Puedes repararlo aquí.');else if(n.type===2||n.type===3||n.type===4)toast(world.attack?'Usa Escudo para proteger la zona del ataque.':'La amenaza ha pasado. Revisa el estado de las defensas.');else world.burst(o.x,1,o.z,'#f2df98',12)})}else toast(E[n.type][0])}
function any(arr){return arr[Math.floor(rand()*arr.length)]}
function triggerEvent(type){if(!ready||state.hiring.pending)return;if(type===9)return startNextDay();let target,detail,extra={};const mainWalls=world.walls.filter(w=>Math.abs(w.x)<18&&Math.abs(w.z)<18);switch(type){case 0:target=any(world.plots);world.mature(target);break;case 1:target=any(world.plots);extra.value=30+Math.floor(rand()*80);changeMoney(extra.value,target);detail='+'+fmt(extra.value)+' monedas';sound('coin');break;case 2:target=world.spawnAttack(any(mainWalls));break;case 3:target=any(world.items.filter(o=>o.kind==='building'));if(target.destroyed)world.repair(target);world.damage(target,.25);world.spawnAttack(target);break;case 4:target=any(mainWalls);if(target.destroyed)world.repair(target);world.damage(target,.25);world.spawnAttack(target);break;case 5:target=any(world.items.filter(o=>o.kind==='building'));world.damage(target,1);break;case 6:target=any(mainWalls);world.damage(target,1);break;case 7:target=world.addWall(-6+rand()*15,12.0+rand()*2,0);world.burst(target.x,1,target.z,'#dce190',14);break;case 8:target=world.items.find(o=>o.kind!=='crop'&&o.hp<1)||any(mainWalls);world.repair(target);break;case 10:if(world.towns.length<8){let x=22+rand()*13,z=10+rand()*15;target=world.addTown(x,z,'Refugio '+(world.towns.length+1));world.mark(x,z,'#eed38c',4)}else target=any(world.towns);break;case 11:target=world.towns[0];world.mark(target.x,target.z,'#ffd47a',4);detail='Pulsa para revisar el asentamiento.';break}return addNotice(type,target,detail,extra)}
function randomEvent(){let allowed=[0,1,2,3,4,5,6,7,8,10,11];if(world.attack)allowed=allowed.filter(n=>![2,3,4].includes(n));if(world.walls.length>64)allowed=allowed.filter(n=>n!==7);return triggerEvent(any(allowed))}
// UI event delegation keeps all controls functional after rebuilding a menu.
$('actions').addEventListener('click',e=>{let b=e.target.closest('[data-menu]');if(b)openMenu(b.dataset.menu)});$('menuButton').addEventListener('click',()=>openMenu('menu'));$('systemDim').addEventListener('click',closeMenu);$('tutorialClose').addEventListener('click',hideTutorial);$('cancelPlacement').addEventListener('click',cancelPlacement);
$('events').addEventListener('click',e=>{let d=e.target.closest('[data-dismiss]');if(d){removeNotice(Number(d.dataset.dismiss));return}let n=e.target.closest('[data-notice]');if(n)visitNotice(Number(n.dataset.notice))});$('contextPanel').addEventListener('click',e=>{let b=e.target.closest('[data-context]');if(b)contextAction(b.dataset.context)});
 host.addEventListener('input',e=>{if(e.target.dataset.crewCount!==undefined){editCrew(+e.target.dataset.crewCount,e.target.value,true);return}if(e.target.id==='eventInterval'){state.eventInterval=Number(e.target.value);state.eventCountdown=state.eventInterval;$('intervalLabel').textContent=state.eventInterval+' s'}});
 host.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
 if(b.dataset.crewStep!==undefined){const i=+b.dataset.crewStep;editCrew(i,state.hiring.draft[i]+Number(b.dataset.delta));sound();return}
 if(b.dataset.hire==='clear'){NPC_TYPES.forEach((_,i)=>editCrew(i,0));return}
 if(b.dataset.hire==='confirm'){confirmHiring();return}
 if(state.hiring.pending)return;if(b.dataset.open){openMenu(b.dataset.open);return}if(b.dataset.town){let o=world.towns.find(t=>t.id===+b.dataset.town);closeMenu();flyTo(o.x,o.z,()=>{selectItem(o);toast('Has vuelto a '+o.name+'.')});return}if(b.dataset.build){beginPlacement(b.dataset.build);return}if(b.dataset.crop!==undefined){beginPlacement('crop',+b.dataset.crop);return}if(b.dataset.spell!==undefined){beginPlacement('spell',+b.dataset.spell);return}if(b.dataset.test!==undefined){let n=+b.dataset.test;closeMenu();triggerEvent(n);return}if(b.dataset.toggle){const key=b.dataset.toggle;state[key]=!state[key];b.setAttribute('aria-checked',state[key]);$('tutorialGuide').style.display=state.guide?'block':'none';sound();return}if(b.dataset.preview){closeMenu();setPreview(b.dataset.preview);return}switch(b.dataset.do){case'close':case'resume':closeMenu();break;case'day':closeMenu();state.minute=870;updateStats();toast('Luz de día.');break;case'night':closeMenu();state.minute=1320;updateStats();toast('La sabana de noche.');break;case'tutorial':closeMenu();showTutorial('Aquí aparecerán los tutoriales. Toda esta franja queda libre de botones, paneles y notificaciones.',13);break;case'money':changeMoney(500);closeMenu();toast('+500 monedas de prueba.');sound('coin');break;case'reset':location.reload();break}});
host.addEventListener('change',e=>{if(e.target.dataset.crewCount!==undefined)editCrew(+e.target.dataset.crewCount,e.target.value)});
host.addEventListener('toggle',()=>{if(state.modal==='hire')requestAnimationFrame(placeModal)},true);
// Pointer gestures: one finger pans, two fingers pinch/rotate. UI is not part of this surface.
const pointers=new Map();let gesture=null,lastPinch=null;function local(e){let r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top}}
canvas.addEventListener('contextmenu',e=>e.preventDefault());canvas.addEventListener('pointerdown',e=>{if(!ready||state.systemPaused)return;sound('silent');if(state.audio&&audioContext?.state==='suspended')audioContext.resume();const p=local(e);pointers.set(e.pointerId,p);canvas.setPointerCapture(e.pointerId);fly=null;if(pointers.size===1)gesture={start:p,last:p,moved:false,rotate:e.button===2||e.shiftKey,multi:false};else{if(gesture)gesture.multi=true;const a=[...pointers.values()];lastPinch={distance:Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y),angle:Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x),x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2}}});
canvas.addEventListener('pointermove',e=>{if(!ready||state.systemPaused)return;const p=local(e);if(placement){let pt=gfx.groundAt(p.x,p.y);placement.point=pt;placement.valid=validPoint(pt,placement.kind)}if(!pointers.has(e.pointerId))return;pointers.set(e.pointerId,p);if(pointers.size>=2){const a=[...pointers.values()],q={distance:Math.hypot(a[1].x-a[0].x,a[1].y-a[0].y),angle:Math.atan2(a[1].y-a[0].y,a[1].x-a[0].x),x:(a[0].x+a[1].x)/2,y:(a[0].y+a[1].y)/2};if(lastPinch){gfx.camera.distance=clamp(gfx.camera.distance*lastPinch.distance/Math.max(5,q.distance),15,65);let da=q.angle-lastPinch.angle;if(da>Math.PI)da-=TAU;if(da<-Math.PI)da+=TAU;gfx.camera.yaw-=da;pan(q.x-lastPinch.x,q.y-lastPinch.y)}lastPinch=q;return}if(!gesture)return;let dx=p.x-gesture.last.x,dy=p.y-gesture.last.y;if(Math.hypot(p.x-gesture.start.x,p.y-gesture.start.y)>5)gesture.moved=true;if(gesture.moved){if(gesture.rotate){gfx.camera.yaw-=dx*.007;gfx.camera.pitch=clamp(gfx.camera.pitch+dy*.005,.40,1.1)}else pan(dx,dy)}gesture.last=p});
function pointerEnd(e){if(state.hiring.pending||!pointers.has(e.pointerId))return;let p=local(e),g=gesture;pointers.delete(e.pointerId);if(!pointers.size){gesture=null;lastPinch=null;if(g&&!g.moved&&!g.multi&&e.button!==2){if(state.modal){closeMenu();return}let hit=gfx.groundAt(p.x,p.y);if(!hit)return;if(placement)commitPlacement(hit);else selectItem(world.pick(hit[0],hit[2]))}}else{if(gesture)gesture.multi=true;lastPinch=null}}
canvas.addEventListener('pointerup',pointerEnd);canvas.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);gesture=null;lastPinch=null});canvas.addEventListener('wheel',e=>{if(!ready||state.systemPaused)return;e.preventDefault();fly=null;gfx.camera.distance=clamp(gfx.camera.distance*Math.exp(e.deltaY*.001),15,65)},{passive:false});
function pan(dx,dy){const c=gfx.camera,k=c.distance*.00155,x=dx*k,y=dy*k/Math.sin(c.pitch);
 // Screen-space drag: the terrain follows the finger on BOTH axes, at any yaw.
 c.target[0]=clamp(c.target[0]-Math.cos(c.yaw)*x-Math.sin(c.yaw)*y,-72,72);
 c.target[2]=clamp(c.target[2]+Math.sin(c.yaw)*x-Math.cos(c.yaw)*y,-72,72)}
const keys=new Set();window.addEventListener('keydown',e=>{if(state.hiring.pending){if(e.key==='Escape')e.preventDefault();if(e.key==='Tab')trapHiringFocus(e);return}if(!ready||e.target.matches('input,textarea,select'))return;const k=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright',' '].includes(k))e.preventDefault();keys.add(k);if(e.repeat)return;if(k==='escape'){if(state.modal)closeMenu();else if(placement)cancelPlacement();else if(selection)selectItem(null);else openMenu('menu')}else if(['1','2','3','4'].includes(k))openMenu(['home','build','grow','magic'][+k-1]);else if(k==='h'){closeMenu();const o=world.towns[0];flyTo(o.x,o.z,()=>selectItem(o))}else if(k==='e'&&!state.systemPaused)randomEvent();else if(k==='t')showTutorial();else if(k==='p')openMenu('menu')});window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{keys.clear();pointers.clear();gesture=null});document.addEventListener('visibilitychange',()=>{last=performance.now();if(document.hidden)keys.clear()});
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();ready=false;$('fatal').style.display='flex';$('fatal').querySelector('p').textContent='Se ha interrumpido la vista 3D. Pulsa Volver a intentar para reiniciar el laboratorio.'});
window.addEventListener('resize',()=>{if(state.preview==='real')layout();else setPreview(state.preview)});window.visualViewport?.addEventListener('resize',()=>{if(state.preview==='real')layout()});
function tick(t){if(!ready)return;const elapsed=Math.min(.1,Math.max(0,(t-last)/1000||0));last=t;if(document.hidden){requestAnimationFrame(tick);return}uiClock=t/1000;let dt=state.systemPaused?0:elapsed*state.speed;let reachedDawn=false;
 if(dt){const clockStep=dailyClockStep(dt);dt=clockStep.dt;reachedDawn=clockStep.dawn;world.workMinute=state.minute;for(let i=0;i<3;i++)state.cooldowns[i]=Math.max(0,state.cooldowns[i]-dt);world.update(dt);for(let task of [...state.tasks])if(task.at<=world.time){state.tasks.splice(state.tasks.indexOf(task),1);task.fn()}if(state.autoEvents){state.eventCountdown-=dt;if(state.eventCountdown<=0){randomEvent();state.eventCountdown=state.eventInterval*(.75+rand()*.5)}}
 // Keyboard moves the camera in the requested direction; pointer drag moves the terrain.
 if(keys.has('arrowleft')||keys.has('a'))pan(elapsed*220,0);if(keys.has('arrowright')||keys.has('d'))pan(-elapsed*220,0);if(keys.has('arrowup')||keys.has('w'))pan(0,elapsed*220);if(keys.has('arrowdown')||keys.has('s'))pan(0,-elapsed*220);
 for(let n of [...state.events]){n.life-=dt;if(n.life<=0)removeNotice(n.id);else n.el.querySelector('.life').style.transform=`scaleX(${n.life/n.max})`}}
 if(reachedDawn)startNextDay();
 if(fly&&!state.systemPaused){const f=fly,p=clamp((uiClock-f.start)/f.duration,0,1),e=p*p*(3-2*p);gfx.camera.target=f.from.map((v,i)=>mix(v,f.to[i],e));gfx.camera.distance=f.distance+(state.reduced?0:Math.sin(p*Math.PI)*Math.min(7,Math.hypot(f.from[0]-f.to[0],f.from[2]-f.to[2])*.1));if(p>=1){fly=null;gfx.camera.distance=f.distance;f.callback?.()}}
 if(!state.systemPaused||state.renderDirty){world.draw(world.time,state.night,selection,placement);state.renderDirty=false}positionContext();
 for(let f of [...state.floats]){f.life-=dt;const p=gfx.project([f.x,f.y+(f.max-f.life)*.75,f.z]);if(f.life<=0||!p){f.el.remove();state.floats.splice(state.floats.indexOf(f),1)}else{f.el.style.left=p.x+'px';f.el.style.top=p.y+'px';f.el.style.opacity=p.y>dims.h-dims.reserve?0:Math.min(1,f.life)}}
 if(tutorialUntil&&uiClock>tutorialUntil)hideTutorial();uiTick+=elapsed;if(uiTick>.25){uiTick=0;updateStats();updateCooldowns();if(selection&&!state.modal)renderContext()}requestAnimationFrame(tick)}
async function init(){try{document.querySelectorAll('[data-sprite]').forEach(img=>img.src=ASSETS[img.dataset.sprite].src);await Promise.all(Object.entries(ASSETS).map(([key,value])=>new Promise((resolve,reject)=>{let img=new Image();img.onload=()=>{A[key]=img;resolve()};img.onerror=()=>reject(Error('No se ha podido cargar el sprite '+key));img.src=value.src})));await new Promise(r=>requestAnimationFrame(r));gfx=new TinyRenderer(canvas);world=new DemoWorld(gfx);world.workMinute=state.minute;world.setCrew([0,0,0,0]);ready=true;world.onReady=p=>{if(state.autoEvents)addNotice(0,p)};layout();updateStats();world.update(0);world.draw(0,state.night,null,null);$('loading').style.opacity=0;setTimeout(()=>$('loading').remove(),350);uiClock=performance.now()/1000;openHiringDay();last=performance.now();requestAnimationFrame(tick);window.HUDLAB={ready:true,state,world,gfx,openMenu,closeMenu,triggerEvent,showTutorial,setPreview,selectItem,beginPlacement,commitPlacement,visitNotice,openHiringDay,confirmHiring,startNextDay,crewSummary,editCrew,updateHiringTotals,changeMoney,dailyClockStep,HIRING_RULES,NPC_TYPES};
 }catch(err){console.error(err);$('loading').style.display='none';$('fatal').style.display='flex';$('fatal').querySelector('p').textContent=err.message||String(err)}}
init();
})();
