// Generated by tools/prepare_contacts.py from Bioma Lab V4.0.
export const CONTACT_SOURCE_SHA256="c1eaa6a1fa947b53110bacc5d776672159217350d40ded570b7f53fd85591ebe";
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export function buildContactData(prototypes,instances,bo,layers){
 const world={instances},state={layers},size=256,bytes=new Uint8Array(size*size).fill(255),width=bo[2]-bo[0],height=bo[3]-bo[1];
  for(let slot=0;slot<20;slot++){
   const p=prototypes[slot],group=p.group;if(!state.layers[group]||group===2)continue;
   const weight=group===0?.26:group===3?.34:group===1?.18:.24;
   for(const a of world.instances[slot]){
    const radius=clamp(p.radius*Math.max(a.sx,a.sz)*(group===0?.35:.55),.5,9);
    const px=(a.x-bo[0])/width*size,pz=(a.z-bo[1])/height*size,rx=radius/width*size,rz=radius/height*size;
    const minX=Math.max(0,Math.floor(px-rx)),maxX=Math.min(size-1,Math.ceil(px+rx)),minZ=Math.max(0,Math.floor(pz-rz)),maxZ=Math.min(size-1,Math.ceil(pz+rz));
    for(let z=minZ;z<=maxZ;z++)for(let x=minX;x<=maxX;x++){
     const d=((x+.5-px)/rx)**2+((z+.5-pz)/rz)**2;if(d>=1)continue;const value=Math.round(255*(1-weight*(1-d)**2));
     const at=z*size+x;bytes[at]=Math.min(bytes[at],value);
    }
   }
  }
 return {pixels:bytes,bounds:[bo[0],bo[1],width,height]};
}
