// Generated by tools/prepare_destruction_renderer.py from original DEST V1.6.6.
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x)), mix=(a,b,t)=>a+(b-a)*t;
const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a));return t*t*(3-2*t)};
const fract=x=>x-Math.floor(x), TAU=Math.PI*2;
const V={add:(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]],sub:(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]],mul:(a,s)=>[a[0]*s,a[1]*s,a[2]*s],dot:(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2],cross:(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],len:a=>Math.hypot(...a),norm:a=>{let l=Math.hypot(...a)||1;return a.map(v=>v/l)}};
function rng(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return((t^t>>>14)>>>0)/4294967296}}
function applyBuildingGeometryPatches(building,positions,normals,uv,indices,bounds){
 if(!building||!building.roofCap)return{positions,normals,uv,indices,bounds};
 const opts=building.roofCap, min=bounds.min, max=bounds.max;
 const span=[max[0]-min[0],max[1]-min[1],max[2]-min[2]];
 let roofY=min[1]+span[1]*(opts.heightRatio??.6);
 const selectionMargin=opts.selectionMargin??0;
 const selected=[];
 for(let i=0;i<positions.length;i+=3)if(positions[i+1]>=roofY-selectionMargin)selected.push(i/3);
 const sample=selected.length?selected:[...Array(positions.length/3).keys()];
 let x0=Infinity,x1=-Infinity,z0=Infinity,z1=-Infinity,u=0,v=0;
 for(const idx of sample){
  const p=idx*3,t=idx*2;
  x0=Math.min(x0,positions[p]);x1=Math.max(x1,positions[p]);
  z0=Math.min(z0,positions[p+2]);z1=Math.max(z1,positions[p+2]);
  u+=uv[t]||0;v+=uv[t+1]||0;
 }
 if(!Number.isFinite(x0)||!Number.isFinite(z0))return{positions,normals,uv,indices,bounds};
 u/=sample.length;v/=sample.length;
 if(Array.isArray(opts.uv)&&opts.uv.length>=2){u=opts.uv[0];v=opts.uv[1];}
 const hasRect=Array.isArray(opts.uvRect)&&opts.uvRect.length>=4;
 const rectUV=hasRect?[[opts.uvRect[0],opts.uvRect[1]],[opts.uvRect[2],opts.uvRect[1]],[opts.uvRect[2],opts.uvRect[3]],[opts.uvRect[0],opts.uvRect[3]]]:null;
 const insetAbsX=(opts.insetX??opts.inset??.05)*(x1-x0);
 const insetAbsZ=(opts.insetZ??opts.inset??.05)*(z1-z0);
 x0+=insetAbsX;x1-=insetAbsX;z0+=insetAbsZ;z1-=insetAbsZ;
 if(!(x1>x0&&z1>z0))return{positions,normals,uv,indices,bounds};
 const pOut=new Float32Array(positions.length+8*3), nOut=new Float32Array(normals.length+8*3), uvOut=new Float32Array(uv.length+8*2);
 pOut.set(positions);nOut.set(normals);uvOut.set(uv);
 const top=[[x0,roofY,z0],[x1,roofY,z0],[x1,roofY,z1],[x0,roofY,z1]];
 const start=positions.length/3;
 const roofUV=opts.capYellow?[-1,-1]:null;
 for(let i=0;i<4;i++){
  pOut.set(top[i],positions.length+i*3);nOut.set([0,1,0],normals.length+i*3);uvOut.set(roofUV??(hasRect?rectUV[i]:[u,v]),uv.length+i*2);
 }
 for(let i=0;i<4;i++){
  pOut.set(top[i],positions.length+(i+4)*3);nOut.set([0,-1,0],normals.length+(i+4)*3);uvOut.set(roofUV??(hasRect?rectUV[i]:[u,v]),uv.length+(i+4)*2);
 }
 const idxCtor=(indices instanceof Uint32Array)?Uint32Array:Uint32Array;
 const iOut=new idxCtor(indices.length+12);
 iOut.set(indices);
 iOut.set([start,start+1,start+2,start,start+2,start+3,start+4,start+6,start+5,start+4,start+7,start+6],indices.length);
 const b={min:[Math.min(bounds.min[0],x0),Math.min(bounds.min[1],roofY),Math.min(bounds.min[2],z0)],max:[Math.max(bounds.max[0],x1),Math.max(bounds.max[1],roofY),Math.max(bounds.max[2],z1)]};
 return{positions:pOut,normals:nOut,uv:uvOut,indices:iOut,bounds:b};
}
export const destructionVertex=`#version 300 es
precision highp float;precision highp int;
layout(location=0) in vec3 aPos;
layout(location=1) in vec3 aNormal;
layout(location=2) in vec2 aUV;
layout(location=3) in vec3 aAnchor;
layout(location=4) in float aSeed;
layout(location=5) in vec3 aRepairNormal;
uniform mat4 uVP;
uniform mat4 uLightVP;
uniform float uDamage;
uniform float uInner;
uniform int uMode;
out vec3 vWorld;
out vec3 vOriginal;
out vec3 vNormal;
out vec2 vUV;
out vec4 vShadow;
out float vSeed;out vec3 vRepairNormal;
vec3 rotateAxis(vec3 p,vec3 axis,float angle){float c=cos(angle),s=sin(angle);return p*c+cross(axis,p)*s+axis*dot(axis,p)*(1.0-c);}
void main(){
 vec3 p=aPos,n=aNormal,rn=aRepairNormal;vOriginal=aPos;vUV=aUV;vSeed=aSeed;
 if(uMode==0){
  p-=n*uInner*.21;
  float c=smoothstep(.79,1.0,uDamage);
  float start=(1.0-clamp(aAnchor.y/8.0,0.0,1.0))*.20+aSeed*.12;
  float t=clamp((c-start)/(1.0-start),0.0,1.0);
  vec3 axis=normalize(vec3(sin(aSeed*47.8),.12,cos(aSeed*32.9)));
  float angle=t*t*(aSeed-.5)*2.8;
  p=rotateAxis(p-aAnchor,axis,angle)+aAnchor;
  n=rotateAxis(n,axis,angle);rn=rotateAxis(rn,axis,angle);
  p.xz+=vec2(sin(aSeed*59.0),cos(aSeed*73.0))*t*t*.72;
  p.y-=aAnchor.y*t*t*1.22;
  p.y=max(p.y,.035+abs(sin(aSeed*27.0))*.045*t);
 }
 if(uMode==2){float ashGrow=smoothstep(.22,1.0,uDamage);p.xz*=mix(.15,1.0,ashGrow);p.y*=mix(.3,1.0,ashGrow);}
 vRepairNormal=rn;vWorld=p;vNormal=n;vShadow=uLightVP*vec4(p,1.0);gl_Position=uVP*vec4(p,1.0);
}`;
export const destructionDamageGLSL=`
uniform vec4 uHoles[8];
uniform sampler3D uNoise;
uniform float uDamage;
uniform float uInner;
float n3(vec3 p){return textureLod(uNoise,p,0.).r;}
float damageField(vec3 p){float f=100.0;for(int i=0;i<8;i++){float r=uHoles[i].w;if(r>.005){r*=mix(1.0,smoothstep(.42,.90,uDamage)*.87,uInner);f=min(f,length(p-uHoles[i].xyz)-r);}}return f+(n3(p*.141)-.5)*.40+(n3(p*.427+vec3(.21))-.5)*.12;}
`;
export const destructionFragment=`#version 300 es
precision highp float;precision highp int;
precision highp sampler3D;
in vec3 vWorld;in vec3 vOriginal;in vec3 vNormal;in vec2 vUV;in vec4 vShadow;in float vSeed;in vec3 vRepairNormal;
uniform vec3 uEye;uniform vec3 uSun;uniform sampler2D uAlbedo;uniform sampler2D uNormalMap;uniform sampler2D uMR;uniform highp sampler2D uShadow;
uniform highp sampler2D uIntactDepth;uniform highp sampler2D uOpeningMask;uniform vec2 uResolution;uniform float uAshAge;
uniform float uRepair;uniform float uTime;uniform float uShadowSize;uniform float uShadows;uniform float uEmbers;uniform float uQuality;uniform int uMode;
out vec4 fragColor;
${destructionDamageGLSL}
vec3 tonemap(vec3 x){x=max(x,vec3(0));return clamp((x*(2.51*x+.03))/(x*(2.43*x+.59)+.14),0.0,1.0);}
vec3 toSRGB(vec3 x){return mix(x*12.92,1.055*pow(max(x,vec3(0)),vec3(1./2.4))-.055,step(vec3(.0031308),x));}
mat3 cotangent(vec3 N,vec3 p,vec2 uv){vec3 dp1=dFdx(p),dp2=dFdy(p);vec2 duv1=dFdx(uv),duv2=dFdy(uv);vec3 a=cross(dp2,N),b=cross(N,dp1);vec3 T=a*duv1.x+b*duv2.x,B=a*duv1.y+b*duv2.y;float l=inversesqrt(max(max(dot(T,T),dot(B,B)),.000001));return mat3(T*l,B*l,N);}
float shadowFactor(vec3 N){if(uShadows<.5)return 1.;vec3 p=vShadow.xyz/vShadow.w*.5+.5;if(p.z>1.||p.x<0.||p.x>1.||p.y<0.||p.y>1.)return 1.;float bias=max(.00075,.0022*(1.-max(dot(N,uSun),0.)));float s=0.;for(int x=-1;x<=1;x++)for(int y=-1;y<=1;y++){float d=texture(uShadow,p.xy+vec2(x,y)*1.35/uShadowSize).r;s+=p.z-bias<=d?1.:0.;}return mix(.08,1.,s/9.);}
void main(){
 vec3 N=normalize(vNormal);vec3 base=vec3(.4),emit=vec3(0);float rough=.9,metal=0.;
 if(uMode==0){
  // Evaluate implicit texture gradients / cotangent derivatives before discard.
  // uInner and uQuality are uniform branches, not per-fragment branches.
  if(uInner<.5){
   bool cap=vUV.x<-.5&&vUV.y<-.5;
   if(cap){
    // Explicit facade-yellow cap: same lighting/shading path as adobe walls, without inheriting the brown atlas tint.
    base=vec3(0.93,0.77,0.44);
    rough=.88;metal=.02;
   }else{
    base=texture(uAlbedo,vUV).rgb;
    vec2 mr=texture(uMR,vUV).gb;rough=clamp(mr.x,.64,1.);metal=mr.y*.15;
    if(uQuality>.2){vec3 map=texture(uNormalMap,vUV).xyz*2.-1.;map.xy*=.55;N=normalize(cotangent(N,vWorld,vUV)*normalize(map));}
    // Keep albedo and all GLB bytes intact: fix only how pale plaster is lit.
    float mx=max(base.r,max(base.g,base.b)),mn=min(base.r,min(base.g,base.b));
    float plaster=(1.-smoothstep(.30,.65,(mx-mn)/max(mx,.001)))*smoothstep(.06,.20,mn)*(1.-smoothstep(5.65,6.15,vOriginal.y));
    N=normalize(mix(N,normalize(vRepairNormal),plaster*uRepair));
   }
  }
  if(uInner>.5){
   // Only a removed NEAREST exterior surface may reveal the auxiliary shell.
   // Integer texel coordinates avoid sampling a neighbour along the silhouette.
   ivec2 pixel=ivec2(gl_FragCoord.xy);
   if(texelFetch(uOpeningMask,pixel,0).r<.5)discard;
   highp float originalDepth=texelFetch(uIntactDepth,pixel,0).r;
   // Two 24-bit depth-buffer steps; the highp sampler is essential on mobile.
   if(originalDepth>=1.||gl_FragCoord.z<=originalDepth+2./16777215.)discard;
  }
  if(uDamage>=.9998)discard;
  if(uDamage>.972+vSeed*.027)discard;
  float f=damageField(vOriginal);if(f<0.)discard;
  float soot=1.-smoothstep(.13,.79,f);float global=smoothstep(.42,.98,uDamage)*.76;
  float burn=max(soot*.97,global*(.8+n3(vOriginal*.5)*.3));
  vec3 coal=vec3(.032,.026,.022)*(0.65+n3(vOriginal*.8)*.9);
  float crack=(1.-smoothstep(.009,.032,abs(n3(vOriginal*.33)-.53)))*soot;
  base=mix(base,coal,burn);base*=1.-crack*.55;
  float edge=1.-smoothstep(.015,.085,f);
  float pulse=.65+.35*sin(uTime*2.6+vOriginal.y*9.+vOriginal.x*7.);
  emit=vec3(.43,.083,.008)*edge*pulse*uEmbers*smoothstep(.09,.4,uDamage)*(1.-smoothstep(.93,1.,uDamage));
  if(uInner>.5){base=vec3(.035,.027,.020)*(0.6+.7*n3(vOriginal*.61));emit*=.12;rough=1.;}
  if(!gl_FrontFacing){N=-N;base*=.31;emit*=.35;}
 }else if(uMode==1){
  float n=n3(vOriginal*.17)*.54+n3(vOriginal*.63)*.32+n3(vOriginal*2.8)*.14;
  base=mix(vec3(.22,.205,.143),vec3(.38,.345,.248),n);
  float edge=clamp(length(vWorld.xz)/8.,0.,1.);base*=mix(1.015,.88,smoothstep(.6,1.,edge));
 }else if(uMode==2){
  if(uDamage<.235)discard;
  float a=n3(vOriginal*.28),b=n3(vOriginal*1.8),c=n3(vOriginal*8.);
  if(vUV.x>.88+(b-.5)*.14)discard;
  base=mix(vec3(.025,.024,.023),vec3(.132,.127,.115),a*.68+b*.32);
  base=mix(base,vec3(.20,.194,.18),smoothstep(.67,.9,c)*.55);
  base*=mix(1.,.38,smoothstep(.70,.95,vUV.x));
  float hot=pow(max(0.,b-.73)*3.7,3.)*(1.-smoothstep(4.,11.,uAshAge));
  emit=vec3(.5,.06,.003)*hot*uEmbers;
 }
 vec3 V=normalize(uEye-vWorld),L=normalize(uSun),H=normalize(L+V);
 float ndl=max(dot(N,L),0.),ndv=max(dot(N,V),.05),ndh=max(dot(N,H),0.);
 float sh=shadowFactor(N);
 vec3 ambient=mix(vec3(.28,.265,.20),vec3(.47,.56,.61),N.y*.5+.5);
 vec3 direct=vec3(1.90,1.59,1.11)*ndl*sh;
 vec3 rim=vec3(.14,.20,.27)*max(dot(N,normalize(vec3(1.,.5,-1.))),0.);
 float a=rough*rough,a2=a*a,den=ndh*ndh*(a2-1.)+1.;float D=a2/max(3.14159*den*den,.001);
 vec3 F=mix(vec3(.04),base,metal);vec3 spec=F*D*ndl*sh*.3;
 vec3 color=base*(ambient+direct+rim)+spec+emit;
 if(uMode==1){float foot=exp(-dot(vWorld.xz*vec2(.27,.31),vWorld.xz*vec2(.27,.31))*1.8);color*=1.-foot*.34*(1.-smoothstep(.75,1.,uDamage));}
 float dist=length(uEye-vWorld);float fog=uMode==1?smoothstep(20.,52.,dist):smoothstep(38.,84.,dist);
 vec2 screenUV=gl_FragCoord.xy/uResolution;vec3 bg=mix(vec3(.665,.684,.574),vec3(.47,.552,.533),smoothstep(0.,1.,screenUV.y));float glow=pow(max(0.,1.-length((screenUV-vec2(.2,.77))*vec2(1.,.75))),3.);bg+=vec3(.16,.11,.035)*glow;
 fragColor=vec4(mix(toSRGB(tonemap(color)),bg,fog),1.);
}`;
export const destructionDepthFragment=`#version 300 es
precision highp float;precision highp int;precision highp sampler3D;
in vec3 vOriginal;in float vSeed;
uniform int uMode;uniform float uUncut;
${destructionDamageGLSL}
void main(){if(uUncut>.5)return;if(uDamage>=.9998||uDamage>.972+vSeed*.027)discard;if(damageField(vOriginal)<0.)discard;}
`;
export const destructionOpeningFragment=`#version 300 es
precision highp float;precision highp int;precision highp sampler3D;
in vec3 vOriginal;in float vSeed;
out vec4 fragMask;
${destructionDamageGLSL}
void main(){
 bool removed=uDamage>=.9998||uDamage>.972+vSeed*.027||damageField(vOriginal)<0.;
 fragMask=vec4(removed?1.:0.,0.,0.,1.);
}`;

export const COLLAPSE_THRESHOLD=.79, COLLAPSE_SECONDS=3.2;
export function createNativeDestruction(building,input){
 let {positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds}=input;
 ({positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds}=applyBuildingGeometryPatches(building,sourcePositions,sourceNormals,sourceUV,sourceIndices,bounds));
 let damage=0,openingDirty=true,activeBuilding=building,seed=building.seed,rand=rng(57021),sourceTriGroups=[],hitSites=[];
 const holes=new Float32Array(32),noiseBytes=new Uint8Array(32*32*32);
 for(let i=0;i<noiseBytes.length;i++)noiseBytes[i]=rand()*255;
 const createMesh=data=>new Float32Array(data);
function vertex(out,p,n,uv=[0,0],anchor=p,seed=.5){out.push(...p,...n,...uv,...anchor,seed)}
function convexHull(points){points.sort((a,b)=>a[0]-b[0]||a[1]-b[1]);const cross=(o,a,b)=>(a[0]-o[0])*(b[1]-o[1])-(a[1]-o[1])*(b[0]-o[0]);let lower=[],upper=[];for(const p of points){while(lower.length>1&&cross(lower.at(-2),lower.at(-1),p)<=0)lower.pop();lower.push(p)}for(let i=points.length-1;i>=0;i--){const p=points[i];while(upper.length>1&&cross(upper.at(-2),upper.at(-1),p)<=0)upper.pop();upper.push(p)}lower.pop();upper.pop();return lower.concat(upper)}
let hull=[];
function radiusAt(a){const dx=Math.cos(a),dz=Math.sin(a);let radius=0;for(let i=0;i<hull.length;i++){const p=hull[i],q=hull[(i+1)%hull.length],ex=q[0]-p[0],ez=q[1]-p[1],det=dx*ez-dz*ex;if(Math.abs(det)<1e-8)continue;const t=(p[0]*ez-p[1]*ex)/det,s=(p[0]*dz-p[1]*dx)/det;if(t>0&&s>=-.001&&s<=1.001)radius=Math.max(radius,t)}return radius||4}
function makeAsh(){const out=[],N=160,R=18;function p(a,r){const rad=radiusAt(a)*1.10*(1+Math.sin(a*17.3)*.016+Math.sin(a*9.2)*.018);const x=Math.cos(a)*rad*r,z=Math.sin(a)*rad*r;return [x,.015+Math.pow(1-r*r,2)*(.15+.04*Math.sin(x*2.1)*Math.sin(z*1.8)),z]}
 for(let j=0;j<R;j++)for(let i=0;i<N;i++){let a=i/N*TAU,b=(i+1)/N*TAU,r=j/R,s=(j+1)/R,ps=[p(a,r),p(b,r),p(b,s),p(a,s)],uvs=[[r,a],[r,b],[s,b],[s,a]];for(const ids of [[0,1,2],[0,2,3]]){let n=V.norm(V.cross(V.sub(ps[ids[1]],ps[ids[0]]),V.sub(ps[ids[2]],ps[ids[0]])));for(const k of ids)vertex(out,ps[k],n,uvs[k])}}
 return createMesh(out)}
function makeRepairNormals(){
 const nf=sourceIndices.length/3, fns=[],areas=[],adj=new Map(),keys=[];
 for(let k=0;k<sourcePositions.length;k+=3){const key=[0,1,2].map(j=>Math.round(sourcePositions[k+j]*1e5)).join(',');keys.push(key);if(!adj.has(key))adj.set(key,new Set());}
 for(let f=0;f<nf;f++){const ids=Array.from(sourceIndices.subarray(f*3,f*3+3)),p=ids.map(k=>Array.from(sourcePositions.subarray(k*3,k*3+3))),cross=V.cross(V.sub(p[1],p[0]),V.sub(p[2],p[0]));fns.push(V.norm(cross));areas.push(V.len(cross)*.5);for(const k of ids)adj.get(keys[k]).add(f);}
 const out=new Float32Array(nf*9);
 for(let f=0;f<nf;f++)for(let j=0;j<3;j++){
  const k=sourceIndices[f*3+j],fn=fns[f];let n=[0,0,0];
  for(const q of adj.get(keys[k]))if(V.dot(fn,fns[q])>.72){const w=Math.pow(areas[q],.75);n=V.add(n,V.mul(fns[q],w));}
  n=V.norm(n);
  const axis=Math.abs(fn[0])>Math.abs(fn[1])?(Math.abs(fn[0])>Math.abs(fn[2])?0:2):(Math.abs(fn[1])>Math.abs(fn[2])?1:2);
  if(Math.abs(fn[axis])>.95){const pn=[0,0,0];pn[axis]=Math.sign(fn[axis]);n=V.norm(n.map((x,i)=>mix(x,pn[i],smooth(.95,.996,Math.abs(fn[axis])))));}
  out.set(n,(f*3+j)*3);
 }
 return out;
}
 const points=[];for(let i=0;i<sourcePositions.length;i+=3)points.push([sourcePositions[i],sourcePositions[i+2]]);hull=convexHull(points);
 const modelData=[],groups=new Map();sourceTriGroups=[];const modelRand=rng(building.seed||57021);
 for(let i=0;i<sourceIndices.length;i+=3){const c=[0,0,0];for(let j=0;j<3;j++){const k=sourceIndices[i+j]*3;for(let a=0;a<3;a++)c[a]+=sourcePositions[k+a]/3;}
  const key=c.map(x=>Math.floor(x/1.10)).join(',');if(!groups.has(key))groups.set(key,{sum:[0,0,0],count:0,seed:modelRand()});
  const g=groups.get(key);g.count++;for(let a=0;a<3;a++)g.sum[a]+=c[a];sourceTriGroups.push(g);
 }
 for(const g of groups.values())g.anchor=g.sum.map(x=>x/g.count);
 for(let i=0;i<sourceIndices.length;i++){const k=sourceIndices[i],g=sourceTriGroups[Math.floor(i/3)];vertex(modelData,Array.from(sourcePositions.subarray(k*3,k*3+3)),Array.from(sourceNormals.subarray(k*3,k*3+3)),Array.from(sourceUV.subarray(k*2,k*2+2)),g.anchor,g.seed);}
function sampleNoise(p){const c=p.map(x=>fract(x)*32-.5),base=c.map(Math.floor),f=c.map(fract);let total=0;for(let z=0;z<2;z++)for(let y=0;y<2;y++)for(let x=0;x<2;x++){const id=((base[0]+x)&31)+(((base[1]+y)&31)<<5)+(((base[2]+z)&31)<<10);total+=noiseBytes[id]/255*(x?f[0]:1-f[0])*(y?f[1]:1-f[1])*(z?f[2]:1-f[2])}return total}
function field(p){let f=100;for(let i=0;i<8;i++)if(holes[i*4+3]>.005)f=Math.min(f,V.len(V.sub(p,Array.from(holes.subarray(i*4,i*4+3))))-holes[i*4+3]);return f+(sampleNoise(p.map(v=>v*.141))-.5)*.40+(sampleNoise(p.map(v=>v*.427+.21))-.5)*.12}
// CPU picking mirrors the vertex collapse so touches keep following falling pieces.
function collapsedPoint(p,g){
 if(damage<COLLAPSE_THRESHOLD)return p;
 const c=smooth(COLLAPSE_THRESHOLD,1,damage),start=(1-clamp(g.anchor[1]/8))*.20+g.seed*.12;
 const t=clamp((c-start)/(1-start)),axis=V.norm([Math.sin(g.seed*47.8),.12,Math.cos(g.seed*32.9)]),angle=t*t*(g.seed-.5)*2.8;
 const q=V.sub(p,g.anchor),cs=Math.cos(angle),sn=Math.sin(angle);
 let out=V.add(V.add(V.mul(q,cs),V.mul(V.cross(axis,q),sn)),V.mul(axis,V.dot(axis,q)*(1-cs)));
 out=V.add(out,g.anchor);out[0]+=Math.sin(g.seed*59)*t*t*.72;out[2]+=Math.cos(g.seed*73)*t*t*.72;
 out[1]-=g.anchor[1]*t*t*1.22;out[1]=Math.max(out[1],.035+Math.abs(Math.sin(g.seed*27))*.045*t);return out;
}
function raycast(origin,dir,respectDamage=true){
 let best=Infinity,hit=null;
 for(let i=0;i<sourceIndices.length;i+=3){
  const g=sourceTriGroups[i/3];if(respectDamage&&damage>.972+g.seed*.027)continue;
  const ids=[sourceIndices[i],sourceIndices[i+1],sourceIndices[i+2]];
  const originals=ids.map(k=>[sourcePositions[k*3],sourcePositions[k*3+1],sourcePositions[k*3+2]]);
  const a=collapsedPoint(originals[0],g),b=collapsedPoint(originals[1],g),c=collapsedPoint(originals[2],g);
  const e1=V.sub(b,a),e2=V.sub(c,a),h=V.cross(dir,e2),det=V.dot(e1,h);if(Math.abs(det)<1e-8)continue;
  const inv=1/det,s=V.sub(origin,a),u=inv*V.dot(s,h);if(u<0||u>1)continue;
  const q=V.cross(s,e1),v=inv*V.dot(dir,q);if(v<0||u+v>1)continue;
  const t=inv*V.dot(e2,q);if(t<=0||t>=best)continue;
  const p=V.add(origin,V.mul(dir,t));
  const original=originals[0].map((x,k)=>x*(1-u-v)+originals[1][k]*u+originals[2][k]*v);
  if(respectDamage&&field(original)<.015)continue;
  let n=V.norm(V.cross(e1,e2));if(V.dot(n,dir)>0)n=V.mul(n,-1);
  best=t;hit={p,n,t,original};
 }
 return hit;
}

function surfaceFrom(origin,target){return raycast(origin,V.norm(V.sub(target,origin)),false)||{p:target,n:V.norm(V.sub(origin,target))}}
function resetSites(){rand=rng(seed);const siteScale=activeBuilding.fitSites?[(bounds.max[0]-bounds.min[0])/8.82395076751709,(bounds.max[1]-bounds.min[1])/8,(bounds.max[2]-bounds.min[2])/7.824930191040039]:[1,1,1];const specs=[[[1.2,2.6,11],[1.2,2.6,0]],[[10,3.4,1.6],[0,3.4,1.6]],[[-2.0,11,2.0],[-2,3,1.2]],[[-10,2.4,1],[-1,2.4,0]],[[.5,3.0,-11],[.5,3.0,0]],[[3,11,-1.9],[2,3,-1.5]],[[-2.4,2.0,-11],[-2.4,2,0]],[[-1.3,11,-2],[-1.2,2,-1.8]]];hitSites=specs.map((s,i)=>{let origin=s[0].map((v,j)=>(v+(j===1?0:(rand()-.5)*.6))*siteScale[j]),target=s[1].map((v,j)=>v*siteScale[j]);const hit=surfaceFrom(origin,target);return{p:hit.p,n:hit.n,birth:[.045,.17,.29,.40,.50,.58,.66,.72][i],maxRadius:[2.65,2.50,2.55,2.45,2.50,2.45,2.4,2.5][i],manual:false,emission:0,lastRadius:0}});updateHoles()}
function updateHoles(){openingDirty=true;let active=0;for(let i=0;i<8;i++){const s=hitSites[i];let t=clamp((damage-s.birth)/(.91-s.birth));let radius=s.maxRadius*Math.pow(t,.70);if(s.manual)radius=Math.max(radius,s.minRadius*smooth(s.birth,s.birth+.075,damage));if(damage<=.0001)radius=0;holes.set([...s.p,radius],i*4);if(radius>.06)active++;s.radius=radius}}
resetSites();
function stages(){
 if(damage<.005)return['Intacto','01 / EDIFICIO INTACTO','#a3bba0'];
 if(damage<.20)return['Primeros impactos','02 / PRIMEROS IMPACTOS','#cbca9a'];
 if(damage<.52)return['Daño localizado','03 / DAÑO LOCALIZADO','#dfc27e'];
 if(damage<COLLAPSE_THRESHOLD)return['Daño severo','04 / PÉRDIDA DE ESTRUCTURA','#e7ad75'];
 if(damage<.9998)return['Colapso inevitable','05 / COLAPSO IRREVERSIBLE','#edac8c'];
 return['Cenizas','06 / DESTRUCCIÓN TOTAL','#a3ada1'];
}

 const repairNormals=makeRepairNormals(),ash=makeAsh();
 return {
  positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds,
  triangles:sourceTriGroups,vertices:new Float32Array(modelData),repairNormals,ash,hull,noiseBytes,holes,hitSites,
  setDamage(value){if(!Number.isFinite(value))throw new Error('Daño visual no finito');damage=clamp(value);updateHoles();return damage;},
  get damage(){return damage;},stages,field,sampleNoise,collapsedPoint,raycast,radiusAt
 };
}
