// Generated by tools/prepare_horizon.py from Bioma Lab V4.0.
import {TerrainField,canyonFrame,canyonGroundColor,desertGroundColor,hex} from '../world/terrain.js';
import {Geometry,desertSmoothNormals} from './terrain-source.js';
const mix=(a,b,t)=>a+(b-a)*t;
export const HORIZON_SOURCE_SHA256="c1eaa6a1fa947b53110bacc5d776672159217350d40ded570b7f53fd85591ebe";
function makeCanyonHorizon(config,b,cx,cz,near){
 const field=new TerrainField(config),g=new Geometry(),water=new Geometry(),ox=cx*48,oz=cz*48,R=384,dx=4,dz=8;
 const cols=2*R/dx,rows=2*R/dz,pts=[],colors=[];
 const point=(x,z)=>[x-ox,field.height(x,z),z-oz];
 for(let j=0;j<=rows;j++)for(let i=0;i<=cols;i++){
  const x=ox-R+i*dx,z=oz-R+j*dz;pts.push(point(x,z));colors.push(canyonGroundColor(field,b,x,z));
 }
 for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){
  const x=ox-R+i*dx,z=oz-R+j*dz;
  if(x>=near[0]&&z>=near[1]&&x+dx<=near[2]&&z+dz<=near[3])continue;
  const a=j*(cols+1)+i,bb=a+1,d=a+cols+1,c=d+1;
  const touches=((x+dx===near[0]||x===near[2])&&z>=near[1]&&z+dz<=near[3])||((z+dz===near[1]||z===near[3])&&x>=near[0]&&x+dx<=near[2]);
  if(touches){
   // The inner edge has the EXACT 1m lattice of the resident chunks. A fan joins
   // it to the coarser outer mesh, so no T-junction cracks or floating triangles.
   const corners=[[x,z],[x,z+dz],[x+dx,z+dz],[x+dx,z]],ring=[];
   for(let k=0;k<4;k++){
    const p=corners[k],q=corners[(k+1)%4];
    const edge=(p[0]===q[0]&&(p[0]===near[0]||p[0]===near[2])&&p[1]>=near[1]&&q[1]>=near[1]&&p[1]<=near[3]&&q[1]<=near[3])||(p[1]===q[1]&&(p[1]===near[1]||p[1]===near[3])&&p[0]>=near[0]&&q[0]>=near[0]&&p[0]<=near[2]&&q[0]<=near[2]);
    const steps=edge?Math.abs(p[0]-q[0])+Math.abs(p[1]-q[1]):1;
    for(let t=0;t<steps;t++)ring.push([mix(p[0],q[0],t/steps),mix(p[1],q[1],t/steps)]);
   }
   const center=point(x+dx*.5,z+dz*.5),col=canyonGroundColor(field,b,x+dx*.5,z+dz*.5);
   for(let k=0;k<ring.length;k++){const p=ring[k],q=ring[(k+1)%ring.length];g.tri(center,point(...p),point(...q),col,[col,canyonGroundColor(field,b,...p),canyonGroundColor(field,b,...q)]);}
  }else{
   g.tri(pts[a],pts[d],pts[bb],colors[a],[colors[a],colors[d],colors[bb]]);
   g.tri(pts[bb],pts[d],pts[c],colors[c],[colors[bb],colors[d],colors[c]]);
  }
 }
 if(config.river)for(let z=oz-R;z<oz+R;z++){
  const z1=z+1,x=field.riverX(z),x1=field.riverX(z1),w=canyonFrame(field,z).waterHalf+1.2,w1=canyonFrame(field,z1).waterHalf+1.2,y=field.riverLevel,co=hex(b.colors.water);
  const a=[x-w-ox,y,z-oz],bb=[x+w-ox,y,z-oz],d=[x1-w1-ox,y,z1-oz],c=[x1+w1-ox,y,z1-oz];water.tri(a,d,bb,co);water.tri(bb,d,c,co);
 }
 return {terrain:new Float32Array(g.v),water:new Float32Array(water.v)};
}

function makeDesertHorizon(config,b,cx,cz,near){
 const field=new TerrainField(config),g=new Geometry(),water=new Geometry(),ox=cx*48,oz=cz*48,R=576,dx=8,dz=8;
 const cols=2*R/dx,rows=2*R/dz,pts=[],colors=[];
 const point=(x,z)=>[x-ox,field.height(x,z),z-oz];
 for(let j=0;j<=rows;j++)for(let i=0;i<=cols;i++){
  const x=ox-R+i*dx,z=oz-R+j*dz;pts.push(point(x,z));colors.push(desertGroundColor(field,b,x,z));
 }
 for(let j=0;j<rows;j++)for(let i=0;i<cols;i++){
  const x=ox-R+i*dx,z=oz-R+j*dz;
  if(x>=near[0]&&z>=near[1]&&x+dx<=near[2]&&z+dz<=near[3])continue;
  const a=j*(cols+1)+i,bb=a+1,d=a+cols+1,c=d+1;
  const touches=((x+dx===near[0]||x===near[2])&&z>=near[1]&&z+dz<=near[3])||((z+dz===near[1]||z===near[3])&&x>=near[0]&&x+dx<=near[2]);
  if(touches){
   // The inner edge has the EXACT 1m lattice of the resident chunks. A fan joins
   // it to the coarser outer mesh, so no T-junction cracks or floating triangles.
   const corners=[[x,z],[x,z+dz],[x+dx,z+dz],[x+dx,z]],ring=[];
   for(let k=0;k<4;k++){
    const p=corners[k],q=corners[(k+1)%4];
    const edge=(p[0]===q[0]&&(p[0]===near[0]||p[0]===near[2])&&p[1]>=near[1]&&q[1]>=near[1]&&p[1]<=near[3]&&q[1]<=near[3])||(p[1]===q[1]&&(p[1]===near[1]||p[1]===near[3])&&p[0]>=near[0]&&q[0]>=near[0]&&p[0]<=near[2]&&q[0]<=near[2]);
    const steps=edge?Math.abs(p[0]-q[0])+Math.abs(p[1]-q[1]):1;
    for(let t=0;t<steps;t++)ring.push([mix(p[0],q[0],t/steps),mix(p[1],q[1],t/steps)]);
   }
   const center=point(x+dx*.5,z+dz*.5),col=desertGroundColor(field,b,x+dx*.5,z+dz*.5);
   for(let k=0;k<ring.length;k++){const p=ring[k],q=ring[(k+1)%ring.length];g.tri(center,point(...p),point(...q),col,[col,desertGroundColor(field,b,...p),desertGroundColor(field,b,...q)]);}
  }else{
   g.tri(pts[a],pts[d],pts[bb],colors[a],[colors[a],colors[d],colors[bb]]);
   g.tri(pts[bb],pts[d],pts[c],colors[c],[colors[bb],colors[d],colors[c]]);
  }
 }

 // A narrow subsurface apron covers raster precision cracks at the fine/coarse seam.
 // It sits UNDER both meshes; it changes neither dune height nor object placement.
 const apron=(axis,value,from,to)=>{
  const p=(t,offset)=>{const x=axis===0?value+offset:t,z=axis===0?t:value+offset;return[x-ox,field.height(x,z)-.012,z-oz];};
  for(let t=from;t<to;t++){
   const a=p(t,-.10),b=p(t,.10),c=p(t+1,.10),d=p(t+1,-.10);
   const col=desertGroundColor(field,bBiome,axis===0?value:t,axis===0?t:value);
   g.tri(a,b,d,col);g.tri(b,c,d,col);
  }
 };
 const bBiome=b;
 apron(0,near[0],near[1],near[3]);apron(0,near[2],near[1],near[3]);
 apron(1,near[1],near[0],near[2]);apron(1,near[3],near[0],near[2]);
 desertSmoothNormals(field,g.v,ox,oz);
 return {terrain:new Float32Array(g.v),water:new Float32Array(water.v)};
}

export {makeCanyonHorizon,makeDesertHorizon};
