// Generated by tools/prepare_terrain_renderer.py from Bioma Lab V4.0.
import {canyonGroundColor,desertGroundColor} from '../world/terrain.js';
import {chunkBounds} from './water-source.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;
const smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t)}, TAU=Math.PI*2;
const add=(a,b)=>[a[0]+b[0],a[1]+b[1],a[2]+b[2]], sub=(a,b)=>[a[0]-b[0],a[1]-b[1],a[2]-b[2]], mul=(a,k)=>[a[0]*k,a[1]*k,a[2]*k];
const dot=(a,b)=>a[0]*b[0]+a[1]*b[1]+a[2]*b[2], cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]], norm=a=>mul(a,1/(Math.hypot(...a)||1));
const hex=s=>[parseInt(s.slice(1,3),16)/255,parseInt(s.slice(3,5),16)/255,parseInt(s.slice(5,7),16)/255];
const cmix=(a,b,t)=>a.map((v,i)=>mix(v,b[i],t)), shade=(c,k)=>c.map(v=>clamp(v*k,0,1));
function hashString(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return h>>>0}
function avalanche(h){h=Math.imul(h^(h>>>16),0x7feb352d);h=Math.imul(h^(h>>>15),0x846ca68b);return(h^(h>>>16))>>>0}
function hashCell(s,x,z,k=0){return avalanche(s^Math.imul(x|0,0x9e3779b1)^Math.imul(z|0,0x85ebca77)^Math.imul(k|0,0xc2b2ae3d))}
function rand(seed){let a=seed>>>0;return()=>{a=(a+0x6D2B79F5)|0;let t=Math.imul(a^(a>>>15),1|a);t^=t+Math.imul(t^(t>>>7),61|t);return((t^(t>>>14))>>>0)/4294967296}}
function noise(x,z,s){const ix=Math.floor(x),iz=Math.floor(z),fx=x-ix,fz=z-iz;const q=t=>t*t*t*(t*(t*6-15)+10);const u=q(fx),v=q(fz);return mix(mix(hashCell(s,ix,iz)/4294967296,hashCell(s,ix+1,iz)/4294967296,u),mix(hashCell(s,ix,iz+1)/4294967296,hashCell(s,ix+1,iz+1)/4294967296,u),v)}
function fbm(x,z,s){return noise(x,z,s)*.58+noise(x*2.03,z*2.03,s^9271)*.28+noise(x*4.13,z*4.13,s^29714)*.14}
class Geometry{
 constructor(){this.v=[];this.min=[Infinity,Infinity,Infinity];this.max=[-Infinity,-Infinity,-Infinity]}
 tri(a,b,c,color,colors=null){const n=norm(cross(sub(b,a),sub(c,a)));for(let j=0;j<3;j++){const p=[a,b,c][j],co=colors?colors[j]:color;this.v.push(...p,...n,...co);for(let k=0;k<3;k++){this.min[k]=Math.min(this.min[k],p[k]);this.max[k]=Math.max(this.max[k],p[k])}}}
 line(a,b,color){for(const p of[a,b]){this.v.push(...p,0,1,0,...color);for(let k=0;k<3;k++){this.min[k]=Math.min(this.min[k],p[k]);this.max[k]=Math.max(this.max[k],p[k])}}}
 merge(g,offset=[0,0,0],scale=[1,1,1],yaw=0){const si=Math.sin(yaw),co=Math.cos(yaw);for(let k=0;k<g.v.length;k+=27){const ps=[];const cs=[];for(let j=0;j<3;j++){const i=k+j*9,x=g.v[i]*scale[0],y=g.v[i+1]*scale[1],z=g.v[i+2]*scale[2];ps.push([x*co+z*si+offset[0],y+offset[1],-x*si+z*co+offset[2]]);cs.push(g.v.slice(i+6,i+9))}this.tri(...ps,cs[0],cs)}return this}
}
function smoothTerrainLighting(field,data,ox,oz){
 if(field.canyon||field.desert)return;const normals=new Map();
 for(let k=0;k<data.length;k+=9){const x=data[k]+ox,z=data[k+2]+oz,key=x+','+z;let n=normals.get(key);
  if(!n){const dx=field.height(x+.5,z)-field.height(x-.5,z),dz=field.height(x,z+.5)-field.height(x,z-.5);n=norm([-dx,1,-dz]);normals.set(key,n);}
  data[k+3]=n[0];data[k+4]=n[1];data[k+5]=n[2];
 }
}
function desertSmoothNormals(field,vertices,ox,oz){
 const normals=new Map();
 for(let i=0;i<vertices.length;i+=9){
  const x=ox+vertices[i],z=oz+vertices[i+2],key=x+','+z;let n=normals.get(key);
  if(!n){n=norm([field.height(x-.5,z)-field.height(x+.5,z),1,field.height(x,z-.5)-field.height(x,z+.5)]);normals.set(key,n);}
  vertices[i+3]=n[0];vertices[i+4]=n[1];vertices[i+5]=n[2];
 }
}

function groundColor(field,b,x,z){
 if(field.desert)return desertGroundColor(field,b,x,z);
 if(field.canyon)return canyonGroundColor(field,b,x,z);
 const soil=hex(b.colors.soil),grass=hex(b.colors.grass),rock=hex(b.colors.rock),p=fbm(x*.041,z*.041,field.seed^8913),s=field.slope(x,z);
 let t=smooth(.28,.72,p);if(b.style===1)t=clamp(t*.75+.25,0,1);if(b.style===2)t*=.48;
 let col=cmix(soil,grass,t);if(s>.42)col=cmix(col,rock,smooth(.42,1.4,s)*.62);
 if(field.riverActive){const d=Math.abs(x-field.riverX(z));col=cmix(col,cmix(soil,hex(b.fluid==='lava'?'#4f3932':'#d2ba87'),.34),(1-smooth(6,10,d))*.58);col=cmix(col,cmix(hex(b.colors.water),hex(b.fluid==='lava'?'#51443b':'#c8cb93'),.76),(1-smooth(9,13,d))*.18);}
 if(field.wetland){const info=field.waterInfo(x,z),wetMud=cmix(soil,hex('#2b241f'),.74),peat=cmix(wetMud,hex('#43563a'),.28),moss=cmix(peat,grass,.18);col=cmix(col,wetMud,(1-smooth(0,24,info.shore))*.84);col=cmix(col,moss,(1-smooth(0,11,info.shore))*.46);if(info.inside)col=cmix(col,cmix(wetMud,hex(b.colors.water),.14),.52);}
 if(field.canyon){const d=Math.abs(x-field.riverX(z));const warm=cmix(soil,rock,.46),shadow=cmix(rock,hex('#6c3d27'),.34),riparian=cmix(soil,grass,.28);col=cmix(col,warm,(1-smooth(8,22,d))*.58);col=cmix(col,shadow,smooth(.55,1.9,s)*.55);col=cmix(col,riparian,(1-smooth(4,11,d))*clamp(field.moisture(x,z)*1.18,0,.55));}
 return shade(col,.94+noise(x*.11,z*.11,field.seed^1181)*.12);
}
export const TERRAIN_SOURCE_SHA256="c1eaa6a1fa947b53110bacc5d776672159217350d40ded570b7f53fd85591ebe";
export function buildGroundData(field,b,cx,cz){const bo=chunkBounds(cx,cz),g=new Geometry(),wire={line(){}};
 const points=[],colors=[];
 for(let iz=0;iz<=48;iz++)for(let ix=0;ix<=48;ix++){
  const x=bo.minX+ix,z=bo.minZ+iz;points.push([ix-24,field.lattice(x,z),iz-24]);colors.push(groundColor(field,b,x,z));
 }
 const wireColor=hex('#3e5141');
 for(let iz=0;iz<48;iz++)for(let ix=0;ix<48;ix++){
  const a=iz*49+ix,bb=a+1,d=a+49,c=d+1;
  g.tri(points[a],points[d],points[bb],colors[a],[colors[a],colors[d],colors[bb]]);
  g.tri(points[bb],points[d],points[c],colors[c],[colors[bb],colors[d],colors[c]]);
  for(const[k,l]of[[a,bb],[a,d],[bb,d]]){const p=[...points[k]],q=[...points[l]];p[1]+=.035;q[1]+=.035;wire.line(p,q,wireColor);}
 }

 smoothTerrainLighting(field,g.v,bo.centerX,bo.centerZ);
 if(field.desert)desertSmoothNormals(field,g.v,bo.centerX,bo.centerZ);
 return new Float32Array(g.v);
}
