// Generated by tools/prepare_wall_renderer.py from native Bastion V4.1.
function regionalEase(t){t=Math.max(0,Math.min(1,t));return t*t*t*(t*(t*6-15)+10);}
export function wallStages(p){
  if(p.asset)return[{key:p.asset,dest:null,morph:0}];
  const d=1-Math.max(0,Math.min(1,p.visual??p.hp/p.maxHp));let a,b,t;
  if(p.kind==='gate'){a='puerta';b='destruido';t=d;}
  else if(d<=.5){a='intacto';b='danado';t=d*2;}
  else{a='danado';b='destruido';t=d*2-1;}
  const ka=p.material+'_'+a,kb=p.material+'_'+b;
  if(t<=0)return[{key:ka,dest:null,morph:0}];
  if(t>=1)return[{key:kb,dest:null,morph:0}];
  return[{key:ka,dest:kb,morph:t,role:0},{key:kb,dest:ka,morph:1-t,role:1}];
 }
export function morphedWallPositions(mesh,morph){
  if(morph===0)return mesh.pos;
  if(mesh.lastMorph===morph&&mesh.morphed)return mesh.morphed;
  const t=regionalEase(morph),scale=Math.sqrt(Math.max(0,1-regionalEase((t-.5)*2)));
  const out=mesh.morphed||new Float32Array(mesh.pos.length);
  for(let k=0;k<out.length;k++){const pivot=mesh.roots[k]+(mesh.peers[k]-mesh.roots[k])*t,fitted=mesh.pos[k]+(mesh.targets[k]-mesh.pos[k])*t;out[k]=pivot+(fitted-pivot)*scale;}
  mesh.lastMorph=morph;mesh.morphed=out;return out;
 }
