// Generated by tools/prepare_water.py from Bioma Lab V4.0.
import {canyonFrame,hex} from '../world/terrain.js';
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
export const WATER_SOURCE_SHA256="c1eaa6a1fa947b53110bacc5d776672159217350d40ded570b7f53fd85591ebe";
function buildWetlandWater(field,bo,b,water){
 const step=.75,n=64,mask=new Uint8Array(n*n),color=hex(b.colors.water);
 for(let z=0;z<n;z++)for(let x=0;x<n;x++)mask[z*n+x]=field.waterInfo(bo.minX+(x+.5)*step,bo.minZ+(z+.5)*step).inside?1:0;
 // Lossless greedy rectangles over the existing occupancy cells; no altered coastline.
 for(let z=0;z<n;z++)for(let x=0;x<n;x++){
  if(!mask[z*n+x])continue;let w=1;while(x+w<n&&mask[z*n+x+w])w++;
  let h=1,expand=true;while(z+h<n&&expand){for(let dx=0;dx<w;dx++)if(!mask[(z+h)*n+x+dx]){expand=false;break;}if(expand)h++;}
  for(let dz=0;dz<h;dz++)for(let dx=0;dx<w;dx++)mask[(z+dz)*n+x+dx]=0;
  const x0=-24+x*step,z0=-24+z*step,y=field.wetlandLevel(bo.minX+x*step,bo.minZ+z*step);
  const a=[x0,y,z0],bb=[x0+w*step,y,z0],c=[x0+w*step,y,z0+h*step],d=[x0,y,z0+h*step];water.tri(a,d,bb,color);water.tri(bb,d,c,color);
 }
}
export function chunkBounds(cx,cz){return{minX:cx*48-24,minZ:cz*48-24,maxX:cx*48+24,maxZ:cz*48+24,size:48,centerX:cx*48,centerZ:cz*48};}
export function buildChunkWater(field,bo,b,water){
 if(field.riverActive){const color=hex(b.colors.water);
  for(let z=bo.minZ;z<bo.maxZ;z++){
   const z1=z+1,x0=field.riverX(z),x1=field.riverX(z1),w0=field.canyon?canyonFrame(field,z).waterHalf+1.2:10,w1=field.canyon?canyonFrame(field,z1).waterHalf+1.2:10,l0=clamp(x0-w0,bo.minX,bo.maxX),r0=clamp(x0+w0,bo.minX,bo.maxX),l1=clamp(x1-w1,bo.minX,bo.maxX),r1=clamp(x1+w1,bo.minX,bo.maxX);
   if(r0<=l0&&r1<=l1)continue;
   const y=field.riverLevel,a=[l0-bo.centerX,y,z-bo.centerZ],bb=[r0-bo.centerX,y,z-bo.centerZ],c=[r1-bo.centerX,y,z1-bo.centerZ],d=[l1-bo.centerX,y,z1-bo.centerZ];water.tri(a,d,bb,color);water.tri(bb,d,c,color);
  }
 }
 if(field.wetland)buildWetlandWater(field,bo,b,water);

}
export function buildAssetWater(a,water){
   const pts=a.water.outline;if(pts.some(p=>!Array.isArray(p)||p.length!==2||p.some(v=>!Number.isFinite(v)||Math.abs(v)>100)))throw Error('Contorno de charca fuera de rango.');
   const center=pts.reduce((q,p)=>[q[0]+p[0]/pts.length,q[1]+p[1]/pts.length],[0,0]),y=a.water.level;
   for(let j=0;j<pts.length;j++){const p=pts[j],q=pts[(j+1)%pts.length];water.tri([center[0],y,center[1]],[p[0],y,p[1]],[q[0],y,q[1]],[.2,.6,.65]);}
}
