// Bake the user's V4 recipe verbatim; no repair search or camera-dependent fitting.
import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import vm from 'node:vm';import {execFileSync} from 'node:child_process';import assert from 'node:assert/strict';
import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {readGlb,writeGlb} from './glb-container.mjs';import {createCropBatch} from '../src/rendering/crop-batch.js';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),dir='references/crops-v4/',zip=process.argv[2]??dir+'1-biomas.zip';
fs.mkdirSync(dir,{recursive:true});if(zip!==dir+'1-biomas.zip')fs.copyFileSync(zip,dir+'1-biomas.zip');
const html=execFileSync('python',['-c',"import sys,zipfile; z=zipfile.ZipFile(sys.argv[1]); n=[n for n in z.namelist() if not n.endswith('/')]; assert len(n)==1 and n[0].lower().endswith('.html'); sys.stdout.buffer.write(z.read(n[0]))",dir+'1-biomas.zip'],{maxBuffer:40*1024*1024}).toString('utf8');
const block=id=>{const m=html.match(new RegExp('<script\\b[^>]*\\bid=["\\\']'+id+'["\\\'][^>]*>([\\s\\S]*?)<\\/script>','i'));if(!m)throw Error('Missing lab block '+id);return zlib.gunzipSync(Buffer.from(m[1].trim(),'base64'));};
const source=block('assetData'),plans=JSON.parse(block('repairData')),bridgeSource=JSON.parse(block('bridgeData')),original=readGlb(source);assert.equal(original.json.meshes.length,40);assert.equal(original.json.skins?.length??0,0);assert.equal(original.json.animations?.length??0,0);
const functions={repair:html.slice(html.indexOf('function repairGeometry('),html.indexOf('function effectiveBridgeData(')),protect:html.slice(html.indexOf('function protectBridgeBackfaces('),html.indexOf('function prepareModels('))};
fs.writeFileSync(dir+'recipe-functions.js',functions.repair+functions.protect);fs.writeFileSync(dir+'repairData.json',JSON.stringify(plans));fs.writeFileSync(dir+'bridgeData-original.json',JSON.stringify(bridgeSource));
const repair=vm.runInNewContext('('+functions.repair.trim()+')',{THREE}),protect=vm.runInNewContext('('+functions.protect.trim()+')',{THREE,repairPlans:plans,REPAIR_MODES:{fixed:{fixed:true}},repairMode:'fixed'});
const parseJson=structuredClone(original.json);function stripTextures(o){if(!o||typeof o!=='object')return;for(const k of Object.keys(o))if(k.endsWith('Texture'))delete o[k];else stripTextures(o[k]);}stripTextures(parseJson.materials);delete parseJson.images;delete parseJson.textures;
const gltf=await new GLTFLoader().parseAsync(writeGlb(parseJson,original.bin).buffer,''),models=Array(40),totals={originalFaces:0,faces:0,reversed:0,reverseFaces:0,capFaces:0,rimFaces:0};
gltf.scene.traverse(o=>{if(!o.isMesh)return;const i=o.userData.cropIndex*5+o.userData.stage-1;assert.ok(Number.isInteger(i)&&i>=0&&i<40);assert.equal(models[i],undefined);o.geometry.setAttribute('iGrowth',new THREE.InstancedBufferAttribute(new Float32Array(4),4));o.geometry=repair(o.geometry,plans.models[i]);models[i]={mesh:o,geo:o.geometry};for(const k of Object.keys(totals))totals[k]+=o.geometry.userData.repair[k];});assert.equal(models.filter(Boolean).length,40);
const effective={...bridgeSource,models:bridgeSource.models.map((r,i)=>({...r,vertices:models[i].geo.attributes.position.count,faces:models[i].geo.index.count/3,faceLabels:models[i].geo.userData.faceSource.map(f=>f>=0?r.faceLabels[f]:plans.models[i].caps[-f-1].label)}))};
function writer(template){const json=structuredClone(template),views=[],accessors=[],chunks=[];let size=0;function append(b){const offset=size;chunks.push({offset,b});size+=Math.ceil(b.byteLength/4)*4;return offset;}
 function attribute(array,itemSize,index=false){const b=new Uint8Array(array.buffer,array.byteOffset,array.byteLength),v=views.length;views.push({buffer:0,byteOffset:append(b),byteLength:b.length,target:index?34963:34962});const a={bufferView:v,componentType:index?(array instanceof Uint16Array?5123:5125):5126,count:array.length/itemSize,type:['','SCALAR','VEC2','VEC3','VEC4'][itemSize]};if(!index&&itemSize===3){a.min=[Infinity,Infinity,Infinity];a.max=[-Infinity,-Infinity,-Infinity];for(let i=0;i<array.length;i++) {const k=i%3;a.min[k]=Math.min(a.min[k],array[i]);a.max[k]=Math.max(a.max[k],array[i]);}}accessors.push(a);return accessors.length-1;}
 function finish(){json.accessors=accessors;json.bufferViews=views;json.buffers=[{byteLength:size}];const bin=new Uint8Array(size);for(const {offset,b}of chunks)bin.set(b,offset);return writeGlb(json,bin);}
 return{json,views,append,attribute,finish};}
const steady=writer(original.json);for(const material of steady.json.materials??[]){material.doubleSided=false;const pbr=material.pbrMetallicRoughness??={};pbr.metallicFactor=0;pbr.roughnessFactor=.91;delete pbr.metallicRoughnessTexture;if(material.normalTexture)material.normalTexture.scale=.48;}
for(const image of steady.json.images??[]){const view=original.json.bufferViews[image.bufferView],b=original.bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength);image.bufferView=steady.views.length;steady.views.push({buffer:0,byteOffset:steady.append(b),byteLength:b.length});}
for(let mi=0;mi<steady.json.meshes.length;mi++){const m=steady.json.meshes[mi],o=models.find(r=>r.mesh.name===m.name)?.mesh;if(!o)throw Error('Mesh identity missing '+m.name);assert.equal(m.primitives.length,1);assert.equal(m.primitives[0].targets,undefined);const geo=o.geometry,p=m.primitives[0];p.attributes={POSITION:steady.attribute(geo.attributes.position.array,3),NORMAL:steady.attribute(geo.attributes.normal.array,3),TEXCOORD_0:steady.attribute(geo.attributes.uv.array,2)};p.indices=steady.attribute(geo.index.array,1,true);}
const steadyBytes=steady.finish(),steadySha=sha(steadyBytes);fs.writeFileSync('public/assets/'+steadySha+'.glb',steadyBytes);
// Use the existing identical regional-driver construction, then apply the lab's
// authored protection before attaching any dynamic per-instance attribute.
const scene=new THREE.Scene(),batch=createCropBatch(scene,{capabilities:{getMaxAnisotropy:()=>1}},gltf,effective,1),templates=scene.children.filter(m=>m.name.startsWith('puente_'));assert.equal(templates.length,32);
const bridgeWriter=writer({asset:{version:'2.0',generator:'User CULT V4 exact offline bridge bake'},scene:0,scenes:[{nodes:[]}],nodes:[],meshes:[]}),bridgeRecords=[];
function indexExactCorners(geo){
 const entries=Object.entries(geo.attributes),count=geo.attributes.position.count,source=entries.map(([name,a])=>({name,size:a.itemSize,bits:new Uint32Array(a.array.buffer,a.array.byteOffset,a.array.length),out:new Uint32Array(a.array.length)})),lanes=source.reduce((n,a)=>n+a.size,0),key=Buffer.alloc(lanes*4),map=new Map(),indices=new Uint32Array(count);let unique=0;
 for(let vi=0;vi<count;vi++){let lane=0;for(const a of source)for(let k=0;k<a.size;k++)key.writeUInt32LE(a.bits[vi*a.size+k],lane++*4);const id=key.toString('base64');let index=map.get(id);if(index===undefined){index=unique++;map.set(id,index);for(const a of source)for(let k=0;k<a.size;k++)a.out[index*a.size+k]=a.bits[vi*a.size+k];}indices[vi]=index;}
 for(const a of source){const floats=new Float32Array(a.out.buffer,0,unique*a.size);for(let vi=0;vi<count;vi++)for(let k=0;k<a.size;k++)assert.equal(a.out[indices[vi]*a.size+k],a.bits[vi*a.size+k]);geo.setAttribute(a.name,new THREE.BufferAttribute(floats,a.size));}geo.setIndex(new THREE.BufferAttribute(unique<=65535?new Uint16Array(indices):indices,1));return{expandedCorners:count,indexedVertices:unique,allCornerAttributeBitsPreserved:true};
}
for(const pair of effective.pairs){const a=models[pair.a].mesh.userData,index=a.cropIndex*4+a.stage-1,mesh=templates.find(m=>m.name===`puente_${a.crop}_${a.stage}_${a.stage+1}`);assert.ok(mesh);mesh.geometry.deleteAttribute('iBridge');protect(mesh.geometry,index);const indexing=indexExactCorners(mesh.geometry),attrs={};for(const [name,semantic]of [['position','POSITION'],['normal','NORMAL'],['uv','TEXCOORD_0'],['aRoot','_AROOT'],['aPeerRoot','_APEERROOT'],['aSpin','_ASPIN'],['aPart','_APART']]){const attr=mesh.geometry.getAttribute(name);attrs[semantic]=bridgeWriter.attribute(attr.array,attr.itemSize);}
 const id=bridgeWriter.json.meshes.length;bridgeWriter.json.meshes.push({name:mesh.name,primitives:[{attributes:attrs,indices:bridgeWriter.attribute(mesh.geometry.index.array,1,true),mode:4}],extras:{bridgeIndex:index,a:pair.a,b:pair.b}});bridgeWriter.json.nodes.push({mesh:id,name:mesh.name,extras:{bridgeIndex:index,a:pair.a,b:pair.b}});bridgeWriter.json.scenes[0].nodes.push(id);bridgeRecords.push({index,name:mesh.name,a:pair.a,b:pair.b,vertices:mesh.geometry.attributes.position.count,...indexing,reverseFaces:mesh.geometry.userData.transitionReverseFaces??0});}
const bridgeBytes=bridgeWriter.finish(),bridgeSha=sha(bridgeBytes);fs.writeFileSync('public/assets/'+bridgeSha+'.glb',bridgeBytes);
const manifest={version:4,source:'Bioma_Cultivos_Lab_V4_Culling.html',zipSha256:sha(fs.readFileSync(dir+'1-biomas.zip')),htmlSha256:sha(Buffer.from(html)),assetDataSha256:sha(source),recipeSha256:sha(Buffer.from(functions.repair+functions.protect)),repairDataSha256:sha(block('repairData')),bridgeDataSha256:sha(block('bridgeData')),steady:{url:'/assets/'+steadySha+'.glb',sha256:steadySha,bytes:steadyBytes.length,models:40,...totals},bridges:{url:'/assets/'+bridgeSha+'.glb',sha256:bridgeSha,bytes:bridgeBytes.length,models:32,records:bridgeRecords},geometryRecipe:'Verbatim user V4 repairGeometry and protectBridgeBackfaces; unchanged region drivers before baking; no index reordering',materialRecipe:{side:'FrontSide',shadowSide:'FrontSide',metalness:0,roughness:.91,normalScale:[.48,.48]},faceSources:models.map(m=>m.geo.userData.faceSource),effectiveBridgeModels:effective.models};
fs.mkdirSync('content/manifests',{recursive:true});fs.writeFileSync('content/manifests/crops-v4.json',JSON.stringify(manifest,null,2)+'\n');fs.writeFileSync('public/content/crop-bridges.json',JSON.stringify({...effective,bakedAsset:manifest.bridges.url,recipeVersion:4})+'\n');
const modelList=JSON.parse(fs.readFileSync('public/content/models.json'));const crop=modelList.find(m=>m.source.includes('Cultivos'));crop.url=manifest.steady.url;crop.source='Bioma_Cultivos_Lab_V4_Culling.html#assetData+repairData';crop.extras={recipeVersion:4};fs.writeFileSync('public/content/models.json',JSON.stringify(modelList)+'\n');
const assets=JSON.parse(fs.readFileSync('content/manifests/assets.json'));for(const item of [manifest.steady,manifest.bridges])if(!assets.resources.some(r=>r.url===item.url))assets.resources.push({url:item.url,sha256:item.sha256,bytes:item.bytes,source:manifest.source,encoding:'glb',derived:true});
if(!assets.sources.some(s=>s.file===manifest.source))assets.sources.push({file:manifest.source,sha256:manifest.htmlSha256,bytes:Buffer.byteLength(html),archive:dir+'1-biomas.zip',archiveSha256:manifest.zipSha256,payloads:[{id:'repairData',path:dir+'repairData.json'},{id:'bridgeData',path:dir+'bridgeData-original.json'},{id:'bakedStates',url:manifest.steady.url},{id:'bakedBridges',url:manifest.bridges.url}],code:[dir+'recipe-functions.js']});fs.writeFileSync('content/manifests/assets.json',JSON.stringify(assets,null,2)+'\n');
batch.dispose();console.log(JSON.stringify({status:'LAB_V4_BAKED',steadySha,steadyBytes:steadyBytes.length,bridgeSha,bridgeBytes:bridgeBytes.length,totals,bridgeModels:32}));
