"""Build the shared browser catalog from the reviewable bilingual TSV."""
from pathlib import Path
import json
root=Path(__file__).resolve().parents[1]
messages={}
for line_number,line in enumerate((root/'public/i18n/translations.tsv').read_text(encoding='utf-8').splitlines(),1):
    if not line.strip() or line.startswith('#'): continue
    source,translation=line.split('\t',1)
    if source in messages: raise ValueError(f'Duplicate source on line {line_number}: {source}')
    if not source.strip() or not translation.strip(): raise ValueError(f'Empty message on line {line_number}')
    messages[source]=translation
(root/'public/i18n/messages.js').write_text('// Generated by tools/build_i18n_catalog.py from translations.tsv.\nexport const messages = '+json.dumps(messages,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')
print(f'{len(messages)} bilingual messages')
