import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {prepareAnimalClips} from '../src/rendering/animal-actions.js';
const root=new URL('../',import.meta.url),read=p=>JSON.parse(readFileSync(new URL(p,root)));
const workers=read('public/content/worker-actions.json'),animals=read('public/content/animal-actions.json').animals;
export function geometryOnly(bytes){
 const length=bytes.readUInt32LE(12),doc=JSON.parse(bytes.subarray(20,20+length));
 for(const m of doc.materials??[]){delete m.normalTexture;delete m.occlusionTexture;delete m.emissiveTexture;delete m.pbrMetallicRoughness?.baseColorTexture;delete m.pbrMetallicRoughness?.metallicRoughnessTexture;}
 const json=Buffer.from(JSON.stringify(doc)),size=Math.ceil(json.length/4)*4,tail=bytes.subarray(20+length),out=Buffer.alloc(20+size+tail.length,32);bytes.copy(out,0,0,20);out.writeUInt32LE(out.length,8);out.writeUInt32LE(size,12);json.copy(out,20);tail.copy(out,20+size);return out.buffer.slice(out.byteOffset,out.byteOffset+out.length);
}
export function measureFootsteps(scene,clip){
 const mixer=new THREE.AnimationMixer(scene),samples=Math.ceil(clip.duration*120),feet=['Left','Right'].map(side=>{let bone;scene.traverse(o=>{if(o.isBone&&o.name.endsWith(side+'ToeBase'))bone=o;});if(!bone)throw Error('Missing native toe bone: '+side);return {side,bone,points:[]};});
 mixer.clipAction(clip).play();
 for(let i=0;i<samples;i++){mixer.setTime(i*clip.duration/samples);scene.updateMatrixWorld(true);for(const foot of feet)foot.points.push(foot.bone.getWorldPosition(new THREE.Vector3()).toArray());}
 const contacts=[],heights={};
 for(const foot of feet){
  const min=Math.min(...foot.points.map(p=>p[1])),max=Math.max(...foot.points.map(p=>p[1])),threshold=min+.2*(max-min);heights[foot.side]={min,max,threshold};
  if(max-min<1e-5)continue;
  for(let i=0;i<samples;i++){
   const previous=foot.points[(i+samples-1)%samples],current=foot.points[i];
   if(previous[1]>threshold&&current[1]<=threshold){const fraction=(previous[1]-threshold)/(previous[1]-current[1]),time=((i-1+fraction+samples)%samples)*clip.duration/samples;contacts.push({foot:foot.side,time,point:[THREE.MathUtils.lerp(previous[0],current[0],fraction),THREE.MathUtils.lerp(previous[2],current[2],fraction)]});}
  }
 }
 mixer.stopAllAction();contacts.sort((a,b)=>a.time-b.time);
 if(!contacts.length)throw Error('No native foot contacts: '+clip.name);
 return {duration:clip.duration,samples,heights,contacts};
}
async function main(){
 const sources={};
 for(const [id,library] of [...Object.entries(workers),...Object.entries(animals)]){
  const animal=id in animals,bytes=readFileSync(new URL('public'+library.url,root)),gltf=await new GLTFLoader().parseAsync(geometryOnly(bytes),'');
  const names=animal?['Walking','Running']:['Walk_Skip','Run','Carry_Crate'],clips=animal?prepareAnimalClips(gltf.animations):gltf.animations;
  sources[id]={url:library.url,sha256:createHash('sha256').update(bytes).digest('hex'),clips:Object.fromEntries(names.map(name=>[name,measureFootsteps(gltf.scene,clips.find(c=>c.name===name))]))};
 }
 const data={schema:'wg-footsteps/1',method:'120 Hz native ToeBase height sampling; descending crossing of lowest 20% of each foot vertical range; in-place native clips; presentation contacts only',sources};
 for(const p of ['content/manifests/footsteps.json','public/content/footsteps.json'])writeFileSync(new URL(p,root),JSON.stringify(data,null,2)+'\n');
 writeFileSync(new URL('src/rendering/footsteps-data.js',root),'// Generated by tools/calibrate_footsteps.mjs from original GLB toe trajectories.\nexport const FOOTSTEPS = '+JSON.stringify(data,null,2)+';\n');
 console.log(JSON.stringify(Object.fromEntries(Object.entries(sources).map(([id,s])=>[id,Object.fromEntries(Object.entries(s.clips).map(([name,c])=>[name,c.contacts.length]))]))));
}
if(process.argv[1]&&pathToFileURL(process.argv[1]).href===import.meta.url)await main();
