// Native labs normalize timestamps and keep each complete slash/combo non-looping.
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
const assets=JSON.parse(readFileSync(new URL('../content/manifests/assets.json',import.meta.url)));
const fragments={warthog:'Facoquero',hyena:'Hiena',buffalo:'Bufalo',lion:'Leon',rhino:'Rinoceronte'};
const actions={};
for(const [species,fragment] of Object.entries(fragments)){
  const model=assets.models.find(m=>m.source.includes(fragment));
  const bytes=readFileSync(new URL('../public'+model.url,import.meta.url));
  const jsonLength=bytes.readUInt32LE(12),doc=JSON.parse(bytes.subarray(20,20+jsonLength)),bin=bytes.subarray(28+jsonLength);
  const clips={};
  for(const animation of doc.animations){
    let first=Infinity,last=0;
    for(const sampler of animation.samplers){
      const accessor=doc.accessors[sampler.input],view=doc.bufferViews[accessor.bufferView],offset=(view.byteOffset??0)+(accessor.byteOffset??0);
      first=Math.min(first,bin.readFloatLE(offset));last=Math.max(last,bin.readFloatLE(offset+(accessor.count-1)*4));
    }
    clips[animation.name]={duration:last-first,start:first,loop:['Walking','Running'].includes(animation.name)};
  }
  for(const name of ['Walking','Running','Right_Hand_Sword_Slash','Charged_Upward_Slash','Weapon_Combo','Weapon_Combo_2'])
    if(!(clips[name]?.duration>0))throw new Error(`Missing native clip ${species}/${name}`);
  actions[species]={url:model.url,source:model.source,sha256:createHash('sha256').update(bytes).digest('hex'),clips};
}
const manifest={schema:'wg-animal-actions/1',logicalMarker:'Complete native clip. Original bestiary labs encode no logical damage/contact markers; decorative contacts do not drive damage.',animals:actions};
for(const path of ['content/manifests/animal-actions.json','public/content/animal-actions.json'])writeFileSync(new URL('../'+path,import.meta.url),JSON.stringify(manifest,null,2)+'\n');
writeFileSync(new URL('../src/simulation/animal-actions-data.js',import.meta.url),'// Generated by tools/calibrate_animal_actions.mjs from the five original bestiary GLBs.\nexport const ANIMAL_ACTIONS = '+JSON.stringify(manifest,null,2)+';\n');
console.log(JSON.stringify(Object.fromEntries(Object.entries(actions).map(([species,a])=>[species,Object.fromEntries(Object.entries(a.clips).map(([name,c])=>[name,c.duration]))])),null,2));
