// Calibrate one long trip against native village-to-center routes in world metres.
import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {Navigation,BIOME_IDS} from '../src/world/navigation.js';
import {findInitialLocation} from '../src/world/villages.js';
const read=name=>JSON.parse(readFileSync(new URL(`../public/content/${name}.json`,import.meta.url),'utf8'));
const libraries=read('worker-actions'),villages=read('villages'),sources=[];
for(const library of Object.values(libraries)){
  const file=library.exporterScripts[0].path,bytes=readFileSync(new URL('../'+file,import.meta.url));
  const text=bytes.toString('utf8'),match=text.match(/travelTime\?\?t\)\*\(isRun\?([\d.]+):([\d.]+)\)\/([\d.]+)/);
  if(!match)throw new Error('Missing native route calibration: '+file);
  sources.push({profile:library.profile,file,sha256:createHash('sha256').update(bytes).digest('hex'),
    walkMetresPerSecond:Number(match[2]),runMetresPerSecond:Number(match[1]),routeRadiusMetres:Number(match[3]),fallSeconds:library.actions.Fall.duration});
}
if(sources.some(s=>s.walkMetresPerSecond!==sources[0].walkMetresPerSecond||s.runMetresPerSecond!==sources[0].runMetresPerSecond))
  throw new Error('Worker profiles require separate native speed calibration');
const samples=[];
for(const payload of villages){
  const nav=new Navigation(712,'sabana',read('biome-'+BIOME_IDS.sabana).profile);
  const location=findInitialLocation(nav,payload),state={villages:[location],structures:[],spells:[],suppressed:location.suppress};
  nav.setState(state);
  const destination={x:location.center.x+3.4,z:location.center.z};
  const path=nav.path(location.entry,destination,.28,null,true);
  if(!path)throw new Error('Native reference route is unreachable');
  let last=location.entry,distance=0;
  for(const point of path){distance+=Math.hypot(point.x-last.x,point.z-last.z);last=point;}
  samples.push({culture:payload.id,seed:712,biome:'sabana',entry:location.entry,destination,distanceMetres:distance});
}
const sorted=samples.map(s=>s.distanceMetres).sort((a,b)=>a-b),longTripMetres=sorted[Math.floor(sorted.length/2)];
const calibration={schema:'wg-worker-locomotion/1',method:'Native lab route speeds; median of the five native initial village-to-center walking paths on Sabana/712 at production scale.',
  walkMetresPerSecond:sources[0].walkMetresPerSecond,runMetresPerSecond:sources[0].runMetresPerSecond,longTripMetres,sources,samples};
writeFileSync(new URL('../content/manifests/worker-locomotion.json',import.meta.url),JSON.stringify(calibration,null,2)+'\n');
writeFileSync(new URL('../src/simulation/locomotion-calibration.js',import.meta.url),'// Generated by tools/calibrate_locomotion.mjs from original labs and native world routes.\nexport const LOCOMOTION = '+JSON.stringify(calibration,null,2)+';\n');
console.log(JSON.stringify({walk:calibration.walkMetresPerSecond,run:calibration.runMetresPerSecond,longTripMetres,samples:samples.map(s=>({culture:s.culture,distance:s.distanceMetres}))}));
