import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {pathToFileURL} from 'node:url';
const root=new URL('../',import.meta.url),read=p=>readFileSync(new URL(p,root)),hash=b=>createHash('sha256').update(b).digest('hex');
const number='([.0-9]+)';
function captures(text,pattern,label){const match=text.match(pattern);if(!match)throw Error('Missing original marker: '+label);return match.slice(1).map(Number);}
export function inverseSmoothstep(value){let lo=0,hi=1;for(let i=0;i<60;i++){const t=(lo+hi)/2;if(t*t*(3-2*t)<value)lo=t;else hi=t;}return (lo+hi)/2;}
export function calibrateFarmActions(){
 const libraries=JSON.parse(read('public/content/worker-actions.json')),sources={};
 for(const [profile,library] of Object.entries(libraries)){
  const code=library.exporterScripts[0],bytes=read(code.path),source=bytes.toString('utf8'),glb=read('public'+library.url);
  if(hash(bytes)!==code.sha256||hash(glb)!==library.sha256)throw Error('Original source hash mismatch: '+profile);
  const [sowStart]=captures(source,new RegExp('sow=down\\*smooth\\('+number+','+number+',p\\)'),'sow');
  const [seedDrop]=captures(source,new RegExp("name==='plant'&&p>"+number+"&&p<"+number),'seeds');
  const [harvestContact]=captures(source,new RegExp("name==='harvest'&&p>"+number+"&&p<"+number),'harvest');
  const [riseStart,riseEnd,fallStart,fallEnd]=captures(source,new RegExp("let f=name==='water'\\?smooth\\("+number+','+number+",p\\)\\*\\(1-smooth\\("+number+','+number+",p\\)\\):0"),'watering tilt');
  const [threshold]=captures(source,new RegExp('if\\(f>'+number+'\\)'),'visible water');
  const t=inverseSmoothstep(threshold),plant=library.actions.Plant.duration,harvest=library.actions.Harvest.duration,water=library.actions.Water.duration;
  if(!source.includes("plant:{")&&!source.includes('plant: {'))throw Error('Missing original Plant definition');
  sources[profile]={url:library.url,sha256:library.sha256,script:code.path,scriptSha256:code.sha256,
   durations:{Plant:plant,Harvest:harvest,Water:water},fractions:{sowStart,seedDrop,harvestContact,pourStart:riseStart+(riseEnd-riseStart)*t,pourEnd:fallStart+(fallEnd-fallStart)*inverseSmoothstep(1-threshold)},
   markers:{sowStart:sowStart*plant,seedDrop:seedDrop*plant,harvestContact:harvestContact*harvest,pourStart:(riseStart+(riseEnd-riseStart)*t)*water,pourEnd:(fallStart+(fallEnd-fallStart)*inverseSmoothstep(1-threshold))*water},
   waterGate:{riseStart,riseEnd,fallStart,fallEnd,threshold},initialTool:library.actions.Plant.defaultAccessory==='none'?'hands':library.actions.Plant.defaultAccessory,hoeDuringPlant:library.actions.Plant.defaultAccessory==='hoe'};
 }
 return {schema:'wg-farm-actions/1',method:'Authored native lab gesture/effect gates, traced source and original GLB hashes; seconds are native clip time before worker speed scaling. Calibration data only, not audio integration.',sources};
}
if(process.argv[1]&&pathToFileURL(process.argv[1]).href===import.meta.url){
 const data=calibrateFarmActions();writeFileSync(new URL('content/manifests/farm-actions.json',root),JSON.stringify(data,null,2)+'\n');
 writeFileSync(new URL('src/audio/farm-actions-data.js',root),'// Generated by tools/calibrate_farm_actions.mjs from original authored worker phases.\nexport const FARM_ACTIONS = '+JSON.stringify(data,null,2)+';\n');
 console.log(JSON.stringify(Object.fromEntries(Object.entries(data.sources).map(([id,s])=>[id,s.markers]))));
}
