// Separate Front training snapshot; retain accepted Double-control source intact.
import fs from 'node:fs';import crypto from 'node:crypto';
const input='tests/browser/frontside-crop-local-stem-double.js';let source=fs.readFileSync(input,'utf8');
const hash=text=>crypto.createHash('sha256').update(text).digest('hex'),inputSha256=hash(source);
if(inputSha256!=='b37310be270cb8280e1b11b56b56f86258778d18809c3315229a78d778dac55d')throw Error('Frozen Double fixture changed');
function replaceOnce(before,after){if(source.split(before).length!==2)throw Error('Unexpected Double source: '+before.slice(0,80));source=source.replace(before,after);}
source=source.replaceAll('localStemDoubleQuality','localStemFrontQuality');
replaceOnce("const originalMaterial=mesh.material,materials=(reverseFaces.length?[0,1,2]:[0,1]).map(group=>{const material=originalMaterial.clone();material.onBeforeCompile=originalMaterial.onBeforeCompile;material.customProgramCacheKey=originalMaterial.customProgramCacheKey;material.side=THREE.DoubleSide;", "const originalMaterial=mesh.material,materials=(reverseFaces.length?[0,1,2]:[0,1]).map(group=>{const material=originalMaterial.clone();material.onBeforeCompile=originalMaterial.onBeforeCompile;material.customProgramCacheKey=originalMaterial.customProgramCacheKey;material.side=arm===3&&group===0?THREE.FrontSide:THREE.DoubleSide;");
replaceOnce("report.arms=['original young maize Double','indexed original control Double','native young-maize stem/others grouped Double','same grouped Double repeated'];report.localStemDoubleOnly=true;", "report.arms=['original young maize Double','indexed original control Double','native young-maize stem/others grouped Double','same245 stem faces Front with original DOUBLE_SIDED recipe; other1009 faces Double'];report.localStemDoubleOnly=false;report.localStemFrontTraining=true;");
replaceOnce("All four arms DoubleSide: no culling/reverse/shader edits, no FrontSide interpretation. Only maiz_02_joven grouped, ALL bridges/other native meshes unchanged. Geometry filter is local, not full-component closure or visual approval.", "Only native young-maize driver1 group changes to FrontSide in arm3; source DOUBLE_SIDED recipe retained, other1009 faces and ALL bridges/other native meshes Double. No new/reverse face or attribute edit. This reused TRAINING camera is not independent acceptance; shadowFront and netGPU remain separate pending gates.");
replaceOnce(" campaign:for(const {growth,clock,biome,night,elevation,azimuth} of cases){", " document.querySelector('#arms').textContent=report.arms.join(' → ')+'. TRAINING controlado; no aprobación ni benchmark.';\n const sourceTarget=rigs[0].group.getObjectByName('maiz_02_joven'),sourceIndices=sourceTarget.geometry.index.array,localLabels=data.models[1].faceLabels;\n report.localStemPreDrawContracts=rigs.map((rig,arm)=>{const target=rig.group.getObjectByName('maiz_02_joven');const materials=Array.isArray(target.material)?target.material:[target.material];if(arm<2){if(materials.some(m=>m.side!==THREE.DoubleSide))throw Error('Original Double control material changed');return{arm,mesh:target.name,colorSides:materials.map(m=>m.side),indexCount:target.geometry.index.count};}\n const map=target.geometry.userData.qaTriangleSourceFaces,labels=target.geometry.userData.qaFaceLabels,index=target.geometry.index.array;if(map.length!==1254||new Set(map).size!==1254||labels.filter(x=>x===1).length!==245||target.geometry.groups.length!==2)throw Error('Young maize face/group contract changed');for(let face=0;face<map.length;face++){if(labels[face]!==localLabels[map[face]])throw Error('Source faceLabel correspondence changed');for(let lane=0;lane<3;lane++)if(index[face*3+lane]!==sourceIndices[map[face]*3+lane])throw Error('Source face/winding changed');}\n if(materials.length!==2||materials[0].side!==(arm===3?THREE.FrontSide:THREE.DoubleSide)||materials[1].side!==THREE.DoubleSide||materials.some(m=>m.shadowSide!==THREE.DoubleSide)||arm===3&&!Object.hasOwn(materials[0].defines??{},'DOUBLE_SIDED'))throw Error('Front/Double/retained source shading-side contract changed');return{arm,mesh:target.name,sourceFaceIds:map.slice(0,245),colorSides:materials.map(m=>m.side),shadowSides:materials.map(m=>m.shadowSide),sourceDoubleShaderDefine:arm===3?Object.hasOwn(materials[0].defines,'DOUBLE_SIDED'):null,indexCount:index.length,groups:target.geometry.groups};});\n renderer.info.autoReset=false;report.referenceDrawInfo=[];\n campaign:for(const {growth,clock,biome,night,elevation,azimuth} of cases){");
replaceOnce("shaderContractAudit?.frame('arm'+arm+'-reference');renderer.render(scene,camera);gl.readPixels", "shaderContractAudit?.frame('arm'+arm+'-reference');renderer.info.reset();renderer.render(scene,camera);report.referenceDrawInfo.push({arm,...renderer.info.render,meaning:'Logical submissions include native color/shadow draws, not GPU elapsed time or invocation count.'});gl.readPixels");
replaceOnce("gl.readPixels(0,0,size,size,gl.RGBA,gl.UNSIGNED_BYTE,pixels[arm]);if(arm===0)", "gl.readPixels(0,0,size,size,gl.RGBA,gl.UNSIGNED_BYTE,pixels[arm]);report.frontArmRendered=arm===3?true:(report.frontArmRendered??false);if(arm===2){const checks=[1,2].map(i=>({arm:i,...colorMetrics(pixels[0],pixels[i],envelope)}));if(checks.some(c=>!c.passes)){report.preFrontInvalidDouble={growth,clock,biome,night,elevation,azimuth,comparisons:checks,meaning:'Double controls failed; Front arm NOT rendered or interpreted'};stop=true;break;}}if(arm===0)");
replaceOnce("const materials=Array.isArray(target.material)?target.material:[target.material];if(arm<2)", "const materials=Array.isArray(target.material)?target.material:[target.material];for(const name of ['position','normal','uv']){const a=target.geometry.getAttribute(name),b=sourceTarget.geometry.getAttribute(name);if(a.itemSize!==b.itemSize||a.count!==b.count||a.normalized!==b.normalized)throw Error('Native static attribute layout changed');for(let vertex=0;vertex<a.count;vertex++)for(const lane of ['getX','getY','getZ'].slice(0,a.itemSize)){const av=a[lane](vertex),bv=b[lane](vertex);if(!Number.isFinite(av)||!Object.is(av,bv))throw Error('Native source PN/UV values changed');}}if(arm<2)");
source=source.replace('Isolated native young-maize Double-only training requires limit1','Isolated native young-maize Front training requires limit1');
const output='tests/browser/frontside-crop-local-stem-front.js';fs.writeFileSync(output,source);
fs.writeFileSync('docs/qa/frontside-model-pilot/local-stem-front-fixture-receipt.json',JSON.stringify({status:'FRONT_TRAINING_NOT_APPROVED',input,inputSha256,output,outputSha256:hash(source),sourceTriangles:1254,frontStemTriangles:245,newTriangles:0,shadowSide:'Double isolation; Front shadow gate not passed'},null,2)+'\n');
console.log(output,hash(source));
