// Read-only camera-independent topology diagnostics. Region boundaries may be
// internal interfaces, and closedness is never a universal FrontSide gate.
import fs from 'node:fs';import crypto from 'node:crypto';import {readGlb} from './glb-container.mjs';
const folder='docs/qa/frontside-model-pilot/',receipt=JSON.parse(fs.readFileSync(folder+'maize-blender-leaf-reduction-diagnostic.json')),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),archive=fs.readFileSync(receipt.archive),raw=fs.readFileSync('public/assets/'+receipt.sourceSha256+'.glb');if(sha(archive)!==receipt.archiveSha256||sha(raw)!==receipt.sourceSha256)throw Error('Immutable identity mismatch');const payload=JSON.parse(archive),{json,bin}=readGlb(raw),node=json.nodes.find(n=>n.name===receipt.mesh),primitive=json.meshes[node.mesh].primitives[0];
function attribute(index,lanes){const a=json.accessors[index],v=json.bufferViews[a.bufferView],types={5123:[2,'getUint16'],5126:[4,'getFloat32']},[bytes,method]=types[a.componentType]??[];if(!bytes||a.sparse||v.extensions)throw Error('Unsupported raw accessor');const data=new DataView(bin.buffer,bin.byteOffset,bin.byteLength),stride=v.byteStride??lanes*bytes,start=(v.byteOffset??0)+(a.byteOffset??0);return Array.from({length:a.count},(_,i)=>Array.from({length:lanes},(_,k)=>data[method](start+i*stride+k*bytes,true)));}
const pos=attribute(primitive.attributes.POSITION,3),norm=attribute(primitive.attributes.NORMAL,3),uv=attribute(primitive.attributes.TEXCOORD_0,2),indices=attribute(primitive.indices,1).flat(),models=JSON.parse(fs.readFileSync('public/content/crop-bridges.json')).models,sourceMeta=models.find(m=>m.name===receipt.mesh)??models[4];if(sourceMeta.vertices!==pos.length||sourceMeta.faces*3!==indices.length||sourceMeta.faceLabels.length!==sourceMeta.faces)throw Error('Source label/index contract mismatch');const original=Array.from({length:indices.length/3},(_,face)=>indices.slice(face*3,face*3+3).map(i=>[...pos[i],...norm[i],...uv[i]]));
const vector=(a,b)=>a.map((v,i)=>v-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((sum,v,i)=>sum+v*b[i],0),key=row=>Array.from(Float32Array.from(row.slice(0,3)),v=>v===0?0:v).join(',');
function audit(corners,labels){const map=new Map(),globalEdges=new Map();let nonfinite=0,zeroNormals=0;
 for(let face=0;face<corners.length;face++){const label=labels[face],row=map.get(label)??{label,faces:0,vertices:new Map(),edges:new Map(),volume6:0,zeroAreaFaces:0,normalsOpposeWinding:0};map.set(label,row);row.faces++;const points=corners[face].map(c=>c.slice(0,3)),keys=corners[face].map(key),n=cross(vector(points[1],points[0]),vector(points[2],points[0]));if(dot(n,n)===0)row.zeroAreaFaces++;if(dot(n,corners[face].map(c=>c.slice(3,6)).reduce((a,b)=>a.map((v,i)=>v+b[i]),[0,0,0]))<0)row.normalsOpposeWinding++;row.volume6+=dot(points[0],cross(points[1],points[2]));
  corners[face].forEach((c,i)=>{row.vertices.set(keys[i],points[i]);nonfinite+=c.filter(v=>!Number.isFinite(v)).length;zeroNormals+=c.slice(3,6).every(v=>v===0);});for(let i=0;i<3;i++){const a=keys[i],b=keys[(i+1)%3],edge=a<b?a+'|'+b:b+'|'+a,sign=a<b?1:-1,r=row.edges.get(edge)??{count:0,balance:0};r.count++;r.balance+=sign;row.edges.set(edge,r);const g=globalEdges.get(edge)??{count:0,labels:new Set()};g.count++;g.labels.add(label);globalEdges.set(edge,g);}}
 const regions=[...map.values()].map(r=>{const boundary=[...r.edges].filter(([,e])=>e.count===1),nonManifold=[...r.edges.values()].filter(e=>e.count>2).length,inconsistent=[...r.edges.values()].filter(e=>e.count===2&&e.balance!==0).length;return{label:r.label,faces:r.faces,uniqueGeometricVertices:r.vertices.size,boundaryEdges:boundary.length,boundariesCoincidentWithOtherLabels:boundary.filter(([key])=>globalEdges.get(key).labels.size>1).length,nonManifoldEdges:nonManifold,inconsistentPairedWindingEdges:inconsistent,closedConsistent:!boundary.length&&!nonManifold&&!inconsistent,signedVolume:r.volume6/6,signedVolumeMeaning:'Meaningful as enclosed volume only when closed and consistently oriented; otherwise origin-dependent diagnostic.',zeroAreaFaces:r.zeroAreaFaces,normalsOpposeWinding:r.normalsOpposeWinding};});return{faces:corners.length,nonfiniteCornerValues:nonfinite,zeroNormalCorners:zeroNormals,regions,globalBoundaryEdges:[...globalEdges.values()].filter(e=>e.count===1).length,globalNonManifoldEdges:[...globalEdges.values()].filter(e=>e.count>2).length};}
const report={status:'STRUCTURAL_DIAGNOSTIC_NOT_FRONT_OR_VISUAL_APPROVAL',sourceSha256:sha(raw),archiveSha256:sha(archive),positionEquality:'Exact Float32 geometric coordinates; signed zero canonicalized. Normals/UV seams coalesce only for this geometric adjacency diagnostic.',original:audit(original,sourceMeta.faceLabels),derivedForward:audit(payload.corners,payload.faceLabels),limitations:['Labels>=2 select botanical regions, not proven purely planar leaves. Closed region components need separate consideration before blindly duplicating future categories.','Coincident region boundaries can be internal interfaces; no caps, winding changes, normal recalculation or faces selected from cameras.','Exact-edge adjacency does not identify near-coincident/T-junction interfaces or prove material/UV/morph continuity.','Current immutable derivative and historic captures are unchanged; this audit does not approve or automatically reject appearance.']};fs.writeFileSync(folder+'maize-leaf-shared-structural-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,original:report.original.regions,derivedForward:report.derivedForward.regions,finite:[report.original.nonfiniteCornerValues,report.derivedForward.nonfiniteCornerValues]}));
