import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import {youngLeafFrontReportPrefix} from './lib/frontside-young-leaf-front-report.mjs';
const tab=Number(process.argv[2]),expectedCase={926:11,927:15}[tab];assert.ok(Number.isInteger(expectedCase),'Only recorded root926/927 copies are supported');
const origin='C:/Users/PC/source/repos/wild-guardians-africa/.cache/front-young-'+tab,out='docs/qa/frontside-model-pilot/young-front-native-'+tab,sha=b=>crypto.createHash('sha256').update(b).digest('hex');fs.mkdirSync(out,{recursive:true});const files=[];
function retain(name,b){const target=out+'/'+name;if(fs.existsSync(target))assert.equal(sha(fs.readFileSync(target)),sha(b),'No overwrite '+name);else fs.writeFileSync(target,b);files.push({name,bytes:b.length,sha256:sha(b)});}
for(const name of ['report.json','atlas.png','console.json'])retain(name,fs.readFileSync(origin+'/'+name));const r=JSON.parse(fs.readFileSync(out+'/report.json'));assert.equal(youngLeafFrontReportPrefix(r),'crop-young-leaf-front-human');assert.equal(r.viewCaseIndex,expectedCase);assert.equal(r.cleanup.errors.length,0);
const logs=JSON.parse(fs.readFileSync(out+'/console.json')),image=fs.readFileSync(out+'/atlas.png');assert.equal(image.readUInt32BE(16),4096);assert.equal(image.readUInt32BE(20),1024);
const sourceFiles=['tests/browser/frontside-crop-young-leaf-front-review.js','tools/lib/frontside-young-leaf-front-report.mjs','tools/lib/frontside-young-leaf-front-review-cases.mjs'].map(name=>({name,sha256:sha(fs.readFileSync(name))}));assert.equal(sourceFiles[0].sha256,'993e0faee076589bd27ee5d7e793d09eb82bd67a979308799691b5135f5dbf19');
retain('manifest.json',Buffer.from(JSON.stringify({tab,caseIndex:expectedCase,caseId:r.viewCaseId,sourceHead:'8ebe283c4f4c78939ca02bc5eb898598da61e09e',receiptOrigin:'Independent root copy, no claim of separately retained matching rolling POST',files,sourceFiles,console:{warnings:logs.filter(x=>x.level==='warn').length,errors:logs.filter(x=>x.level==='error').length},scope:'Predefined static Front young view; shadows Double isolated. No human-user/all-growth/World/GPU benefit approval.'},null,2)+'\n'));
console.log('Archived immutable native'+tab+' case'+expectedCase+'; source and actual culling schema verified, no automated perceptual decision.');
