// One original maize03→04 bridge, CPU-only. No textures, WebGL or asset export.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import * as THREE from 'three';
import {readGlb} from './glb-container.mjs';import {createCropBatch} from '../src/rendering/crop-batch.js';import {cropSpec} from '../src/simulation/rules.js';import {indexedBridgeControl} from './lib/frontside-indexed-bridge-control.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),raw=fs.readFileSync('public/assets/be4bb7e7eab2149516c1ecc0c364d77c4a62f116c4847cf0ef6f3308dc6180ef.glb');
assert.equal(sha(raw),'be4bb7e7eab2149516c1ecc0c364d77c4a62f116c4847cf0ef6f3308dc6180ef');
const glb=readGlb(raw),types={5123:Uint16Array,5125:Uint32Array,5126:Float32Array},sizes={SCALAR:1,VEC2:2,VEC3:3},sourceScene=new THREE.Scene();
function accessor(id){const a=glb.json.accessors[id],v=glb.json.bufferViews[a.bufferView],Type=types[a.componentType],size=sizes[a.type];assert.ok(Type&&size&&!a.sparse&&!v.extensions&&v.buffer===0);const width=Type.BYTES_PER_ELEMENT*size,stride=v.byteStride??width,array=new Uint8Array(a.count*width);for(let i=0;i<a.count;i++)array.set(glb.bin.subarray((v.byteOffset??0)+(a.byteOffset??0)+i*stride,(v.byteOffset??0)+(a.byteOffset??0)+i*stride+width),i*width);return new THREE.BufferAttribute(new Type(array.buffer),size,!!a.normalized);}
for(const node of glb.json.nodes??[]){if(node.mesh===undefined)continue;const model=glb.json.meshes[node.mesh];assert.equal(model.primitives.length,1);const p=model.primitives[0],geo=new THREE.BufferGeometry();for(const [semantic,name] of [['POSITION','position'],['NORMAL','normal'],['TEXCOORD_0','uv']])geo.setAttribute(name,accessor(p.attributes[semantic]));geo.setIndex(accessor(p.indices));const mesh=new THREE.Mesh(geo,new THREE.MeshStandardMaterial());mesh.name=node.name;mesh.userData=structuredClone(node.extras);sourceScene.add(mesh);}
const bridgeRaw=fs.readFileSync('public/content/crop-bridges.json'),scene=new THREE.Scene(),batch=createCropBatch(scene,{capabilities:{getMaxAnisotropy:()=>8}},{scene:sourceScene},JSON.parse(bridgeRaw),64),mesh=scene.children.find(m=>m.name==='puente_maiz_3_4');assert.ok(mesh);assert.equal(mesh.material.side,THREE.DoubleSide);assert.equal(mesh.customDepthMaterial.side,THREE.DoubleSide);
const original=mesh.geometry,result=indexedBridgeControl(original),indexed=result.geometry,stream=crypto.createHash('sha256');
for(const [name,a] of Object.entries(original.attributes)){if(a.isInstancedBufferAttribute){assert.equal(indexed.getAttribute(name),a);continue;}const sourceBits=new Uint32Array(a.array.buffer,a.array.byteOffset,a.array.length),target=indexed.getAttribute(name),targetBits=new Uint32Array(target.array.buffer,target.array.byteOffset,target.array.length);for(let corner=0;corner<a.count;corner++)for(let lane=0;lane<a.itemSize;lane++)assert.equal(sourceBits[corner*a.itemSize+lane],targetBits[indexed.index.getX(corner)*a.itemSize+lane]);stream.update(name);stream.update(new Uint8Array(a.array.buffer,a.array.byteOffset,a.array.byteLength));}
const plant={id:'qa-bridge-index',species:'maiz',x:2,z:3,rotation:.2,growth:.7325*cropSpec('maiz').growth_seconds};batch.update([plant],12.5,()=>.25);assert.equal(mesh.visible,true);assert.equal(mesh.count,1);assert.equal(batch.sample('maiz',plant.growth).phase,'morph');const material=mesh.material,shadow=mesh.customDepthMaterial;mesh.geometry=indexed;plant.growth=.736*cropSpec('maiz').growth_seconds;batch.update([plant],13,()=>.25);assert.equal(indexed.getAttribute('iBridge'),original.getAttribute('iBridge'));assert.equal(mesh.material,material);assert.equal(mesh.customDepthMaterial,shadow);
const report={status:'SOURCE_BRIDGE_INDEX_CONTROL_CPU_PASS_NOT_VISUAL_OR_GPU_APPROVAL',sourceSha256:sha(raw),bridgeSha256:sha(bridgeRaw),mesh:mesh.name,sourceCornerStreamSha256:stream.digest('hex'),originalCorners:result.originalCorners,uniqueVertices:result.uniqueVertices,originalStaticBytes:result.originalStaticBytes,indexedStaticBytes:result.indexedStaticBytes,indexBytes:indexed.index.array.byteLength,byteReductionPercent:100*(1-result.indexedStaticBytes/result.originalStaticBytes),allStaticCornerBitsEqual:true,liveInstanceAttributeShared:true,materialSide:mesh.material.side,shadowSide:mesh.customDepthMaterial.side,limitations:['Actual original geometry/drivers and native createCropBatch; blank CPU materials without source textures.','Indexing only: original face/corner order and every shader driver preserved. No FrontSide or simplification.','Static typed-array bytes exclude instances, materials, programs, textures and coexistence; no resident GPU/VRAM claim.','GPU interpolation/cache behavior, perceptual review and net timing remain untested.']};
mesh.geometry=original;indexed.dispose();batch.dispose();for(const m of [...sourceScene.children]){m.geometry.dispose();m.material.dispose();}
fs.writeFileSync('docs/qa/frontside-model-pilot/maize-bridge-index-control-audit.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
