import fs from 'node:fs';import crypto from 'node:crypto';import {gzipSync} from 'node:zlib';
import {sharedLeafGpuReportPrefix} from './lib/frontside-shared-leaf-gpu-report.mjs';import {analysePairedGpu} from './lib/frontside-paired-gpu-analysis.mjs';
const [runId,reportPath,pngPath]=process.argv.slice(2),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
if(!/^(timing|resources)-v[1-9][0-9]*$/.test(runId??'')||!reportPath||!pngPath)throw Error('Usage: campaign-vN native-json native-png');
const fixtureJsSha256='c55fa37dd9e84b82f61fac2613f2cb54a62374489c54f3e776f2b5638c7c86a5';if(sha(fs.readFileSync('tests/browser/frontside-crop-leaf-shared-gpu.js'))!==fixtureJsSha256)throw Error('Frozen GPU fixture changed');
const raw=fs.readFileSync(reportPath),png=fs.readFileSync(pngPath),report=JSON.parse(raw);sharedLeafGpuReportPrefix(report);if(!runId.startsWith(report.campaign+'-'))throw Error('Campaign mismatch');if(png.readUInt32BE(16)!==1280||png.readUInt32BE(20)!==720)throw Error('Unexpected GPU capture dimensions');
let analysis=null,analysisError=null;
if(report.campaign==='timing'){try{analysis=analysePairedGpu(report.blocks);if(JSON.stringify(report.analysis)!==JSON.stringify(analysis))throw Error('Native recorded analysis differs from fixed CPU replay');}catch(error){analysisError=error.message;if(report.analysis)throw error;}}
const directory='docs/qa/frontside-model-pilot/shared-leaf-gpu/'+runId+'/';fs.mkdirSync(directory,{recursive:true});
function preserve(name,bytes){const path=directory+name;if(fs.existsSync(path)&&sha(fs.readFileSync(path))!==sha(bytes))throw Error('Refusing immutable replacement '+path);fs.writeFileSync(path,bytes);}
const zipped=gzipSync(raw);preserve('report.json.gz',zipped);preserve('last-frame.png',png);
const manifest={status:analysisError?'INVALID_GPU_COLLECTION_ARCHIVED_NOT_APPROVED':'NATIVE_GPU_EXPERIMENT_ARCHIVED_NOT_CATEGORY_APPROVAL',runId,fixtureSourceCommit:'519f7d01',fixtureJsSha256,rawJsonSha256:sha(raw),gzipSha256:sha(zipped),pngSha256:sha(png),sourceMapping:report.sourceMapping,archiveSha256:report.archiveSha256,gpu:report.gpu,browser:report.browser,contextAttributes:report.contextAttributes,campaignConditions:report.campaignConditions,analysis,analysisError,blocks:report.blocks.map(b=>({pair:b.pair,order:b.order,arm:b.arm,warmupFrames:b.warmupFrames,validQuerySamples:b.gpu?.samples?.length,queryFailures:b.gpu?Object.fromEntries(['pending','disjointEvents','discarded','overflowSkipped','foreignQuerySkipped','allocationFailures','contextLost'].map(k=>[k,b.gpu[k]])):null,submissions:b.submissions,rendererMemory:b.rendererMemory,programCount:b.programCount})),cleanup:report.cleanup,contextLost:report.contextLost,limitations:['Elapsed query blocks are retained without reroll; pooled, paired and tail statistics refer only to this synthetic mature lot.','Actual authoritative process inventory and native console observations must accompany this archive; URL condition text alone is not proof of liveness.','Double-shadow isolation remains; complete Front shadow correctness, mixed-world regression, resident memory, deployment and category visual/functional evidence remain separate.','Final PNG is one draw, not the multiview appearance inspection or proof of human acceptance.']};preserve('manifest.json',Buffer.from(JSON.stringify(manifest,null,2)+'\n'));console.log(JSON.stringify({status:manifest.status,runId,samples:report.blocks.reduce((sum,b)=>sum+(b.gpu?.samples?.length??0),0),analysis:analysis?{savedMs:analysis.savedMs,savedPercent:analysis.savedPercent,gates:analysis.gates}:null,analysisError}));
