// HTTP/CPU transport check only. No Three renderer, browser or artifact POST.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';
import {bridgeIndexReportPrefix} from './lib/frontside-bridge-index-report.mjs';
import {bridgeIndexReviewCases} from './lib/frontside-bridge-index-review-cases.mjs';
import {attachHumanVisualReview} from './lib/frontside-human-visual-review.mjs';
const base='http://127.0.0.1:5284',sourceSha256='be4bb7e7eab2149516c1ecc0c364d77c4a62f116c4847cf0ef6f3308dc6180ef',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
async function bytes(url){const r=await fetch(new URL('/'+url.replace(/^\//,''),base));assert.equal(r.status,200,url);return Buffer.from(await r.arrayBuffer());}
const mapping=JSON.parse(await bytes('/content/manifests/web-assets.json')).records.find(r=>r.sourceSha256===sourceSha256),models=JSON.parse(await bytes('/content/models.json')),url=models.find(m=>m.source.includes('Cultivos')).url;
assert.equal(url.replace(/^\//,''),mapping.runtime);
const runtime=await bytes(url),bridge=await bytes('/content/crop-bridges.json');assert.equal(sha(runtime),mapping.runtimeSha256);assert.equal(sha(bridge),sha(fs.readFileSync('public/content/crop-bridges.json')));
const report=attachHumanVisualReview({status:'VISUAL_SCREEN_NOT_APPROVED',cropVisual:true,originalBridgeIndexHuman:true,preflightOnly:true,viewProfile:'ORIGINAL_BRIDGE_INDEX_DOUBLE_REVIEW_V1',source:url,sourceOriginal:mapping.source,runtimeSource:mapping.runtime,sourceSha256,runtimeSha256:sha(runtime),bridgeSha256:sha(bridge),viewCaseIndex:0,prospectiveCase:bridgeIndexReviewCases[0],arms:['native original nonindexed DoubleSide','same original indexed DoubleSide'],phase:{phase:'morph'},runtime:{status:'EXPORT_PREFLIGHT_PLACEHOLDER_NOT_NATIVE',control:{mesh:'puente_maiz_3_4',closed:false,liveBridgeShared:true,instanceMatrixShared:true,materialUnchanged:true,shadowUnchanged:true,indexCount:17844,sourceCorners:17844},arms:[0,1].map(arm=>({arm,visible:true,count:1,materialSide:2,shadowSide:2}))},campaignConditions:{gpuTiming:false},cleanup:{closed:true,contextLost:true,errors:[]},errors:[],limitations:['These runtime/cleanup fields are export placeholders, not observed native execution. No WebGL context or artifact report is created.']});
assert.equal(bridgeIndexReportPrefix(report,{preflight:true}),'crop-bridge-index-double');assert.throws(()=>bridgeIndexReportPrefix(report),/preflight placeholder/);
const response=await fetch(base+'/__frontside_export_preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'BRIDGE_INDEX_EXPORT_PREFLIGHT_ONLY',gpuDraws:0,report})});assert.equal(response.status,200,await response.clone().text());const result=await response.json();assert.equal(result.prefix,'crop-bridge-index-double');assert.equal(result.artifactsWritten,false);
const receipt={status:'BRIDGE_INDEX_EXPORT_PREFLIGHT_PASS_NOT_NATIVE',sourceOriginal:mapping.source,runtimeSource:mapping.runtime,sourceSha256,runtimeSha256:sha(runtime),bridgeSha256:sha(bridge),runtimeBytes:runtime.length,bridgeBytes:bridge.length,gpuContextCreated:false,gpuDraws:0,artifactsWritten:false,placeholderNativeFields:true};
fs.writeFileSync('docs/qa/frontside-model-pilot/maize-bridge-index-export-preflight.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
