// CPU/HTTP only. Placeholder draw fields never become native artifacts.
import crypto from 'node:crypto';import fs from 'node:fs';import zlib from 'node:zlib';
import {deserialize,serialize} from '../src/persistence/snapshots.js';
import {denseNativeMaizeScenario} from './lib/frontside-dense-native-maize-scenario.mjs';
import {decodeCompactLeafPayload} from './lib/frontside-compact-leaf-payload.mjs';
const sha=value=>crypto.createHash('sha256').update(value).digest('hex'),base='http://127.0.0.1:5284',archiveResponse=await fetch(base+'/docs/qa/intensive-gran-rio-suajili-e461b550/state.json.gz');if(!archiveResponse.ok)throw Error('Archive HTTP failed');let bytes=Buffer.from(await archiveResponse.arrayBuffer());const text=(bytes[0]===31&&bytes[1]===139?zlib.gunzipSync(bytes):bytes).toString('utf8'),dense=denseNativeMaizeScenario(deserialize(text));
const payloadResponse=await fetch(base+'/__frontside_candidate/maize-leaf-shared-compact');if(!payloadResponse.ok)throw Error('Payload HTTP failed');const payloadBytes=Buffer.from(await payloadResponse.arrayBuffer()),payload=decodeCompactLeafPayload(payloadBytes);if(sha(payloadBytes)!=='3eba51ae256663c20bdfcfc4f9e0133a304e8a6dfa25b072a07154b82f0ee65c')throw Error('Payload changed');
const report={status:'WORLD_DENSE_MAIZE_GPU_NOT_APPROVED',denseWorldMaizeQa:true,preflightOnly:true,visualAcceptancePolicyVersion:3,viewProfile:'DECLARED_DENSE_NATIVE_WORLD_MAIZE_V1',campaign:'review',qaDepth:'off',vfx:'on',sourceStateSha256:sha(text),workloadStateSha256:sha(serialize(dense.state)),scenario:dense.receipt,candidateBinarySha256:sha(payloadBytes),candidateBinaryBytes:payloadBytes.length,sourceSha256:payload.sourceSha256,resolution:[1280,720],quality:'media',visualReview:{status:'HUMAN_REVIEW_PENDING',reviewer:null,decision:null},conditions:{gpuTiming:false,bufferReadback:false},cleanup:{closed:true,contextLost:true,errors:[],placeholder:true},errors:[],arms:[]};
// The bounded preflight transports summary identity only; full changed-plant
// provenance belongs to the separate native report (20 MB limit).
delete report.scenario.changed;
const response=await fetch(base+'/__frontside_export_preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'DENSE_WORLD_MAIZE_EXPORT_PREFLIGHT_ONLY',gpuDraws:0,report})}),result=await response.json();if(!response.ok||result.artifactsWritten!==false)throw Error('Dense export preflight failed '+JSON.stringify(result));
const receipt={status:'DENSE_WORLD_HTTP_CPU_PREFLIGHT_PASS_NOT_NATIVE',gpuContextsCreated:0,gpuDraws:0,artifactsWritten:false,archiveHttpBytes:bytes.length,archiveHttpContentType:archiveResponse.headers.get('content-type'),sourceStateSha256:report.sourceStateSha256,workloadStateSha256:report.workloadStateSha256,scenario:{...dense.receipt,changed:undefined},candidateBinarySha256:report.candidateBinarySha256,candidateBinaryBytes:payloadBytes.length,exportResult:result,limitations:['No native draw or buffer/actor binding observed.','The preflight synthetic state precedes fixture lighting, pause and VFX setup; its workload hash is not the final native timing state.']};fs.writeFileSync('docs/qa/frontside-model-pilot/maize-world/dense-http-preflight.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
