// CPU functional audit of the actual source GLB and production batch factory.
// No texture loading, GPU context, rendered appearance or completed harvest claim.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import * as THREE from 'three';import {readGlb} from './glb-container.mjs';import {createCropBatch} from '../src/rendering/crop-batch.js';import {cropSpec} from '../src/simulation/rules.js';import {decodeCompactLeafPayload} from './lib/frontside-compact-leaf-payload.mjs';import {installWorldMaizeQaAdapter} from './lib/frontside-world-maize-adapter.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),sourcePath='public/assets/be4bb7e7eab2149516c1ecc0c364d77c4a62f116c4847cf0ef6f3308dc6180ef.glb',raw=fs.readFileSync(sourcePath),glb=readGlb(raw),scene=new THREE.Scene(),types={5123:Uint16Array,5125:Uint32Array,5126:Float32Array},widths={SCALAR:1,VEC2:2,VEC3:3},sourceMaterials=[];
function accessor(id){const a=glb.json.accessors[id],v=glb.json.bufferViews[a.bufferView],Type=types[a.componentType],size=widths[a.type];assert.ok(Type&&size&&!a.sparse&&!v.extensions&&v.buffer===0);const width=Type.BYTES_PER_ELEMENT*size,stride=v.byteStride??width,output=new Uint8Array(a.count*width);for(let i=0;i<a.count;i++)output.set(glb.bin.subarray((v.byteOffset??0)+(a.byteOffset??0)+i*stride,(v.byteOffset??0)+(a.byteOffset??0)+i*stride+width),i*width);return new THREE.BufferAttribute(new Type(output.buffer),size,!!a.normalized);}
for(const node of glb.json.nodes??[]){if(node.mesh===undefined)continue;const m=glb.json.meshes[node.mesh];assert.equal(m.primitives.length,1);const p=m.primitives[0],g=new THREE.BufferGeometry();for(const [semantic,name] of [['POSITION','position'],['NORMAL','normal'],['TEXCOORD_0','uv']])g.setAttribute(name,accessor(p.attributes[semantic]));g.setIndex(accessor(p.indices));const material=new THREE.MeshStandardMaterial(),mesh=new THREE.Mesh(g,material);mesh.name=node.name;mesh.userData=structuredClone(node.extras);scene.add(mesh);sourceMaterials.push(material);}
const bridgeBytes=fs.readFileSync('public/content/crop-bridges.json'),bridgeData=JSON.parse(bridgeBytes),binary=fs.readFileSync('.cache/frontside-model-pilot/candidates/archive/3eba51ae256663c20bdfcfc4f9e0133a304e8a6dfa25b072a07154b82f0ee65c.wgleaf');assert.equal(sha(binary),'3eba51ae256663c20bdfcfc4f9e0133a304e8a6dfa25b072a07154b82f0ee65c');const payload=decodeCompactLeafPayload(binary),renderer={capabilities:{getMaxAnisotropy:()=>8}},originalScene=new THREE.Scene(),derivedScene=new THREE.Scene(),original=createCropBatch(originalScene,renderer,{scene},bridgeData,64),world={scene:derivedScene,cropBatch:createCropBatch(derivedScene,renderer,{scene},bridgeData,64)},adapter=installWorldMaizeQaAdapter(world,payload),duration=cropSpec('maiz').growth_seconds,plants=[{id:'qa-growth-1',species:'maiz',x:2,z:3,rotation:.2,growth:0}],rows=[];
const normalized=[0,.03,.065,.228,.23105,.234,.269,.27,.477,.4806,.484,.529,.53,.729,.7325,.736,.779,.78,.94,.954,.9582,.962,.97,.99,.992,.994,.996,.998,1,1.01];for(const growth of normalized){plants[0].growth=growth*duration;original.update(plants,12.5,()=>.25);world.cropBatch.update(plants,12.5,()=>.25);assert.deepEqual(original.sample('maiz',plants[0].growth),world.cropBatch.sample('maiz',plants[0].growth));assert.equal(originalScene.children.length,derivedScene.children.length);const active=[];for(let i=0;i<originalScene.children.length;i++){const a=originalScene.children[i],b=derivedScene.children[i];assert.equal(a.name,b.name);assert.equal(a.count,b.count);assert.equal(a.visible,b.visible);assert.deepEqual(a.instanceMatrix.array,b.instanceMatrix.array);for(const key of ['iGrowth','iBridge'])if(a.geometry.getAttribute(key))assert.deepEqual(a.geometry.getAttribute(key).array,b.geometry.getAttribute(key).array);if(a.visible)active.push({name:a.name,count:a.count});}rows.push({normalizedGrowth:growth,phase:original.sample('maiz',plants[0].growth).phase,active});}
assert.equal(payload.sourceSha256,sha(raw));
const sample=original.sample('maiz',duration),unchangedSamples=rows.length;
// Mirror the native disposal/replacement contract with real factory batches,
// then fill beyond the old capacity using original and morph/mature stages.
original.dispose();world.cropBatch.dispose();
const resizedOriginal=createCropBatch(originalScene,renderer,{scene},bridgeData,128);
world.cropBatch=createCropBatch(derivedScene,renderer,{scene},bridgeData,128);
const resizedPlants=Array.from({length:65},(_,i)=>({id:'qa-resize-'+i,species:'maiz',x:i%9,z:Math.floor(i/9),rotation:i*.01,growth:normalized[i%normalized.length]*duration}));
resizedOriginal.update(resizedPlants,12.5,()=>.25);world.cropBatch.update(resizedPlants,12.5,()=>.25);
assert.equal(originalScene.children.length,derivedScene.children.length);
for(let i=0;i<originalScene.children.length;i++){const a=originalScene.children[i],b=derivedScene.children[i];assert.equal(a.name,b.name);assert.equal(a.count,b.count);assert.equal(a.visible,b.visible);assert.deepEqual(a.instanceMatrix.array,b.instanceMatrix.array);for(const key of ['iGrowth','iBridge'])if(a.geometry.getAttribute(key))assert.deepEqual(a.geometry.getAttribute(key).array,b.geometry.getAttribute(key).array);}
const capacityRecreation={oldCapacity:64,newCapacity:128,plants:resizedPlants.length,adapter:adapter.snapshot(),liveLanesAndDispatchEqual:true};
assert.equal(capacityRecreation.adapter.capacity,128);assert.equal(capacityRecreation.adapter.events.filter(e=>e.event==='installed').length,2);
adapter.dispose();resizedOriginal.dispose();world.cropBatch.dispose();for(const mesh of [...scene.children]){mesh.geometry.dispose();mesh.material.dispose();}const report={status:'ACTUAL_BATCH_GROWTH_DISPATCH_AND_LIVE_LANES_PASS_NOT_VISUAL_APPROVAL',sourceSha256:sha(raw),bridgeSha256:sha(bridgeBytes),candidateBinarySha256:sha(binary),rows,unchangedSamples,matureSample:sample,capacityRecreation,limitations:['Actual source geometry/metadata and production batch factory; CPU-only, source textures were not loaded.','Actual factory disposal/recreation64 to128 preserves live lanes/dispatch for65 plants; WorldScene demand scheduling itself was not invoked.','Original and candidate stage/bridge dispatch, live instance matrices and growth lanes agree. GPU deformation/interpolation, switch perceptual continuity and completed worker harvest/delivery remain unproven.']};fs.writeFileSync('docs/qa/frontside-model-pilot/maize-world-growth-contract.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({status:report.status,samples:unchangedSamples,capacityRecreation,phases:[...new Set(rows.map(r=>r.phase))]}));
