// Precommit independent cases; never select geometry from rendered images.
import fs from 'node:fs';import crypto from 'node:crypto';
import {cropSpec} from '../src/simulation/rules.js';
const folder='docs/qa/frontside-model-pilot/',input='tests/browser/frontside-crop-local-stem-front.js';let source=fs.readFileSync(input,'utf8');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),inputSha256=hash(source);
if(inputSha256!=='f7d6936f253982dd6fe3547382423ef8ae814e9ee16846e435e3e3209c442fec')throw Error('Frozen Front training changed');
const marks=[.065,.27,.53,.78,1],biomes=['sabana','gran-rio','manglares','volcanes','gran-canon','desierto'],nights=[0,.5,1],clocks=[.8125,2.4375,4.6875,6.3125],locals=[.017,.187,.437,.637],cases=[];
for(const [ei,elevation]of [-15,5,25,55,85].entries())for(let az=0;az<16;az++){
 const i=ei*16+az;
 cases.push({growth:.27+.26*locals[(az+ei)%4],clock:clocks[(az+2*ei)%4],biome:biomes[(az+ei)%6],night:nights[(az+ei)%3],elevation,azimuth:(13.8125+az*22.5)%360,expectedPhase:'original',expectedYoungActive:true,purpose:'Native young stage at varied growth/wind; full16azimuths×5elevations'});
}
for(let stage=0;stage<4;stage++){
 const interval=marks[stage+1]-marks[stage],width=Math.min(.34,2/(interval*cropSpec('maiz').growth_seconds)),start=.81-width*.5,end=.81+width*.5;
 for(const [j,local]of [start-1e-5,start+width*.05,start+width*.5,start+width*.95,end+1e-5].entries()){
  const i=cases.length;cases.push({growth:marks[stage]+interval*local,clock:clocks[(stage+j)%4],biome:biomes[(stage+2*j)%6],night:nights[(stage+j)%3],elevation:[5,25,55,85,-15][j],azimuth:(28.9375+stage*77+j*41.5)%360,
   expectedPhase:j===0||j===4?'original':'morph',expectedYoungActive:j===0&&stage===1||j===4&&stage===0,purpose:'Continuous bridge'+(stage+1)+'→'+(stage+2)+' with original Double geometry; boundary±1e-5 local and interior .05/.5/.95'});
 }
}
for(const [j,growth]of [.025,.56,.815,1].entries())cases.push({growth,clock:clocks[j],biome:biomes[(j+1)%6],night:nights[j%3],elevation:[85,25,5,55][j],azimuth:51.9375+j*89,expectedPhase:'original',expectedYoungActive:false,purpose:'Unmodified native other states remain originalDouble'});
if(cases.length!==104)throw Error('Prospective matrix count mismatch');
const profile={status:'PROSPECTIVE_INDEPENDENT_SCREEN_NOT_APPROVED',profile:'LOCAL_YOUNG_MAIZE_INDEPENDENT_V1',selection:'Unchanged245 native young driver1 faces from local geometric filter; no image masks',crop:'maiz',growthSeconds:cropSpec('maiz').growth_seconds,morphSeconds:2,blockSize:26,blockOffsets:[0,26,52,78],cases,
 limitations:['Precommitted104cases; passing subsets is not full profile/category approval. Stop after source/Double/Front failure, no later blocks or rerolls to recover a pass.',
 'Color isolation retains all shadowsDouble; effective Front shadow/depth and resource/netGPU gates are separate unpassed requirements.',
 '80views all16az×5elev on selected native state;20bridge-boundary/interior cases and4unmodified other native states preserve continuous original route.',
 'Crop shader input has biome/day/night/growth/wind; real WorldScene culture/light composition and dense-world integration remain additional gates.']};
fs.writeFileSync(folder+'local-stem-independent-v1.json',JSON.stringify(profile,null,2)+'\n');
const profileSha256=hash(fs.readFileSync(folder+'local-stem-independent-v1.json'));
function replaceOnce(before,after){if(source.split(before).length!==2)throw Error('Unexpected Front source: '+before.slice(0,80));source=source.replace(before,after);}
replaceOnce(" if(options.get('limit')!=='1'||!options.has('localStemFrontQuality')||[...options.keys()].some(k=>!['localStemFrontQuality','limit','cpuCampaigns'].includes(k)))throw Error('Isolated native young-maize Front training requires limit1 and no other experiment flags');", " const caseOffset=Number(options.get('caseOffset')??0);if(options.get('limit')!=='26'||!options.has('localStemFrontIndependent')||![0,26,52,78].includes(caseOffset)||[...options.keys()].some(k=>!['localStemFrontIndependent','limit','caseOffset','cpuCampaigns'].includes(k)))throw Error('IndependentV1 requires frozen26case blocks/offsets and no training/other experiment flags');");
replaceOnce("cases.push({growth:.31,clock:3.0625,biome:'gran-rio',night:0,elevation:46.25,azimuth:57.625});report.prospectiveCases=cases;report.viewProfile='NATIVE_YOUNG_MAIZE_LOCAL_STEM_DOUBLE_TRAINING_V1';", "const independent=await fetch('/docs/qa/frontside-model-pilot/local-stem-independent-v1.json').then(r=>r.json());if(independent.profile!=='LOCAL_YOUNG_MAIZE_INDEPENDENT_V1'||independent.cases.length!==104)throw Error('Frozen independent profile mismatch');cases.push(...independent.cases.slice(caseOffset,caseOffset+26));report.independentProfile=independent;report.caseOffset=caseOffset;report.prospectiveCases=cases;report.viewProfile=independent.profile;");
replaceOnce("report.localStemFrontTraining=true;", "report.localStemFrontTraining=false;report.localStemIndependentScreen=true;report.localStemCaseCpuContracts=[];");
replaceOnce("for(const rig of rigs){const target=rig.group.getObjectByName('maiz_02_joven');if(!target?.visible||target.count!==1||rig.batch.sample(pilotSpecies,growth*cropSpec(pilotSpecies).growth_seconds).phase!=='original')throw Error('Double-only quality must actually render native young maize, not a bridge/other state');}", "const expected=cases.find(row=>row.growth===growth&&row.clock===clock&&row.biome===biome&&row.elevation===elevation&&row.azimuth===azimuth);for(const rig of rigs){const target=rig.group.getObjectByName('maiz_02_joven'),sample=rig.batch.sample(pilotSpecies,growth*cropSpec(pilotSpecies).growth_seconds);if(!target||sample.phase!==expected.expectedPhase||target.count!==(expected.expectedYoungActive?1:0)||target.visible!==expected.expectedYoungActive)throw Error('Independent native/bridge phase or selected-mesh coverage contract mismatch');}");
replaceOnce("if(stop)break campaign;", "if(stop)break campaign;report.localStemCaseCpuContracts.push({caseIndex:caseOffset+report.samples.length,growth,clock,phase:rigs[0].batch.sample(pilotSpecies,growth*cropSpec(pilotSpecies).growth_seconds).phase,arms:await Promise.all(rigs.map((rig,arm)=>cpuContractAudit.snapshot(rig.group.getObjectByName('maiz_02_joven'),arm)))});");
replaceOnce("const independent=await fetch('/docs/qa/frontside-model-pilot/local-stem-independent-v1.json').then(r=>r.json());", "const independentBytes=await fetch('/docs/qa/frontside-model-pilot/local-stem-independent-v1.json').then(r=>{if(!r.ok)throw Error('Independent profile fetch failed');return r.arrayBuffer();}),independentSha256=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',independentBytes)),b=>b.toString(16).padStart(2,'0')).join('');if(independentSha256!=='"+profileSha256+"')throw Error('Frozen independent profile SHA mismatch');const independent=JSON.parse(new TextDecoder().decode(independentBytes));report.independentProfileSha256=independentSha256;");
source=source.replaceAll('TRAINING controlado','Selección independiente V1').replace('This reused TRAINING camera is not independent acceptance','This NEW independent profile is not category acceptance').replace('// Generated Double-only local stem quality snapshot; no production activation.','// Generated independent local stem Front screen; no production activation.');
source=source.replace(/\r\n/g,'\n');
const output='tests/browser/frontside-crop-local-stem-independent.js';fs.writeFileSync(output,source);
fs.writeFileSync(folder+'local-stem-independent-fixture-receipt.json',JSON.stringify({status:'INDEPENDENT_SCREEN_PENDING_NOT_APPROVED',input,inputSha256,output,outputSha256:hash(source),profileSha256:hash(fs.readFileSync(folder+'local-stem-independent-v1.json')),profile:profile.profile,totalCases:104,blocks:profile.blockOffsets},null,2)+'\n');console.log(output,hash(source));
