// Functional CPU contract for the new isolated rig builder; no renderer/images.
import fs from 'node:fs';import crypto from 'node:crypto';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {readGlb,writeGlb} from './glb-container.mjs';import {AfricanToon} from '../src/rendering/african-toon.js';import {SceneMaterialRegistry} from '../src/rendering/material-registry.js';import {createQaResourceScope} from './lib/frontside-qa-resource-scope.mjs';import {createSharedLeafRuntimeRigs} from './lib/frontside-shared-leaf-runtime-rigs.mjs';import {sharedLeafContinuousPlan as plan} from './lib/frontside-shared-leaf-continuous-plan.mjs';
const folder='docs/qa/frontside-model-pilot/',receipt=JSON.parse(fs.readFileSync(folder+'maize-blender-leaf-reduction-diagnostic.json')),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),raw=fs.readFileSync('public/assets/'+receipt.sourceSha256+'.glb'),archive=fs.readFileSync(receipt.archive),bridgeRaw=fs.readFileSync('public/content/crop-bridges.json');if(sha(raw)!==receipt.sourceSha256||sha(archive)!==receipt.archiveSha256)throw Error('Immutable input mismatch');
const {json,bin}=readGlb(raw);function omitTextures(o){if(!o||typeof o!=='object')return;for(const key of Object.keys(o))if(key.endsWith('Texture'))delete o[key];else omitTextures(o[key]);}omitTextures(json.materials);delete json.images;delete json.textures;
const gltf=await new GLTFLoader().parseAsync(writeGlb(json,bin).buffer,''),scene=new THREE.Scene(),toon=new AfricanToon(),registry=new SceneMaterialRegistry(scene,toon),scope=createQaResourceScope();scope.defer('registry',()=>registry.dispose());const runtime=createSharedLeafRuntimeRigs({scene,renderer:{capabilities:{getMaxAnisotropy:()=>1}},gltf,bridges:JSON.parse(bridgeRaw),payload:JSON.parse(archive),capacity:64,scope,wrapSourceMaterials(){registry.update(plan.windClockStart);}});
const plants=Array.from({length:plan.plants},(_,i)=>({id:String(i+1),species:'maiz',x:(i%plan.grid-3)*plan.spacing,z:(Math.floor(i/plan.grid)-3)*plan.spacing,growth:0,rotation:i*2.399963229728653})),rows=[];
try{for(const growth of [.94,.9582,.96179,.96202,.983]){plants.forEach(p=>p.growth=growth*plan.growthSeconds);for(const {batch} of runtime.rigs)batch.update(plants,plan.windClockStart,()=>0);const base=runtime.rigs[0].target,baseMatrix=Buffer.from(base.instanceMatrix.array.buffer),baseGrowth=Buffer.from(base.geometry.getAttribute('iGrowth').array.buffer),states=runtime.rigs.map(({arm,batch,target})=>{if(!Buffer.from(target.instanceMatrix.array.buffer).equals(baseMatrix)||!Buffer.from(target.geometry.getAttribute('iGrowth').array.buffer).equals(baseGrowth))throw Error('Live instance contract mismatch arm'+arm);const sampled=batch.sample('maiz',growth*plan.growthSeconds);return{arm,phase:sampled.phase,stage:sampled.stage,matureActive:target.visible&&target.count>0,count:target.count};});if(states.some(s=>s.phase!==states[0].phase||s.matureActive!==states[0].matureActive))throw Error('Phase mismatch');rows.push({growth,states});}runtime.select(3);if(runtime.rigs.filter(r=>r.group.visible).length!==1)throw Error('Rig selection mismatch');}
finally{scope.cleanup();}
const report={status:'CPU_RUNTIME_RIG_CONTRACT_PASS_NOT_VISUAL_OR_GPU_APPROVAL',sourceSha256:sha(raw),archiveSha256:sha(archive),bridgeSha256:sha(bridgeRaw),runtimeBuilderSha256:sha(fs.readFileSync('tools/lib/frontside-shared-leaf-runtime-rigs.mjs')),continuousPlanSha256:sha(fs.readFileSync('tools/lib/frontside-shared-leaf-continuous-plan.mjs')),plantCount:plants.length,resources:runtime.resources,rows,cleanup:scope.result,limitations:['Actual source batch, phase logic, instance matrices and growth lanes; temporary CPU loader omits textures only in memory.','No GPU upload, shader compilation, material map appearance, human continuity observation or timing.']};if(report.cleanup.errors.length)throw Error('Cleanup errors');fs.writeFileSync(folder+'maize-leaf-shared-continuous-runtime-contract.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
