// Read-only actual web decode verification. No asset mutation or browser context.
import fs from 'node:fs';import crypto from 'node:crypto';import {MeshoptDecoder} from 'three/addons/libs/meshopt_decoder.module.js';import {readGlb} from './glb-container.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),filename='be4bb7e7eab2149516c1ecc0c364d77c4a62f116c4847cf0ef6f3308dc6180ef.glb',raw=fs.readFileSync('public/assets/'+filename),web=fs.readFileSync('public/assets/web/'+filename),source=readGlb(raw),runtime=readGlb(web);
if(sha(raw)!==filename.slice(0,-4)||sha(web)!=='617568fc66595c635739ff83bc0256535a72fdf7bfcb016dc68a7f7f1e1a8a52')throw Error('Source/web bytes changed');
await MeshoptDecoder.ready;
const cache=new WeakMap(),componentBytes={5120:1,5121:1,5122:2,5123:2,5125:4,5126:4},components={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
function lane(container,id){const accessor=container.json.accessors[id],view=container.json.bufferViews[accessor.bufferView];if(accessor.sparse)throw Error('Sparse lane unsupported');let maps=cache.get(container);if(!maps){maps=new Map();cache.set(container,maps);}let bytes=maps.get(accessor.bufferView);
 if(!bytes){const ext=view.extensions?.EXT_meshopt_compression;if(ext){if(ext.buffer!==0)throw Error('External compressed buffer');bytes=new Uint8Array(ext.count*ext.byteStride);MeshoptDecoder.decodeGltfBuffer(bytes,ext.count,ext.byteStride,container.bin.subarray(ext.byteOffset??0,(ext.byteOffset??0)+ext.byteLength),ext.mode,ext.filter??'NONE');}else{if(view.buffer!==0)throw Error('Unavailable external/fallback buffer');bytes=container.bin.subarray(view.byteOffset??0,(view.byteOffset??0)+view.byteLength);}maps.set(accessor.bufferView,bytes);}
 const width=componentBytes[accessor.componentType]*components[accessor.type],stride=view.byteStride??width;if(!Number.isSafeInteger(width)||!width)throw Error('Unknown accessor lane');const output=new Uint8Array(accessor.count*width);
 for(let i=0;i<accessor.count;i++){const offset=(accessor.byteOffset??0)+i*stride;if(offset+width>bytes.length)throw Error('Accessor outside decoded view');output.set(bytes.subarray(offset,offset+width),i*width);}
 return {accessor,bytes:output};
}
const sourceMesh=source.json.meshes.find(m=>m.name==='maiz_05_maduro'),webMesh=runtime.json.meshes.find(m=>m.name==='maiz_05_maduro');if(!sourceMesh||!webMesh||sourceMesh.primitives.length!==1||webMesh.primitives.length!==1)throw Error('Mature mesh contract changed');
const a=sourceMesh.primitives[0],b=webMesh.primitives[0],rows=[];
for(const name of ['POSITION','NORMAL','TEXCOORD_0','indices']){const x=lane(source,name==='indices'?a.indices:a.attributes[name]),y=lane(runtime,name==='indices'?b.indices:b.attributes[name]);if(JSON.stringify(x.accessor)!==JSON.stringify(y.accessor)||!Buffer.from(x.bytes).equals(Buffer.from(y.bytes)))throw Error('Actual web lane differs '+name);rows.push({name,count:x.accessor.count,componentType:x.accessor.componentType,type:x.accessor.type,bytes:x.bytes.length,sourceLaneSha256:sha(x.bytes),decodedWebLaneSha256:sha(y.bytes),byteExact:true});}
const report={status:'ACTUAL_WEB_MATURE_LANES_BYTE_EXACT_NOT_VISUAL_OR_GPU_APPROVAL',sourceSha256:sha(raw),runtimeSha256:sha(web),mesh:'maiz_05_maduro',decoder:'MeshoptDecoder from pinned Three runtime',rows,limitations:['Read-only mature P/N/UV/index CPU decoding only. No texture, shader evaluation, rig, whole category or driver-resident equivalence is asserted.','Actual native timing/resource campaigns remain separate and unexecuted by this script.']};fs.writeFileSync('docs/qa/frontside-model-pilot/maize-mature-actual-web-lanes.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report));
