import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import * as THREE from 'three';
import {readGlb,writeGlb} from './glb-container.mjs';import {decodeCompactLeafPayload} from './lib/frontside-compact-leaf-payload.mjs';import {sharedLeafReverseGeometry} from './lib/frontside-shared-leaf-reverse.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex'),receipt=JSON.parse(fs.readFileSync('docs/qa/frontside-model-pilot/maize-young-leaf-pilot/receipt.json')),raw=fs.readFileSync('public/assets/'+receipt.sourceSha256+'.glb');assert.equal(sha(raw),receipt.sourceSha256);
const {json,bin}=readGlb(raw),baseline=structuredClone(json),payload=decodeCompactLeafPayload(fs.readFileSync(receipt.binary)),node=json.nodes.find(n=>n.name===payload.mesh);assert.ok(node);assert.equal(node.skin,undefined);const primitive=json.meshes[node.mesh].primitives[0];assert.ok(!primitive.targets);assert.deepEqual(Object.keys(primitive.attributes).sort(),['NORMAL','POSITION','TEXCOORD_0']);
const built=sharedLeafReverseGeometry(new THREE.BufferGeometry(),payload,{reverseLeaves:false}),geo=built.geometry,parts=[bin];let offset=bin.length;
function accessor(array,type,target){const aligned=Math.ceil(offset/4)*4;if(aligned>offset)parts.push(new Uint8Array(aligned-offset));offset=aligned;const bytes=new Uint8Array(array.buffer,array.byteOffset,array.byteLength),view=json.bufferViews.length;json.bufferViews.push({buffer:0,byteOffset:offset,byteLength:bytes.length,target});parts.push(bytes);offset+=bytes.length;const index=json.accessors.length,item={bufferView:view,componentType:array instanceof Uint16Array?5123:5126,count:array.length/({VEC3:3,VEC2:2,SCALAR:1}[type]),type};if(target===34962&&type==='VEC3'){const bounds=[[],[]];for(let c=0;c<3;c++){let lo=Infinity,hi=-Infinity;for(let i=c;i<array.length;i+=3){lo=Math.min(lo,array[i]);hi=Math.max(hi,array[i]);}bounds[0].push(lo);bounds[1].push(hi);}item.min=bounds[0];item.max=bounds[1];}json.accessors.push(item);return index;}
primitive.attributes={POSITION:accessor(geo.getAttribute('position').array,'VEC3',34962),NORMAL:accessor(geo.getAttribute('normal').array,'VEC3',34962),TEXCOORD_0:accessor(geo.getAttribute('uv').array,'VEC2',34962)};primitive.indices=accessor(geo.index.array,'SCALAR',34963);json.buffers[0].byteLength=offset;
const binary=new Uint8Array(offset);let at=0;for(const p of parts){binary.set(p,at);at+=p.length;}const out=writeGlb(json,binary),digest=sha(out),path='.cache/frontside-model-pilot/candidates/archive/'+digest+'.glb';fs.writeFileSync(path,out);
assert.deepEqual(json.nodes,baseline.nodes);assert.deepEqual(json.materials,baseline.materials);assert.deepEqual(json.animations,baseline.animations);assert.deepEqual(json.skins,baseline.skins);assert.deepEqual(binary.subarray(0,bin.length),bin);for(let i=0;i<json.meshes.length;i++)if(i!==node.mesh)assert.deepEqual(json.meshes[i],baseline.meshes[i]);
const report={status:'YOUNG_FORWARD_DOUBLE_GLB_CPU_ONLY',sourceSha256:sha(raw),payloadSha256:receipt.binarySha256,output:path,outputSha256:digest,sourceBytes:raw.length,outputBytes:out.length,appendedBufferBytes:offset-bin.length,targetNode:payload.mesh,triangles:geo.index.count/3,materialsUnchanged:true,nodesPivotsExtrasUnchanged:true,other39MeshesUnchanged:true,skinsAnimationsUnchanged:true,originalBinaryPrefixUnchanged:true,limitations:['Controlled glTF writer appends geometry without Blender roundtrip; source metadata/images/materials and other states are unchanged.','Forward DoubleSide derivative only; reverses/shader recipe belong to runtime candidate and are not represented by this standalone GLB.','Old unused target accessors/bufferviews retained to preserve existing references. This inspection GLB is not a web-compressed deployment asset or whole-category package.','Source bridge data still references original geometry; this GLB is not activated in native crop pipeline.']};fs.writeFileSync('docs/qa/frontside-model-pilot/maize-young-leaf-pilot/glb-receipt.json',JSON.stringify(report,null,2)+'\n');geo.dispose();console.log(JSON.stringify(report));
