import {nativeReportStatus} from './lib/frontside-native-report-status.mjs';
// CPU/HTTP only. Placeholder draw fields never become native artifacts.
import crypto from 'node:crypto';import fs from 'node:fs';import zlib from 'node:zlib';
import {deserialize,serialize} from '../src/persistence/snapshots.js';
import {denseNativeYoungMaizeScenario} from './lib/frontside-dense-native-young-maize-scenario.mjs';
import assert from 'node:assert/strict';import {denseWorldYoungMaizeReportPrefix} from './lib/frontside-dense-world-young-maize-report.mjs';
const sha=value=>crypto.createHash('sha256').update(value).digest('hex'),base='http://127.0.0.1:5284',archiveResponse=await fetch(base+'/docs/qa/intensive-gran-rio-suajili-e461b550/state.json.gz');if(!archiveResponse.ok)throw Error('Archive HTTP failed');let bytes=Buffer.from(await archiveResponse.arrayBuffer());const text=(bytes[0]===31&&bytes[1]===139?zlib.gunzipSync(bytes):bytes).toString('utf8'),dense=denseNativeYoungMaizeScenario(deserialize(text));
const payloadResponse=await fetch(base+'/__frontside_candidate/maize-young-leaf-reduction');if(!payloadResponse.ok)throw Error('Payload HTTP failed');const payloadBytes=Buffer.from(await payloadResponse.arrayBuffer()),payload=JSON.parse(payloadBytes);if(sha(payloadBytes)!=='d4796b80770b472ace76372cbb12f75138a294eed8daa0ed8085606f8b2d8335')throw Error('Payload changed');
const report={status:'WORLD_DENSE_YOUNG_MAIZE_GPU_NOT_APPROVED',denseWorldYoungMaizeQa:true,preflightOnly:true,visualAcceptancePolicyVersion:3,viewProfile:'DECLARED_DENSE_NATIVE_WORLD_YOUNG_MAIZE_V1',campaign:'review',qaDepth:'off',vfx:'on',sourceStateSha256:sha(text),workloadStateSha256:sha(serialize(dense.state)),scenario:dense.receipt,candidatePayloadSha256:sha(payloadBytes),candidatePayloadBytes:payloadBytes.length,candidatePayloadFormat:'BLENDER_JSON',candidateMesh:payload.mesh,sourceSha256:payload.sourceSha256,resolution:[1280,720],quality:'media',visualReview:{status:'HUMAN_REVIEW_PENDING',reviewer:null,decision:null},conditions:{gpuTiming:false,bufferReadback:false},cleanup:{closed:true,contextLost:true,errors:[],placeholder:true},errors:[],arms:[]};
// The bounded preflight transports summary identity only; full changed-plant
// provenance belongs to the separate native report (20 MB limit).
delete report.scenario.changed;
assert.equal(nativeReportStatus(report),false);assert.throws(()=>nativeReportStatus({...report,denseWorldYoungMaizeQa:false}),/identity missing/);assert.throws(()=>nativeReportStatus({...report,status:'APPROVED'}),/Unexpected report status/);
for(const campaign of ['review','resources','timing']){const test=structuredClone(report);test.campaign=campaign;test.qaDepth=campaign==='timing'?'front':'off';test.conditions.gpuTiming=campaign==='timing';delete test.arms;if(campaign==='timing')test.timing={blocks:[]};else test.arms=[];assert.match(denseWorldYoungMaizeReportPrefix(test,{preflight:true}),/^maize-young-world-dense-/);const wrong=structuredClone(test);wrong.candidateMesh='maiz_05_maduro';assert.throws(()=>denseWorldYoungMaizeReportPrefix(wrong,{preflight:true}),/candidateMesh/);}
assert.throws(()=>denseWorldYoungMaizeReportPrefix(report),/preflightOnly/);
const response=await fetch(base+'/__frontside_export_preflight',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:'DENSE_WORLD_YOUNG_MAIZE_EXPORT_PREFLIGHT_ONLY',gpuDraws:0,report})}),result=await response.json();if(!response.ok||result.artifactsWritten!==false)throw Error('Dense export preflight failed '+JSON.stringify(result));
const receipt={status:'DENSE_YOUNG_WORLD_HTTP_CPU_PREFLIGHT_PASS_NOT_NATIVE',gpuContextsCreated:0,gpuDraws:0,artifactsWritten:false,archiveHttpBytes:bytes.length,archiveHttpContentType:archiveResponse.headers.get('content-type'),sourceStateSha256:report.sourceStateSha256,workloadStateSha256:report.workloadStateSha256,scenario:{...dense.receipt,changed:undefined},candidatePayloadSha256:report.candidatePayloadSha256,candidatePayloadBytes:payloadBytes.length,exportResult:result,limitations:['No native draw or buffer/actor binding observed.','The preflight synthetic state precedes fixture lighting, pause and VFX setup; its workload hash is not the final native timing state.']};fs.writeFileSync('docs/qa/frontside-model-pilot/maize-young-leaf-pilot/world-http-preflight.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
