// Archive root's completed fixed-case captures. Originals and live prefix untouched.
import fs from 'node:fs';import crypto from 'node:crypto';import {gzipSync} from 'node:zlib';
import {sharedLeafReportPrefix} from './lib/frontside-shared-leaf-report.mjs';
const rootCache='C:/Users/PC/source/repos/wild-guardians-africa/.cache/',folder='docs/qa/frontside-model-pilot/shared-leaf-multiview/',sha=b=>crypto.createHash('sha256').update(b).digest('hex');
if(sha(fs.readFileSync('tests/browser/frontside-crop-leaf-shared-review.js'))!=='60c79fe48cd9ee4f807f4d460814739cf4c8b2c9129f808d5c1d90bc363b0bf6')throw Error('Frozen fixture source changed');
const snapshots=[1,2,7,8].map(index=>{const raw=fs.readFileSync(rootCache+'leaf-review-case'+index+'.json'),png=fs.readFileSync(rootCache+'leaf-review-case'+index+'.png'),report=JSON.parse(raw);sharedLeafReportPrefix(report);if(report.viewCaseIndex!==index||report.contextLost!==true||report.cleanup.errors.length)throw Error('Native identity/cleanup mismatch case'+index);if(png.readUInt32BE(16)!==4096||png.readUInt32BE(20)!==1024)throw Error('Unexpected four-arm capture size');return{index,raw,png,report};});
fs.mkdirSync(folder,{recursive:true});function preserve(file,bytes){if(fs.existsSync(file)&&sha(fs.readFileSync(file))!==sha(bytes))throw Error('Refusing to replace immutable native archive: '+file);fs.writeFileSync(file,bytes);}
const rows=[];for(const {index,raw,png,report} of snapshots){const stem='case'+index,gzip=gzipSync(raw);preserve(folder+stem+'.json.gz',gzip);preserve(folder+stem+'.png',png);rows.push({index,id:report.viewCaseId,json:stem+'.json.gz',png:stem+'.png',rawJsonSha256:sha(raw),gzipSha256:sha(gzip),pngSha256:sha(png),phaseSummary:report.phaseSummary,sourceControls:report.controls,comparisons:report.comparisons.map(({arm,alphaIoU,missingPixels,addedPixels,linearRgbMae,maxTileMae,passes})=>({arm,alphaIoU,missingPixels,addedPixels,linearRgbMae,maxTileMae,historicalDiagnosticWithinThreshold:passes})),shadowUniformAtCapture:report.shadowUniformAtCapture,effectiveShadowDrawCount:report.effectiveShadowDraws.length,materialSides:report.materialSides,cleanup:report.cleanup,contextLost:report.contextLost,visualReview:report.visualReview});}
const manifest={status:'NATIVE_CAPTURES_ARCHIVED_HUMAN_REVIEW_PENDING',visualAcceptancePolicyVersion:3,fixtureSourceCommit:'353036e9fe7d450889530298ba3e8213ecd26f4f',fixtureJsSha256:'60c79fe48cd9ee4f807f4d460814739cf4c8b2c9129f808d5c1d90bc363b0bf6',rows,limitations:['Original runtime report bytes preserved, including its live-prefix capture reference. PNG filenames in this manifest locate the corresponding archived pixels.','Cases7/8 bracket the source bridge and changed mature mesh; they are static samples, not continuous gameplay validation.','Numeric differences are diagnostic under policy3. Assistant observations do not invent a named human decision.','ShadowSide/customDepth remain Double isolation. GPU timing, resident memory and net category benefit are unmeasured.','Process labels in runtime reports are not authoritative liveness inventories; background campaign conditions require root capture records.']};preserve(folder+'manifest.json',Buffer.from(JSON.stringify(manifest,null,2)+'\n'));console.log(JSON.stringify({status:manifest.status,cases:rows.map(r=>({index:r.index,id:r.id,mature:r.phaseSummary[3].matureActive})),gpuBenchmarks:0,humanDecision:null}));
