import fs from 'node:fs';import crypto from 'node:crypto';import zlib from 'node:zlib';import assert from 'node:assert/strict';import * as THREE from 'three';
import {encodeCompactLeafPayload,decodeCompactLeafPayload} from './lib/frontside-compact-leaf-payload.mjs';
import {sharedLeafReverseGeometry} from './lib/frontside-shared-leaf-reverse.mjs';
const sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const source='.cache/frontside-model-pilot/candidates/archive/d4796b80770b472ace76372cbb12f75138a294eed8daa0ed8085606f8b2d8335.json';
const raw=fs.existsSync(source)?fs.readFileSync(source):zlib.gunzipSync(fs.readFileSync('docs/qa/frontside-model-pilot/maize-young-leaf-pilot/blender-payload.json.gz'));assert.equal(sha(raw),'d4796b80770b472ace76372cbb12f75138a294eed8daa0ed8085606f8b2d8335');const payload=JSON.parse(raw);assert.equal(payload.mesh,'maiz_02_joven');
const encoded=encodeCompactLeafPayload(payload),decoded=decodeCompactLeafPayload(encoded.bytes);assert.deepEqual(decoded.faceLabels,payload.faceLabels);assert.deepEqual(decoded.originalCoreFaceIds,payload.originalCoreFaceIds);
assert.deepEqual(Float32Array.from(decoded.corners.flat(2)),Float32Array.from(payload.corners.flat(2)));
const native=sharedLeafReverseGeometry(new THREE.BufferGeometry(),decoded),report=JSON.parse(fs.readFileSync('docs/qa/frontside-model-pilot/maize-young-leaf-reduction-diagnostic.json'));
assert.equal(native.coreTriangles,936);assert.equal(native.leafTriangles,159);assert.equal(native.reverseTriangles,159);
const digest=sha(encoded.bytes),output='.cache/frontside-model-pilot/candidates/archive/'+digest+'.wgleaf';fs.writeFileSync(output,encoded.bytes);
const dir='docs/qa/frontside-model-pilot/maize-young-leaf-pilot';fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(dir+'/blender-payload.json.gz',zlib.gzipSync(raw));
const receipt={status:'CPU_CONTRACT_ONLY_NOT_NATIVE_APPROVAL',mesh:payload.mesh,sourceSha256:payload.sourceSha256,blenderPayloadSha256:sha(raw),binary:output,binarySha256:digest,binaryBytes:encoded.bytes.length,counts:encoded.counts,nativeSharedRecipe:{uniqueVertices:native.uniqueVertices,triangles:native.coreTriangles+native.leafTriangles+native.reverseTriangles,attributeBytes:native.attributeBytes,indexBytes:native.indexBytes,geometryBytes:native.attributeBytes+native.indexBytes,sourceGeometryBytes:report.sourceStateGeometryBytes,geometryByteChangePercent:100*((native.attributeBytes+native.indexBytes)/report.sourceStateGeometryBytes-1),drawGroups:native.geometry.groups},limitations:['CPU Float32 decoder equivalence only; visual/UV interpolation and live growth quality not approved.','936 original core triangles are preserved; their sidedness still requires independent validation.','Native shared reverses reuse PN/UV vertices and draw-level normal recipe; original Blender nine-lane projection is a different cost model, retained unchanged.','Source bridges remain untouched. New topology cannot reuse source face IDs silently; no state or bridge runtime activation.','Binary and geometry are separate costs, not category package, resident coexistence or GPU savings.']};fs.writeFileSync(dir+'/receipt.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));native.geometry.dispose();

