// Generate an isolated frozen QA copy without mutating pending native fixtures.
import fs from 'node:fs';
import crypto from 'node:crypto';
const base='tests/browser/frontside-crop-visual.js';
let source=fs.readFileSync(base,'utf8');
const inputSha256=crypto.createHash('sha256').update(source).digest('hex');
function replaceOnce(before,after){if(source.split(before).length!==2)throw Error('Unexpected fixture source: '+before.slice(0,70));source=source.replace(before,after);}
replaceOnce(" const sidePartition=options.has('sidePartition');", " if(options.get('limit')!=='1'||!options.has('localStemDoubleQuality')||[...options.keys()].some(k=>!['localStemDoubleQuality','limit','cpuCampaigns'].includes(k)))throw Error('Isolated native young-maize Double-only training requires limit1 and no other experiment flags');\n options.set('sidePartition','');options.set('stemOnly','');options.set('preserveDoubleShader','');\n const sidePartition=options.has('sidePartition');");
replaceOnce("if(sorgoStateStem&&arm>1&&(match||species!=='sorgo'))", "if(arm>1&&(match||mesh.name!=='maiz_02_joven'))");
replaceOnce("material.side=arm===3&&group!==1?THREE.FrontSide:THREE.DoubleSide;", "material.side=THREE.DoubleSide;");
replaceOnce("cpuContractAudit=derivedContractAudit||sorgoStateStem?createCropContractAudit():null;", "cpuContractAudit=createCropContractAudit();");
replaceOnce("if(sorgoStateStem){cases.push({growth:1,clock:2.375,biome:'sabana',night:0,elevation:37.5,azimuth:38.75});report.prospectiveCases=cases;report.viewProfile='SORGO_NATIVE_STEM_TRAINING_V1';", "if(true){cases.push({growth:.31,clock:3.0625,biome:'gran-rio',night:0,elevation:46.25,azimuth:57.625});report.prospectiveCases=cases;report.viewProfile='NATIVE_YOUNG_MAIZE_LOCAL_STEM_DOUBLE_TRAINING_V1';report.arms=['original young maize Double','indexed original control Double','native young-maize stem/others grouped Double','same grouped Double repeated'];report.localStemDoubleOnly=true;report.limitations.push('All four arms DoubleSide: no culling/reverse/shader edits, no FrontSide interpretation. Only maiz_02_joven grouped, ALL bridges/other native meshes unchanged. Geometry filter is local, not full-component closure or visual approval.');");
replaceOnce("if(sorgoStateStem)report.sorgoSourceStateCpuContracts=await Promise.all(rigs.map((rig,arm)=>cpuContractAudit.snapshot(rig.group.getObjectByName('sorgo_05_maduro'),arm)));", "report.localStemCpuContracts=await Promise.all(rigs.map((rig,arm)=>cpuContractAudit.snapshot(rig.group.getObjectByName('maiz_02_joven'),arm)));");
replaceOnce("const gl=renderer.getContext(),sourceAssets=new Assets()", "const localFilter=await fetch('/docs/qa/frontside-model-pilot/crop-native-stem-local-filter.json').then(r=>r.json());const localRow=localFilter.states.find(row=>row.mesh==='maiz_02_joven');if(localFilter.status!=='LOCAL_NATIVE_STEM_FILTER_NOT_FRONT_APPROVAL'||!localRow?.localGeometricFilterEligible||localRow.stemTriangles!==245||localRow.sourceTriangles!==1254)throw Error('Native young-maize local source audit contract mismatch');\n const gl=renderer.getContext(),sourceAssets=new Assets()");
replaceOnce("const height=rigs[0].batch.sample(pilotSpecies,growth*cropSpec(pilotSpecies).growth_seconds).height", "for(const rig of rigs){const target=rig.group.getObjectByName('maiz_02_joven');if(!target?.visible||target.count!==1||rig.batch.sample(pilotSpecies,growth*cropSpec(pilotSpecies).growth_seconds).phase!=='original')throw Error('Double-only quality must actually render native young maize, not a bridge/other state');}\n  const height=rigs[0].batch.sample(pilotSpecies,growth*cropSpec(pilotSpecies).growth_seconds).height");
source='// Generated Double-only local stem quality snapshot; no production activation.\n'+source;
const output='tests/browser/frontside-crop-local-stem-double.js';fs.writeFileSync(output,source);
const receipt={status:'ISOLATED_DOUBLE_ONLY_FIXTURE_NOT_APPROVED',input:base,inputSha256,output,outputSha256:crypto.createHash('sha256').update(source).digest('hex'),target:'maiz_02_joven',growth:.31,clock:3.0625,biome:'gran-rio',night:0,elevation:46.25,azimuth:57.625};
fs.writeFileSync('docs/qa/frontside-model-pilot/local-stem-double-fixture-receipt.json',JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt));
