import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {installLiveGrowthBufferProbe} from './lib/frontside-live-growth-buffer-probe.mjs';
function fixture(){
 const geometry=new THREE.BufferGeometry(),growth=new THREE.InstancedBufferAttribute(new Float32Array([1,1,1,0,1,1,1,2]),4);geometry.setAttribute('iGrowth',growth);const mesh=new THREE.InstancedMesh(geometry,new THREE.MeshStandardMaterial(),2);mesh.name='maiz_05_maduro';
 const cpu=()=>new Uint8Array(growth.array.buffer),buffer={bytes:cpu().slice()},originalBinding={bytes:new Uint8Array(4)},program={},calls=[];
 const gl={CURRENT_PROGRAM:35725,ARRAY_BUFFER_BINDING:34964,ARRAY_BUFFER:34962,BUFFER_SIZE:34660,FLOAT:5126,VERTEX_ATTRIB_ARRAY_BUFFER_BINDING:34975,VERTEX_ATTRIB_ARRAY_SIZE:34339,VERTEX_ATTRIB_ARRAY_TYPE:34341,VERTEX_ATTRIB_ARRAY_NORMALIZED:34922,VERTEX_ATTRIB_ARRAY_STRIDE:34340,VERTEX_ATTRIB_ARRAY_POINTER:34373,VERTEX_ATTRIB_ARRAY_DIVISOR:35070,VERTEX_ATTRIB_ARRAY_ENABLED:34338,binding:originalBinding,
  getParameter(name){return name===this.CURRENT_PROGRAM?program:this.binding;},getAttribLocation(){return 3;},getVertexAttrib(_location,name){return new Map([[this.VERTEX_ATTRIB_ARRAY_BUFFER_BINDING,buffer],[this.VERTEX_ATTRIB_ARRAY_SIZE,4],[this.VERTEX_ATTRIB_ARRAY_TYPE,this.FLOAT],[this.VERTEX_ATTRIB_ARRAY_NORMALIZED,false],[this.VERTEX_ATTRIB_ARRAY_STRIDE,16],[this.VERTEX_ATTRIB_ARRAY_DIVISOR,1],[this.VERTEX_ATTRIB_ARRAY_ENABLED,true]]).get(name);},getVertexAttribOffset(){return 0;},isBuffer(value){return value===buffer;},bindBuffer(_target,value){this.binding=value;},getBufferParameter(){return this.binding.bytes.length;},getBufferSubData(_target,_offset,out){if(this.failReadback)throw Error('injected readback failure');out.set(this.binding.bytes);},drawElements(...args){calls.push(args);return 'native draw delegated';}
 };
 return{mesh,growth,buffer,gl,calls,originalBinding,cpu,renderer:{getContext:()=>gl},dispose(){geometry.dispose();mesh.material.dispose();mesh.dispose();}};
}
test('draw probe observes match, stale upload and updated bytes without changing array binding',()=>{const f=fixture(),before=f.gl.drawElements,probe=installLiveGrowthBufferProbe(f.renderer,f.mesh,{label:()=> 'CPU-mock-not-native'});f.mesh.onBeforeRender();f.gl.drawElements(4,3,5123,0);assert.equal(probe.snapshot().records.length,0);probe.capture(true);assert.equal(f.gl.drawElements(4,3,5123,0),'native draw delegated');assert.equal(f.gl.binding,f.originalBinding);f.growth.setX(0,.5);f.growth.needsUpdate=true;f.gl.drawElements(4,3,5123,0);f.buffer.bytes=f.cpu().slice();f.gl.drawElements(4,3,5123,0);probe.capture(false);f.mesh.onAfterRender();const r=probe.snapshot();assert.deepEqual(r.records.map(v=>v.status),['BOUND_GPU_BYTES_MATCH_CPU','BOUND_GPU_BYTES_DIFFER','BOUND_GPU_BYTES_MATCH_CPU']);assert.ok(r.records[1].changedBytes>0);assert.equal(r.records[0].bufferToken,r.records[2].bufferToken);assert.equal(r.records[2].cpuVersion,f.growth.version);assert.equal(f.calls.length,4);probe.dispose();assert.equal(f.gl.drawElements,before);f.dispose();});
test('readback failure restores binding and delegates draw; budget exhaustion performs no readback',()=>{const f=fixture(),probe=installLiveGrowthBufferProbe(f.renderer,f.mesh);probe.capture(true);f.mesh.onBeforeRender();f.gl.failReadback=true;assert.equal(f.gl.drawElements(4,3,5123,0),'native draw delegated');assert.equal(f.gl.binding,f.originalBinding);assert.equal(probe.snapshot().errors.length,1);probe.dispose();const limited=installLiveGrowthBufferProbe(f.renderer,f.mesh,{readbackByteLimit:1});limited.capture(true);f.mesh.onBeforeRender();f.gl.drawElements(4,3,5123,0);assert.equal(limited.snapshot().records[0].status,'READBACK_BUDGET_EXHAUSTED');assert.equal(limited.snapshot().readBytes,0);assert.equal(f.gl.binding,f.originalBinding);limited.dispose();f.dispose();});
