import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {readGlb,writeGlb} from './glb-container.mjs';import {createCropBatch} from '../src/rendering/crop-batch.js';import {sharedLeafReverseGeometry} from './lib/frontside-shared-leaf-reverse.mjs';import {decodeCompactLeafPayload} from './lib/frontside-compact-leaf-payload.mjs';import {youngLeafReviewCases} from './lib/frontside-young-leaf-review-cases.mjs';import validator from 'gltf-validator';
const dir='docs/qa/frontside-model-pilot/maize-young-leaf-pilot/',receipt=JSON.parse(fs.readFileSync(dir+'receipt.json')),exportReceipt=JSON.parse(fs.readFileSync(dir+'glb-receipt.json')),raw=fs.readFileSync('public/assets/'+receipt.sourceSha256+'.glb'),{json,bin}=readGlb(raw),sha=b=>crypto.createHash('sha256').update(b).digest('hex');assert.equal(sha(raw),receipt.sourceSha256);
const validation=await validator.validateBytes(new Uint8Array(fs.readFileSync(exportReceipt.output)),{maxIssues:100});assert.equal(validation.issues.numErrors,0);fs.writeFileSync(dir+'glb-validator.json',JSON.stringify(validation,null,2)+'\n');
function stripTextures(o){if(!o||typeof o!=='object')return;for(const k of Object.keys(o))if(k.endsWith('Texture'))delete o[k];else stripTextures(o[k]);}stripTextures(json.materials);delete json.images;delete json.textures;
const gltf=await new GLTFLoader().parseAsync(writeGlb(json,bin).buffer,''),bridges=JSON.parse(fs.readFileSync('public/content/crop-bridges.json')),payload=decodeCompactLeafPayload(fs.readFileSync(receipt.binary)),rigs=Array.from({length:2},()=>{const group=new THREE.Group();return{group,batch:createCropBatch(group,{capabilities:{getMaxAnisotropy:()=>1}},gltf,bridges,4)};}),target=rigs[1].group.getObjectByName(payload.mesh),source=target.geometry,material=target.material,depth=target.customDepthMaterial,borrowed=source.getAttribute('iGrowth'),derived=sharedLeafReverseGeometry(source,payload,{reverseLeaves:false}).geometry;target.geometry=derived;
assert.equal(derived.getAttribute('iGrowth'),borrowed);assert.equal(target.material,material);assert.equal(target.customDepthMaterial,depth);const rows=[];
for(const view of youngLeafReviewCases)for(const clock of [view.clock,view.clock+.75]){const plants=[{id:'young-qa',species:'maiz',growth:view.growth*270,x:2,z:3,rotation:.7,seed:.31}];for(const r of rigs)r.batch.update(plants,clock,()=>.2);const sample=rigs[0].batch.sample('maiz',view.growth*270);assert.equal(sample.phase,view.expectedPhase);assert.equal(target.visible&&target.count>0,view.expectedYoungActive);rigs[0].group.traverse(mesh=>{if(!mesh.isInstancedMesh)return;const other=rigs[1].group.getObjectByName(mesh.name);assert.equal(other.count,mesh.count);assert.equal(other.visible,mesh.visible);assert.deepEqual(other.instanceMatrix.array,mesh.instanceMatrix.array);for(const name of ['iGrowth','iBridge'])if(mesh.geometry.getAttribute(name))assert.deepEqual(other.geometry.getAttribute(name).array,mesh.geometry.getAttribute(name).array);});rows.push({id:view.id,growth:view.growth,clock,phase:sample.phase,stage:sample.stage,targetActive:target.visible&&target.count>0});}
target.geometry=source;for(const[name,a]of Object.entries(derived.attributes))if(a===source.getAttribute(name))derived.deleteAttribute(name);derived.dispose();assert.equal(source.getAttribute('iGrowth'),borrowed);assert.equal(target.material,material);assert.equal(target.customDepthMaterial,depth);for(const r of rigs)r.batch.dispose();
const report={status:'YOUNG_NATIVE_BATCH_CPU_CONTRACT_PASS',sourceSha256:sha(raw),payloadSha256:receipt.binarySha256,bridgeSha256:sha(fs.readFileSync('public/content/crop-bridges.json')),glbValidatorErrors:validation.issues.numErrors,glbValidatorWarnings:validation.issues.numWarnings,rows,originalDerivedInstancesAndDriversExact:true,materialAndDepthIdentityPreserved:true,borrowedAttributeIdentityAfterDetach:true,limitations:['Texture references stripped only in CPU parse; this does not assess GPU texels, UV appearance, wind rendering or shadow appearance.','All four native bridge geometry/attributes remain unchanged and are compared, not remapped to derived faces.','Young model replacement only; no actual Game biology or worker rig validation.','Shader clock updated through real batch but no renderer upload/continuity evidence.']};fs.writeFileSync(dir+'runtime-contract.json',JSON.stringify(report,null,2)+'\n');console.log('PASS: validator errors0, '+rows.length+' native batch states/clocks, phase/instances/drivers/material/depth/borrowed ownership CPU contracts.');
