import test from 'node:test';import assert from 'node:assert/strict';import * as THREE from 'three';
import {installWorldMaizeQaAdapter} from './lib/frontside-world-maize-adapter.mjs';import {AfricanToon} from '../src/rendering/african-toon.js';import {SceneMaterialRegistry} from '../src/rendering/material-registry.js';
const corners=[[[0,0,0,0,1,0,0,0],[1,0,0,0,1,0,1,0],[0,0,1,0,1,0,0,1]],[[0,1,0,0,1,0,0,0],[1,1,0,0,1,0,1,0],[0,1,1,0,1,0,0,1]]],payload={status:'BLENDER_REMODELLING_TRAINING_NOT_APPROVED',mesh:'maiz_05_maduro',sourceSha256:'test-original-immutable',corners,faceLabels:[0,2],originalCoreFaceIds:[0]};
function setup(){const scene=new THREE.Scene(),toon=new AfricanToon(),materialRegistry=new SceneMaterialRegistry(scene,toon),state={plants:[{id:'1',species:'maiz',growth:270,alive:true}]},world={scene,toon,materialRegistry,state};
 function batch(capacity){const geo=new THREE.BufferGeometry(),material=new THREE.MeshStandardMaterial({side:THREE.DoubleSide});geo.setAttribute('position',new THREE.Float32BufferAttribute([0,0,0,1,0,0,0,0,1],3));geo.setAttribute('normal',new THREE.Float32BufferAttribute([0,1,0,0,1,0,0,1,0],3));geo.setAttribute('uv',new THREE.Float32BufferAttribute([0,0,1,0,0,1],2));geo.setIndex([0,1,2]);geo.setAttribute('iGrowth',new THREE.InstancedBufferAttribute(new Float32Array(capacity*4),4));const mesh=new THREE.InstancedMesh(geo,material,capacity);mesh.name=payload.mesh;scene.add(mesh);const result={capacity,mesh,originalGeometry:geo,originalMaterial:material,sample(){return{phase:'original',stage:4};},dispose(){assert.equal(mesh.geometry,geo);assert.equal(mesh.material,material);scene.remove(mesh);mesh.dispose();geo.dispose();material.dispose();}};return result;}
 world.cropBatch=batch(4);return{world,batch};}
test('QA adapter preserves native state/live growth and scalar disposal contract',()=>{const {world}=setup(),original=world.cropBatch,stateBefore=JSON.stringify(world.state),growth=original.originalGeometry.getAttribute('iGrowth'),sample=original.sample,adapter=installWorldMaizeQaAdapter(world,payload);assert.equal(world.cropBatch.sample,sample);assert.equal(original.mesh.geometry.getAttribute('iGrowth'),growth);assert.equal(JSON.stringify(world.state),stateBefore);assert.deepEqual(adapter.snapshot().materialSides,[0,0,0]);assert.deepEqual(adapter.snapshot().shadowSides,[2,2,2]);assert.equal(world.materialRegistry.nodes.has(original.mesh),false);const shader={vertexShader:THREE.ShaderLib.standard.vertexShader,fragmentShader:THREE.ShaderLib.standard.fragmentShader,uniforms:{}};original.mesh.material[0].onBeforeCompile(shader,{});assert.equal((shader.vertexShader.match(/varying vec3 vToonWorld;/g)||[]).length,1);adapter.dispose();assert.equal(original.mesh.geometry,original.originalGeometry);assert.equal(original.mesh.material,original.originalMaterial);assert.equal(world.materialRegistry.nodes.has(original.mesh),true);assert.equal(Object.getOwnPropertyDescriptor(world,'cropBatch').writable,true);world.cropBatch.dispose();world.materialRegistry.dispose();});
test('native capacity recreation reapplies candidate with fresh growth then cleans once',()=>{const {world,batch}=setup(),adapter=installWorldMaizeQaAdapter(world,payload),first=world.cropBatch;first.dispose();const second=batch(8);world.cropBatch=second;assert.equal(adapter.snapshot().capacity,8);assert.equal(second.mesh.geometry.getAttribute('iGrowth'),second.originalGeometry.getAttribute('iGrowth'));assert.notEqual(second.mesh.geometry.getAttribute('iGrowth'),first.originalGeometry.getAttribute('iGrowth'));second.dispose();adapter.dispose();adapter.dispose();assert.equal(adapter.events.filter(e=>e.event==='installed').length,2);assert.equal(adapter.events.filter(e=>e.event==='restored').length,2);assert.equal(world.cropBatch,second);world.materialRegistry.dispose();});

test('authored Front world depth borrows native growth recipe and restores separately from shadows',()=>{const {world}=setup(),mesh=world.cropBatch.mesh,shadow=new THREE.MeshDepthMaterial({side:THREE.DoubleSide}),previous=new THREE.MeshDepthMaterial();shadow.userData.worldDepthCompatible=true;shadow.userData.nativeShadowInputs=()=>[.1,1,2,3];shadow.onBeforeCompile=shader=>{shader.uniforms.uClock={value:2};shader.vertexShader+='\n// native growth';};shadow.customProgramCacheKey=()=> 'native-growth-test';mesh.customDepthMaterial=shadow;mesh.customWorldDepthMaterial=previous;const adapter=installWorldMaizeQaAdapter(world,payload,{worldDepth:true}),depth=mesh.customWorldDepthMaterial;assert.notEqual(depth,shadow);assert.equal(depth.side,THREE.FrontSide);assert.equal(depth.onBeforeCompile,shadow.onBeforeCompile);assert.equal(depth.userData.nativeShadowInputs,shadow.userData.nativeShadowInputs);assert.equal(mesh.customDepthMaterial,shadow);assert.equal(shadow.side,THREE.DoubleSide);let disposed=0;depth.addEventListener('dispose',()=>disposed++);adapter.dispose();assert.equal(mesh.customWorldDepthMaterial,previous);assert.equal(mesh.customDepthMaterial,shadow);assert.equal(disposed,1);world.cropBatch.dispose();shadow.dispose();previous.dispose();world.materialRegistry.dispose();});
