import fs from 'node:fs';import assert from 'node:assert/strict';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {readGlb,writeGlb} from './glb-container.mjs';import {decodeCompactLeafPayload} from './lib/frontside-compact-leaf-payload.mjs';import {createYoungLeafFrontRuntimeRigs} from './lib/frontside-young-leaf-front-runtime-rigs.mjs';import {createQaResourceScope} from './lib/frontside-qa-resource-scope.mjs';import {youngLeafContinuousPlan} from './lib/frontside-young-leaf-continuous-plan.mjs';import {youngLeafContinuousReportPrefix} from './lib/frontside-young-leaf-continuous-report.mjs';import {sourceFineIdentity} from './lib/frontside-source-fine-report.mjs';
const dir='docs/qa/frontside-model-pilot/maize-young-leaf-pilot/',receipt=JSON.parse(fs.readFileSync(dir+'receipt.json')),{json,bin}=readGlb(fs.readFileSync('public/assets/'+receipt.sourceSha256+'.glb'));function strip(o){if(!o||typeof o!=='object')return;for(const k of Object.keys(o))if(k.endsWith('Texture'))delete o[k];else strip(o[k]);}strip(json.materials);delete json.images;delete json.textures;
const gltf=await new GLTFLoader().parseAsync(writeGlb(json,bin).buffer,''),scope=createQaResourceScope(),scene=new THREE.Scene(),runtime=createYoungLeafFrontRuntimeRigs({scene,renderer:{capabilities:{getMaxAnisotropy:()=>1}},gltf,bridges:JSON.parse(fs.readFileSync('public/content/crop-bridges.json')),payload:decodeCompactLeafPayload(fs.readFileSync(receipt.binary)),capacity:16,scope,wrapSourceMaterials(){}}),rows=[];
const target=runtime.rigs[3].target,original=runtime.rigs[0].target,frontGeometry=target.geometry;
assert.equal(frontGeometry.getAttribute('position').count,1921);assert.equal(frontGeometry.index.count/3,1254);assert.equal(frontGeometry.groups.length,3);assert.deepEqual(frontGeometry.groups.map(g=>g.count),[2808,477,477]);assert.ok(target.material.every(m=>m.side===0&&m.shadowSide===2&&Object.hasOwn(m.defines,'DOUBLE_SIDED')));
const index=frontGeometry.index.array;for(let i=0;i<159;i++){const f=2808+i*3,r=3285+i*3;assert.deepEqual([...index.slice(r,r+3)],[index[f],index[f+2],index[f+1]]);}
const shader={uniforms:{},vertexShader:'#include <begin_vertex>\n#include <beginnormal_vertex>',fragmentShader:'#include <normal_fragment_begin>\nbool facing=gl_FrontFacing;'};target.material[2].onBeforeCompile(shader,{});assert.ok(shader.vertexShader.includes('breeze'));assert.ok(shader.fragmentShader.includes('bool facing=false'));assert.ok(!shader.fragmentShader.includes('gl_FrontFacing'));
for(const seam of[0,1]){const plan=youngLeafContinuousPlan(seam);for(let step=0;step<=32;step++){const elapsed=step/2,growth=plan.growthStart+elapsed/270,clock=plan.windClockStart+elapsed,plants=[{id:'front-young',species:'maiz',growth:growth*270,x:2,z:3,seed:.31}];for(const r of runtime.rigs)r.batch.update(plants,clock,()=>0);const state=runtime.rigs.map(({arm,batch,target})=>{const s=batch.sample('maiz',growth*270);return{arm,phase:s.phase,stage:s.stage,youngActive:target.visible&&target.count>0};});runtime.rigs[0].group.traverse(m=>{if(!m.isInstancedMesh)return;for(const r of runtime.rigs.slice(1)){const other=r.group.getObjectByName(m.name);assert.equal(other.count,m.count);assert.equal(other.visible,m.visible);assert.deepEqual(other.instanceMatrix.array,m.instanceMatrix.array);for(const lane of ['iGrowth','iBridge'])if(m.geometry.getAttribute(lane))assert.deepEqual(other.geometry.getAttribute(lane).array,m.geometry.getAttribute(lane).array);}});rows.push({seam,elapsed,growth,clock,state});}}
const sourceReferencedVertices=new Set(original.geometry.index.array).size,perGroupReferencedVertices=frontGeometry.groups.map(g=>new Set(frontGeometry.index.array.slice(g.start,g.start+g.count)).size),geometryBytes=Object.entries(frontGeometry.attributes).filter(([name])=>['position','normal','uv'].includes(name)).reduce((sum,[,a])=>sum+a.array.byteLength,0)+frontGeometry.index.array.byteLength;
const cleanup=scope.cleanup();assert.equal(cleanup.errors.length,0);const report={status:'YOUNG_FRONT_SHARED_REVERSE_CPU_CONTRACT_ONLY',triangles:1254,vertices:1921,groups:[2808,477,477],geometryBytes,sourceReferencedVertices,perGroupReferencedVertices,perGroupReferenceSum:perGroupReferencedVertices.reduce((a,b)=>a+b,0),vertexReferenceMeaning:'Unique index references per draw group are an invocation proxy, not measured vertex shader executions or cross-draw cache reuse.',resources:runtime.resources,rows,cleanup,backRecipeTextualCheck:true,limitations:['Actual shared reverse indices/normals/UVs and procedural instance/bridge lanes tested in CPU only.','Shader textual check includes native growth and reversed face normal recipe, without a GPU/compiler or material texture inspection.','Target source contains no skin/morph targets; native procedural bridges remain original.','No native colour/shadow/cull or visual acceptance; resources exclude resident coexistence and benefit must be measured separately.']};fs.writeFileSync(dir+'front-runtime-contract.json',JSON.stringify(report,null,2)+'\n');console.log('PASS Front candidate CPU:1254tri/1921verts/threegroups/shared reverses,66 updates and borrowed ownership cleanup.');

