// Generate an independent prospective fixture; never rewrite frozen continuous QA.
import fs from 'node:fs';import crypto from 'node:crypto';
const source=fs.readFileSync('tests/browser/frontside-crop-leaf-shared-continuous.js','utf8');
if(crypto.createHash('sha256').update(source).digest('hex')!=='2f11e4ec6dab786272d894b70e2f97c96eef2b993e911c13ba0f362177f5441e')throw Error('Frozen continuous template changed');
let prefix=source.slice(0,source.indexOf(' function draw('));
prefix=prefix.replace("import {createQaResourceScope}","import {createGpuQueryRecorder} from '../../tools/lib/frontside-gpu-query-recorder.mjs';import {installBufferStorageAudit} from '../../tools/lib/frontside-gpu-buffer-budget.mjs';import {sharedLeafGpuPlan,pairedArmSchedule,analysePairedGpu} from '../../tools/lib/frontside-paired-gpu-analysis.mjs';\nimport {createQaResourceScope}");
prefix=prefix.replace(/const query=new URLSearchParams\(location.search\),mode=query.get\('mode'\)[\s\S]*?if\(cropSpec/,"const query=new URLSearchParams(location.search),mode='game',night=0,campaign=query.get('campaign')??'timing';if(!['timing','resources'].includes(campaign)||[...query.keys()].some(k=>!['campaign','cpuCampaigns'].includes(k)))throw Error('Unexpected prospective GPU campaign');if(cropSpec");
prefix=prefix.replace('const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:true});',"const canvas=document.createElement('canvas'),contextOptions={antialias:true,alpha:false,depth:true,stencil:false,premultipliedAlpha:true,preserveDrawingBuffer:true,powerPreference:'default'},gl=canvas.getContext('webgl2',contextOptions);if(!gl)throw Error('WebGL2 unavailable');const bufferAudit=campaign==='resources'?installBufferStorageAudit(gl):null;const renderer=new THREE.WebGLRenderer({canvas,context:gl,...contextOptions});");
prefix=prefix.replace('new THREE.PlaneGeometry(28,28)','new THREE.PlaneGeometry(80,80)').replace('capacity:64','capacity:2048').replace('length:plan.plants','length:1089').replace('i%plan.grid-3','i%33-16').replace('Math.floor(i/plan.grid)-3','Math.floor(i/33)-16');
const tail=String.raw`
 camera.aspect=1280/720;camera.updateProjectionMatrix();const fixedGrowth=1,fixedClock=1.75;
 for(const plant of plants)plant.growth=fixedGrowth*plan.growthSeconds;
 for(const {batch} of runtime.rigs)batch.update(plants,fixedClock,()=>0);
 toon.update(night,sun,plan.biome);registry.update(fixedClock);
 function draw(arm){scope.assertOpen();activeArm=arm;lastShadowDraws=[];runtime.select(arm);renderer.info.reset();renderer.setViewport(0,0,1280,720);renderer.setScissorTest(false);renderer.autoClear=false;renderer.clear();sky.render(renderer,camera,skyState);renderer.render(scene,camera);}
 const gpuInfo=gl.getExtension('WEBGL_debug_renderer_info');
 const report={status:'GPU_CANDIDATE_EXPERIMENT_NOT_APPROVED',sharedLeafGpuNet:true,visualAcceptancePolicyVersion:3,campaign,source,sourceOriginal:mapping.source,runtimeSource:mapping.runtime,sourceMapping:{source:mapping.source,runtime:mapping.runtime,sourceSha256:mapping.sourceSha256,runtimeSha256:mapping.runtimeSha256},archiveSha256,viewProfile:'SHARED_LEAF_MATURE_NET_GPU_V1',plantCount:1089,growth:fixedGrowth,clock:fixedClock,resolution:[1280,720],cameraFov:camera.fov,cameraPosition:camera.position.toArray(),cameraTarget:plan.target,contextAttributes:gl.getContextAttributes(),gpu:gpuInfo?gl.getParameter(gpuInfo.UNMASKED_RENDERER_WEBGL):gl.getParameter(gl.RENDERER),browser:navigator.userAgent,resources:runtime.resources,materialSides:runtime.rigs.map(({arm,target})=>({arm,sides:(Array.isArray(target.material)?target.material:[target.material]).map(m=>m.side),shadowSides:(Array.isArray(target.material)?target.material:[target.material]).map(m=>m.shadowSide)})),campaignConditions:{cpuCampaigns:query.get('cpuCampaigns')??'unspecified',gpuTiming:campaign==='timing',bufferMetadataQueries:campaign==='resources'},blocks:[],limitations:['Representative synthetic dense mature maize lot with native sky/materials/shadows and simple receiver, not full mixed WorldScene.','Original0 versus shared-reverse Front color3; both retain Double shadows. Net query includes sky, color and current native shadow submissions.','Four CPU rigs coexist; original and candidate GPU allocation coexistence is reported separately from hypothetical standalone deployment.','Fixed growth/wind/camera/lights preserve submitted workload. No reduction/indexing-only gain or category benefit is inferred.','Pixel metrics are diagnostic under policy3; appearance and compatibility acceptance remain independent.']};
 let frame=0;
 if(campaign==='resources'){
  report.bufferSnapshots=[bufferAudit.snapshot('before-first-draw')];
  for(const arm of [0,3]){bufferAudit.setPhase('warm-arm-'+arm);for(let i=0;i<120;i++){await raf();draw(arm);}report.bufferSnapshots.push(bufferAudit.snapshot('after-arm-'+arm));report.blocks.push({arm,warmupFrames:120,submissions:{...renderer.info.render},rendererMemory:{...renderer.info.memory},programCount:renderer.info.programs.length,shadowDraws:lastShadowDraws,states:stateAt(fixedGrowth)});}
 }else{
  collection:for(const {pair,order,arms} of pairedArmSchedule(0,3))for(const arm of arms){
   status.textContent='Warmup pair '+pair+' '+order+' arm '+arm;
   for(let i=0;i<sharedLeafGpuPlan.warmupFrames;i++){await raf();draw(arm);}
   const recorder=createGpuQueryRecorder(gl);scope.defer('query recorder '+pair+'-'+arm,()=>recorder.dispose());
   if(!recorder.snapshot().supported)throw Error('EXT_disjoint_timer_query_webgl2 unavailable');
   for(let i=0;i<sharedLeafGpuPlan.samplesPerBlock;i++){await raf();recorder.poll();const begun=recorder.begin(frame++);try{draw(arm);}finally{if(begun)recorder.end();}status.textContent='Pair '+pair+' '+order+' arm '+arm+', submitted '+(i+1)+'/'+sharedLeafGpuPlan.samplesPerBlock;}
   gl.flush();for(let i=0;i<240&&recorder.snapshot().pending;i++){await raf();scope.assertOpen();recorder.poll();}
   const gpu=recorder.snapshot();recorder.dispose();report.blocks.push({pair,order,arm,warmupFrames:sharedLeafGpuPlan.warmupFrames,gpu,submissions:{...renderer.info.render},rendererMemory:{...renderer.info.memory},programCount:renderer.info.programs.length,shadowDraws:lastShadowDraws,states:stateAt(fixedGrowth)});
   if(gpu.pending||gpu.disjointEvents||gpu.discarded||gpu.overflowSkipped||gpu.foreignQuerySkipped||gpu.allocationFailures||gpu.contextLost||gpu.samples.length!==sharedLeafGpuPlan.samplesPerBlock){report.invalidCollection='Elapsed query block incomplete/invalid. No reroll.';break collection;}
  }
  try{report.analysis=analysePairedGpu(report.blocks);}catch(error){report.analysisError=error.message;}
 }
 report.capturePng=canvas.toDataURL('image/png');const retained=document.createElement('img');retained.src=report.capturePng;retained.alt='Final frozen dense crop draw; not a four-arm visual review';await retained.decode();document.querySelector('#view').replaceChildren(retained);report.cleanup=scope.cleanup();report.contextLost=gl.isContextLost();if(bufferAudit)report.bufferAudit=bufferAudit.finish();
 const details=document.createElement('pre'),{capturePng,...visible}=report;details.textContent=JSON.stringify(visible,null,2);document.querySelector('#view').after(details);const exported=await fetch('/__frontside_report',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(report)});if(!exported.ok)throw Error(await exported.text());status.textContent='GPU experiment exported, cleanup complete. NO CATEGORY APPROVAL.';
 }finally{lastCleanup=scope.cleanup();if(activeScope===scope)activeScope=null;}}
document.querySelector('#stop').onclick=()=>{status.textContent+='\nCancelled '+JSON.stringify(activeScope?.cleanup());};button.onclick=async()=>{button.disabled=true;try{await run();}catch(error){status.textContent=error.stack+'\nCleanup '+JSON.stringify(lastCleanup);}};button.disabled=false;status.textContent='Prepared prospectively: no GPU until click and coordinated window.';
`;
fs.writeFileSync('tests/browser/frontside-crop-leaf-shared-gpu.js',prefix+tail);
fs.writeFileSync('tests/browser/frontside-crop-leaf-shared-gpu.html',`<!doctype html><html lang="es"><meta charset="utf-8"><title>GPU neto de maíz derivado</title><style>body{font:16px system-ui;background:#10211f;color:#e4f1e8;margin:24px}button{padding:12px}pre{white-space:pre-wrap}img,canvas{max-width:90vw}</style><h1>GPU neto: original0 y derivado3</h1><p>1089 plantas maduras, seis pares AB/BA, consultas EXT GPU. Campaña de recursos separada. Sombras Double aisladas, no WorldScene completo ni aprobación de categoría.</p><button id="run" disabled>Ejecutar campaña coordinada</button><button id="stop">Liberar GPU</button><pre id="status">Cargando…</pre><div id="view"></div><script type="module" src="./frontside-crop-leaf-shared-gpu.js"></script></html>\n`);
console.log('Independent GPU fixture generated; not executed.');
