// Offline bridge deformation diagnosis, not camera visibility or pixel fitting.
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {readGlb,writeGlb} from './glb-container.mjs';
import {createCropBatch} from '../src/rendering/crop-batch.js';
import {cropSpec} from '../src/simulation/rules.js';
const folder='docs/qa/frontside-model-pilot/',receipt=JSON.parse(await readFile(folder+'selective-candidate-receipts.json','utf8')).find(r=>r.category==='crops');
const raw=await readFile('public'+receipt.source),bridgeRaw=await readFile('public/content/crop-bridges.json'),data=JSON.parse(bridgeRaw),source=await readFile('src/rendering/crop-batch.js','utf8'),shader=source.match(/const BRIDGE_DECL=`([\s\S]*?)`;/)?.[1];
const sha=b=>createHash('sha256').update(b).digest('hex');if(sha(raw)!==receipt.sourceSha256||!shader)throw Error('Source shader mismatch');
const {json,bin}=readGlb(raw);function strip(o){if(!o||typeof o!=='object')return;for(const k of Object.keys(o)){if(k.endsWith('Texture'))delete o[k];else strip(o[k]);}}strip(json.materials);delete json.images;delete json.textures;
const gltf=await new GLTFLoader().parseAsync(writeGlb(json,bin).buffer,''),scene=new THREE.Scene(),batch=createCropBatch(scene,{capabilities:{getMaxAnisotropy:()=>1}},gltf,data,1);
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x)),mix=(a,b,t)=>a+(b-a)*t,smooth=(a,b,x)=>{const t=clamp((x-a)/(b-a),0,1);return t*t*(3-2*t);},ease=x=>{const t=clamp(x,0,1);return t*t*t*(t*(t*6-15)+10);};
const vec=(a,i)=>[a.getX(i),a.getY(i),a.getZ(i)],sub=(a,b)=>a.map((x,i)=>x-b[i]),cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]],dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0),normalize=a=>{const n=Math.hypot(...a);return n?a.map(v=>v/n):[NaN,NaN,NaN];};
const rows=[],marks=[.065,.27,.53,.78,1],cycle=cropSpec('maiz').growth_seconds;
for(let pairIndex=0;pairIndex<4;pairIndex++){
 const pair=data.pairs.find(p=>p.a===pairIndex&&p.b===pairIndex+1),meta=[pair.a,pair.b].map(model=>json.nodes.find(n=>n.extras?.cropIndex===0&&n.extras.stage===model+1).extras),mesh=scene.children.find(m=>m.name===`puente_maiz_${pairIndex+1}_${pairIndex+2}`),g=mesh.geometry;
 const labels=[...data.models[pair.a].faceLabels,...data.models[pair.b].faceLabels],stemFaces=labels.flatMap((label,face)=>label===1?[face]:[]),width=Math.min(.34,2/((marks[pairIndex+1]-marks[pairIndex])*cycle));
 for(const t of [.0625,.1875,.3125,.4375,.5625,.6875,.8125,.9375])for(const clock of [.5,2.25,4.75,6.5])for(const seed of [0,17]){
  const growth=mix(marks[pairIndex],marks[pairIndex+1],.81-width*.5+width*t);batch.update([{id:'bridge-audit',species:'maiz',growth:growth*cycle,x:0,z:0,seed}],clock,()=>0);if(mesh.count!==1||!mesh.visible)throw Error('Actual bridge not active');
  const ib=Array.from(g.attributes.iBridge.array.subarray(0,4));
  function base(p,role){const H=mix(meta[0].height,meta[1].height,ib[1]),R=mix(meta[0].foliageRadius,meta[1].foliageRadius,ib[1]),own=meta[role],sy=(H-.1)/Math.max(.12,own.height-.1),sr=clamp(R/Math.max(.08,own.foliageRadius),.25,2.8),pm=smooth(.1,.22,p[1]),above=Math.max(0,p[1]-.1),lm=pm*smooth(.035,.22,Math.hypot(p[0],p[2])),fold=role*(1-mix(.70,1,ib[1])),h=clamp(above/Math.max(.15,own.height-.1),0,1),breeze=(Math.sin(clock*1.55+ib[2])*.017+Math.sin(clock*2.71+ib[2]*1.7)*.009)*h**1.7*pm;return[p[0]*mix(1,sr,pm)*(1-lm*fold*.16)+breeze,p[1]+above*(mix(1,sy,pm)-1)+lm*fold*(.10+above*.12),p[2]*mix(1,sr,pm)*(1-lm*fold*.16)+breeze*.47];}
  function deform(v){const p=vec(g.attributes.position,v),n=vec(g.attributes.normal,v),role=g.attributes.aPart.getX(v),kind=g.attributes.aPart.getY(v);if(kind!==1)throw Error('Stem driver mismatch');const time=ease(ib[0]+g.attributes.aPart.getZ(v)*Math.sin(Math.PI*ib[0])*.055),away=mix(time,1-time,role),scale=Math.sqrt(Math.max(0,1-away)),root=base(vec(g.attributes.aRoot,v),role),peer=base(vec(g.attributes.aPeerRoot,v),1-role),pivot=root.map((x,i)=>mix(x,peer[i],away)),out=base(p,role);out[0]=mix(pivot[0],out[0],scale);out[2]=mix(pivot[2],out[2],scale);const own=meta[role],pm=smooth(.1,.22,p[1]),sy=(mix(meta[0].height,meta[1].height,ib[1])-.1)/Math.max(.12,own.height-.1),sr=clamp(mix(meta[0].foliageRadius,meta[1].foliageRadius,ib[1])/Math.max(.08,own.foliageRadius),.25,2.8),bn=normalize([n[0]/mix(1,sr,pm),n[1]/mix(1,sy,pm),n[2]/mix(1,sr,pm)]),ns=Math.max(.001,scale);return{p,n,out,normal:normalize([bn[0]/ns,bn[1],bn[2]/ns])};}
  const flips=[],undefinedNormal=[],collapsed=[];let positive=0,negative=0;
  for(const face of stemFaces){const v=[0,1,2].map(c=>deform(face*3+c)),rest=cross(sub(v[1].p,v[0].p),sub(v[2].p,v[0].p)),changed=cross(sub(v[1].out,v[0].out),sub(v[2].out,v[0].out)),mean=key=>[0,1,2].map(c=>v.reduce((s,o)=>s+o[key][c],0)/3),before=dot(rest,mean('n')),after=dot(changed,mean('normal'));if(!Number.isFinite(after)){undefinedNormal.push(face);continue;}if(Math.hypot(...changed)===0){collapsed.push(face);continue;}if(after>0)positive++;else if(after<0)negative++;if(before!==0&&after!==0&&(before<0)!==(after<0))flips.push(face);}
  rows.push({pair:[pair.a,pair.b],t,growth,clock,seed,actualFloat32IBridge:ib,stemFaces:stemFaces.length,positiveAuthoredNormalDot:positive,negativeAuthoredNormalDot:negative,changedDotSignFaces:flips,undefinedNormalFaces:undefinedNormal,collapsedFaces:collapsed});
 }
}
batch.dispose();const report={status:'BRIDGE_STEM_DISCRETE_ORIENTATION_DIAGNOSTIC_NOT_APPROVAL',sourceSha256:sha(raw),bridgeSha256:sha(bridgeRaw),cropBatchSha256:sha(source),recordedBridgeShader:shader,rows,limitations:['Actual bridge driver buffers and production stageSample; formula evaluated CPU Float64, not GPU Float32/raster visibility.', 'Discrete cross dot mean authored transformed normals may indicate incompatible orientation, not outward/closed volume proof or cause of a saved hole.', 'Deterministic domain grid independent of visual reports; never reads V3 failure pixels or selects reverse geometry.', 'Maize stem driver1 only; leaves and other species excluded. No model/material/shader/bridge contract changed.']};await writeFile(folder+'maize-bridge-stem-orientation-diagnostic.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({samples:rows.length,samplesWithChangedDotSign:rows.filter(r=>r.changedDotSignFaces.length).length,samplesWithUndefinedNormals:rows.filter(r=>r.undefinedNormalFaces.length).length,maxChangedDotSignFaces:Math.max(...rows.map(r=>r.changedDotSignFaces.length))}));
