// Actual GLB transforms/metadata and production factory; CPU-only, no textures/GPU.
import fs from 'node:fs';import zlib from 'node:zlib';import crypto from 'node:crypto';import assert from 'node:assert/strict';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {readGlb,writeGlb} from './glb-container.mjs';import {createCropBatch} from '../src/rendering/crop-batch.js';import {cropSpec} from '../src/simulation/rules.js';import {installWorldYoungMaizeQaAdapter} from './lib/frontside-world-young-maize-adapter.mjs';
const dir='docs/qa/frontside-model-pilot/maize-young-leaf-pilot/',sha=b=>crypto.createHash('sha256').update(b).digest('hex'),source=fs.readFileSync('public/assets/be4bb7e7eab2149516c1ecc0c364d77c4a62f116c4847cf0ef6f3308dc6180ef.glb'),glb=readGlb(source);
function stripTextures(o){if(!o||typeof o!=='object')return;for(const k of Object.keys(o))if(k.endsWith('Texture'))delete o[k];else stripTextures(o[k]);}stripTextures(glb.json.materials);delete glb.json.images;delete glb.json.textures;
const gltf=await new GLTFLoader().parseAsync(writeGlb(glb.json,glb.bin).buffer,''),payloadBytes=zlib.gunzipSync(fs.readFileSync(dir+'blender-payload.json.gz')),payload=JSON.parse(payloadBytes);assert.equal(sha(payloadBytes),'d4796b80770b472ace76372cbb12f75138a294eed8daa0ed8085606f8b2d8335');assert.equal(payload.sourceSha256,sha(source));
const bridgesBytes=fs.readFileSync('public/content/crop-bridges.json'),bridges=JSON.parse(bridgesBytes),renderer={capabilities:{getMaxAnisotropy:()=>1}},duration=cropSpec('maiz').growth_seconds;assert.equal(duration,270);
const originalScene=new THREE.Scene(),scene=new THREE.Scene(),original=createCropBatch(originalScene,renderer,gltf,bridges,64),world={scene,cropBatch:createCropBatch(scene,renderer,gltf,bridges,64)};
const mesh=scene.children.find(m=>m.name==='maiz_02_joven'),sourceGeometry=mesh.geometry,sourceMaterial=mesh.material,sourceDepth=mesh.customDepthMaterial,sourceAttributes={...sourceGeometry.attributes},sourceIndex=sourceGeometry.index;const rows=[],releaseChecks=[];
function unchangedSource(){assert.equal(mesh.geometry,sourceGeometry);assert.equal(mesh.material,sourceMaterial);assert.equal(mesh.customDepthMaterial,sourceDepth);assert.equal(sourceGeometry.index,sourceIndex);for(const[name,a]of Object.entries(sourceAttributes))assert.equal(sourceGeometry.getAttribute(name),a);}
for(const worldDepth of[false,true]){const adapter=installWorldYoungMaizeQaAdapter(world,payload,{worldDepth}),geometry=mesh.geometry;assert.notEqual(geometry,sourceGeometry);assert.equal(geometry.getAttribute('iGrowth'),sourceAttributes.iGrowth);assert.equal(geometry.index.count/3,1254);assert.equal(geometry.groups.length,3);let disposed=false;
 geometry.addEventListener('dispose',()=>{disposed=true;for(const[name,a]of Object.entries(sourceAttributes))assert.notEqual(geometry.getAttribute(name),a,'Borrowed attribute still attached on dispose: '+name);assert.ok(geometry.getAttribute('position'));assert.ok(geometry.index);});
 if(worldDepth){assert.equal(mesh.customWorldDepthMaterial.side,THREE.FrontSide);assert.equal(mesh.customWorldDepthMaterial.onBeforeCompile,sourceDepth.onBeforeCompile);assert.equal(mesh.customDepthMaterial,sourceDepth);}
 adapter.dispose();assert.equal(disposed,true);unchangedSource();releaseChecks.push({worldDepth,sourceAttributeIdentity:true,sourceIndexIdentity:true,sourceMaterialDepthIdentity:true,borrowedDetachedAtDispose:true,ownPositionIndexRetainedAtDispose:true});}
const adapter=installWorldYoungMaizeQaAdapter(world,payload,{worldDepth:true}),normalized=[0,.03,.065,.228,.23105,.234,.269,.27,.31,.477,.4806,.484,.529,.53,.729,.7325,.736,.779,.78,.94,.954,.9582,.962,.97,.99,.992,.994,.996,.998,1,1.01],plants=[{id:'qa-young-growth',species:'maiz',x:2,z:3,rotation:.2,growth:0}];
function equalBatches(a,b){assert.equal(a.children.length,b.children.length);for(let i=0;i<a.children.length;i++){const x=a.children[i],y=b.children[i];assert.equal(x.name,y.name);assert.equal(x.count,y.count);assert.equal(x.visible,y.visible);assert.deepEqual(x.instanceMatrix.array,y.instanceMatrix.array);for(const name of['iGrowth','iBridge'])if(x.geometry.getAttribute(name))assert.deepEqual(x.geometry.getAttribute(name).array,y.geometry.getAttribute(name).array);}}
for(const growth of normalized){plants[0].growth=growth*duration;original.update(plants,12.5,()=>.25);world.cropBatch.update(plants,12.5,()=>.25);assert.deepEqual(original.sample('maiz',plants[0].growth),world.cropBatch.sample('maiz',plants[0].growth));equalBatches(originalScene,scene);rows.push({growth,phase:original.sample('maiz',plants[0].growth).phase,stage:original.sample('maiz',plants[0].growth).stage,youngCount:mesh.count,youngVisible:mesh.visible});}
original.dispose();world.cropBatch.dispose();const resizedOriginal=createCropBatch(originalScene,renderer,gltf,bridges,128);world.cropBatch=createCropBatch(scene,renderer,gltf,bridges,128);const resized=Array.from({length:65},(_,i)=>({id:'qa-young-resize-'+i,species:'maiz',x:i%9,z:Math.floor(i/9),rotation:i*.01,growth:normalized[i%normalized.length]*duration}));resizedOriginal.update(resized,13,()=>.25);world.cropBatch.update(resized,13,()=>.25);equalBatches(originalScene,scene);assert.equal(adapter.snapshot().capacity,128);assert.equal(adapter.events.filter(e=>e.event==='installed').length,2);const recreation=adapter.snapshot();adapter.dispose();resizedOriginal.dispose();world.cropBatch.dispose();gltf.scene.traverse(m=>{if(m.isMesh){m.geometry.dispose();m.material.dispose();}});
const report={status:'YOUNG_WORLD_ACTUAL_BATCH_GROWTH_AND_RELEASE_CPU_CONTRACT_ONLY',sourceSha256:sha(source),payloadSha256:sha(payloadBytes),bridgeSha256:sha(bridgesBytes),rows,releaseChecks,recreation,limitations:['Actual GLTFLoader node transforms/metadata and native factory, source textures removed only for CPU parse; no GPU/compiler/material texture proof.','Release event checks actual attribute identity and detachment before geometry.dispose; no claim of tracked GL buffer ownership.','Native factory recreation64→128 with65 plants preserves dispatch/live inputs; WorldScene demand scheduling and save/restore are not invoked.','No harvested/delivered worker or net GPU benefit approval.']};fs.writeFileSync(dir+'world-growth-release-contract.json',JSON.stringify(report,null,2)+'\n');console.log('PASS CPU young World adapter:31 growth samples, two release/reinstall modes, borrowed ownership and actual factory recreation.');
