// Read-only interpretation of metadata, never a visual/GPU acceptance gate.
import {readFile} from 'node:fs/promises';
const path=process.argv[2]??'docs/qa/frontside-model-pilot/crop-runtime-visual-selection.json',report=JSON.parse(await readFile(path,'utf8')),audit=report.derivedShaderDrawAudit,cpu=report.derivedCpuContracts;
if(audit?.scope!=='DERIVED_CROP_CONTRACT_DIAGNOSTIC'||cpu?.length!==4)throw Error('Missing native derived contract diagnostic');
const same=(a,b)=>JSON.stringify(a)===JSON.stringify(b),fields=(a,b)=>Object.keys(a).filter(k=>!same(a[k],b[k]));
const reference=audit.frames.filter(f=>f.label==='arm0-reference'&&f.mesh===cpu[0].mesh);
if(reference.length!==1)throw Error('Unexpected original active maize draw count');
const a=reference[0],program=id=>audit.programs.find(p=>p.id===id),rows=[];
for(let arm=1;arm<4;arm++){
 const draws=audit.frames.filter(f=>f.label===`arm${arm}-reference`&&f.mesh===cpu[0].mesh),c=cpu[arm];
 rows.push({arm,draws:draws.length,cpuMatricesEqual:['matrix','matrixWorld','modelViewMatrix','normalMatrix'].every(k=>same(cpu[0][k],c[k])),iGrowthEqual:same(cpu[0].iGrowth,c.iGrowth),instanceMatrixEqual:same(cpu[0].instanceMatrix,c.instanceMatrix),sourceTangentPresent:cpu[0].geometry.tangentPresent,candidateTangentPresent:c.geometry.tangentPresent,boundsEqual:same(cpu[0].geometry.boundingBox,c.geometry.boundingBox)&&same(cpu[0].geometry.boundingSphere,c.geometry.boundingSphere),sourceBounds:{box:cpu[0].geometry.boundingBox,sphere:cpu[0].geometry.boundingSphere},candidateBounds:{box:c.geometry.boundingBox,sphere:c.geometry.boundingSphere},materialDifferences:c.materials.map(m=>fields(cpu[0].materials[0],m)),shaderDraws:draws.map(f=>({group:f.group,programId:f.program,sameProgram:f.program===a.program,programSourcesEqual:same(program(a.program)?.shaders,program(f.program)?.shaders),uniformsEqual:same(a.uniforms,f.uniforms),changedUniforms:f.uniforms.filter(u=>!same(u,a.uniforms.find(v=>v.name===u.name))),texturesEqual:same(a.textures,f.textures),matricesEqual:['matrixWorld','modelViewMatrix','normalMatrix'].every(k=>same(a[k],f[k])),vertexAttributeLayoutDifferences:f.attributes.filter(v=>{const s=a.attributes.find(x=>x.name===v.name);return !s||!same({...v,buffer:null},{...s,buffer:null});})}))});
}
console.log(JSON.stringify({status:'DERIVED_CONTRACT_DIAGNOSTIC_NOT_APPROVAL',file:path,sourceDraws:reference.length,rows,limitations:['CPU texture/mipmap and instance hashes do not read GPU texture contents.', 'Different vertex/index data and primitive ordering are expected; attributes/payload must be interpreted separately.', 'Geometry bounds changes do not by themselves prove active shader bounds changes; inspect active uniforms and frustum/recipe use.', 'Equal program/metadata snapshots do not prove identical raster interpolation, normal-map derivatives, occlusion, quality or causality.', 'The .75 native DoubleSide quality rejection remains unchanged; no performance benefit or acceptance.']},null,2));
