"""Generate a browser/Node module from the authoritative approved JSON."""
import pathlib,json
root=pathlib.Path(__file__).resolve().parents[1]
balance=json.loads((root/'content/balance/balance_confirmado.json').read_text(encoding='utf-8'))
(root/'src/simulation/balance.js').write_text('// Generated by tools/generate_balance.py. Edit canonical JSON, then regenerate.\nexport const BALANCE = '+json.dumps(balance,ensure_ascii=False,indent=2)+';\n',encoding='utf-8')

