"""Generate a browser/Node module from the authoritative approved JSON."""
import pathlib,json,difflib,sys
root=pathlib.Path(__file__).resolve().parents[1]
balance=json.loads((root/'content/balance/balance_confirmado.json').read_text(encoding='utf-8'))
revisions=json.loads((root/'content/balance/player_revisions.json').read_text(encoding='utf-8'))
balance['initial_money']=revisions['initial_money']
balance['workers'].update(revisions['workers'])
for animal in balance['animals']:
    animal['structure_hit_damage']=revisions['structure_hit_damage'][animal['id']]
harvest_values=revisions.get('crop_harvest_values',{})
plant_costs=revisions.get('crop_plant_costs',{})
attraction_values=revisions.get('crop_attraction_values',{})
assert set(attraction_values)<=set(c['id'] for c in balance['crops'])
assert all(type(v) is int and v>0 for v in attraction_values.values())
assert set(harvest_values)<=set(c['id'] for c in balance['crops'])
assert all(type(v) is int and v>0 for v in harvest_values.values())
assert set(plant_costs)<=set(c['id'] for c in balance['crops'])
assert all(type(v) is int and v>0 for v in plant_costs.values())
for crop in balance['crops']:
    if crop['id'] in harvest_values:
        crop['base_harvest_value']=harvest_values[crop['id']]
    crop['base_attraction_value']=attraction_values.get(crop['id'],crop['base_harvest_value'])
    if crop['id'] in plant_costs:
        crop['plant_cost']=plant_costs[crop['id']]
boundaries=revisions['night_attraction_boundaries']
assert len(boundaries)==len(balance['threat_tiers'])
for i,tier in enumerate(balance['threat_tiers']):
    tier['attraction_min']=boundaries[i]
    tier['attraction_max_exclusive']=boundaries[i+1] if i+1<len(boundaries) else None
    tier['night_attack_probability']=revisions['night_attack_probability']
target=root/'src/simulation/balance.js'
new_lines=('// Generated by tools/generate_balance.py. Edit canonical JSON and player revisions, then regenerate.\nexport const BALANCE = '+json.dumps(balance,ensure_ascii=False,indent=2)+';\n').encode('utf-8').splitlines(keepends=True)
old_lines=target.read_bytes().splitlines(keepends=True) if target.exists() else []
# Preserve existing line endings for unchanged generated rows on Windows.
matcher=difflib.SequenceMatcher(None,[v.rstrip(b'\r\n') for v in old_lines],[v.rstrip(b'\r\n') for v in new_lines],autojunk=False)
result=[]
for tag,i,j,k,l in matcher.get_opcodes():
    result.extend(old_lines[i:j] if tag=='equal' else new_lines[k:l])
generated=b''.join(result)
if '--check' in sys.argv:
    if not target.exists() or generated!=target.read_bytes():
        raise SystemExit('Generated balance is stale; run python tools/generate_balance.py')
    print('PASS: balance reproduces original data and approved player revisions')
else:
    target.write_bytes(generated)
