"""Generate a browser/Node module from the authoritative approved JSON."""
import pathlib,json,difflib,sys
root=pathlib.Path(__file__).resolve().parents[1]
balance=json.loads((root/'content/balance/balance_confirmado.json').read_text(encoding='utf-8'))
revisions=json.loads((root/'content/balance/player_revisions.json').read_text(encoding='utf-8'))
balance['initial_money']=revisions['initial_money']
balance['workers'].update(revisions['workers'])
additional_village_cost=revisions['additional_village_cost']
if type(additional_village_cost) is not int or additional_village_cost<=0:
    raise SystemExit('Additional villages require a positive fixed integer price')
balance['postgame']['additional_village_cost'].update({'formula':str(additional_village_cost),'fixed_cost':additional_village_cost})
# These amounts are spoken in existing tutorial audio. Later economic pilots
# may vary other parameters, but must not invalidate those instructions.
if balance['work_center']['cost'] != 800:
    raise SystemExit('Tutorial audio requires a work centre price of 800 coins')
if balance['workers']['older_wage'] != 30 or balance['workers']['young_wage'] < 30:
    raise SystemExit('Tutorial audio requires an older-worker wage of 30 and no wage below 30 coins')
for animal in balance['animals']:
    animal['structure_hit_damage']=revisions['structure_hit_damage'][animal['id']]
if revisions.get('unlock_raid_animal_limits',False):
    balance['raids']['max_animals']=None
    for animal in balance['animals']:
        animal['max_per_raid']=None
harvest_values=revisions.get('crop_harvest_values',{})
assert set(harvest_values)<=set(c['id'] for c in balance['crops'])
assert all(type(v) is int and v>0 for v in harvest_values.values())
for crop in balance['crops']:
    if crop['id'] in harvest_values:
        crop['base_harvest_value']=harvest_values[crop['id']]
boundaries=revisions['night_attraction_boundaries']
assert len(boundaries)==len(balance['threat_tiers'])
for i,tier in enumerate(balance['threat_tiers']):
    tier['attraction_min']=boundaries[i]
    tier['attraction_max_exclusive']=boundaries[i+1] if i+1<len(boundaries) else None
    tier['night_attack_probability']=revisions['night_attack_probability']
# Optional canonical pressure calendar. No mutation of introduction/postgame rules.
calendar=revisions.get('night_raid_budget_calendar')
if calendar is not None:
    if not isinstance(calendar,list) or not calendar:
        raise SystemExit('Raid budget calendar requires nonempty stages')
    expected=6
    for stage in calendar:
        if set(stage)!={'first_night','last_night','tier_budgets'}:
            raise SystemExit('Unexpected raid budget calendar fields')
        first,last=stage['first_night'],stage['last_night']
        if type(first) is not int or type(last) is not int or first!=expected or last<first or last>balance['postgame']['after_completed_nights']:
            raise SystemExit('Raid calendar must cover consecutive nights from 6 through campaign end')
        ranges=stage['tier_budgets']
        if not isinstance(ranges,list) or len(ranges)!=len(balance['threat_tiers']):
            raise SystemExit('Raid calendar requires every attraction tier')
        for interval in ranges:
            if not isinstance(interval,list) or len(interval)!=2 or any(type(v) is not int for v in interval) or not 1<=interval[0]<=interval[1]<=256:
                raise SystemExit('Raid budget interval must be positive bounded integers')
        expected=last+1
    if expected!=balance['postgame']['after_completed_nights']+1:
        raise SystemExit('Raid calendar must reach campaign end')
    balance['raids']['night_budget_calendar']=calendar
target=root/'src/simulation/balance.js'
new_lines=('// Generated by tools/generate_balance.py. Edit canonical JSON and player revisions, then regenerate.\nexport const BALANCE = '+json.dumps(balance,ensure_ascii=False,indent=2)+';\n').encode('utf-8').splitlines(keepends=True)
old_lines=target.read_bytes().splitlines(keepends=True) if target.exists() else []
# Preserve existing line endings for unchanged generated rows on Windows.
matcher=difflib.SequenceMatcher(None,[v.rstrip(b'\r\n') for v in old_lines],[v.rstrip(b'\r\n') for v in new_lines],autojunk=False)
result=[]
for tag,i,j,k,l in matcher.get_opcodes():
    result.extend(old_lines[i:j] if tag=='equal' else new_lines[k:l])
generated=b''.join(result)
if '--check' in sys.argv:
    if not target.exists() or generated!=target.read_bytes():
        raise SystemExit('Generated balance is stale; run python tools/generate_balance.py')
    print('PASS: balance reproduces original data and approved player revisions')
else:
    target.write_bytes(generated)
