"""Retain the authored volcanic mask and carry its emission through cel grading."""
from pathlib import Path
import hashlib
import json
root=Path(__file__).resolve().parents[1]
source=(root/'content/shaders/1-African_Toon_Shader_V4_1_4.frag.glsl').read_text(encoding='utf-8')
start=source.index('vec3 africanToon4(')
toon=source[start:source.index('void main(){',start)]
# The supplied cel bands ignore lit. Carry the same authored emission into
# the cel radiance before its existing filmic grade and ink output.
toon=toon.replace('africanToon4(', 'africanToonEmission4(',1).replace('vec3 worldP){','vec3 worldP,vec3 emission){',1)
toon=toon.replace(' vec3 outC=filmic4(toon);',' toon+=emission;\n vec3 outC=filmic4(toon);',1)
start=source.rindex('  float hot=')
glow=source[start:source.index('\n }',start)].replace('  lit+=', '  return ')
functions='vec3 nativeVolcanic4(vec3 texel){\n'+glow+'\n}\n'+toon
output='// Generated by tools/prepare_volcanic.py; authored source is archived unchanged.\n'
output+='export const VOLCANIC_SHADER_SHA256='+json.dumps(hashlib.sha256(source.encode()).hexdigest())+';\n'
output+='export const volcanicFunctions='+json.dumps(functions,ensure_ascii=False)+';\n'
(root/'src/rendering/volcanic-source.js').write_bytes(output.encode('utf-8'))
