"""Extract the native chunk and asset water recipes without changing constants."""
from pathlib import Path
import hashlib
import json

root = Path(__file__).resolve().parents[1]
source = (root / 'references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js').read_text(encoding='utf-8')
wetland = source[source.index('function buildWetlandWater('):source.index('\nclass Renderer{')].strip()
bounds = source[source.index('function chunkBounds('):source.index('\nfunction groundColor(')]
chunk = source[source.index(' if(field.riverActive){const color=hex(b.colors.water);'):source.index('\n smoothTerrainLighting(field,g.v,bo.centerX,bo.centerZ);')]
pond = source[source.index('   const pts=a.water.outline;'):source.index('\n  }\n  return {g,water,index:i')]
output = '// Generated by tools/prepare_water.py from Bioma Lab V4.0.\n'
output += "import {canyonFrame,hex} from '../world/terrain.js';\nconst clamp=(v,a,b)=>Math.max(a,Math.min(b,v));\n"
output += 'export const WATER_SOURCE_SHA256=' + json.dumps(hashlib.sha256(source.encode()).hexdigest()) + ';\n'
output += wetland + '\nexport ' + bounds + '\n'
output += 'export function buildChunkWater(field,bo,b,water){\n' + chunk + '\n}\n'
output += 'export function buildAssetWater(a,water){\n' + pond + '\n}\n'
(root / 'src/rendering/water-source.js').write_bytes(output.encode('utf-8'))
