"""Preserve the lab HDR recipe and the supplied shader's complete fluid lighting."""
from pathlib import Path
import json
import hashlib

root=Path(__file__).resolve().parents[1]
lab=(root/'references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js').read_text(encoding='utf-8')
shader=(root/'content/shaders/1-African_Toon_Shader_V4_1_4.frag.glsl').read_text(encoding='utf-8')
environment=lab[lab.index('  const w=256,h=128,bytes='):lab.index('  const t=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,t);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA8,w,h')]
functions=shader[shader.index('vec3 toLinear4('):shader.index('float contact4(')]
grade=shader[shader.index('vec3 saturateGrade4('):shader.index('vec3 africanToon4(')]
branch_start=shader.index(' if(uKind>.5&&uKind<1.5){\n  vec2 wp=')
branch=shader[branch_start:shader.index(' if(uVolcanicGlow>.5',branch_start)]
fluid='const float PI4=3.14159265359;\n'+functions+grade
fluid+='vec3 nativeFluid4(vec3 worldP,vec3 V,float visibility){\n vec3 vWorld=worldP;vec2 uWorldOrigin=vec2(0.);vec3 lit=vec3(0.);\n vec3 sun=mix(vec3(3.35,2.90,2.28),vec3(.26,.40,.72)*uNightLight,uNight);\n'+branch
fluid+=' vec3 outC=filmic4(lit);\n outC=saturateGrade4(outC*vec3(.99,1.03,1.07),1.02);\n return outC;\n}\n'
output='// Generated by tools/prepare_fluid_lighting.py; original recipes preserved.\n'
output+='export const FLUID_SHADER_SHA256='+json.dumps(hashlib.sha256(shader.encode()).hexdigest())+';\n'
output+='export const fluidLightingFunctions='+json.dumps(fluid,ensure_ascii=False)+';\n'
output+='const SKY_EXPOSURES=[1.33,.62],clamp=(v,a,b)=>Math.max(a,Math.min(b,v));\nexport function buildEnvironmentPixels(data,index){\n'+environment+' return {width:w,height:h,pixels:bytes};\n}\n'
(root/'src/rendering/fluid-lighting-source.js').write_bytes(output.encode('utf-8'))
