"""Extract the original DEST geometry, masks and collapse kernels without WebGL UI."""
import hashlib, json, pathlib

root = pathlib.Path(__file__).resolve().parents[1]
source = root/'references/extracted/BIOMA_Destruccion_Lab_V1_6_6/script-5.js'
code = source.read_text(encoding='utf-8')
def section(start, end):
    return code[code.index(start):code.index(end)]

helpers = section('const clamp=', 'const M=')
helpers += section('function rng(', 'let rand=')
shaders = section('const vertexBase=', 'const fullscreenVS=')
shaders = shaders.replace('const vertexBase=', 'export const destructionVertex=').replace('const damageGLSL=', 'export const destructionDamageGLSL=').replace('const fragmentMain=', 'export const destructionFragment=').replace('const fragmentDepth=', 'export const destructionDepthFragment=').replace('const fragmentOpening=', 'export const destructionOpeningFragment=').replace('${damageGLSL}', '${destructionDamageGLSL}')
geometry = section('function vertex(', 'function makeGround(')
geometry += section('function convexHull(', 'function makeRepairNormals(')
normals = section('function makeRepairNormals(', '\n\n\nfunction applyBuildingGeometryPatches(')
normals = normals[:normals.index(' gl.bindVertexArray(mesh.vao);')]+' return out;\n}\n'
patches = section('function applyBuildingGeometryPatches(', '\n/* A building registry')
groups = section(' const modelData=[],groups=new Map();', ' mesh=createMesh(modelData);')
noise = section('function sampleNoise(', 'function cameraUpdate(')
noise = noise.replace("if($('foci').textContent!==String(active))$('foci').textContent=active", '')
# The source call after the function definitions is kept: sites are built once.
stages = section('function stages(', 'function updateUI(')

factory = '''
export const COLLAPSE_THRESHOLD=.79, COLLAPSE_SECONDS=3.2;
export function createNativeDestruction(building,input){
 let {positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds}=input;
 ({positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds}=applyBuildingGeometryPatches(building,sourcePositions,sourceNormals,sourceUV,sourceIndices,bounds));
 let damage=0,openingDirty=true,activeBuilding=building,seed=building.seed,rand=rng(57021),sourceTriGroups=[],hitSites=[];
 const holes=new Float32Array(32),noiseBytes=new Uint8Array(32*32*32);
 for(let i=0;i<noiseBytes.length;i++)noiseBytes[i]=rand()*255;
 const createMesh=data=>new Float32Array(data);
'''+geometry+normals+groups+noise+stages+'''
 const repairNormals=makeRepairNormals(),ash=makeAsh();
 return {
  positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds,
  triangles:sourceTriGroups,vertices:new Float32Array(modelData),repairNormals,ash,hull,noiseBytes,holes,hitSites,
  setDamage(value){if(!Number.isFinite(value))throw new Error('Daño visual no finito');damage=clamp(value);updateHoles();return damage;},
  get damage(){return damage;},stages,field,sampleNoise,collapsedPoint,raycast,radiusAt
 };
}
'''
# Hull is calculated in the original loader immediately before group creation.
factory = factory.replace(' const modelData=[],groups=new Map();', ' const points=[];for(let i=0;i<sourcePositions.length;i+=3)points.push([sourcePositions[i],sourcePositions[i+2]]);hull=convexHull(points);\n const modelData=[],groups=new Map();')
module = '// Generated by tools/prepare_destruction_renderer.py from original DEST V1.6.6.\n'+helpers+patches+shaders+factory
target = root/'src/rendering/destruction-native.js'
target.write_text(module,encoding='utf-8',newline='\n')
effect_shaders = ''
for name, export in [('smokeVS','destructionSmokeVertex'),('smokeFS','destructionSmokeFragment'),('debrisVS','destructionDebrisVertex'),('debrisFS','destructionDebrisFragment')]:
    start=code.index('const '+name+'=`')
    end=code.index('`;',start)+2
    effect_shaders += code[start:end].replace('const '+name+'=', 'export const '+export+'=')+'\n'
shape = section('const shape=', 'let debrisBuffer=')
shape = 'export const destructionDebrisVertices=(()=>{'+shape+'return new Float32Array(debrisVerts);})();\n'
chips = section('let ashChips=[];', 'const finalFS=')
emitters = section('function emitPuff(', 'const smokeUpload=')
# Default contact is the original flat floor. The world adapter can supply
# a contact height without changing gravity, bounce, friction or fragment shape.
emitters = emitters.replace('const floor=.028+p.size[1]*.23;', 'const floor=contactFloor?contactFloor(p):.028+p.size[1]*.23;')
apply_damage = section('function applyDamage(', 'function startCollapse(').replace(' updateUI(true);','')
holes = section('function updateHoles(', 'resetSites();').replace("if($('foci').textContent!==String(active))$('foci').textContent=active", '')
debris_pack = section('function renderDebris(', ' gl.useProgram(debrisProgram.p);').replace('function renderDebris()', 'function debrisInstances()').replace('if(!n)return;', 'return {count:n,data:debrisUpload};')+'}\n'
smoke_pack = section('function renderSmoke(', ' gl.disable(gl.DEPTH_TEST);gl.enable(gl.BLEND);').replace('function renderSmoke()', 'function smokeInstances(eye)').replace('if(!smokeEnabled||!smoke.length)return;', 'if(!smokeEnabled||!smoke.length)return {count:0,data:smokeUpload};')+' return {count:n,data:smokeUpload};}\n'
effects = '// Generated by tools/prepare_destruction_renderer.py from original DEST V1.6.6.\n'+helpers+effect_shaders+shape+'''
export function createNativeDestructionEffects(kernel,building,{contactFloor=null}={}){
 let rand=rng(building.seed),damage=0,time=0,quality='medium',smokeEnabled=true,debrisEnabled=true,embersEnabled=true,smokeAmount=.65;
 let destructionAt=-100,lastHitStage=-1,shadowDirty=true,openingDirty=true,playing=false;
 const smoke=[],debris=[],stats={particles:0},holes=new Float32Array(32),hitSites=kernel.hitSites.map(s=>({...s,p:s.p.slice(),n:s.n.slice(),radius:0,emission:0,lastRadius:0}));
 const radiusAt=kernel.radiusAt,smokeUpload=new Float32Array(512*11),debrisUpload=new Float32Array(650*12);
 // resetSites consumes two horizontal jitter samples per original focus.
 const resetRandom=()=>{rand=rng(building.seed);for(const s of hitSites){rand();rand();}};
 resetRandom();
'''+chips+emitters+holes+apply_damage+debris_pack+smoke_pack+'''
 return {
  smoke,debris,ashChips,hitSites,stats,smokeInstances,debrisInstances,burst,emitPuff,emitDebris,
  get damage(){return damage;},get time(){return time;},get destructionAt(){return destructionAt;},
  configure(value){if(!['low','medium','high'].includes(value))throw new Error('Calidad DEST desconocida');quality=value;},
  initialize(value){damage=clamp(value);updateHoles();lastHitStage=Math.floor(damage/.047);},
  restore(value){if(!Number.isFinite(value))throw new Error('Daño DEST no finito');this.clear();resetRandom();time=0;destructionAt=-100;this.initialize(value);},
  setDamage(value){
   if(!Number.isFinite(value))throw new Error('Daño DEST no finito');value=clamp(value);
   if(value<damage-.01&&value<=.0001){smoke.length=0;debris.length=0;for(const s of hitSites)s.emission=0;lastHitStage=-1;destructionAt=-100;resetRandom();}
   if(damage<.79&&value>=.79){applyDamage(.79,false);burst([0,3.3,0],[0,1,0],1.1,true);}
   applyDamage(value,true);stats.particles=smoke.length+debris.length;
  },
  advance(dt){if(!Number.isFinite(dt)||dt<0)throw new Error('Paso DEST inválido');if(dt===0)return;time+=dt;for(let remaining=dt;remaining>1e-7;){const sub=Math.min(1/30,remaining);updateEffects(sub);remaining-=sub;}},
  frame(value,dt){if(!Number.isFinite(value)||!Number.isFinite(dt)||dt<0)throw new Error('Paso DEST inválido');time+=dt;this.setDamage(value);for(let remaining=dt;remaining>1e-7;){const sub=Math.min(1/30,remaining);updateEffects(sub);remaining-=sub;}},
  clear(){smoke.length=0;debris.length=0;stats.particles=0;for(const s of hitSites)s.emission=0;}
 };
}
'''
# Observe emissions and first floor contacts without changing native RNG/physics.
effects = effects.replace('stats={particles:0},holes=', 'stats={particles:0,debrisEmitted:0,groundContacts:0},holes=')
effects = effects.replace('if(debris.length>=340)return;const r=rand()', 'if(debris.length>=340)return;stats.debrisEmitted++;const r=rand()')
effects = effects.replace('if(p.p[1]<floor){p.p[1]=floor;', 'if(p.p[1]<floor){if(p.bounces===0)stats.groundContacts++;p.p[1]=floor;')
effects_target = root/'src/rendering/destruction-effects-native.js'
effects_target.write_text(effects,encoding='utf-8',newline='\n')
inventory = json.loads((root/'content/manifests/assets.json').read_text(encoding='utf-8'))
payloads = next(s['payloads'] for s in inventory['sources'] if s['file']==source.parent.name+'.html')
urls = {p['id']:p['url'] for p in payloads}
buildings = [
 {'culture':'suajili','name':'Casa Suajili','dataId':'model-data','seed':57021,'repairPlaster':True},
 {'culture':'etiope','name':'Casa etíope','dataId':'model-data-2','seed':66173,'repairPlaster':False,'fitSites':True},
 {'culture':'mapungubwe','name':'Casa Mapungubwe','dataId':'model-data-3','seed':75329,'repairPlaster':False,'fitSites':True},
 {'culture':'saheliana','name':'Casa saheliana','dataId':'model-data-4','seed':84503,'repairPlaster':False,'fitSites':True,'fitGround':True,'roofCap':{'heightRatio':.525,'insetX':.158,'insetZ':.09,'selectionMargin':0,'capYellow':True}},
 {'culture':'musgum','name':'Casa musgum','dataId':'model-data-5','seed':91217,'repairPlaster':False,'fitSites':True,'fitGround':True},
]
for building in buildings:
    building['url']=urls[building['dataId']]
    building['sha256']=hashlib.sha256((root/'public'/building['url'].lstrip('/')).read_bytes()).hexdigest()
manifest={'source':source.relative_to(root).as_posix(),'sourceSha256':hashlib.sha256(source.read_bytes()).hexdigest(),'moduleSha256':hashlib.sha256(target.read_bytes()).hexdigest(),'effectsModuleSha256':hashlib.sha256(effects_target.read_bytes()).hexdigest(),'buildings':buildings}
(root/'content/manifests/destruction-native.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
(root/'public/content/destruction.json').write_text(json.dumps({'buildings':buildings},ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
