"""Recover the native ground triangles, colors and lighting normals."""
from pathlib import Path
import hashlib
import json

root = Path(__file__).resolve().parents[1]
source = (root / 'references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js').read_text(encoding='utf-8')
helpers = source[source.index('const smooth='):source.index('const GROUPS=')]
geometry = source[source.index('class Geometry{'):source.index('\nfunction branch(')]
normals = source[source.index('function smoothTerrainLighting('):source.index('\nfunction compactStaticMesh(')]
desert = source[source.index('function desertSmoothNormals('):source.index('\nclass TerrainField{')]
color = source[source.index('function groundColor('):source.index('\nfunction buildChunkData(')]
recipe = source[source.index(' const points=[],colors=[];', source.index('function buildChunkData(')):source.index(' const edges={west:')]
# Wire is a debug overlay, separate from the terrain; retain its recipe but discard its output.
output = '// Generated by tools/prepare_terrain_renderer.py from Bioma Lab V4.0.\n'
output += "import {canyonGroundColor,desertGroundColor} from '../world/terrain.js';\nimport {chunkBounds} from './water-source.js';\nconst clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),mix=(a,b,t)=>a+(b-a)*t;\n"
output += helpers + geometry + '\n' + normals + '\n' + desert + '\n' + color + '\n'
output += 'export const TERRAIN_SOURCE_SHA256=' + json.dumps(hashlib.sha256(source.encode()).hexdigest()) + ';\n'
output += 'export function buildGroundData(field,b,cx,cz){const bo=chunkBounds(cx,cz),g=new Geometry(),wire={line(){}};\n' + recipe
output += '\n smoothTerrainLighting(field,g.v,bo.centerX,bo.centerZ);\n if(field.desert)desertSmoothNormals(field,g.v,bo.centerX,bo.centerZ);\n return new Float32Array(g.v);\n}\n'
output += 'export {Geometry,desertSmoothNormals};\n'
output = '\n'.join(line.rstrip() for line in output.split('\n'))
(root / 'src/rendering/terrain-source.js').write_bytes(output.encode('utf-8'))
