"""Extend the recovered Bastion graph with face polygons for occupancy checks."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / 'src/world/wall-layout-native.js').read_text(encoding='utf-8')
helper = source[source.index('function pointSegment('):source.index('function simplify(')]
body = source[source.index(' closedFaces(){') + len(' closedFaces(){'):source.index('\n ensureAutomaticGates(){')]
body = body.rstrip().removesuffix(',').removesuffix('}').replace('this.pieces', 'pieces').replace('this.endpoints(p)', 'endpoints(p)')
body = body.replace('faces.push({area,ids,hosts,', 'faces.push({polygon:path.map(e=>nodes[e.from].q),area,ids,hosts,')
body = '\n'.join(line.rstrip() for line in body.splitlines()).rstrip()
target = root / 'src/world/boundary-faces.js'
target.write_text('// Generated by tools/prepare_boundary_faces.py from the recovered Bastion graph.\n'
                  'const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);\n'
                  'function endpoints(p){const h=2.18*p.scaleX/2,dx=Math.cos(p.angle)*h,dz=Math.sin(p.angle)*h;return [[p.x-dx,p.z-dz],[p.x+dx,p.z+dz]];}\n'
                  + helper + 'export function boundaryFaces(pieces){' + body + '\n}\n', encoding='utf-8', newline='\n')
