"""Extract the native V8 avatar renderer and eight gesture curves reproducibly."""
import hashlib,json,pathlib,re
root=pathlib.Path(__file__).resolve().parents[1]
source=root/'references/extracted/Guardian_Tutorial_V8_Avatar_y_Manos_3D/script-0.js'
code=source.read_text(encoding='utf-8')
helpers=code[code.index('const clamp ='):code.index('const reducedMotion =')]
renderer=code[code.index('class SpriteMesh {'):code.index('// V4: un único modo')]
# The slice ends inside a separator comment: remove that last separator.
renderer=renderer[:renderer.rfind('// --------------------------------------------------------------------------')]
renderer=renderer.replace("$('engine-label').textContent=",'this.canvas.dataset.engine=')
renderer=renderer.replace("const size=$('avatar').clientWidth||300",'const size=this.canvas.clientWidth||300')
for name in ['GuardianMesh','OrnamentPhysics','GuardianMagic']:
    renderer=renderer.replace('class '+name+' {','export class '+name+' {').replace('class '+name+' extends','export class '+name+' extends')
curves=code[code.index('const hump='):code.index('function advancePhases(')]
sprite=re.search(r"const SPRITE_DATA = ('[^']+');",code).group(1)
minimum=re.search(r'const GESTURE_MIN_SECONDS=([^;]+);',code).group(1)
module=f'// Generated by tools/prepare_guardian.py from the original Guardian V8 lab.\n{helpers}\nexport const GUARDIAN_SPRITE={sprite};\nexport const GESTURE_MIN_SECONDS={minimum};\n{renderer}\nexport function guardianPose(state,age,duration,logicalTime=age,restIntensity=1){{\n{curves}\nreturn enhancedPose(state,age,duration);\n}}\n'
target=root/'src/ui/guardian-native.js';target.write_text(module,encoding='utf-8')
manifest={'source':str(source.relative_to(root)).replace('\\','/'),'sourceSha256':hashlib.sha256(source.read_bytes()).hexdigest(),'moduleSha256':hashlib.sha256(target.read_bytes()).hexdigest(),'gestures':['greeting','speak','acknowledge','curious','warning','reveal','idle','farewell']}
(root/'content/manifests/guardian-native.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
markup=(source.parent/'markup.html').read_text(encoding='utf-8')
style=re.search(r'<style>([\s\S]*?)</style>',markup).group(1)
def scoped_rules(css):
    output=[];at=0
    while at<len(css):
        opening=css.find('{',at)
        if opening<0:break
        header=css[at:opening].strip();depth=1;end=opening+1
        while depth and end<len(css):
            depth+=(css[end]=='{')-(css[end]=='}');end+=1
        body=css[opening+1:end-1];at=end
        if header.startswith('@media'):
            nested=scoped_rules(body)
            if nested:output.append(header+'{'+nested+'}')
        else:
            selectors=[]
            for selector in header.split(','):
                if not any(key in selector for key in [':root','#tutorial','.avatar-shell','#avatar','#magic-fx','.bubble','.message','.next-button','.sr-only']):continue
                selector=selector.strip().replace(':root','#guardian-root').replace('#tutorial','#guardian-root').replace('#avatar','#guardian-avatar').replace('#magic-fx','#guardian-magic')
                if '#guardian-root' not in selector:selector='#guardian-root '+selector
                selectors.append(selector)
            if selectors:output.append(','.join(selectors)+'{'+body+'}')
    return '\n'.join(output)
(root/'src/ui/guardian-native.css').write_text('/* Original Guardian V8 rules scoped to its overlay. */\n'+scoped_rules(style)+'\n#guardian-root{color:var(--ink)}\n',encoding='utf-8')
print('Native avatar mesh, ornaments, lights and eight gesture curves extracted')
