"""Extend the recovered Bastion graph with face polygons for occupancy checks."""
from pathlib import Path
root = Path(__file__).resolve().parents[1]
source = (root / 'src/world/wall-layout-native.js').read_text(encoding='utf-8')
helper = source[source.index('function pointSegment('):source.index('function simplify(')]
body = source[source.index(' closedFaces(){') + len(' closedFaces(){'):source.index('\n ensureAutomaticGates(){')]
body = body.rstrip().removesuffix(',').removesuffix('}').replace('this.pieces', 'pieces').replace('this.endpoints(p)', 'endpoints(p)')
body = body.replace('faces.push({area,ids,hosts,', 'faces.push({polygon:path.map(e=>nodes[e.from].q),area,ids,hosts,')
# Keep the recovered narrow-phase arithmetic/order; reject distant pairs first.
old = 'return{p,a,b,d:[b[0]-a[0],b[1]-a[1]],cuts:[0,1]};'
new = ('const dx=b[0]-a[0],dz=b[1]-a[1],margin=EPS+1e-6*Math.max(Math.abs(dx),Math.abs(dz));'
       'return{p,a,b,d:[dx,dz],cuts:[0,1],box:[Math.min(a[0],b[0])-margin,Math.min(a[1],b[1])-margin,Math.max(a[0],b[0])+margin,Math.max(a[1],b[1])+margin]};')
assert body.count(old) == 1
body = body.replace(old, new)
old = 'const a=segs[i],b=segs[j],den=cross(a.d,b.d),v=[b.a[0]-a.a[0],b.a[1]-a.a[1]];'
new = ('const a=segs[i],b=segs[j];'
       'if(a.box[2]<b.box[0]||b.box[2]<a.box[0]||a.box[3]<b.box[1]||b.box[3]<a.box[1])continue;'
       'const den=cross(a.d,b.d),v=[b.a[0]-a.a[0],b.a[1]-a.a[1]];')
assert body.count(old) == 1
body = body.replace(old, new)
old = 'const nodes=[],edges=[],edgeKeys=new Set();'
assert body.count(old) == 1
body = body.replace(old, 'const nodes=[],edges=[],edgeKeys=new Set(),nodeCells=new Map(),cellSize=EPS*2;')
old = 'const node=(q)=>{let id=nodes.findIndex(n=>dist(n.q,q)<EPS);if(id<0){id=nodes.length;nodes.push({q,out:[]});}return id;};'
new = '''// Preserve the earliest matching node, rather than choosing a closest one.
  const node=(q)=>{
   const cx=Math.floor(q[0]/cellSize),cz=Math.floor(q[1]/cellSize),indexed=Number.isSafeInteger(cx)&&Number.isSafeInteger(cz);let id=-1;
   if(indexed){for(let x=cx-1;x<=cx+1;x++)for(let z=cz-1;z<=cz+1;z++)for(const candidate of nodeCells.get(x+':'+z)??[]){if((id<0||candidate<id)&&dist(nodes[candidate].q,q)<EPS)id=candidate;}}
   else id=nodes.findIndex(n=>dist(n.q,q)<EPS);
   if(id<0){id=nodes.length;nodes.push({q,out:[]});if(indexed){const key=cx+':'+cz;if(!nodeCells.has(key))nodeCells.set(key,[]);nodeCells.get(key).push(id);}}
   return id;
  };'''
assert body.count(old) == 1
body = body.replace(old, new)
body = '\n'.join(line.rstrip() for line in body.splitlines()).rstrip()
target = root / 'src/world/boundary-faces.js'
target.write_text('// Generated by tools/prepare_boundary_faces.py from the recovered Bastion graph.\n'
                  'const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);\n'
                  'function endpoints(p){const h=2.18*p.scaleX/2,dx=Math.cos(p.angle)*h,dz=Math.sin(p.angle)*h;return [[p.x-dx,p.z-dz],[p.x+dx,p.z+dz]];}\n'
                  + helper + 'export function boundaryFaces(pieces){' + body + '\n}\n', encoding='utf-8', newline='\n')
