"""Extract the supplied shader's terrain surface and BRDF recipes."""
from pathlib import Path
import json
import hashlib

root = Path(__file__).resolve().parents[1]
source = (root/'content/shaders/1-African_Toon_Shader_V4_1_4.frag.glsl').read_text(encoding='utf-8')
surface = source[source.index('  float greenery='):source.index('  objAO=contact4();')]
brdf = source[source.index('vec3 fresnel4('):source.index('float contact4(')]
# environment4 is already shared by all world materials.
brdf = brdf[:brdf.index('vec3 environment4(')] + brdf[brdf.index('vec3 brdf4('):]
lighting = source[source.index(' vec3 sun=mix', source.index('void main(){', source.index('vec3 africanToon4('))):source.index(' float back=', source.index('vec3 africanToon4('))]
lighting = lighting.replace(' vec3 reflected=environment4(reflect(-V,N),rough);\n', '')
lighting = lighting.replace(' vec3 lit=', ' return ')
functions = brdf
functions += 'void nativeGroundSurface4(vec3 worldP,inout vec3 color,inout vec3 N,out float rough,out float wet,float uCanyon,float uDesert,float uDetail){\n vec3 vWorld=worldP;rough=1.;wet=0.;\n'+surface+'}\n'
functions += 'vec3 nativeGroundLight4(vec3 albedo,vec3 N,vec3 V,float rough,float visibility,vec3 reflected){\n float metal=0.,objAO=1.,nv=max(dot(N,V),0.);\n'+lighting+'}\n'
output = '// Generated by tools/prepare_ground_lighting.py from the supplied shader.\n'
output += 'export const GROUND_SHADER_SHA256='+json.dumps(hashlib.sha256(source.encode()).hexdigest())+';\n'
output += 'export const groundLightingFunctions='+json.dumps(functions,ensure_ascii=False)+';\n'
(root/'src/rendering/ground-lighting-source.js').write_bytes(output.encode('utf-8'))
