"""Extract the two native far-terrain recipes, including fine/coarse seams."""
from pathlib import Path
import hashlib
import json
root = Path(__file__).resolve().parents[1]
source = (root / 'references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js').read_text(encoding='utf-8')
recipe = source[source.index('function makeCanyonHorizon('):source.index('\nclass ChunkManager{')]
output = '// Generated by tools/prepare_horizon.py from Bioma Lab V4.0.\n'
output += "import {TerrainField,canyonFrame,canyonGroundColor,desertGroundColor,hex} from '../world/terrain.js';\nimport {Geometry,desertSmoothNormals} from './terrain-source.js';\nconst mix=(a,b,t)=>a+(b-a)*t;\n"
output += 'export const HORIZON_SOURCE_SHA256=' + json.dumps(hashlib.sha256(source.encode()).hexdigest()) + ';\n'
output += recipe + '\nexport {makeCanyonHorizon,makeDesertHorizon};\n'
output = '\n'.join(line.rstrip() for line in output.split('\n'))
(root / 'src/rendering/horizon-source.js').write_bytes(output.encode('utf-8'))
