"""Recover the lab's contact-map rasterizer without altering its stamps."""
from pathlib import Path
import hashlib
import json
root=Path(__file__).resolve().parents[1]
source=(root/'references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js').read_text(encoding='utf-8')
start=source.index(' prepareContacts(){')
body=source[source.index('  for(let slot=0;slot<20;slot++){',start):source.index('  gl.activeTexture(gl.TEXTURE7);',start)]
output='// Generated by tools/prepare_contacts.py from Bioma Lab V4.0.\n'
output+='export const CONTACT_SOURCE_SHA256='+json.dumps(hashlib.sha256(source.encode()).hexdigest())+';\n'
output+='const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));\n'
output+='export function buildContactData(prototypes,instances,bo,layers){\n const world={instances},state={layers},size=256,bytes=new Uint8Array(size*size).fill(255),width=bo[2]-bo[0],height=bo[3]-bo[1];\n'+body
output+=' return {pixels:bytes,bounds:[bo[0],bo[1],width,height]};\n}\n'
(root/'src/rendering/contact-source.js').write_bytes(output.encode('utf-8'))
