"""Extract original Bastion stage selection and opaque regional morph curves."""
import hashlib,json,pathlib
root=pathlib.Path(__file__).resolve().parents[1]
source=root/'references/extracted/Bastion_Lab_V4_1_Puerta_Reforzada_Mas_Grande/script-1.js'
code=source.read_text(encoding='utf-8')
ease=code[code.index('function regionalEase('):code.index('const MORPH_VS=')]
stages=code[code.index(' stages(p){'):code.index(' drawPieces(')]
morph=code[code.index(' morphedPositions(mesh,morph){'):code.index(' pick(x,y,pieces')]
module='// Generated by tools/prepare_wall_renderer.py from native Bastion V4.1.\n'+ease+stages.replace(' stages(p){','export function wallStages(p){')+morph.replace(' morphedPositions(mesh,morph){','export function morphedWallPositions(mesh,morph){')
target=root/'src/rendering/walls-native.js'
target.write_text(module,encoding='utf-8',newline='\n')
(root/'content/manifests/walls-native.json').write_text(json.dumps({'source':source.relative_to(root).as_posix(),'sourceSha256':hashlib.sha256(source.read_bytes()).hexdigest(),'moduleSha256':hashlib.sha256(target.read_bytes()).hexdigest()},indent=2)+'\n',encoding='utf-8',newline='\n')
