"""Extend the recovered Bastion graph with face polygons for occupancy checks."""
from pathlib import Path
import sys
root = Path(__file__).resolve().parents[1]
source = (root / 'src/world/wall-layout-native.js').read_text(encoding='utf-8')
helper = source[source.index('function pointSegment('):source.index('function simplify(')]
body = source[source.index(' closedFaces(){') + len(' closedFaces(){'):source.index('\n ensureAutomaticGates(){')]
body = body.rstrip().removesuffix(',').removesuffix('}').replace('this.pieces', 'pieces').replace('this.endpoints(p)', 'endpoints(p)')
body = body.replace('faces.push({area,ids,hosts,', 'faces.push({polygon:path.map(e=>nodes[e.from].q),area,ids,hosts,')
body = '\n'.join(line.rstrip() for line in body.splitlines()).rstrip()
# Share the recovered ordering between synchronous and cooperative consumers.
# Assert each source transform, so a future native graph edit cannot silently
# drop a yield point or fork the generated algorithm.
def once(old, new):
    global body
    assert body.count(old) == 1, old
    body = body.replace(old, new)
once('const segs=pieces.filter(p=>p.hp>0&&!p.collapse).map(p=>{const [a,b]=endpoints(p);return{p,a,b,d:[b[0]-a[0],b[1]-a[1]],cuts:[0,1]};});',
     'const segs=[];for(const p of pieces){yield {phase:"face-input"};if(p.hp>0&&!p.collapse){const [a,b]=endpoints(p);segs.push({p,a,b,d:[b[0]-a[0],b[1]-a[1]],cuts:[0,1]});}}')
once('for(let i=0;i<segs.length;i++)for(let j=i+1;j<segs.length;j++){',
     'for(let i=0;i<segs.length;i++)for(let j=i+1;j<segs.length;j++){\n   if((j-i-1)%32===0)yield {phase:"face-intersection",units:Math.min(32,segs.length-j)};')
once('const node=(q)=>{let id=nodes.findIndex(n=>dist(n.q,q)<EPS);if(id<0){id=nodes.length;nodes.push({q,out:[]});}return id;};',
     'function* node(q){for(let i=0;i<nodes.length;i++){if(i%32===0)yield {phase:"face-node-scan",units:Math.min(32,nodes.length-i)};if(dist(nodes[i].q,q)<EPS)return i;}const id=nodes.length;nodes.push({q,out:[]});return id;}')
once('for(const s of segs){', 'for(const s of segs){\n   yield {phase:"face-cut-sort"};')
once('u=node(at(ts[i-1])),v=node(at(ts[i]));', 'u=yield* node(at(ts[i-1])),v=yield* node(at(ts[i]));')
once('for(const n of nodes)n.out.sort(', 'for(const n of nodes){yield {phase:"face-node-sort"};n.out.sort(')
once('q[0]-n.q[0]));', 'q[0]-n.q[0]));}')
once('for(const start of edges){', 'for(const start of edges){\n   yield {phase:"face-start"};')
once('for(let guard=0;guard<=edges.length;guard++){', 'for(let guard=0;guard<=edges.length;guard++){\n    yield {phase:"face-walk"};')
once('let area=0;', 'yield {phase:"face-area-hosts"};let area=0;')
once('faces.sort((a,b)=>', 'yield {phase:"face-sort"};faces.sort((a,b)=>')
target = root / 'src/world/boundary-faces.js'
output = ('// Generated by tools/prepare_boundary_faces.py from the recovered Bastion graph.\n'
          + "import {drainGeometrySteps} from './geometry-steps.js';\n"
          + 'const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);\n'
          + 'function endpoints(p){const h=2.18*p.scaleX/2,dx=Math.cos(p.angle)*h,dz=Math.sin(p.angle)*h;return [[p.x-dx,p.z-dz],[p.x+dx,p.z+dz]];}\n'
          + helper + 'export function* boundaryFacesSteps(pieces){' + body + '\n}\n'
          + 'export const boundaryFaces=pieces=>drainGeometrySteps(boundaryFacesSteps(pieces));\n')
encoded = output.encode('utf-8')
if '--check' in sys.argv:
    if target.read_bytes() != encoded:
        raise SystemExit('Generated cooperative boundary faces are stale')
else:
    target.write_bytes(encoded)
