"""Extract the original DEST geometry, masks and collapse kernels without WebGL UI."""
import hashlib, json, pathlib

root = pathlib.Path(__file__).resolve().parents[1]
source = root/'references/extracted/BIOMA_Destruccion_Lab_V1_6_6/script-5.js'
code = source.read_text(encoding='utf-8')
def section(start, end):
    return code[code.index(start):code.index(end)]

helpers = section('const clamp=', 'const M=')
helpers += section('function rng(', 'let rand=')
shaders = section('const vertexBase=', 'const fullscreenVS=')
shaders = shaders.replace('const vertexBase=', 'export const destructionVertex=').replace('const damageGLSL=', 'export const destructionDamageGLSL=').replace('const fragmentMain=', 'export const destructionFragment=').replace('const fragmentDepth=', 'export const destructionDepthFragment=').replace('const fragmentOpening=', 'export const destructionOpeningFragment=').replace('${damageGLSL}', '${destructionDamageGLSL}')
geometry = section('function vertex(', 'function makeGround(')
geometry += section('function convexHull(', 'function makeRepairNormals(')
normals = section('function makeRepairNormals(', '\n\n\nfunction applyBuildingGeometryPatches(')
normals = normals[:normals.index(' gl.bindVertexArray(mesh.vao);')]+' return out;\n}\n'
patches = section('function applyBuildingGeometryPatches(', '\n/* A building registry')
groups = section(' const modelData=[],groups=new Map();', ' mesh=createMesh(modelData);')
noise = section('function sampleNoise(', 'function cameraUpdate(')
noise = noise.replace("if($('foci').textContent!==String(active))$('foci').textContent=active", '')
# The source call after the function definitions is kept: sites are built once.
stages = section('function stages(', 'function updateUI(')

factory = '''
export const COLLAPSE_THRESHOLD=.79, COLLAPSE_SECONDS=3.2;
export function createNativeDestruction(building,input){
 let {positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds}=input;
 ({positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds}=applyBuildingGeometryPatches(building,sourcePositions,sourceNormals,sourceUV,sourceIndices,bounds));
 let damage=0,openingDirty=true,activeBuilding=building,seed=building.seed,rand=rng(57021),sourceTriGroups=[],hitSites=[];
 const holes=new Float32Array(32),noiseBytes=new Uint8Array(32*32*32);
 for(let i=0;i<noiseBytes.length;i++)noiseBytes[i]=rand()*255;
 const createMesh=data=>new Float32Array(data);
'''+geometry+normals+groups+noise+stages+'''
 const repairNormals=makeRepairNormals(),ash=makeAsh();
 return {
  positions:sourcePositions,normals:sourceNormals,uv:sourceUV,indices:sourceIndices,bounds,
  triangles:sourceTriGroups,vertices:new Float32Array(modelData),repairNormals,ash,hull,noiseBytes,holes,hitSites,
  setDamage(value){if(!Number.isFinite(value))throw new Error('Daño visual no finito');damage=clamp(value);updateHoles();return damage;},
  get damage(){return damage;},stages,field,sampleNoise,collapsedPoint,raycast,radiusAt
 };
}
'''
# Hull is calculated in the original loader immediately before group creation.
factory = factory.replace(' const modelData=[],groups=new Map();', ' const points=[];for(let i=0;i<sourcePositions.length;i+=3)points.push([sourcePositions[i],sourcePositions[i+2]]);hull=convexHull(points);\n const modelData=[],groups=new Map();')
module = '// Generated by tools/prepare_destruction_renderer.py from original DEST V1.6.6.\n'+helpers+patches+shaders+factory
target = root/'src/rendering/destruction-native.js'
target.write_text(module,encoding='utf-8',newline='\n')
inventory = json.loads((root/'content/manifests/assets.json').read_text(encoding='utf-8'))
payloads = next(s['payloads'] for s in inventory['sources'] if s['file']==source.parent.name+'.html')
urls = {p['id']:p['url'] for p in payloads}
buildings = [
 {'culture':'suajili','name':'Casa Suajili','dataId':'model-data','seed':57021,'repairPlaster':True},
 {'culture':'etiope','name':'Casa etíope','dataId':'model-data-2','seed':66173,'repairPlaster':False,'fitSites':True},
 {'culture':'mapungubwe','name':'Casa Mapungubwe','dataId':'model-data-3','seed':75329,'repairPlaster':False,'fitSites':True},
 {'culture':'saheliana','name':'Casa saheliana','dataId':'model-data-4','seed':84503,'repairPlaster':False,'fitSites':True,'fitGround':True,'roofCap':{'heightRatio':.525,'insetX':.158,'insetZ':.09,'selectionMargin':0,'capYellow':True}},
 {'culture':'musgum','name':'Casa musgum','dataId':'model-data-5','seed':91217,'repairPlaster':False,'fitSites':True,'fitGround':True},
]
for building in buildings:
    building['url']=urls[building['dataId']]
    building['sha256']=hashlib.sha256((root/'public'/building['url'].lstrip('/')).read_bytes()).hexdigest()
manifest={'source':source.relative_to(root).as_posix(),'sourceSha256':hashlib.sha256(source.read_bytes()).hexdigest(),'moduleSha256':hashlib.sha256(target.read_bytes()).hexdigest(),'buildings':buildings}
(root/'content/manifests/destruction-native.json').write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
