"""Extract the Bioma Lab V4.0 receiver-plane PCF; retain its source for audit."""
from pathlib import Path
import hashlib
import json

source_path = Path('references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js')
source = source_path.read_text(encoding='utf-8')
start = source.index('float filteredShadow4(vec3 normal){')
end = source.index('\n}', start) + 2
original = source[start:end]
adapted = original.replace('filteredShadow4(vec3 normal)', 'nativeShadowOcclusion(vec3 normal,vec3 worldPosition)')
adapted = adapted.replace(' vec3 p=vLight.xyz/vLight.w*.5+.5;', ' vec4 lightPosition=uNativeLightVP*vec4(worldPosition,1.);\n vec3 p=lightPosition.xyz/lightPosition.w*.5+.5;')
for old, new in [('uShadowOn', 'uNativeShadowOn'), ('uShadowFiltered', 'uNativeShadowFiltered'), ('uTexel', 'uNativeShadowTexel'), ('uLightDir', 'uNativeShadowLight')]:
    adapted = adapted.replace(old, new)
# There are no mip levels in this depth attachment. Explicit LOD zero retains
# the native hardware PCF and avoids implicit derivatives inside the tap loop.
adapted = adapted.replace('texture(uNativeShadowFiltered,vec3(p.xy+o,p.z+dot(slope,o)-bias))', 'textureLod(uNativeShadowFiltered,vec3(p.xy+o,p.z+dot(slope,o)-bias),0.)')
# Evaluate derivatives across the whole quad before the varying map-edge guard.
# The original early return otherwise leaves edge derivatives undefined on ANGLE.
guard = next(line for line in adapted.splitlines() if line.startswith(' if(uNativeShadowOn'))
adapted = adapted.replace(guard + '\n', '')
derivative_line = next(line for line in adapted.splitlines() if line.startswith(' vec2 ux='))
adapted = adapted.replace(derivative_line + '\n', derivative_line + '\n' + guard + '\n')
declarations = 'uniform highp sampler2DShadow uNativeShadowFiltered;\nuniform mat4 uNativeLightVP;\nuniform float uNativeShadowOn,uNativeShadowTexel;\nuniform vec3 uNativeShadowLight;\n'
output = '// Generated by tools/prepare_native_shadow.py from Bioma Lab V4.0.\n'
output += 'export const nativeShadowSourceHash=' + json.dumps(hashlib.sha256(original.encode()).hexdigest()) + ';\n'
output += 'export const nativeShadowFunctions=' + json.dumps(declarations + adapted, ensure_ascii=False) + ';\n'
Path('src/rendering/native-shadow-source.js').write_bytes(output.encode('utf-8'))
