"""Preserve the native biome lab sky shaders and adapt only HDR input transport."""
import hashlib
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'references/extracted/Bioma_Lab_V4_0_Materiales_Luz_Optimizado/script-8.js'
source = SOURCE.read_text(encoding='utf-8')
core = re.search(r'const SKY_CORE=`([\s\S]*?)`;', source).group(1)
vertex = re.search(r'const SKY_VS=`([\s\S]*?)`;', source).group(1)
fragment = re.search(r'const SKY_FS=`([\s\S]*?)`\+SKY_CORE\+`([\s\S]*?)`;', source)
fragment = fragment.group(1) + core + fragment.group(2)
decoder = source[source.index('function decodeRadiance(encoded){'):source.index('\n// These surface recipes')].strip()
decoder = decoder.replace('function decodeRadiance(encoded){', 'export function decodeRadiance(buffer){').replace(
    ' const raw=atob(encoded.trim()),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);',
    ' const bytes=buffer instanceof Uint8Array?buffer:new Uint8Array(buffer);')
output = '// Generated by tools/prepare_sky.py from the original biome lab.\n'
output += 'export const SKY_SOURCE_SHA256=' + json.dumps(hashlib.sha256(source.encode()).hexdigest()) + ';\n'
for name, value in [('SKY_VERTEX', vertex), ('SKY_FRAGMENT', fragment)]:
    output += f'export const {name}=' + json.dumps(value, ensure_ascii=False) + ';\n'
output += decoder + '\n'
(ROOT / 'src/rendering/sky-source.js').write_bytes(output.encode('utf-8'))
inventory = json.loads((ROOT / 'content/manifests/assets.json').read_text(encoding='utf-8'))
panoramas = []
for kind in ['day', 'night']:
    resource = next(r for r in inventory['resources'] if any(origin.endswith('#sky-' + kind + '-data') for origin in r.get('origins', [])))
    panoramas.append({key: resource[key] for key in ['url', 'bytes', 'sha256', 'origins']})
(ROOT / 'public/content/skies.json').write_bytes((json.dumps({'panoramas': panoramas}, indent=2) + '\n').encode())
