// Reproduce all approved HQ atlases before writing any public asset or module.
import fs from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {spawnSync} from 'node:child_process';
const root=fileURLToPath(new URL('../',import.meta.url)),check=process.argv.includes('--check');
if(process.argv.slice(2).some(arg=>arg!=='--check'))throw Error('Use --check or no arguments');
await fs.mkdir(path.join(root,'.cache'),{recursive:true});const stage=await fs.mkdtemp(path.join(root,'.cache/mountain-public-export-'));
const heights={savanna:110,grand_river:85,mangrove:60,volcanoes:160,canyons:130,desert:115},profiles={};
for(const [biome,height]of Object.entries(heights)){
 const output=path.join(stage,biome),result=spawnSync(process.execPath,[path.join(root,'tools/prepare_mountain_arc_four.mjs'),output,biome],{cwd:root,encoding:'utf8',timeout:60000});
 if(result.error||result.status!==0)throw Error('Mountain export failed for '+biome+': '+(result.stderr||result.error));
 const receipt=JSON.parse(await fs.readFile(path.join(output,'export.json'),'utf8'));
 profiles[biome]={atlas:'assets/far-vegetation/'+biome+'-hq-backdrop.webp',height,dimensions:receipt.dimensions,bytes:receipt.bytes,sha256:receipt.atlasSha256,cells:receipt.sourceAssets.map(({uv,baseline,heightScale})=>({uv,baseline,...(heightScale!==undefined?{heightScale}:{})}))};
}
const module=`// Generated by tools/prepare_mountain_backdrops.mjs from pinned imagegen source contracts.\nimport {mountainArcComposition} from './mountain-arc-composition.js';\nconst atlases=${JSON.stringify(profiles,null,2)};\nexport function mountainBackdropProfile(biome,seed){\n const data=atlases[biome];if(!data)throw Error('Unknown mountain biome');\n if(!(Number.isSafeInteger(seed)||(typeof seed==='string'&&seed.length)))throw Error('Invalid mountain seed');\n let numeric=Number(seed);if(!Number.isSafeInteger(numeric)){numeric=2166136261;for(const character of String(seed))numeric=Math.imul(numeric^character.codePointAt(0),16777619)>>>0;}\n return {atlas:data.atlas,sha256:data.sha256,bytes:data.bytes,dimensions:[...data.dimensions],arcLayout:mountainArcComposition(data.cells,numeric,{height:data.height}),stableAltitude:true,fogBaseMix:1};\n}\n`;
const modulePath=path.join(root,'src/rendering/mountain-backdrop-profile.js');
if(check){
 if(await fs.readFile(modulePath,'utf8')!==module)throw Error('Mountain runtime module differs from pinned export');
 for(const [biome,data]of Object.entries(profiles))if(!(await fs.readFile(path.join(root,'public',data.atlas))).equals(await fs.readFile(path.join(stage,biome,'atlas.webp'))))throw Error('Public mountain atlas differs: '+biome);
}else{
 for(const [biome,data]of Object.entries(profiles))await fs.copyFile(path.join(stage,biome,'atlas.webp'),path.join(root,'public',data.atlas));
 await fs.writeFile(modulePath,module);
}
console.log(JSON.stringify({check,stage,profiles,publicBytes:Object.values(profiles).reduce((sum,p)=>sum+p.bytes,0)},null,2));
