from pathlib import Path
import json,gzip,hashlib,math
folder=Path('docs/qa/economic-candidates-a518/quota-g10-92637210')
inputs={name:hashlib.sha256((folder/name).read_bytes()).hexdigest() for name in ['diagnostic.json.gz','report.json.gz','terminal-audit.json.gz']}
diag=json.loads(gzip.decompress((folder/'diagnostic.json.gz').read_bytes()));report=json.loads(gzip.decompress((folder/'report.json.gz').read_bytes()));audit=json.loads(gzip.decompress((folder/'terminal-audit.json.gz').read_bytes()))
opening=[]
for cost in [800,600]:
    beforeHire=1500-cost-5;staff=math.ceil((1+beforeHire/10)/12);post=beforeHire-staff*30
    reserve=staff*30+100;additional=max(0,math.floor((post-reserve)/5))
    opening.append({'centerCost':cost,'initialMoney':1500,'firstSeedCost':5,'cashBeforeHire':beforeHire,'staff':staff,'paidWages':staff*30,'postHireCash':post,'nextTeamReserve':staff*30,'maintenanceFloor':100,'additionalSeedsBeforeNextIncome':additional,'livingBeforeBudgetBlock':1+additional,'livingPerWorker':(1+additional)/staff})
proposal={'scope':'Read-only arithmetic from existing G10/F10. No runtime changes or simulations. Not an acceptance prediction.','inputs':inputs,'observed':{'budgetSeconds':sum(d['seconds'] for d in diag['daily']),'early1to3Budget':sum(d['seconds'] for d in diag['daily'] if d['day']<=3),'maintenanceSeconds':diag['categories']['maintenanceReserve'],'currentTeamSeconds':diag['categories']['belowCurrentTeamReserve'],'early1to2Maintenance':sum(d['categories'].get('maintenanceReserve',0) for d in diag['daily'] if d['day']<=2),'daily':report['daily'],'F10':audit['F10'],'G10':audit['G10']},'proposedSingleParameter':{'name':'work_center.cost','from':800,'to':600,'base':'G quota4','noChanges':['initial_money','wages','crop prices','harvest values','base attraction','HP','damage','growth','task durations','speed','animation','urgency','FIFO','routes','policy','placement domain','seed712','maintenance floor100','activity threshold']},'openingArithmetic':opening,'repairArithmetic':[{'hp':hp,'oldCost':math.ceil(800*(600-hp)/600),'proposedCost':math.ceil(600*(600-hp)/600),'oldReserve':max(100,math.ceil(800*(600-hp)/600)),'proposedReserve':max(100,math.ceil(600*(600-hp)/600))}for hp in [600,550,470]],'risks':['More absolute queue and earlier plant attraction despite unchanged per-plant attraction','Cheaper extra centres and repairs may reduce bad-management risk','Dawn-only staffing and seed purchases are endogenous, so exact delivery timing/activity cannot be inferred from this arithmetic','Late F100 finite placement and congestion remain untested by G10','Must preserve rejected F/G controls and test poor-management and full100/matrix before promotion']}
out=Path('docs/qa/economic-candidates-a518/quota-g-next-cost-proposal');out.mkdir(exist_ok=True)
(out/'readonly-proposal.json').write_text(json.dumps(proposal,indent=2)+'\n',encoding='utf-8')
print(json.dumps({'opening':opening,'budget':proposal['observed']['budgetSeconds'],'earlyBudget':proposal['observed']['early1to3Budget']},indent=2))
