// Functional/provenance/encoding checks, not a rendering comparison experiment.
import fs from 'node:fs';import crypto from 'node:crypto';import assert from 'node:assert/strict';import * as THREE from 'three';import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';import {readGlb,writeGlb} from './glb-container.mjs';import {createCropBatch} from '../src/rendering/crop-batch.js';import {cropSpec} from '../src/simulation/rules.js';
const manifest=JSON.parse(fs.readFileSync('content/manifests/crops-v4.json')),data=JSON.parse(fs.readFileSync('public/content/crop-bridges.json')),sha=b=>crypto.createHash('sha256').update(b).digest('hex'),loader=new GLTFLoader();
assert.equal(sha(fs.readFileSync('references/crops-v4/1-biomas.zip')),manifest.zipSha256);assert.equal(sha(fs.readFileSync("references/crops-v4/recipe-functions.js")),manifest.recipeSha256);assert.equal(manifest.version,4);assert.equal(data.recipeVersion,4);
async function model(record){const bytes=fs.readFileSync('public'+record.url);assert.equal(bytes.length,record.bytes);assert.equal(sha(bytes),record.sha256);const{json,bin}=readGlb(bytes);function strip(o){if(!o||typeof o!=='object')return;for(const k of Object.keys(o))if(k.endsWith('Texture'))delete o[k];else strip(o[k]);}strip(json.materials);delete json.images;delete json.textures;return loader.parseAsync(writeGlb(json,bin).buffer,'');}
const [states,bridges]=await Promise.all([model(manifest.steady),model(manifest.bridges)]);data.bakedTemplates=new Map();bridges.scene.traverse(m=>{if(m.isMesh){assert.equal(data.bakedTemplates.has(m.userData.bridgeIndex),false);data.bakedTemplates.set(m.userData.bridgeIndex,m);}});assert.equal(data.bakedTemplates.size,32);
const sourceNodes=[];states.scene.traverse(m=>{if(m.isMesh)sourceNodes.push(m)});assert.equal(sourceNodes.length,40);assert.equal(new Set(sourceNodes.map(m=>m.userData.cropIndex*5+m.userData.stage-1)).size,40);for(const m of sourceNodes){assert.equal(m.material.side,THREE.FrontSide);}
const scene=new THREE.Scene(),batch=createCropBatch(scene,{capabilities:{getMaxAnisotropy:()=>1}},states,data,64);assert.equal(scene.children.length,72);
for(const mesh of scene.children){assert.equal(mesh.material.side,THREE.FrontSide);assert.equal(mesh.material.normalScale.x,.48);assert.equal(mesh.material.normalScale.y,.48);assert.equal(mesh.material.shadowSide,THREE.FrontSide);assert.equal(mesh.customDepthMaterial.side,THREE.FrontSide);assert.equal(mesh.customDepthMaterial.userData.worldDepthCompatible,true);assert.ok(mesh.geometry.boundingSphere);for(const attr of Object.values(mesh.geometry.attributes))for(const v of attr.array)assert.ok(Number.isFinite(v));}
const rows=[],ids=['maiz','algodon','girasol','platano','sorgo','mijo','yuca','batata'];
for(const species of ids){const seconds=cropSpec(species).growth_seconds,phases=new Set(),stages=new Set();for(const normalized of [0,.05,.1,.2,.231,.249,.269,.3,.4,.4805,.5,.529,.55,.7,.7325,.755,.779,.8,.9,.9581,.979,.999,1]){const sample=batch.sample(species,normalized*seconds);phases.add(sample.phase);if(sample.phase==='original')stages.add(sample.stage);batch.update([{id:'v4_'+species,species,growth:normalized*seconds,x:2,z:3,rotation:.2}],12.5,()=>.25);const visible=scene.children.filter(m=>m.visible&&m.count>0);assert.equal(visible.length,1);assert.equal(visible[0].count,1);if(sample.phase==='morph')assert.ok(visible[0].name.startsWith('puente_'));rows.push({species,normalized,phase:sample.phase,stage:sample.stage,visible:visible[0].name});}assert.equal(stages.size,5);assert.ok(phases.has('morph'));}
batch.dispose();assert.equal(scene.children.length,0);const rebuilt=createCropBatch(scene,{capabilities:{getMaxAnisotropy:()=>1}},states,data,128),plants=Array.from({length:65},(_,i)=>({id:'v4resize'+i,species:ids[i%8],growth:cropSpec(ids[i%8]).growth_seconds*.5,x:i%9,z:Math.floor(i/9),rotation:0}));rebuilt.update(plants,13,()=>0);assert.equal(scene.children.reduce((n,m)=>n+m.count,0),65);rebuilt.dispose();assert.equal(scene.children.length,0);
fs.mkdirSync('docs/qa/crops-v4',{recursive:true});fs.writeFileSync('docs/qa/crops-v4/functional.json',JSON.stringify({status:'LAB_V4_FUNCTIONAL_CPU_PASS_NOT_VISUAL_REVIEW',models:40,bridges:32,rows,capacityRebuild:[64,128],plantCountAfterRebuild:65,side:0,shadowSide:0,depthSide:0,sourceZipSha256:manifest.zipSha256,limitations:['Textures omitted only for CPU GLTF parsing; compressed image/alpha/decoder conformance checked by verify_web_assets.','No GPU timing, perceptual equivalence, worker animation change or new repair experiment.','Actual game visual/growth/wind/shadow review remains pending.']},null,2)+'\n');console.log('PASS CULT V4:8species/5states/32bridges, Front colour/shadow/depth, finite attributes, native dispatch and resize65/128.');
