
'use strict';
(() => {
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const DEFAULTS={bodySize:16,bodyWeight:400,displayScale:100,leading:1.5,tracking:0,theme:'earth',previewWidth:1280,context:'calm'};
let settings={...DEFAULTS};try{settings={...settings,...JSON.parse($('#initial-settings').textContent)}}catch{}
let bundle;try{bundle=JSON.parse($('#font-payload').textContent)}catch{bundle={schema:1,fonts:[],licences:{},importedNotices:[]}};
bundle.fonts ||= [];bundle.importedNotices ||= [];bundle.licences ||= {};
let activeFonts=[], loading=false, tutorialStep=0;
const ALIASES={ga:'WG Ga Maamli',banga:'WG Banga'};
const tutorialTexts=['Toca una parcela vacía y elige qué quieres sembrar. ¡Cada pequeño brote cuenta!','Acerca la regadera a los brotes. Un poco de agua los ayudará a crecer.','Antes del anochecer, revisa las defensas y deja a los granjeros a salvo.'];
const icon=(id)=>`<svg class="icon" aria-hidden="true"><use href="#${id}"/></svg>`;
function toast(title,body='',kind=''){const div=document.createElement('div');div.className='toast '+kind;if(body){const h=document.createElement('strong');h.textContent=title;div.append(h,document.createTextNode(body));}else div.textContent=title;$('#toasts').append(div);setTimeout(()=>div.remove(),5000)}
function status(text,error=false){const el=$('#loader-status');if(!el)return;el.textContent=text;el.classList.toggle('error',error)}
function saveFile(name,text,type='text/plain;charset=utf-8'){const a=document.createElement('a');const url=URL.createObjectURL(new Blob([text],{type}));a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000)}
function toBase64(data){let s='';const u=new Uint8Array(data);for(let i=0;i<u.length;i+=16384)s+=String.fromCharCode(...u.subarray(i,i+16384));return btoa(s)}
function fromBase64(s){const b=atob(s);return Uint8Array.from(b,c=>c.charCodeAt(0))}
function xmlSafeJSON(x){return JSON.stringify(x).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029')}
function getTable(bytes,tag){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);if(bytes.length<12)throw Error('Archivo demasiado pequeño.');const n=v.getUint16(4);for(let i=0;i<n;i++){const p=12+i*16;if(p+16>bytes.length)throw Error('Directorio tipográfico truncado.');if(String.fromCharCode(...bytes.subarray(p,p+4))===tag){const o=v.getUint32(p+8),l=v.getUint32(p+12);if(o+l>bytes.length)throw Error('Tabla tipográfica fuera del archivo.');return {offset:o,length:l}}}return null}
function inspectFont(bytes,filename){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength), sig=v.getUint32(0);if(sig!==0x00010000&&sig!==0x4f54544f)throw Error(filename+': selecciona un TTF u OTF sin comprimir.');const name=getTable(bytes,'name');if(!name)throw Error('No hay tabla de nombres en '+filename);let names={};const n=v.getUint16(name.offset+2),storage=name.offset+v.getUint16(name.offset+4);for(let i=0;i<n;i++){const p=name.offset+6+i*12;if(p+12>name.offset+name.length)break;const platform=v.getUint16(p),lang=v.getUint16(p+4),id=v.getUint16(p+6),len=v.getUint16(p+8),off=storage+v.getUint16(p+10);if(off+len>bytes.length)continue;let text='';if(platform===0||platform===3){for(let j=0;j+1<len;j+=2)text+=String.fromCharCode(v.getUint16(off+j));}else if(platform===1)text=new TextDecoder('windows-1252').decode(bytes.subarray(off,off+len));if(text&&(!names[id]||lang===1033))names[id]=text}
const family=names[16]||names[1]||'',subfamily=names[17]||names[2]||'';let kind=/ga\s*maamli/i.test(family)?'ga':/^banga(?:\s|$)/i.test(family)?'banga':null;if(!kind)return null;
const os=getTable(bytes,'OS/2'),head=getTable(bytes,'head');let weight=os&&os.length>=6?v.getUint16(os.offset+4):400;weight=Math.max(100,Math.min(900,weight||400));const italic=(os&&os.length>=64&&(v.getUint16(os.offset+62)&1))||/italic|oblique/i.test(subfamily)||(head&&head.length>=46&&(v.getUint16(head.offset+44)&2));let weightRange=null;const fvar=getTable(bytes,'fvar');if(fvar){const axisOff=fvar.offset+v.getUint16(fvar.offset+4),num=v.getUint16(fvar.offset+8),size=v.getUint16(fvar.offset+10);for(let i=0;i<num;i++){let p=axisOff+i*size;if(p+20>bytes.length)break;if(String.fromCharCode(...bytes.subarray(p,p+4))==='wght')weightRange=[v.getInt32(p+4)/65536,v.getInt32(p+12)/65536]}}
return {kind,family,subfamily,filename,weight,weightRange,style:italic?'italic':'normal',version:names[5]||'',copyright:names[0]||'',license:names[13]||'',licenseURL:names[14]||'',bytes:bytes.length,coverage:checkCoverage(bytes,'ÁÉÍÓÚÜÑáéíóúüñ¿¡€0123456789'),format:sig===0x4f54544f?'opentype':'truetype'}}
function checkCoverage(bytes,chars){try{const t=getTable(bytes,'cmap');if(!t)return {checked:false,missing:[]};const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);const n=v.getUint16(t.offset+2),tables=[];for(let i=0;i<n;i++){const p=t.offset+4+i*8,o=t.offset+v.getUint32(p+4);if(o+2<=bytes.length){const f=v.getUint16(o);if(f===4||f===12)tables.push({o,f})}}const has=c=>tables.some(({o,f})=>{if(f===12){const groups=v.getUint32(o+12);for(let i=0;i<groups;i++){let p=o+16+i*12,a=v.getUint32(p),b=v.getUint32(p+4);if(c>=a&&c<=b)return v.getUint32(p+8)+(c-a)!==0;}return false;}let count=v.getUint16(o+6)/2,end=o+14,start=end+count*2+2,delta=start+count*2,range=delta+count*2;for(let i=0;i<count;i++){let e=v.getUint16(end+i*2),s=v.getUint16(start+i*2);if(c<s||c>e)continue;let d=v.getInt16(delta+i*2),r=v.getUint16(range+i*2);if(!r)return ((c+d)&65535)!==0;let p=range+i*2+r+(c-s)*2;if(p+2>bytes.length)return false;let g=v.getUint16(p);return g!==0&&((g+d)&65535)!==0;}return false});return {checked:true,missing:Array.from(new Set(chars)).filter(c=>!has(c.codePointAt(0)))}}catch{return {checked:false,missing:[]}}}
async function activate(font){const bytes=fromBase64(font.data),face=new FontFace(ALIASES[font.kind],bytes.buffer,{weight:font.weightRange?font.weightRange.join(' '):String(font.weight),style:font.style,display:'block'});await face.load();const prev=activeFonts.find(x=>x.font.kind===font.kind&&x.font.weight===font.weight&&x.font.style===font.style);if(prev){document.fonts.delete(prev.face);activeFonts=activeFonts.filter(x=>x!==prev)}document.fonts.add(face);activeFonts.push({font,face});}
async function addFont(bytes,filename,source){const meta=inspectFont(bytes,filename);if(!meta)return false;const font={...meta,source,data:toBase64(bytes)};await activate(font);bundle.fonts=bundle.fonts.filter(f=>!(f.kind===font.kind&&f.weight===font.weight&&f.style===font.style));bundle.fonts.push(font);return true;}
function ready(kind){return activeFonts.some(x=>x.font.kind===kind&&x.font.style==='normal')}
function refresh(){const ga=ready('ga'),banga=ready('banga'),both=ga&&banga;for(const [kind,ok] of [['ga',ga],['banga',banga]]){const e=$('#'+kind+'-status');e.textContent=ok?'Activa':'Pendiente';e.classList.toggle('ready',ok)}document.body.classList.toggle('fonts-not-ready',!both);$('#font-guard').classList.toggle('ready',both);$('#font-guard').innerHTML=icon(both?'i-check':'i-warning')+`<span>${both?'Fuentes reales incrustadas: Ga Maamli en títulos y Banga en los textos. El laboratorio funciona completamente sin conexión.':(ga?'Ga Maamli está activa. Banga sigue pendiente; su texto aún usa una fuente de reserva.':banga?'Banga está activa. Ga Maamli sigue pendiente; los títulos aún usan una fuente de reserva.':'Maqueta provisional: las fuentes de reserva solo permiten revisar la distribución. No representan Ga Maamli ni Banga.')}</span>`;
$('#package-status').textContent=both?'las dos familias se han cargado correctamente en el navegador. La copia guardada con el botón superior no necesita red.':'Ga Maamli y Banga están incrustadas en este HTML; no necesita conexión ni archivos externos.';
const available=activeFonts.filter(x=>x.font.kind==='banga'&&x.font.style==='normal').map(x=>x.font);if(available.length){for(const opt of $('#body-weight').options){const w=Number(opt.value),ok=available.some(f=>f.weightRange?w>=f.weightRange[0]&&w<=f.weightRange[1]:w===f.weight);opt.disabled=!ok;opt.textContent=({'400':'Regular','500':'Medium','600':'Semibold','700':'Bold'}[opt.value]||opt.value)+' · '+w+(!ok?' (sin archivo)':'');}if($('#body-weight').selectedOptions[0]?.disabled){const first=[...$('#body-weight').options].find(o=>!o.disabled);if(first){settings.bodyWeight=Number(first.value);$('#body-weight').value=first.value;applySettings();}}}
const ital=activeFonts.some(x=>x.font.kind==='banga'&&x.font.style==='italic');$('#italic-note').textContent=ital?'Cursiva real de Banga cargada.':'Sin archivo de cursiva: no se simula inclinación.';
$('#font-data').textContent=bundle.fonts.length?bundle.fonts.map(f=>`${f.family} · ${f.subfamily} · peso ${f.weightRange?f.weightRange.join('–'):f.weight}\n${f.filename} · ${(f.bytes/1024).toFixed(1)} KiB\n${f.version}\n${f.copyright||'El archivo no declara copyright en su tabla name.'}\n${f.licenseURL||''}\nOrigen: ${f.source||'Archivo local'}`).join('\n\n'):'Todavía no hay archivos tipográficos incorporados.';
const audited=bundle.fonts.filter(f=>f.style==='normal');$('#glyph-audit').textContent=audited.length?audited.map(f=>`${f.family} ${f.weight}: ${f.coverage?.checked?(f.coverage.missing.length?'faltan '+f.coverage.missing.join(' '):'tildes, eñes, ¿¡, euro y cifras presentes'):'no se pudo comprobar la cobertura'}`).join(' · '):'La cobertura de caracteres se comprueba con los archivos incrustados.';
$('#ga-licence').textContent=bundle.licences.ga||'';$('#banga-licence').textContent=bundle.licences.banga||'';$('#banga-authors').textContent=bundle.licences.bangaAuthors||'';$('#extra-licence-content').replaceChildren();for(const n of bundle.importedNotices){const h=document.createElement('h3'),p=document.createElement('pre');h.textContent=n.filename;p.textContent=n.text;$('#extra-licence-content').append(h,p);}$('#extra-licences').hidden=!bundle.importedNotices.length;
}
// Small local ZIP reader. Uses the browser's native decompression when available.
// Only regular files are read into memory; nothing is written to arbitrary paths.
async function unzip(bytes){const v=new DataView(bytes.buffer,bytes.byteOffset,bytes.byteLength);let e=-1;for(let p=bytes.length-22;p>=Math.max(0,bytes.length-65557);p--)if(v.getUint32(p,true)===0x06054b50){e=p;break}if(e<0)throw Error('No se encuentra el directorio ZIP.');const count=v.getUint16(e+10,true);let p=v.getUint32(e+16,true);if(count>5000)throw Error('ZIP demasiado grande.');const entries=[];let total=0;for(let i=0;i<count;i++){if(p+46>bytes.length||v.getUint32(p,true)!==0x02014b50)throw Error('Directorio ZIP no válido.');const flags=v.getUint16(p+8,true),method=v.getUint16(p+10,true),size=v.getUint32(p+20,true),usize=v.getUint32(p+24,true),nl=v.getUint16(p+28,true),el=v.getUint16(p+30,true),cl=v.getUint16(p+32,true),offset=v.getUint32(p+42,true);if(p+46+nl>bytes.length)throw Error('ZIP truncado.');const name=new TextDecoder().decode(bytes.subarray(p+46,p+46+nl));p+=46+nl+el+cl;if(!/\.(ttf|otf|txt)$/i.test(name)||name.startsWith('__MACOSX/'))continue;if(flags&1)throw Error('No se admiten ZIP con contraseña.');total+=usize;if(usize>20*1024*1024||total>100*1024*1024)throw Error('Los archivos del ZIP superan el límite de 100 MB.');if(offset+30>bytes.length||v.getUint32(offset,true)!==0x04034b50)throw Error('Cabecera ZIP no válida.');const start=offset+30+v.getUint16(offset+26,true)+v.getUint16(offset+28,true);if(start+size>bytes.length)throw Error('Datos ZIP truncados.');let data=bytes.subarray(start,start+size);if(method===8){try{const stream=new Blob([data]).stream().pipeThrough(new DecompressionStream('deflate-raw'));data=new Uint8Array(await new Response(stream).arrayBuffer())}catch{data=inflateRaw(data,usize)}}else if(method!==0)throw Error('Método de compresión ZIP no admitido: '+method);if(data.length!==usize)throw Error('Tamaño ZIP descomprimido incorrecto.');entries.push({name,data})}return entries;}
function inflateRaw(input,expected){let p=0,bitbuf=0,bits=0,op=0;const out=new Uint8Array(expected);function read(n){while(bits<n){if(p>=input.length)throw Error('DEFLATE truncado.');bitbuf|=input[p++]<<bits;bits+=8;}const r=bitbuf&((1<<n)-1);bitbuf>>>=n;bits-=n;return r}function tree(lengths){const count=new Uint16Array(16),next=new Uint16Array(16),map=new Map();let max=0;for(const l of lengths){count[l]++;max=Math.max(max,l)}let code=0;for(let l=1;l<=15;l++){code=(code+(l===1?0:count[l-1]))<<1;next[l]=code}lengths.forEach((l,s)=>{if(l){let c=next[l]++,r=0;for(let i=0;i<l;i++){r=(r<<1)|(c&1);c>>>=1;}map.set((1<<l)|r,s)}});return {map,max}}function sym(t){let c=0;for(let l=1;l<=t.max;l++){c|=read(1)<<(l-1);const s=t.map.get((1<<l)|c);if(s!==undefined)return s}throw Error('Código Huffman no válido.')}const L=[3,4,5,6,7,8,9,10,11,13,15,17,19,23,27,31,35,43,51,59,67,83,99,115,131,163,195,227,258],LE=[0,0,0,0,0,0,0,0,1,1,1,1,2,2,2,2,3,3,3,3,4,4,4,4,5,5,5,5,0],D=[1,2,3,4,5,7,9,13,17,25,33,49,65,97,129,193,257,385,513,769,1025,1537,2049,3073,4097,6145,8193,12289,16385,24577],DE=[0,0,0,0,1,1,2,2,3,3,4,4,5,5,6,6,7,7,8,8,9,9,10,10,11,11,12,12,13,13];let last;do{last=read(1);const type=read(2);if(type===0){bitbuf=0;bits=0;if(p+4>input.length)throw Error('Bloque DEFLATE incompleto.');const n=input[p]|input[p+1]<<8,nn=input[p+2]|input[p+3]<<8;p+=4;if((n^nn)!==65535||p+n>input.length||op+n>expected)throw Error('Bloque DEFLATE no válido.');out.set(input.subarray(p,p+n),op);p+=n;op+=n;continue;}let lit,dist;if(type===1){lit=tree(Array.from({length:288},(_,i)=>i<144?8:i<256?9:i<280?7:8));dist=tree(Array(32).fill(5))}else if(type===2){const hlit=read(5)+257,hdist=read(5)+1,hclen=read(4)+4,order=[16,17,18,0,8,7,9,6,10,5,11,4,10,5];const actual=[16,17,18,0,8,7,9,6,10,5,11,4,12,3,13,2,14,1,15],cl=Array(19).fill(0);for(let i=0;i<hclen;i++)cl[actual[i]]=read(3);const ct=tree(cl),lengths=[];while(lengths.length<hlit+hdist){const s=sym(ct);if(s<16)lengths.push(s);else{let n,val;if(s===16){if(!lengths.length)throw Error('Repetición sin longitud previa.');n=read(2)+3;val=lengths[lengths.length-1]}else if(s===17){n=read(3)+3;val=0}else{n=read(7)+11;val=0}while(n--)lengths.push(val)}if(lengths.length>hlit+hdist)throw Error('Tabla DEFLATE excesiva.')}lit=tree(lengths.slice(0,hlit));dist=tree(lengths.slice(hlit));}else throw Error('Tipo de bloque DEFLATE reservado.');for(;;){const s=sym(lit);if(s<256){if(op>=expected)throw Error('DEFLATE excede el tamaño declarado.');out[op++]=s}else if(s===256)break;else{const i=s-257;if(i>=L.length)throw Error('Longitud DEFLATE no válida.');const n=L[i]+read(LE[i]),d=sym(dist);if(d>=D.length)throw Error('Distancia DEFLATE no válida.');const back=D[d]+read(DE[d]);if(back>op||op+n>expected)throw Error('Referencia DEFLATE no válida.');for(let k=0;k<n;k++)out[op]=out[op++-back];}}}while(!last);if(op!==expected)throw Error('Longitud DEFLATE incorrecta.');return out;}
async function ingest(bytes,name,source){if(/\.zip$/i.test(name)){const entries=await unzip(bytes);let n=0;for(const e of entries){if(/\.txt$/i.test(e.name)){if(/OFL|LICEN[CS]E|COPYRIGHT|AUTHORS|CONTRIBUTORS/i.test(e.name)){const notice={filename:e.name,text:new TextDecoder().decode(e.data)};if(!bundle.importedNotices.some(x=>x.filename===notice.filename&&x.text===notice.text))bundle.importedNotices.push(notice);}continue;}if(await addFont(e.data,e.name,source))n++;}return n;}if(/\.txt$/i.test(name)){bundle.importedNotices.push({filename:name,text:new TextDecoder().decode(bytes)});return 0}return (await addFont(bytes,name,source))?1:0;}
async function fetchBytes(url){const c=new AbortController(),id=setTimeout(()=>c.abort(),22000);try{const r=await fetch(url,{signal:c.signal,credentials:'omit',referrerPolicy:'no-referrer'});if(!r.ok)throw Error('HTTP '+r.status);const b=await r.arrayBuffer();if(b.byteLength>50*1024*1024)throw Error('Descarga demasiado grande.');return new Uint8Array(b)}finally{clearTimeout(id)}}
async function loadOfficial(){if(loading)return;loading=true;$('#load-official').disabled=true;refresh();status('Intentando cargar las fuentes oficiales…');const errors=[],lines=[];if(!ready('ga')){try{const url='https://raw.githubusercontent.com/google/fonts/main/ofl/gamaamli/GaMaamli-Regular.ttf';const n=await ingest(await fetchBytes(url),'GaMaamli-Regular.ttf',url);if(!n)throw Error('No se reconoció la familia.');lines.push('Ga Maamli: cargada.')}catch(e){errors.push('Ga Maamli: '+e.message+'. Descarga su TTF y selecciónalo aquí.');}}refresh();if(!ready('banga')){status([...lines,'Intentando cargar el ZIP oficial de Banga…'].join('\n'));try{const url='https://www.davidsargent.com.au/wp-content/uploads/2026/06/test_fonts.zip';const n=await ingest(await fetchBytes(url),'test_fonts.zip',url);if(!n)throw Error('El ZIP no contiene TTF/OTF reconocibles de Banga.');lines.push('Banga: '+n+' estilos cargados.')}catch(e){errors.push('Banga: la descarga no ha sido posible ('+e.message+'). Abre el enlace al ZIP oficial y selecciónalo aquí. Puede ser un bloqueo de acceso entre dominios del navegador.');}}loading=false;$('#load-official').disabled=false;refresh();status([...lines,...errors].join('\n'),errors.length>0);if(ready('ga')&&ready('banga'))toast('Fuentes incorporadas','Ya puedes comparar la tipografía y guardar la copia sin conexión.');}
async function loadLocal(files){if(loading)return;loading=true;let n=0;const errors=[];status('Leyendo archivos localmente…');for(const f of files){try{if(f.size>50*1024*1024)throw Error('Máximo 50 MB por archivo.');n+=await ingest(new Uint8Array(await f.arrayBuffer()),f.name,'Archivo local: '+f.name)}catch(e){errors.push(f.name+': '+e.message)}}loading=false;refresh();status(`${n} archivo(s) tipográfico(s) incorporado(s).`+(errors.length?'\n'+errors.join('\n'):n?'':' Solo se admiten las familias Ga Maamli y Banga.'),errors.length>0);$('#font-files').value='';}
function applySettings(){const r=document.documentElement.style;r.setProperty('--body-size',settings.bodySize+'px');r.setProperty('--body-weight',settings.bodyWeight);r.setProperty('--display-scale',settings.displayScale/100);r.setProperty('--body-leading',settings.leading);r.setProperty('--tracking',settings.tracking+'em');r.setProperty('--preview-width',settings.previewWidth+'px');$('#game-scene').dataset.theme=settings.theme;$$('.swatch').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.theme===settings.theme)));const vals={'body-size':[settings.bodySize,settings.bodySize+' px'],'display-scale':[settings.displayScale,settings.displayScale+' %'],'leading':[settings.leading,Number(settings.leading).toFixed(2).replace('.',',')],'tracking':[settings.tracking,Number(settings.tracking).toFixed(3).replace('.',',')+' em']};for(const [id,[val,text]]of Object.entries(vals)){$('#'+id).value=val;$('#'+id+'-value').textContent=text}$('#body-weight').value=settings.bodyWeight;$('#preview-width').value=settings.previewWidth;}
function setContext(key,showToast=true){settings.context=key;$$('[data-context]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.context===key)));const data={calm:['El primer brote','La tierra está lista. Ayuda a la aldea a preparar su primera cosecha.','La misión de hoy','La aldea está tranquila','Día 03 · Primeras lluvias','i-sun','earth'],night:['Bajo las estrellas','La aldea descansa. Conserva algo de energía para proteger los cultivos.','Al caer la noche','Los granjeros descansan','Noche 03 · El refugio','i-moon','night'],danger:['¡Protege la granja!','Un facóquero se acerca al acceso norte. Lleva a los granjeros a un lugar seguro.','Peligro cercano','Ataque en el acceso norte','Día 03 · Alerta','i-warning','earth'],success:['Una buena cosecha','El esfuerzo compartido ha dado sus frutos. La aldea tiene provisiones para seguir.','Objetivo completado','Cosecha completada','Día 03 · Buenas noticias','i-seed','earth'],failure:['Volver a empezar','Repara los daños, recupera lo que puedas y prepara una nueva cosecha.','Después del ataque','Es hora de reconstruir','Día 03 · Tras la tormenta','i-warning','earth']}[key]||null;if(!data)return;const [title,desc,kicker,state,time,symbol,theme]=data;$('#quest-title').textContent=title;$('#quest-desc').textContent=desc;$('#quest-kicker').textContent=kicker;$('#scene-status').textContent=state;$('#time-label').textContent=time;$('#time-icon').setAttribute('href','#'+symbol);$('#scene-dot').style.background=key==='danger'||key==='failure'?'#bd7952':'#77a361';settings.theme=theme;applySettings();if(showToast&&key==='danger')toast('¡Se acerca un facóquero!','Protege los cultivos y despeja el camino.','error');if(showToast&&key==='success')toast('¡Cosecha completada!','Has obtenido 8 cestas y 25 de energía.');if(showToast&&key==='failure')toast('Volveremos a brotar','La tierra sigue esperando tus cuidados.','error');}
function selectTab(key,focus=false){$$('[role=tab]').forEach(b=>{const active=b.dataset.tab===key;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;if(active&&focus)b.focus()});$$('[role=tabpanel]').forEach(p=>p.hidden=p.id!=='panel-'+key);}
function updateSizes(){const text=$('#sample-input').value;$('#size-tests').replaceChildren();for(const size of [13,14,16,18,20,24]){const row=document.createElement('div'),label=document.createElement('span'),p=document.createElement('p');row.className='size-row';label.textContent=size+' px';p.style.fontSize=size+'px';p.textContent=text;row.append(label,p);$('#size-tests').append(row)}}
function initControls(){for(const [id,key] of [['body-size','bodySize'],['body-weight','bodyWeight'],['display-scale','displayScale'],['leading','leading'],['tracking','tracking'],['preview-width','previewWidth']])$('#'+id).addEventListener('input',e=>{settings[key]=Number(e.target.value);applySettings()});$$('.swatch').forEach(b=>b.addEventListener('click',()=>{settings.theme=b.dataset.theme;applySettings()}));$$('[data-context]').forEach(b=>b.addEventListener('click',()=>setContext(b.dataset.context)));$$('[role=tab]').forEach((b,i,all)=>{b.addEventListener('click',()=>selectTab(b.dataset.tab));b.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%all.length;else if(e.key==='ArrowLeft')n=(i+all.length-1)%all.length;else if(e.key==='Home')n=0;else if(e.key==='End')n=all.length-1;else return;e.preventDefault();selectTab(all[n].dataset.tab,true)})});$$('[data-go-tab]').forEach(b=>b.addEventListener('click',()=>selectTab(b.dataset.goTab,true)));$$('.toggle').forEach(b=>b.addEventListener('click',()=>b.setAttribute('aria-checked',String(b.getAttribute('aria-checked')!=='true'))));$$('.quest-task').forEach(b=>b.addEventListener('click',()=>{const on=b.getAttribute('aria-pressed')!=='true';b.setAttribute('aria-pressed',String(on));b.querySelector('.check').textContent=on?'✓':'';const n=$$('.quest-task').filter(x=>x.getAttribute('aria-pressed')==='true').length;$('#quest-progress').textContent=n+' de 3 tareas';if(n===3)toast('¡Misión completada!','La aldea ha dado un paso más. +25 de energía.')}));$('#tutorial-next').addEventListener('click',()=>{$('#tutorial-text').textContent=tutorialTexts[++tutorialStep%tutorialTexts.length]});$('#continue-game').addEventListener('click',()=>toast('La aventura continúa','Esta es una maqueta tipográfica: no se abrirá una partida real.'));$$('[data-buy]').forEach(b=>b.addEventListener('click',()=>{toast('Compra completada',b.dataset.buy+' añadida al inventario.');if(b.dataset.buy==='Semillas de mijo')$('#seed-count').textContent=Number($('#seed-count').textContent)+3}));$$('[data-notice]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.notice,'Mensaje de ejemplo de la interfaz.')));$$('[data-action]').forEach(b=>b.addEventListener('click',()=>toast(b.dataset.action==='save'?'Ajustes guardados':'Una nueva aventura','Acción de ejemplo para evaluar la tipografía.')));$('#reset').addEventListener('click',()=>{settings={...DEFAULTS};applySettings();setContext('calm',false);refresh();toast('Ajustes restablecidos','','info')});$('#sample-input').addEventListener('input',updateSizes);$('#export-settings').addEventListener('click',()=>saveFile('Wild_Guardians_Tipografia_Ajustes.json',JSON.stringify({project:'Wild Guardians',...settings,displayFamily:'Ga Maamli',bodyFamily:'Banga',fonts:bundle.fonts.map(({data,...meta})=>meta)},null,2),'application/json'));
}
async function init(){initControls();for(const [target,chars] of [['#banga-glyphs','ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789áéíóúüñÁÉÍÓÚÜÑ¿¡€%&'],['#ga-glyphs','ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789ÁÉÍÓÚÜÑ¿¡']]){const e=$(target);e.replaceChildren();for(const c of chars){const x=document.createElement('span');x.className='glyph';x.textContent=c;e.append(x)}}updateSizes();const theme=settings.theme;setContext(settings.context,false);settings.theme=theme;applySettings();const errors=[];for(const f of bundle.fonts){try{await activate(f)}catch(e){errors.push(f.filename+': '+e.message)}}refresh();if(errors.length)status('No se pudieron activar algunos archivos incorporados:\n'+errors.join('\n'),true);else if(ready('ga')&&ready('banga'))status('Ga Maamli y Banga están incrustadas en este archivo. No se realiza ninguna petición de red.');}
window.WGTypographyLab={inspectFont,inflateRaw,unzip,checkCoverage,getBundle:()=>bundle,getSettings:()=>({...settings}),getActiveFonts:()=>activeFonts.map(x=>({kind:x.font.kind,weight:x.font.weight,style:x.font.style,status:x.face.status}))};
init().catch(e=>{status('No se pudo iniciar el laboratorio: '+e.message,true);console.error(e)});
})();
